demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php

This PR allows to install a specific branch of an addon instead of tags only.
try `bin/<project> dplan:addon:install --github --branch`

chore: install addon from github branch

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_slidebar.scss

**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-11431
As the slidebar is taking the whole available page height, it should be elevated above z-fixed which is applied to fixed headers and other fixed iu elements.
In the page view mentioned in the bug report, the sidebar should display above the sticky header (for the bug to be reproducable, the browser window should be not too wide).

fix: elevate slidebar above z-fixed

---

templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base.html.twig

**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-1963/Speichern-Abbrechen-Button-liegt-auf-Footer-auf-in-Grundeinstellungen
`pb-4` is added globally to prevent this behavior once and for all. Views that add bottom margin or padding, should be adapted in another PR.
All views should feature a decent padding between content and footer.

Add global bottom padding to content area

---

demosplan/DemosPlanCoreBundle/Controller/Platform/FileController.php
demosplan/DemosPlanCoreBundle/Permissions/Permissions.php

**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-11439/Hangenbleiben-nach-PDF-Import 
Distinct route for ai api file access to allow for jwt authentication via query parameter. Otherwise file could not be fetched
import file via pdf import

chore (refs DPLAN-11439): Distinct route for ai api file access to allow jwt authentication

---

client/js/components/map/publicdetail/Map.vue
templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_public_participation_detail.html.twig

The Backend Code was already moved to an addon.
This was supposed to happen with that logic too. But since its not in use anymore and would be really complicated to migrate to an addon, we decided to delete the FE Part.
Along I found some corresponding Templates without any usage.
**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-11457/Verfahrensdetailseite-des-Verfahrenstyps-Teilaufstellung-Regionalplan-Windenergie-fuhrt-zu-Fehlerseite

fix(refs DPLAN-11457): Remove "Dead" Code

---

client/js/components/procedure/SegmentsList/SegmentsList.vue
client/js/components/statement/listStatements/ListStatements.vue

**Ticket:** [DPLAN-3306](https://demoseurope.youtrack.cloud/issue/DPLAN-3306/FE-1-Als-Nutzerin-mochte-ich-sowohl-am-Seitenanfang-als-auch-am-Seitenende-eine-Seitennavigation-vorfinden-um-weniger-Scrollen)
**Description:** Improve usability by adding the pagination to the sticky element at the top of the page (STN-liste and Abschnitte)
After discussing with @hans, it was decided to place pagination on the same line as the sorting (STN page):

feat(DPLAN-3306): move pagionation to the sticky element

---

composer.lock

Ticket:
https://www.dev.diplanung.de/DefaultCollection/BOP-HH/_workitems/edit/15514
Description:
bump demosplan-addon

fix (refs DPLAN-15514): bump demosplan addon

---

composer.lock
demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementController.php
demosplan/DemosPlanCoreBundle/Permissions/Permission.php
demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
demosplan/DemosPlanCoreBundle/Permissions/ProjectPermissions.php
tests/backend/core/Core/Unit/Entity/PermissionTest.php
tests/backend/core/Core/Unit/Logic/PermissionsTest.php
tests/backend/core/Statement/Functional/StatementAnonymizeServiceTest.php
tests/backend/core/Statement/Functional/StatementHandlerTest.php

With the usage of the KnpLabs menu bundle the former mechanism is not used any more and could be removed
How to test:
navigate the app, highlighting should still work

chore: remove menu highlighting that is not used any more

---

demosplan/DemosPlanCoreBundle/Logic/Procedure/ServiceStorage.php
tests/backend/core/Procedure/Functional/ServiceStorageTest.php

**Ticket:** [DPLAN-11429](https://demoseurope.youtrack.cloud/issue/DPLAN-11429/Die-Durchgangsnummer-einer-Phase-muss-eine-positive-Ganzzahl-sein)
Fix bug which leads to an mandatory field error in case of value is not existing.
In a project without this feature it should be possible to save the settings of a procedure.
Change the settings of a procedure and save.
Please merge in case of approvement.

fix (DPLAN-11429): fix false mandatory field error

---

client/js/components/procedure/SegmentsList/SegmentsList.vue
client/js/components/shared/mixins/tableScrollbarMixin.js
client/js/components/statement/listStatements/ListStatements.vue

**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-11516/Scroll-Handle-soll-unten-festgehalten-werden
This PR adds a scrollbar to the SegmentsList that is fixed to the bottom of the page also when not in fullscreen mode. It has been added as a mixin to be able to reuse it in other places. 
When the dataTable is bigger than its container, a scrollbar should appear that is fixed to the bottom of the page:

Add fixed scrollbar to SegmentList

---

client/js/components/procedure/SegmentsList/SegmentsList.vue
client/js/components/statement/listStatements/ListStatements.vue

**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-11518/Textuberlappung-im-Vollbildmodus-wenn-man-einen-Abschnitt-auswahlt
**Description:** This PR adjusts the layout of the fullscreen mode when a bulk-edit is displayed. As the sticky element has a fixed position, its height should be set to properly position the table and avoid overlapping with these two elements.

Fix(DPLAN-11518): adjust fullscreen-mode layout when a bulk-edit is displayed

---

demosplan/DemosPlanCoreBundle/Services/Breadcrumb/Breadcrumb.php

**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-1970/Breadcrumbs-durcheinander-kaputt
**Description:**
- The bug  was introduced by exchanging the `match` function instead of the `switch` function (see here 92d24a2899d895fadc1cb057d994330113b922ef)
- The match function does not break inside a foreach, the switch function can break (using break (2)) to stop the switch function and the foreach
- Because the match function is used, then when a user has 2 roles, the breadcrumb is added twice.
- I wanted to keep the match function, that is why I added the if else. I want to keep the match function in case more user roles are added in the future with a custom breadcrumb
- Go to ewm and login with a user that has 2 or more roles
- Then you should see the duplicated breadcrumbs are …

bug (ref DPLAN-1970) Remove duplicated breadcrumbs

---

client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
translations/messages+intl-icu.de.yml

**Ticket:** [DPLAN-1965](https://demoseurope.youtrack.cloud/issue/DPLAN-1965/Invalid-Inputs-beim-Verfahrenerstellen-werfen-nicht-die-richtigen-Fehlernachrichten)
**Description:** This PR adds an error field name to the `DpDateRangePicker` and includes a tooltip on the 'Zeitraum' label with an explanation about the accepted date format.
Neues Verfahren erstellen -> Pflichtfelder ausfüllen -> in Datumsfeldern invalid Inputs geben
- [Demosplan-ui](https://github.com/demos-europe/demosplan-ui/pull/841)

fix(DPLAN-1965): improve error validation of the Datepicker

---

templates/bundles/DemosPlanCoreBundle/DemosPlanCore/js/dplan.settings.js.twig

**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-11547/Dateien-auf-bauleitplanung.muenchen.de-konnen-nicht-hochgeladen-werden 
When specific organisations have special domains that are mapped to a certain orga page in a customer the absolute url path may show to the customer, which will lead to cors errors. Due to them a file upload will not be possible
upload any file. The upload methods are all same

chore (refs DPLAN-11547): Tus path needs to be relative

---

demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/ProcedureMapSettingResourceConfigBuilder.php
demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureMapSettingResourceType.php
demosplan/DemosPlanCoreBundle/ValueObject/Procedure/AvailableProjectionVO.php

**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-11443/Permissions-checken-ResourceType-vorbereiten
Description:
- For the Kartenausschnitt, the following ProcedureMapSettings resource type is created with following fields:
Following fields needed to be added:
-     availableProjections -> in api request has the same name
-     baseLayer -> baseLayerUrl
-     baseLayerLayers - > baseLayerNames
-     baseLayerProjection -> in api request has the same name
-     defaultProjection -> in api request has the same name
-     globalAvailableScales -> in api request has the same name
-     publicSearchAutoZoom -> in api request has the same name
Those fields are only readable (as they from from yml)
- Use PHPStorm HttpClient
- Create GET api calls like (only  through Procedure …

F dplan 11443 add additional fields procedure  map setting

---

demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php

Just a small quality of life improvement that creates the addonZips folder if it does not exist yet
delete the folder if it exists and install an addon from github

chore: create addonZips dir if it does not exist

---

client/js/components/map/admin/MapAdmin.vue
client/js/components/map/map/MapView.vue
client/js/store/map/ProcedureMapSettings.js

DPLAN-3570
- Add missing permissions for fields
- Remove redundant input fields for territory and coordinate
- Add updating for territory and coordinates
- Show translation if there is no (default) map extent/boundingbox
Verfahren -> Planunterlagen und Planzeichnung -> Startkartenausschnitt -> Geltungsbereich und Ortsbezug zeichnen -> Edit and save should work as expected

feat(refs DPLAN-3570): add permissions for map settings

---

demosplan/DemosPlanCoreBundle/Logic/ProcedureAccessEvaluator.php
demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureResourceType.php

**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-11522/blp-Liste-der-Verfahren-auf-der-Startseite-ladt-sehr-lang
Loading the list of procedures has a very poor performance, taking almost 10 Seconds for a list of only 388 procedures. Two main bottlenecks could be avoided for guest users, as they can neither have DraftStatements nor can they own procedures. Logged in users won't have such a long list, so the performance does (usually) not bite. 
This PR reduces the time to fetch the List for guest users from 9.57s to 1.48s which is still slow but feasible. More performance optimizations can be achieved later on, to keep this PR small I only focused on guest users.
code review and visit blp homepage

chore: improve list performance

---

config/packages/security.yaml
config/services.yml
demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/AiApiAuthenticator.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/ApiAuthenticator.php

Symfony Guard system has been deprecated since a while. New Authenticator system should be used instead.
Use any (internal) api route and check whether it still works. If one does any other should as well

chore: remove deprecated guard authentication

---

demosplan/DemosPlanCoreBundle/Command/ContainerInitCommand.php
demosplan/DemosPlanCoreBundle/Command/InitDbCommand.php

project migrations needs to be set as migrated when a project is newly build from fixtures. The database is set up from scratch and migrations will not work and will do more harm than help

chore: set project migrations as migrated on container setup

---

demosplan/DemosPlanCoreBundle/Command/Data/RegisterUserForCustomerCommand.php
demosplan/DemosPlanCoreBundle/Command/Helpers/Helpers.php
demosplan/DemosPlanCoreBundle/Command/User/UserCreateCommand.php
tests/backend/core/Core/Functional/RegisterUserForCustomerCommandTest.php

When creating a user or granting permissions to another customer only defined allowed roles in project should be suggested

chore: only suggest allowed roles in command

---

demosplan/DemosPlanCoreBundle/Entity/User/SupportContact.php
templates/bundles/DemosPlanCoreBundle/DemosPlanUser/login_idp_error.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T35794
**Ticket:** https://yaits.demos-deutschland.de/T35795
Description: 
- the email property has been adjusted and is a text property now, not anymore a relationship between support contact and email entites.
- text field is not required

F fix related support contact issues

---

demosplan/DemosPlanCoreBundle/Event/Statement/StatementCreatedViaExcelEvent.php
demosplan/DemosPlanCoreBundle/Logic/Import/Statement/ExcelImporter.php

**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-11494/Nach-Excel-Import-von-verschlagworteten-Abschnitten-werden-trotzdem-keine-Vorschlage-bei-Slicing-Tagging-angezeigt
Description: 
PI proposals have to be updated with the new Excel imported tags. The 'StatementCreatedViaExcelEvent' will be dispatched with every new already segmented generated statement and a segmentation request will be send to DATA.
The only purpose to do that here is to get a pi segments proposal resource url from Data which is needed while sending segmentation confirmation request and passing imported tagged sections with Excel to DATA to make them available in the next segmentation proposals.

Fix dplan 11494 update pi proposals with excel imported tags

---

client/js/components/map/admin/MapAdmin.vue
client/js/store/map/ProcedureMapSettings.js
config/permissions.yml

DPLAN-3570
on the mapSettingspage there now is a "reset" Button. It should reset the settings  (not the map zoom) to the data stored before saved. 

fix(refs DPLAN-3570): Add resetbutton to map settings

---

.github/dependabot.yml

This PR introduces a dependency group for all symfony dependencies that are updated together. 
List of excludes can be validated via `composer show`

chore: symfony dependencies could be grouped

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_unregistered_publicagency_email.html.twig
translations/messages+intl-icu.de.yml

[DPLAN-3297](https://demoseurope.youtrack.cloud/issue/DPLAN-3297/2-Als-Fachplanung-mochte-ich-Institutionen-per-E-Mail-zu-einem-Verfahren-einladen-konnen-obwohl-sie-noch-nicht-in-BLP)
**Description:** This PR adds a tooltip for the email text. It is required for the BLP project, but it also needs to be included in the core for other projects with some default text.
Verfahren wählen > Institutionen verwalten > Unregistrierte Institutionen einladen (Tab) (>E-Mail Einladung Verfassen > Ihre Nachricht)
- blp #{[PR-101](https://github.com/demos-europe/demosplan-project-blp/pull/101)}
- demosplan-ui #{[PR-851](https://github.com/demos-europe/demosplan-ui/pull/851)}

Feat(dplan-3297): add tooltip for the email text

---

demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php

DPLAN-1078
Twig referenced to a variable gatewayURL that was not passed to the template because the template is rendered explicitly via php and not as usually as "normal" twig code where the `DefaultTwigVariablesService` enhances a bunch of variables.
See reproduction way in ticket

chore (refs DPLAN-1078): add missing gatewayURL

---

demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php

Description: 
we have till now a universal legend which references only the to blueprint procedure and can not be applied anymore to all other procedures. To make the legend available, the method 'copyLegend' copy the blueprint legend file and make it refer to the created procedure.

f DPLAN-11596 copy blueprint legend while procedure creation

---

composer.lock

Description: upgrade demosplan addon to 0.34

F dplan 11494 upgrade demosplan addon to 0.34

---

config/packages/rate_limiter.yaml
demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserAuthenticationController.php
translations/messages+intl-icu.de.yml

Similar to #3011 the number of password reset requests needs to be throttled
code review or try to reset the password more than 5 times in 15 Minutes

chore (refs DPLAN-603): throttle password reset requests

---

composer.json
composer.lock

DPLAN-11672
Update php-parallel-lint/php-console-highlighter needed for symfony 6 compatibility
perform any console command. It should not break

chore: update php-parallel-lint/php-console-highlighter

---

client/js/components/procedure/admin/AdministrationProceduresList.vue
client/js/store/statement/Filter.js
tests/frontend/unit/__mocks__/UserFilterSetResource.mock.js
tests/frontend/unit/store/Filter.spec.js

It looks like the response from the API changed, so we have to adjust the request to match the json:api specs more strict.
**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-11435/gespeicherte-Filterkombinationen-laden-nicht-A-Tabelle
With this fix, saved filterSets should be loadable again. (A-table as FPA)

fix(refs DPLAN-11435): Fetch Lost Hash to request userFilterSets

---

composer.json
composer.lock

Ticket:
https://www.dev.diplanung.de/DefaultCollection/BOP-HH/_workitems/edit/15514
Description:
add composer_lock_for_minor_demosplan_addon_update

fix (refs DPLAN-11422): add composer_lock_for_minor_demosplan_addon_update

---

client/js/loadSentry.js

After updating sentry, browser tracing was moved to browser package and is now exported as browserTracingIntegration.

bug: fix browser tracing sentry

---

demosplan/DemosPlanCoreBundle/Logic/Import/Statement/ExcelImporter.php
demosplan/DemosPlanCoreBundle/Logic/Statement/XlsxSegmentImport.php

Description: 
request segmentation after statements are committed: dispatch 'StatementCreatedViaExcelEvent' after statements are committed.

F dplan 11494 request segmentation after statements are committed

---

package.json
yarn.lock

This PR bumps demosplan-ui to 0.3.16, which also bumps Tiptap to 2.4. 
Things should run as before.

Bump demosplan-ui to 0.3.16

---

composer.json

**Ticket** DPLAN-11655
We should set the Version always explicit. With that its easier to change versions in between branches etc.

chore: Set concrete Version for demosplan-addon

---

client/js/components/procedure/imageAnnotator/DpImageAnnotator.vue
demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/03/Version20240318172346.php
translations/messages+intl-icu.de.yml

https://demoseurope.youtrack.cloud/issue/DPLAN-11647/Klick-Problem-auf-der-Seite-Importierte-Stellungnahmen-uberprufen-Schulung
The reason for this bug lies in the firefox setting "privacy.resistFingerprinting" when enabled leads to the openLayers method "forEachFeatureAtPixel" to fail. This cannot be fixed on our side. See discussions at openlayers and mozilla:
- https://support.mozilla.org/de/questions/1398931
- https://github.com/openlayers/openlayers/issues/14363
The best we can do (this is implemented here) is to inform users that something will not work with the current settings.
When loading the view in Firefox with "privacy.resistFingerprinting" set to true, an error notification should appear that reads:
**Um alle Funktionen dieser Seite nutzen zu können, deaktivieren Sie in …

DPLAN-11647 ducktest firefox setting

---

templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry_public_citizen.tex.twig

Description:
1. The name of the file was not escaped
2. Now using Latex filter in the template it will be scape, so if the file name is _hello_.png, then the name will be displayed with underscore and not italic
- Follow the steps described in the ticket
- Make sure you use a file that has space in the name, or has unserscore _ in the name

fix (ref DPLAN-11370) Escape special chars to diplay file name using latex

---

config/permissions.yml

DPLAN-11646
The usage of the permission was before only in the twig context and is moved to vue now. while moving, it has been forgotten to expose the permission.
in a project where setting the max-extent should be possible, goto the mapsettings and search for the possibility to set the max extent

fix(refs DPLAN-11646): Expose Permission to control setting the map_max_extent

---

composer.lock

Ticket: 
https://www.dev.diplanung.de/DefaultCollection/BOP-HH/_workitems/edit/16632
Description: 
update version 24.2

F dplan 11422 update composer lock

---

client/js/components/map/publicdetail/Map.vue

[DPLAN-11614](https://demoseurope.youtrack.cloud/issue/DPLAN-11614/ROBOB-Prod-und-Stage-Sobald-ein-WMTS-Layer-eingebunden-ist-werden-alle-Layer-nicht-mehr-dargestellt)
As we do not want to refactor Map.vue to use async all over the place, this is the simplest way of getting synchronous WMTS requests to work.
Prior art:
- https://github.com/demos-europe/demosplan-core/pull/1876
- https://github.com/demos-europe/demosplan-core/pull/1866
WMTS Maps should load and not break the view.
ected to this and explain the connection.

fix(refs DPLAN-11614): use XMLHttpRequest to getCapabilities

---

demosplan/DemosPlanCoreBundle/Logic/Factory/BoilerplateCategoryFactory.php
demosplan/DemosPlanCoreBundle/Logic/Factory/BoilerplateFactory.php

Description: create two factory for Boilerplate and BoilerplateCategory to use in Cckpit
List other PRs that are somehow connected to this and explain the connection.
- https://github.com/demos-europe/demosplan-addon/pull/112
- https://github.com/demos-europe/demosplan-addon-xbauleitplanung/pull/30

feature (ref ADO-16632): create factory for cockpit story

---

templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_edit.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/includes/procedure_newslist.html.twig

Description:
- The file was gotten using core_file. Instead. core_file_procedure must be used to generate the correct url where the file is hosted
- Go as described in ticket
- Make sure you check the News configuration (upload pdf) and also in the Public View
- [ x] Move the tickets on the board accordingly

fix (DPLAN-11584) use method with procedure id to open pdf view correctly

---

client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue

[DPLAN-11685](https://demoseurope.youtrack.cloud/issue/DPLAN-11685/ROBOB-Anzeige-der-Datensatze-funktioniert-nicht)
`flow-root` does not play nice with `v-show` as it is set to `!important`.
In the assessment table, toggling between statement and fragments should result in the statements (or fragments) being exclusively shown in the content area of each card. The "derzeit sind keine Datensätze an der Stellungnahme vorhanden" sentence should only show in the fragment view of the card, and only if there are really no fragments.

fix(refs DPLAN-11685): fix css in assessmentTable

---

yarn.lock

Looks like `yarn upgrade` brings something, not every machine likes. `yarn upgrade jest` should be leaner but fix the problem with `string-width` while building the FE-assets

chore: Run yarn upgrade jest

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig

DPLAN-11551
- Procedure owners should see both phases
- public and invited institutions should see phase depending on role (invited institutions should see internal phase and not public one)
Login as FA: 
Verfahren -> Grundeinstellungen -> Verfahrensschrit Inistitutionen -> Öffentliche Auslegung
Verfahren -> Grundeinstellungen -> Verfahrensschrit Öffentlichkeit -> Konfiguration
Verfahren -> Institutionen verwalten -> Institution hinzufügen
Login as IK from the institution you added:
Verfahren -> Verfahren ansehen -> Verfahrensschritt should be Öffentliche Auslegung

bug (refs DPLAN-11551): Show procedure phase depending on role

---

demosplan/DemosPlanCoreBundle/Repository/ProcedureRepository.php

Description: 
while phases change procedure will be fetched and updated. Customer is missing when a procedure is fetched which caused that customer will be always null after updating
see  'generateObjectValues' in 'ProcedureRepository' to have better Idea how the customer will be handled.

f-DPLAN-11656 include customer in query result 

---

demosplan/DemosPlanCoreBundle/EventListener/AccessProcedureListener.php

DPLAN-609
File uploads failed because permissions are checked more strictly when `X-Demosplan-Procedure-Id` header is set. File uploads should not check procedure permissions even if the file is uploaded within a procedure, as permissions are checked during access.
I tried really hard to write a test for this but was not able to mock the `$controllerEvent->getController()` to return an array.
upload a file in a procedure.

chore (refs DPLAN-609): file uploads itself should not be checked for procedure permissions

---

yarn.lock

Looks like yarn upgrade brings something, not every machine likes. yarn upgrade jest should be leaner but fix the problem with string-width while building the FE-assets
Related PR https://github.com/demos-europe/demosplan-core/pull/3203

chore: Upgrade jest

---

client/js/components/user/DpOrganisationList/DpOrganisationList.vue
client/js/components/user/DpUserList/DpUserList.vue

DPLAN-1910
Vue.delete is removed in Vue3. Better use standard JS delete operator.

bug(refs DPLAN-1910): Use js delete instead of Vue.delete

---

client/js/components/addon/AddonWrapper.vue
templates/bundles/DemosPlanCoreBundle/DemosPlanCore/js/dplan.settings.js.twig

DPLAN-11741
Addons have been loaded every time the component got mounted

fix(refs DPLAN-11741): avoid loading/fetching addons multiple times

---

client/js/components/user/DpUserList/DpUserFormFields.vue

DPLAN-1909
We need whitespace normal for the multiselect, because otherwise the tags overflow the input.
Login as support -> Nutzende -> tags for role should stay inside the input and not overflow

bug(refs DPLAN-1909): Add whitespace normal for multiselect

---

package.json
yarn.lock

There are errors we need to fix first before updating to v28.0

chore: Revert eslint-plugin-jest update

---

demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php

Ticket:
https://www.dev.diplanung.de/DefaultCollection/BOP-HH/_workitems/edit/16169
Description:
Adjust dockBlock of method to not be misleading.

fix (refs ADO-16169): Adjust dockBlock of method to not be misleading.

---

client/js/components/map/admin/LayerSettings.vue
demosplan/DemosPlanCoreBundle/Repository/NewsRepository.php

Description: 
In order to preserve the order of the source procedure news, created date has to beadjusted. The new created procedure has no Manual List Sort yet and the new news will be sorted by created date later, that's why created date has to be adjusted in a way that the first source procedure news will be persisted with the latest date

f-DPLAN-11703 take notifications order in account while procedure creating

---

demosplan/DemosPlanCoreBundle/Services/SubdomainHandler.php
demosplan/DemosPlanCoreBundle/Services/SubdomainHandlerInterface.php

allowedSubdomains are no longer used in SubdomainHandler, documentation was not updated

chore: improve SubdomainHandler docblock

---

client/js/components/procedure/publicindex/DpSearchProcedureMap.vue
client/js/components/procedure/publicindex/drawer/Drawer.vue

DPLAN-1879
The aria-live attribute is used to indicate that an element will be updated, and the screen reader should announce the changes. The value "polite" means that the screen reader will wait until it has finished speaking before announcing updates.

bug(refs DPLAN-1879): Add aria-live for accessibility

---

demosplan/DemosPlanCoreBundle/DataGenerator/Factory/User/OrgaStatusInCustomerFactory.php
demosplan/DemosPlanCoreBundle/DataGenerator/Factory/User/OrgaTypeFactory.php
demosplan/DemosPlanCoreBundle/Logic/Permission/AccessControlService.php
demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
tests/backend/core/AccessControlPermission/AccessControlServiceTest.php

https://demoseurope.youtrack.cloud/issue/DPLAN-11765/Wenn-Planungsburo-Verfahren-anlegen-darf-bekommt-der-Benutzer-ein-Fehlermeldung-beim-erstellen-von-ein-Verfahren
Description:
- In the file demosplan/DemosPlanCoreBundle/Logic/Permission/AccessControlService.php line 134 check the subdomain of the current customer instead of the default config so that the orgaType for the current customer is returned correctly.
- Adjust also demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php line 2137 so that current customer is passed to the AccessControlService method
- Run the tests tests/backend/core/AccessControlPermission/AccessControlServiceTest.php
- Activate checkbox for an orga using customer support role and then login with a planing agency orga to create procedures …

feat (DPLAN-11765) Check customer subdomain instead of globalconfig (default) subdomain

---

demosplan/DemosPlanCoreBundle/Logic/Permission/AccessControlService.php

https://demoseurope.youtrack.cloud/issue/DPLAN-11776/Eine-Rolle-kann-mehrere-Malen-hinzugefugt-sein-blp-ewm
Description:
- some projects like ewm or regio can have multiple roles with the same code stored in DB.
- Because of that, the assert line throws en exception.
- This PR catches the exception and return the first role found in the array
- Log to ewm, blp, regio
- Login to any user
- make sure you can login
https://github.com/demos-europe/demosplan-core/pull/3091

B dplan 11776 catch assert exception

---

client/js/components/procedure/publicindex/DpSearchProcedureMap.vue

DPLAN-1879
Attribute was changed from hidden to hide, see https://github.com/demos-europe/demosplan-ui/pull/894

bug(refs DPLAN-1879): Use the right attribute for label prop

---

demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureHandler.php

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-11794/Ravensburg-Prod-Automatische-Phasenumstellung-funktioniert-nicht
Description: customer have to be a customer object or a customer id, otherwise procedures will be not able to be updated

f DPLAN-11794 use customer id instead array 

---

client/js/components/user/portalUser/PersonalData.vue

https://yaits.demos-deutschland.de/T24505
**Description:** Add `hasIdentityProvider` check to `PersonalData` component and replace inline template with `PersonalData` in BLP project's portal_profile.html.twig file.
login > Meine Daten
[demosplan-project-blp](https://github.com/demos-europe/demosplan-project-blp/pull/1) --> This is an updated PR from 2022

feat(DPLAN-24505): adjust PersonalData component

---

client/css/index.css
client/css/preflight.css
config.webpack.js
demosplan/DemosPlanCoreBundle/Resources/client/scss/_base.dplan.scss
tailwind.config.js
tailwind.preflight.config.js
templates/bundles/DemosPlanCoreBundle/DemosPlanCore/404.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base_oeb.html.twig

The (slightly opinionated) tailwind browser reset, "preflight", sets some defaults that we want to
override with the project css. However, as we also want to include the tailwind utility classes last
(to get rid of making them !important), the preflight styles need to be separately included, not within the same file as the utility classes.
To illustrate the change, here is a before/after comparison of the order and contents of Styles included in demosplan:
**Before:**
- **demosplan-ui.css**
- Tailwindcss Preflight (with opinionated defaults)
- Tailwindcss Utilities (with !important, to win over styles included later in the document while having the same specificity)
- **style.css (or, style-public.css)**
- Base styles (overriding the opinionated defaults of Tailwind, as configured with …

Include Tailwind Preflight as separate file

---

demosplan/DemosPlanCoreBundle/Command/Permission/DisablePermissionForCustomerOrgaRoleCommand.php
demosplan/DemosPlanCoreBundle/Command/Permission/EnablePermissionForCustomerOrgaRoleCommand.php
demosplan/DemosPlanCoreBundle/Command/Permission/PermissionForCustomerOrgaRoleCommand.php
demosplan/DemosPlanCoreBundle/Logic/Permission/AccessControlService.php
tests/backend/core/Core/Functional/Command/DisablePermissionForCustomerOrgaRoleCommandTest.php
tests/backend/core/Core/Functional/Command/EnablePermissionForCustomerOrgaRoleCommandTest.php
tests/backend/core/Core/Functional/Command/PermissionForCustomerOrgaRoleCommandTest.php

https://demoseurope.youtrack.cloud/issue/DPLAN-11799/Befehl-zum-Deaktivieren-Permissions
Description:
1. We want a command that given customer id, role id, and permission, it disables this permission for all the orgas under the given customer and role.
2. The command has customerID roleID and permissionName parameters
3. The command also offers a dry-run, which does not execute the update, it only prints the impacted orgas
4. If customer or role or permission are not found, it throws an exception
1. Type bin/blp dplan:permission:disable:customer-orga-role YOUR_CUSTOMER_ID YOUR_ROLE_ID CREATE_PROCEDURES_PERMISSION --dry-run
2. Adjust param to insert ids based on your db
3. then check if the printed orgas are also removed in the access_control DB
Related to already merged PR about enabling …

F plan 11799 command disable permissions

---

demosplan/DemosPlanCoreBundle/Logic/Permission/AccessControlService.php

https://demoseurope.youtrack.cloud/issue/DPLAN-11470/3-0-BB-Als-Fachplanung-Administration-mochte-ich-keine-neuen-Verfahren-mehr-anlegen-konnen-um-falschliches-Anlegen-in-BLP-zu
Description:
- When the command is run to enable permission for all in a particular customer - role, we should check that which orga type has the orga and if it corresponds to the role given in the command.
- It is like that because we want to avoid cases like:
-- command enables permission CREATE_PROCEDURE for customer XXX and Role PLANNING_AGENCY_ADMIN, and there are orgas that have type Planingburo where actually the role PLANNING_AGENCY_ADMIN is not allowed.
- Using customer support role, find and orga that only has the type PlanungBuro and is accepted in the customer
- Run command bin/blp …

feat (DPLAN-11470) adjust command to take orga type into account

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/utility/_text.scss
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_index.html.twig

As we now got Tailwind breakpoints working, these custom `text-align` mq classes can be dropped as well.
May be tested on the home page of bobsh. The "In allen Beteiligungsverfahren suchen" Header should be left aligned in viewports smaller than 620px width.

feat: drop custom text-align mq utility classes

---

demosplan/DemosPlanCoreBundle/Controller/Segment/SegmentsExportController.php

DPLAN-3268
- use DplanPermissions Attribute instead of deprecated annotation
- add line breaks to avoid too long code line to improve readability
- add throw tags where missing
- add constant for string to improve maintainability
Code Review

feat (DPLAN-3268): Little refactoring of SegmentsExportController

---

client/js/components/procedure/publicindex/map/Map.vue

https://demoseurope.youtrack.cloud/issue/DPLAN-2743/Barrierefreiheit-Karte-hat-keine-Alt-text
- Add aria-label for map.
- Go to BLP Lokal, check for map div container.
- Now with `aria-label="Karte"` attribute.

chore (refs DPLAN-2743): Add aria-label for map.

---

client/js/store/core/VuexApiRoutes.js
client/js/store/core/initStore.js

This is a cherry-pick from https://github.com/demos-europe/demosplan-core/pull/3217 to allow targeting main straight away.

refacor: Create api2.0 Routes Dynamically

---

templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/paragraph_admin_edit.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/paragraph_admin_new.html.twig

DPLAN-11843
The ProcedureId is static in this place and has to be used via twig.

fix(refs dplan 11843): Pass Procedure ID properly to documents editor

---

demosplan/DemosPlanCoreBundle/Controller/AssessmentTable/DemosPlanAssessmentTableController.php

Description: The word search word is called a column in the HashQuery table, so we need to create a new hash after the page refreshing, otherwise the page will be loaded with the same has been adjusted.
Search Word should be removed from search bar after refreshing page

B d2133 remove search bar

---

demosplan/DemosPlanCoreBundle/Logic/Document/ParagraphExporter.php
demosplan/DemosPlanCoreBundle/Twig/Extension/LatexExtension.php
tests/backend/core/Core/Unit/Utilities/Twig/LatexExtensionTest.php

DPLAN-11855
Exports did not support file action with procedure check, which lead to missing pictures in exports.
Upload a file in a paragraph and export the procedure

chore (refs DPLAN-11855): support file paths with procedure

---

demosplan/DemosPlanCoreBundle/Logic/Document/ParagraphExporter.php
templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/paragraph_list_export.tex.twig

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-11684/BLP-Munchen-Bilder-sind-verzerrt-im-Ausdruck
Description: while paragraphs exporting, lists width had to be adjusted

f DPLAN-11684 add listWidth To TemplateVars and pass it on to the latex filter

---

package.json

with the new container 1.8.45 we have yarn@4.2.2 to use that properly, we have to declaire it in the package.json

chore: Bump Yarn@4.2.2

---

yarn.lock

Seems like the yarn.lock was generated with an existing cache directory before. In that case, a `yarn install` with no cache set gives a different yarn.lock.

Updated yarn lock

---

demosplan/DemosPlanCoreBundle/Command/UpdateCommand.php

This looks like some leftovers from decades ago

fix: Remove adding none-existing folder in updateCommand

---

demosplan/DemosPlanCoreBundle/Command/Permission/DisablePermissionForCustomerOrgaRoleCommand.php
demosplan/DemosPlanCoreBundle/Command/Permission/EnablePermissionForCustomerOrgaRoleCommand.php
demosplan/DemosPlanCoreBundle/Command/Permission/PermissionForCustomerOrgaRoleCommand.php
demosplan/DemosPlanCoreBundle/Logic/Permission/AccessControlService.php
tests/backend/core/Core/Functional/Command/PermissionForCustomerOrgaRoleCommandTest.php

DPLAN-11556
To avoid calling the permission:enable command 34 times a possibility is added to provide an array of customers and roles. Along the way a bug was fixed that citizen orga should not be provided with any permissions. Moreover code was deduplicated

allow multiple ids in permission:enable command

---

config/menus.yml
demosplan/DemosPlanCoreBundle/Controller/Document/DemosPlanDocumentController.php
demosplan/DemosPlanCoreBundle/Controller/Map/DemosPlanMapController.php

DPLAN-4020
The menu on the right hand side has to point to an overview page instead of the map settings itself, because we want to extend that section to allow creating and editing layer-settings.
Clicking on "Karteneinstellungen" should lead to a minimap with some links

feat(refs DPLAN-4020): Add Overview Page to Mapsettings

---

demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php

Description: Add message bag for confirm created directly statement

feature (ref 1995): create a message for manually created statement

---

demosplan/DemosPlanCoreBundle/Logic/Permission/AccessControlService.php

DPLAN-11556
Check whether role to grant the permission is allowed in the given orga type to avoid e.g. granting planner permission to institution orga
run command dplan:permission:enable:customer-orga-role with a plnner role in dry-run and ensure that no institution only orgas are listed

chore: check whether role to grant the permission is allowed in the given orga type

---

demosplan/DemosPlanCoreBundle/Controller/Document/DemosPlanDocumentController.php

https://demoseurope.youtrack.cloud/issue/DPLAN-11955/Text-im-Reiter-Element-soll-Karteneinstellungen-heissen
Adjust translation for title

F dplan 11955 adjust translation

---

config/permissions.yml
templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_new.html.twig

https://demoseurope.youtrack.cloud/issue/DPLAN-11957/Verschiedene-Kartenmoglichkeiten-gelten-nicht-fur-EWM
Create permissions instead of overriding the template to display checkboxes
- test ewm: there should not be the checkboxes
- test other project e.g. blp there should be the checkboxes

fix (DPLAN-11957) Create permission to display options

---

client/js/components/statement/publicStatementModal/StatementModal.vue
client/js/components/statement/publicStatementModal/formGroups/FormGroupMapReference.vue
demosplan/DemosPlanCoreBundle/Command/Permission/PermissionForCustomerOrgaRoleCommand.php
tests/backend/core/Core/Functional/Command/PermissionForCustomerOrgaRoleCommandTest.php

- if negative report is set, it should not be possible to send any 'meaningful' data.
- on the other hand if there is already something selected / typed in, it should not be possible to select 'negative_report'
Can be tested on public detail if the procedure is in participation. Check especially the documents relation. for that You need some documents/elements with the posibility to reference them....

fix(refs DPLAN-11801): Prevent negative reports with content

---

config/packages/knpu_oauth2_client.yaml
demosplan/DemosPlanCoreBundle/Controller/Platform/KeycloakController.php
demosplan/DemosPlanCoreBundle/Logic/KeycloakUserDataMapper.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/KeycloakAuthenticator.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/KeycloakUserBadgeCreator.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OzgKeycloakAuthenticator.php
demosplan/DemosPlanCoreBundle/ValueObject/CommonUserData.php
demosplan/DemosPlanCoreBundle/ValueObject/KeycloakUserData.php
demosplan/DemosPlanCoreBundle/ValueObject/OzgKeycloakUserData.php
tests/backend/base/FunctionalTestCase.php
tests/backend/core/Core/Functional/KeycloakUserBadgeCreatorTest.php
tests/backend/core/Core/Functional/KeycloakUserDataMapperTest.php
tests/backend/core/Core/Functional/KeycloakUserDataTest.php

DPLAN-11848
This PR moves the authentication from login via SAML per OneLoginSamlBundle to login per OAuth via OAuth2ClientBundle.
It is mostly a c&p from `SamlUserFactory`, `SamlUserProvider` and friends to new classes that use the OAuth2ClientBundle. Alon the way a lot of tests where added.
It uses the same basis of the value objects like the `OzgKeycloakAuthenticator`, but keeps the logic from the OneLoginSamlBundle whenever possible.
Later on it might be a good idea to merge `OzgKeycloakAuthenticator` and `KeycloakAuthenticator` (and subsequent classes), but to keep this PR as small as possible this was not done yet.
code review or install the branch at the release server and test login

chore: login per keycloak via OAuth2ClientBundle

---

client/js/components/map/admin/AdminLayerList.vue

Description: remove base map and overview map for ewm with permission

feature (ref 11959): use Permissin for map options

---

client/js/components/map/map/DpOlMap.vue
client/js/components/procedure/StatementSegmentsList/SegmentLocationMap.vue

DPLAN-11849
- Boundingbox is an array, so we need to check for length
- Remove unused features ()
Choose a procedure where the initial extent is not set yet (Karteneinstellungen -> Startkartenausschnitt)
Verfahren -> Abschnitte -> Erwiderung verfassen -> Ortsbezug -> There should be a map

bug(refs DPLAN-11849): Set boundingbox only if it exists

---

client/js/store/map/Layers.js
demosplan/DemosPlanCoreBundle/ResourceTypes/GisLayerCategoryResourceType.php
demosplan/DemosPlanCoreBundle/ResourceTypes/GisLayerResourceType.php

DPLAN-11961
Description: get access to delete GisLayer

feature (ref 11961): allow to delete Gislayer

---

Jenkinsfile

Yarn in testcontainer was upgraded to version 4 and throws deprecations

chore: fix yarn 4 deprecations in jenkins pipeline

---

config/permissions.yml
templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_edit.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_new.html.twig

DPLAN-11963
With the fix, A created/ updated Layer should be displayed in the "segements" Map if the permission to set the visibility (feature_map_layer_visibility) is off.
I didn't change the template ecxept of the `if hasPermission` and the following else-blocks

fix(refs dplan-11963): Set layervisibility if the feature is off

---

client/js/components/user/DpUserList/DpUserList.vue

[DPLAN-11931](https://demoseurope.youtrack.cloud/issue/DPLAN-11931/Suche-auf-der-Nutzende-Verwalten-Seite-funktioniert-nicht)
**Description:** This PR adjusts the search URL parameters for the route User list 2.0. 
The question: should it be searchable by **first** and **last** names? If yes, it does not work when I add a second filter with the `path: 'lastname'` or does it work differently?

fix(DPLAN-11899): unable to search users

---

templates/bundles/DemosPlanCoreBundle/DemosPlanUser/alternative_login.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanUser/citizen_register_form.html.twig

If we got a real string from TWIG, we can't try to compute it.

fix: Interpret String as String

---

demosplan/DemosPlanCoreBundle/Command/Data/CopyFaqCommand.php

DPLAN-12006
Copying FAQ from one customer to another is a really annoying and tedious task. This command eases the pain
You probably want to create a new customer via `bin(<projedct> dplan:data:generate-customer`, see that it has no faq and run bin/<project> dplan:data:copy-faq` and be happy about all the faq

chore (refs DPLAN-12006): copy the FAQ from one customer to another

---

demosplan/DemosPlanCoreBundle/Command/Data/GenerateCustomerCommand.php

DPLAN-12006
When the exist the citizen user and the ai api user should be automatically registered to avoid errors
create a new customer via `bin/<project> dplan:data:generate-customer` it should contain two users

chore (refs DPLAN-12006): register default users for new customer

---

client/js/components/support/DpSupport.vue
config/permissions.yml

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-12022/Als-Technischer-Support-mochte-ich-nur-Anfragen-von-bestimmten-Rollen-annehmen-um-Kosten-zu-senken.
Description:
use new permission to read technical support entry.
Rename translation key for 'Inhaltlicher Support' to 'Support'
move over some fix from main to show the Support headline if list not empty
GoTo /informationen in diplanbau/fest/rog and check with and without roles.

fix (refs DPLAN-12022): use new permission to read technical support entry

---

demosplan/DemosPlanCoreBundle/Permissions/Permissions.php

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-11968/BOB-SH-Bau-Stage-Prod-Ein-Planungsburo-kann-ein-anderes-Planungsburo-einladen
Description.:
grant planning_agency invitation permission to fpa-only...
The permission ```field_procedure_adjustments_planning_agency``` was once enable for all and then disabled for private_planning_agencies exclusively within the core.
Something seems to have gone wrong when refactoring this permission...
The enabling of this permission has been removed, but at least one project did not get adjusted accordingly. It would have relied on the core turning the permission off again after it got activated within the project, which does not work....
removed the disabling of this permission here within the core as it only matters for permissions being …

fix (refs DPLAN-11968): grant planning_agency invitation permission to fpa-only

---

demosplan/DemosPlanCoreBundle/Controller/Segment/DraftsInfoApiController.php

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-12068#focus=Comments-4-51132.0-0
Description:
Add interface to event dispatcher
This way the event can be caught inside addons.

fix (refs DPLAN-12068): add interface to event dispatcher

---

demosplan/DemosPlanCoreBundle/Controller/Segment/DraftsInfoApiController.php

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-12068#focus=Comments-4-51132.0-0
Description:
Add interface to event dispatcher.
This way the event can be caught inside addons.

fix (refs DPLAN-12068): add interface to event dispatcher.

---

client/js/components/map/admin/MapAdmin.vue

The Components expects an Object and can't handle (empty) Arrays. Maybe the fix should be done where ever the Array is set. But I couldn't find out where that happens (in acceptable time)
DPLAN-11964

fix(refs DPLAN-11964): Set empty array as empty Object for Territory

---

tests/backend/core/Statement/Functional/TagServiceTest.php

Description:
- Make test of TagServiceTest work again
- Run tests for TagServiceTest in local
- [ x] Tests updated/created

Fix tag service tests

---

client/js/components/map/map/DpOlMap.vue
client/js/components/map/map/DpOlMapLayer.vue
client/js/store/map/ProcedureMapSettings.js

DPLAN-12021
If the Opacity is not 100% but less it should be visible in the segments-map.

fix(refs dplan-12021): Pass Opacity to Segments Map

---

demosplan/DemosPlanCoreBundle/DataGenerator/Factory/Statement/CountyFactory.php
demosplan/DemosPlanCoreBundle/DataGenerator/Factory/Statement/MunicipalityFactory.php
demosplan/DemosPlanCoreBundle/DataGenerator/Factory/Statement/PriorityAreaFactory.php
demosplan/DemosPlanCoreBundle/DataGenerator/Factory/Statement/StatementAttributeFactory.php
tests/backend/core/Statement/Functional/StatementDeleterTest.php

Description:
Fix Statement deleter tests using mocks whenever possible
Run StatementDeleterTest in local.
All tests should pass

Fix Statement Deleter tests

---

client/js/components/procedure/basicSettings/AutoSwitchProcedurePhaseForm.vue

all phases with a "write" permission are participation phases. So we don't have to rely of the string spelling.
DPLAN-11803

fix(refs DPLAN-11803): properly calculate inParticipation phase

---

demosplan/DemosPlanCoreBundle/Controller/Platform/FileController.php
demosplan/DemosPlanCoreBundle/Entity/File.php
demosplan/DemosPlanCoreBundle/Logic/FileService.php
demosplan/DemosPlanCoreBundle/Logic/Statement/StatementCopier.php
demosplan/DemosPlanCoreBundle/Logic/Statement/StatementMover.php
demosplan/DemosPlanCoreBundle/Logic/StatementAttachmentService.php
demosplan/DemosPlanCoreBundle/Repository/FileRepository.php
demosplan/DemosPlanCoreBundle/Repository/StatementRepository.php

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-12009/ROBOB-Prod-Bei-verschobenen-STN-wurden-in-der-Ubersicht-die-Links-von-Anhangen-nicht-angepasst
Description:
All original statement creations where handling their file copy tasks correct as far as setting individual file-entries for all of them. The only problem was a procedureId that was set to late on the new statement in order to be used for those files.
on copy there was a method StatementAttachmentService::copyToStatement that made use of a createAttachment
method that did not create a new file-entry for the attachment but set the same file-reference. Changed this method to use the correct one from the statement-repository.
on move it was more tricky.
When creating new statements - after their originals are done we create …

fix(refs DPLAN-12009): Fix file copies on STN copy to different procedure

---

demosplan/DemosPlanCoreBundle/Logic/Document/DocumentHandler.php
demosplan/DemosPlanCoreBundle/Logic/Document/ElementHandler.php
demosplan/DemosPlanCoreBundle/Logic/Document/ParagraphHandler.php
demosplan/DemosPlanCoreBundle/Logic/Faq/FaqHandler.php
demosplan/DemosPlanCoreBundle/Logic/Forum/ForumHandler.php
demosplan/DemosPlanCoreBundle/Logic/Help/HelpHandler.php
demosplan/DemosPlanCoreBundle/Logic/News/GlobalNewsHandler.php
demosplan/DemosPlanCoreBundle/Logic/News/NewsHandler.php
demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureHandler.php
demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureProposalHandler.php
demosplan/DemosPlanCoreBundle/Logic/Procedure/ServiceStorage.php
demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentHandler.php
demosplan/DemosPlanCoreBundle/Logic/Statement/DraftStatementHandler.php
demosplan/DemosPlanCoreBundle/Logic/Statement/StatementAnonymizeHandler.php
demosplan/DemosPlanCoreBundle/Logic/Statement/StatementFilterHandler.php
demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
demosplan/DemosPlanCoreBundle/Logic/User/CustomerHandler.php
demosplan/DemosPlanCoreBundle/Logic/User/OrgaHandler.php
demosplan/DemosPlanCoreBundle/Logic/User/PublicAffairsAgentHandler.php
demosplan/DemosPlanCoreBundle/Logic/User/RoleHandler.php
demosplan/DemosPlanCoreBundle/Logic/User/UserHandler.php
tests/backend/core/Core/Functional/MessageBagTest.php
tests/backend/core/Core/Unit/Handler/CoreHandlerTest.php

MessageBagInterface should be used in DI everywhere, as otherwise another instance of the MessageBag is instantiated and the collected messages are never shown in the interface

chore: use MessageBagInterface in DI to show all messages

---

client/js/components/user/DpUserList/DpUserFormFields.vue

DPLAN-11488
sometimes a department is not set (yet). So we have to prevent the script from throwing errors in that case. (same with allowed roles)

fix(refs DPLAN-11488): Prevent error on unset departments

---

client/js/components/procedure/SegmentsList/SegmentsList.vue
client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue

DPLAN-1916
- Show warning only if segment has draft list
- Fixed another bug with console errors if segment has no items

bug (refs DPLAN-1916): show warning

---

demosplan/DemosPlanCoreBundle/Logic/ImageLinkConverter.php
demosplan/DemosPlanCoreBundle/Logic/Segment/Export/ImageManager.php
demosplan/DemosPlanCoreBundle/Logic/Segment/Export/Utils/HtmlHelper.php
demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php
demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
demosplan/DemosPlanCoreBundle/ValueObject/SegmentExport/ConvertedSegment.php
demosplan/DemosPlanCoreBundle/ValueObject/SegmentExport/ImageReference.php
tests/backend/core/SegmentExport/HtmlHelperTest.php
tests/backend/core/Statement/Functional/ImageLinkConverterTest.php
translations/messages+intl-icu.de.yml

[DPLAN-11982](https://demoseurope.youtrack.cloud/issue/DPLAN-11982/2-2-Als-Bearbeiterin-mochte-ich-Bilder-in-Stellungnahmetexten-und-dem-Export-anzeigen-konnen-um-Einwendungen-korrekt)
Referenced images in segment text are added to docx export. (segment export)
DATA generates links to images in statement texts in the format "Darstellung_Stell_XXX". DATA adds a class to the link tags so we can filter for the right links in a text. This pr adds logic to adjust these new links to match the format "statementExternId_Darstellung_Stell_XXX", and adds the linked images to the docx exports. The adjusted format is only relvant in the exported file. So in the interface the format that comes from DATA will be used.
code review, For local testing you need "Stellungnahme aufteilen", Images in …

feat (DPLAN-11982): images in segments export

---

demosplan/DemosPlanCoreBundle/Logic/ImageLinkConverter.php
tests/backend/core/Statement/Functional/ImageLinkConverterTest.php

[DPLAN-12156](https://demoseurope.youtrack.cloud/issue/DPLAN-12156/Fehler-bei-Export-wenn-Bilder-sowohl-in-STN-Texten-als-auch-in-Erwiderungstexten-existieren)
I think we have to use the getAbsoluteImagePath() here.
code review

fix (DPLAN-12156): fix path cannot be empty

---

demosplan/DemosPlanCoreBundle/Logic/Segment/Export/ImageManager.php

[DPLAN-12156](https://demoseurope.youtrack.cloud/issue/DPLAN-12166/Beim-Export-von-STN-als-einzelne-DOCX-Dateien-wird-bei-jeder-Datei-am-Ende-eine-leere-Seite-hinzugefugt)
This added check should avoid a page break when no images are present for adding in export.
code review
second try
old pr: https://github.com/demos-europe/demosplan-core/pull/3501

fix (DPLAN-12156): Add no page break if no images are present.

---

client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
client/js/components/statement/splitStatement/CardPaneCard.vue

DPLAN-12154
- Fix segmentation buttons: We need `inline-block` here for the `div` in the addonWrapper and some margin for the icon in the addon
- Fix another bug where we get a console error when recommendationContainer does not exist
~~Move condition for rendering addon component from inside the addon to here, so we don't have an empty div lingering around.
I'm not sure about this approach. We don't have the empty div and therefor no styling issues, but does it make sense to have this condition in core? Or should this logic remain in the addon?~~

bug(refs DPLAN-12154): Fix segmentation buttons

---

demosplan/DemosPlanCoreBundle/Controller/Platform/FileController.php
demosplan/DemosPlanCoreBundle/Logic/FileService.php
demosplan/DemosPlanCoreBundle/Logic/Statement/StatementCopier.php
demosplan/DemosPlanCoreBundle/Logic/Statement/StatementMover.php
demosplan/DemosPlanCoreBundle/Logic/StatementAttachmentService.php
demosplan/DemosPlanCoreBundle/Repository/FileRepository.php
demosplan/DemosPlanCoreBundle/Repository/StatementRepository.php

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-12009/ROBOB-Prod-Bei-verschobenen-STN-wurden-in-der-Ubersicht-die-Links-von-Anhangen-nicht-angepasst
Description:
Merged for project-release here: https://github.com/demos-europe/demosplan-core/pull/3431 https://github.com/demos-europe/demosplan-project-robobsh/pull/85
All original statement creations where handling their file copy tasks correct as far as setting individual file-entries for all of them. The only problem was a procedureId that was set to late on the new statement in order to be used for those files.
on copy there was a method StatementAttachmentService::copyToStatement that made use of a createAttachment
method that did not create a new file-entry for the attachment but set the same file-reference. Changed this method …

fix(refs DPLAN-12009): Apply fix for regio as well since STNs can be copied/moved here as well

---

demosplan/DemosPlanCoreBundle/Logic/Segment/Export/Utils/HtmlHelper.php
tests/backend/core/SegmentExport/HtmlHelperTest.php

[DPLAN-12164](https://demoseurope.youtrack.cloud/issue/DPLAN-12164/ID-fehlt-in-der-Abbildung-US)
[DPLAN-12165](https://demoseurope.youtrack.cloud/issue/DPLAN-12165/Referenz-nicht-als-Hyperlink-markiert-US)
the placement of the class attribut in the a tags should be irrelevant.
code review + run test

fix (DPLAN-12164 & DPLAN-12165): fix image links in export

---

demosplan/DemosPlanCoreBundle/Logic/ImageLinkConverter.php
demosplan/DemosPlanCoreBundle/Logic/Segment/Export/Utils/HtmlHelper.php
demosplan/DemosPlanCoreBundle/ValueObject/SegmentExport/ImageReference.php
tests/backend/core/Statement/Functional/ImageLinkConverterTest.php

[DPLAN-11982](https://demoseurope.youtrack.cloud/issue/DPLAN-11982/2-2-Als-Bearbeiterin-mochte-ich-Bilder-in-Stellungnahmetexten-und-dem-Export-anzeigen-konnen-um-Einwendungen-korrekt)
use correct file path
code review, testing on dev

feat (DPLAN-11982) use correct file path

---

demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-12208/Das-Kopieren-einer-original-Stellungnahme-kopiert-die-weiteren-Anhange-nicht-mit.
Description:
Use the correct method to take attachments into account when copying o-stns
copy ostns with attachments

fix(refs DPLAN-12008): Fix copy of attachments from ostns

---

demosplan/DemosPlanCoreBundle/Logic/Segment/Export/Utils/HtmlHelper.php
tests/backend/core/SegmentExport/HtmlHelperTest.php

[DPLAN-11982](https://demoseurope.youtrack.cloud/issue/DPLAN-11982/2-2-Als-Bearbeiterin-mochte-ich-Bilder-in-Stellungnahmetexten-und-dem-Export-anzeigen-konnen-um-Einwendungen-korrekt)
This should fix the recognition of links when updating them for export.
code review, run test

feat (DPLAN-11982) fix recognition of links

---

demosplan/DemosPlanCoreBundle/EventSubscriber/LogoutSubscriber.php

https://www.dev.diplanung.de/DefaultCollection/EfA%20DiPlanung/_workitems/edit/18403
when redirecting back to beteiligung from keycloak the subdomain needs to be included into the redirect url. This needs to be done dynamically as customer differs
You could set `oauth_keycloak_logout_route: 'http://diplanbau.dplan.local/app_dev.php/?post_logout_redirect_uri=https://something.dplan.local/app_dev.php/impressum'` or something the like in parameters and review URL on logout

chore: add subdomain to oauth_keycloak_logout_route

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_email.html.twig

DPLAN-12231
Planners should be able to edit entire invitation email text to be more flexible about the content
Invite an organisation via email and find the entire text within the textarea, not anymore below

chore refs (DPLAN-12231): allow planners to edit invitation email entirely

---

client/js/components/map/map/DpOlMapLayer.vue

[DPLAN-XXXXX
or
https://www.dev.diplanung.de/DefaultCollection/EfA%20DiPlanung/_workitems/edit/XXXXX
](https://demoseurope.youtrack.cloud/issue/DPLAN-12020/Kartenebene-wird-in-EWM-nicht-angezeigt-in-DiPlanBau-schon)
In the previous fix, the url was adjusted, but not used when creating the layer, so the layer was still not displayed.
- Go to the "Karteneinstellungen" view -> Startkartenausschnitt and set it to an area around Coswig, e.g. like this:
- Hit "Speichern und zurück"
- Go to "Kartenebenen definieren" -> Neue Kartenebene and enter the following data:
**Name***   pick whatever
**URL*** https://maps.deges.de/server/services/AWF_EWMS_WMS_WFS/VKE3251_2_S84_Achse_dxf_25833/MapServer/WMSServer?SERVICE=WMS
**Typ***   WMS
**Layer***   0
**Projektion***   EPSG:25833
**Deckkraft in %*** …

fix(refs DPLAN-12020): use adjusted url to create layer

---

demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadUserData.php

Prod Fixtures should allow planner admins to create procedures by default
create a new database instance with prod fixtures. You should be able to create new procedures

chore: initially fpa should be able to create procedures

---

package.json
yarn.lock

DPLAN-DPLAN-12170
https://www.dev.diplanung.de/DefaultCollection/EfA%20DiPlanung/_workitems/edit/14277
Bumps `dp-consent` so the changes made in https://github.com/demos-europe/cookie-consent/pull/3 become available in demosplan-core.
- Run `yarn && yarn dev:<project>`
- Delete cookies to make the consent bar appear in the project interface
- It should look like this:
Text is adjusted in
- https://github.com/demos-europe/demosplan-core/pull/3528

build(refs AB#14277): bump dp consent

---

demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php

Description:
Use the correct method to take attachments into account when copying o-stns ( already reviewed in https://github.com/demos-europe/demosplan-core/pull/3519 )
copy stns with attachments

F dplan 12208 fix attachment copy on ostn copy

---

tests/backend/core/Core/Unit/Logic/Segment/RpcBulkEditor/SegmentBulkEditorServiceTest.php

[ADO-18954](https://www.dev.diplanung.de/DefaultCollection/EfA%20DiPlanung/_workitems/edit/18954)
fix SegmentBulkEditorServiceTest. testRecommendationUpdate is skipped. I have no idea how to fix this. In SegmentRepository::editSegmentRecommendations the segments are not changed during the test run. I don't know if it worked at all? Test was added here: https://github.com/demos-europe/demosplan-core/pull/3471
run test / code review

fix(refs AB#18954): fix SegmentBulkEditorServiceTest.php

---

client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue

https://www.dev.diplanung.de/DefaultCollection/EfA%20DiPlanung/_workitems/edit/18954
The relationship has to be `tags`, not `tag`.
(See DemosPlanStatementAPIController, where the supported relationships are listed (among them `tags`)). I guess this was changed accidentally in the FE.
Go to the assessment table, add a tag to a statement and save it. There should be no error.

fix(refs AB#18954): send correct relationship to BE

---

demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanAssessmentController.php
demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php

Description: Success notification dependent on Role of user and one of them is about data collector role (Datenerfassung), use a permission to clear when it should be appeared.
create a statement and test the link in success notification.

B ado18953 success notification

---

demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableZipExporter.php
tests/backend/core/Statement/Functional/StatementExportTest.php

[ADO-18561](https://www.dev.diplanung.de/DefaultCollection/BOP-HH/_workitems/edit/18561)
This PR ensures that the ZipExporter no longer extends the xlsExporter. Instead, the xlsExporter is now injected. The export should work exactly as before.
Test the zip export in projects where available. / Code Review / run test

refactor (refs AB#18561): Don't extend xlsExporter

---

templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry_paragraph.tex.twig

Description: refactor latex file and add next line  to adjustment data in pdf export file

Update latex to adjustment data 

---

package.json

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-12105/BOB-SH-BLP-Prod-und-Stage-Andern-oder-hinzufugen-von-Bildern-in-Kapiteln-nicht-moglich
https://demoseurope.youtrack.cloud/issue/DPLAN-11812/Installation-BOBSH-2024.3.4
Description:
add to package.json

fix(refs DPLAN-11812): add to package.json

---

client/js/components/procedure/StatementSegmentsList/StatementSegment.vue

https://demoseurope.youtrack.cloud/issue/DPLAN-12347
- Fix tags display for Segment.
- segment has relationship `tags` not `tag`
- Go to EWM Lokal, login as `Fachplanung-Admin`, then go to `Verfahren` -> `Stellungnahmen` -> `Stellungnahmen mit Abschnitte -> Details und Erwiderungen`
- in `Abschnitt` List, there `#` Mark, when hover you can see now `Schlagworte`

fix (refs DPLAN-12347): Fix tags display for Segment.

---

templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_entry.tex.twig

Description: use new width in latex to adjustment data in pdf export

update latex to adjustment pdf

---

client/js/components/map/publicdetail/DpPublicDetail.vue
demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_actionbox.scss
demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_map.scss
templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_public_participation_detail.html.twig

[DPLAN-2307
](https://demoseurope.youtrack.cloud/issue/DPLAN-2307/Karteneben-ein-ausblenden-verdeckt-Einzeichnen-Werkzeuge)
**Description:** As mentioned in the bug ticket, the toolbar overflows the upper box when it is open. This issue appears to be caused by the toolbars absolute positioning. It is placed at the bottom and opens upwards, which makes it difficult to determine if this behavior is a bug or a feature. 
However, the such behavior can be confusing for users. Adjusted the design as suggested by Ines in the ticket:
_Die aufklapbare Box nach unten akflappen lassen, mit Scrollmöglichkeit.
Die rote (Aktion) Box soll mit im Scrollbereich sein und nicht mehr abgedenkt._

Fix(dplan-2307): map toolbar layout issue

---

templates/bundles/DemosPlanCoreBundle/DemosPlanNews/newsdetail.html.twig

[DPLAN-12326](https://demoseurope.youtrack.cloud/issue/DPLAN-12326/Bild-uberdeckt-Mitteilungstext-Portal-Mitteilungen)
Description: This PR fixes an issue with overlapping images. The `c-image--detail` class adds a `max-width: 530px`, which conflicts with the `max-w-full `class from Tailwind. To resolve this, the `c-image--detail `class has been removed from the Twig template.

fix(DPLAN-12326): image overlaps text

---

config/services.yml
demosplan/DemosPlanCoreBundle/Logic/ConditionFactory/DemosPlanDrupalConditionFactory.php

Description:  add DemosPlanDrupalConditionFactory: in some cases however conditions do have values, we do need the OPERATORS 'IS NULL' and 'IS NOT NULL' and since they are only available in the condition without values, some filters are not working anymore. The DemosPlanDrupalConditionFactory extends the PredefinedDrupalConditionFactory and adds two operators (IsNull and IsNotNull) to the operators with value
Not sure with the name. I am open to any suggestion.

F dplan 12254 custom drupal filter condition factory

---

client/js/components/procedure/publicindex/DpSearchProcedureMap.vue
client/js/components/procedure/publicindex/drawer/Drawer.vue

DPLAN-1879
- Screen reader does not always read the result with "polite".
- Order some attributes and add cypress selectors

bug(refs DPLAN-1879): Change aria live to assertive

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/list_subscriptions.html.twig

DPLAN-1953
We don't have an aside block here, so we can show the content over the whole width.
Login as Privatperson -> Profil icon -> Benachrichtigungen: The table should use the whole width of the page

bug(refs DPLAN-1953): Set full width to true

---

demosplan/DemosPlanCoreBundle/ResourceTypes/UserResourceType.php

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-12385/Userliste-als-Support-ist-nicht-korrekt-nach-Mandant-gefiltert
related to:
https://demoseurope.youtrack.cloud/issue/DPLAN-12372/EWM-Mandant-fur-NOK-anlegen
https://demoseurope.youtrack.cloud/issue/DPLAN-12373/EWM-Mandant-fur-DB-Systel-erstellen
Description:
Fix UserResourceType access conditions for support user to filter available users
- exclude non current customer users as well as citizen and ai-api user

fix(refs DPLAN-12372): Fix UserResourceType access conditions

---

client/js/components/faq/DpFaqCategoryItem.vue
client/js/components/faq/DpFaqItem.vue

[DPLAN-11591](https://demoseurope.youtrack.cloud/issue/DPLAN-11591/FAQ-Verwalten-bearbeiten-Icons-sind-nicht-richtig-ausgerichtet)
**Description:**  This PR fixes an issue with the layout by placing the icons in the same position, wrapping them in a Flexbox.
- before:
- now:
- with delete icons:

fix(DPLAN-11591): layout issue

---

client/js/components/map/map/DpOlMapDrawFeature.vue

DPLAN-12379
Set z index for drawing layer to 1000 to make sure it is always on top. If other layers are on top of it, we can't edit our drawings.
Verfahren -> Planungsdokumente und Planzeichnung -> Startkartenausschnitt -> Edit Startkartenausschnitt and/or Kartenbegrenzung and then try to edit a drawing.

bug(refs DPLAN-12379): Add z index to draw feature

---

config/addons.yml
demosplan/DemosPlanCoreBundle/Addon/AddonInfo.php
demosplan/DemosPlanCoreBundle/Command/Addon/AddonAutoinstallCommand.php
demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php
demosplan/DemosPlanCoreBundle/Command/CacheClearCommand.php
demosplan/DemosPlanCoreBundle/DependencyInjection/Compiler/OptionsLoaderPass.php
demosplan/DemosPlanCoreBundle/DependencyInjection/Configuration/AddonTreeBuilder.php
tests/backend/core/Core/Functional/Command/AddonAutoinstallCommandTest.php

https://www.dev.diplanung.de/DefaultCollection/EfA%20DiPlanung/_workitems/edit/5706
To ease deployment this PR allows to define all addons with their Versions that should be installed and provides a new command to install them e.g. during update or container build
define addons in projects config/addons.yml and call bin/project dplan:addon:autoinstall

Provide command to install automatically all defined project addons

---

templates/bundles/DemosPlanCoreBundle/DemosPlanNews/public_newsdetail.html.twig

https://demoseurope.youtrack.cloud/issue/DPLAN-12400/PDF-in-Aktuelle-Meldung-kann-nicht-heruntergeladen-werden
Adjust how the URL of pdf is gotten in template
1. First login as admin and go to /verfahren/PROCEDURE_ID/verwalten/aktuelles
2. Click on any news and upload a PDF
3. Then logout and check the Verfahren like this:
4. Go to verfahren/PROCEDURE_ID/public/detail and check in the section Aktuelle Mitteiligung if the PDF is clickable
5. Click on Weiter lesen (to go to the details news) and also check that the PDF is clickable and you can see the PDF

F dplan 12400 adjust pdf url

---

demosplan/DemosPlanCoreBundle/Application/DemosPlanKernel.php
docker/demosplan-production/Dockerfile
docker/demosplan-production/nginx.conf.template
docker/demosplan-production/zzz-dplan.ini

https://www.dev.diplanung.de/DefaultCollection/EfA%20DiPlanung/_workitems/edit/17734
To move towards the default symfony 6 directory structure log and cache folders are moved to their default position under var/log and var/cache. During local development a special folder is used to keep the files projectwise separated like var/<project>/log|cache
The usage of the standard structure allows to have a stable path e.g. for log extraction. During local development debugging is easier, as the whole stack is available in the IDE and caches may be deleted there. Moreover the Logfiles are directly available.
The downside to use the default structure was once that docker was quite slow with file synchronization on huge IO (which may be the case for the logfiles). As symfony uses the default path …

chore: reorganize cache & log folders

---

demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-1878/Problem-beim-Neu-Laden-der-Textbaustein-Seite
Description:
prevent resending a post request on page-reload by redirecting to self after a post has been processed.

fix(refs DPLAN-1878): prevent resending a post request on page-reload

---

demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php

Description: show only procedures where statements have been moved

f-DPLAN-12418: show only procedures where Stns have been moved

---

client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerList.vue
client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListLayer.vue
client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListWrapper.vue
client/js/store/map/Layers.js
demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_map.scss

DPLAN-12401
Some fields were missing from the layer request, so the corresponding attributes were `undefined` and some condition checks evaluated to `false`, so elements were not displayed in the interface.
Since for displaying the layers in the navigation, we checked if the attributes `isScope` and `isBplan` were false, the condition evaluated to `false` when the attributes were `undefined`.
I changed the condition to check for falsy to make it slightly more robust.
Apart from the bug fix, this PR also includes a few small improvements.
Go to public detail of a procedure that has overlay layers defined. Make sure they are displayed in the navigation and their opacity can be adjusted. (The opacity slider appears when hovering over the eye icon for toggling layer visibility).

fix(refs DPLAN-12401): add missing fields to request

---

demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/RpcBulkCopyStatements.php
demosplan/DemosPlanCoreBundle/Logic/Report/ReportService.php
demosplan/DemosPlanCoreBundle/Logic/Statement/StatementCopier.php
docker/demosplan-production/Dockerfile

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-12009/ROBOB-Prod-Bei-verschobenen-STN-wurden-in-der-Ubersicht-die-Links-von-Anhangen-nicht-angepasst
Description:
- use 'copyStatementObjectWithinProcedureWithRelatedFiles' instead of 'copyStatementObjectWithinProcedure' to copy statements with container files.
- refactor 'persistAndFlushReportEntries': this method use transaction and try fo flush report while copying statements which cause an exception and close the EntityManager. To avoid that we have to seprate the persisting part from the transaction, and this is done by refactoring 'persistAndFlushReportEntries'. The method 'persistReportEntry' can be used now in the case when we don't want to flush report entities directly after persisting (which is always the case with …

fix: DPLAN-12009 copy statement with file container

---

Jenkinsfile
client/js/components/statement/assessmentTable/Fragment.vue

[DPLAN-12411](https://demoseurope.youtrack.cloud/issue/DPLAN-12411/Datensatze-nicht-sichtbar-via-Abwagungstabelle)
**Description:** This PR fixes the issue by displaying fragments in the STN list: the first letter of the store name should be capitalized.

fix(DPLAN-12411): issue by displaying fragments in the STN list

---

demosplan/DemosPlanCoreBundle/Form/ProcedureUiDefinitionFormType.php
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_procedure_type_edit.html.twig

[DPLAN-1875](https://demoseurope.youtrack.cloud/issue/DPLAN-1875/Fehlerfeld-wird-nicht-gehighlightet-Fehler-Notifcation-gibt-keine-klare-Auskunft)
Description: This PR improves error handling by adding the `maxlength` attribute to the editor, which checks the length, adds a hint for the user and applies an error class `is-invalid` when the conditions are not met.

fix(DPLAN-1875):improve error handling

---

demosplan/DemosPlanCoreBundle/Controller/Document/DemosPlanDocumentController.php
demosplan/DemosPlanCoreBundle/Logic/Statement/ElasticsearchResultCreator.php
demosplan/DemosPlanCoreBundle/Logic/Statement/StatementFragmentService.php
demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
demosplan/DemosPlanCoreBundle/Traits/DI/ElasticsearchQueryTrait.php

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-12428/Fehlermeldung-beim-Original-STn-List
Description:
The params retrieved from the form are parsed as strings. We need an integer to call the method $paginator->setMaxPerPage().
This change within the PagerFanta library was introduced here: https://github.com/BabDev/Pagerfanta/commit/36ab48a0a25e55186b1f002acf5c0ed655b81dae and we have updated to version >3 since the 06.06.24
Added a simple type cast for uses of PagerFanta::setMaxPerPage

fix(refs DPLAN-12428): cast MaxPerPage Param from string to int

---

demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureHandler.php
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_email.html.twig

Description: remove doubled note

f DPLAN-12231 remove doubled note

---

templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/elements_admin_list.html.twig

[DPLAN-12410](https://demoseurope.youtrack.cloud/issue/DPLAN-12410/Keine-Verlinkung-zu-Offentlichkeitsansicht-bei-Planungsdokumente-und-Planzeichnung)
- as in other pages in the admin area, a link to the public participation area should be displayed at the top in the planning documents page
- the `procedure` variable was missing for this to work

fix(refs DPLAN-12410): add link to public detail

---

composer.json
composer.lock

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-1917/Basemap-wird-nicht-per-Default-auf-Startseitenkarte-bei-neuem-Mandanten-eingetragen
Description:
Introduces new constants for use in https://github.com/demos-europe/demosplan-core/pull/3680
Implemented in https://github.com/demos-europe/demosplan-addon/pull/124

fix(refs DPLAN-1917): bump demosplan-addon version to v0.40

---

demosplan/DemosPlanCoreBundle/Entity/User/Customer.php
demosplan/DemosPlanCoreBundle/Logic/ContentService.php
tests/backend/core/News/Functional/GlobalNewsHandlerTest.php

Ticket
https://demoseurope.youtrack.cloud/issue/DPLAN-11379/ADO-Issue-15401-Portal-Mitteilungen-nur-im-Mandanten-sichtbar-in-dem-sie-erstellt-wurden
Description:
Jenkins complains about this test.
globalContent (news) and are expected to include the customer now when fetching entities within the tests.
Throw an invalidArgumentException when trying to fetch a non existing id.

fix(refs DPLAN-11379) the customer got added to the globalContent (news) and are expected to be present when fetching entities within the tests.

---

demosplan/DemosPlanCoreBundle/Logic/ContentService.php
tests/backend/core/News/Functional/GlobalNewsHandlerTest.php

Ticket
https://demoseurope.youtrack.cloud/issue/DPLAN-11379/ADO-Issue-15401-Portal-Mitteilungen-nur-im-Mandanten-sichtbar-in-dem-sie-erstellt-wurden
Description:
the customer got added to the globalContent (news) and is expected to be present when fetching entities within the tests.
throw an invalid argument exception when trying to fetch a global Content by an invalid id.

fix(refs DPLAN-11379) the customer got added to the globalContent (news) and is expected to be present when fetching entities within the tests.

---

client/js/components/map/admin/AdminLayerList.vue
client/js/components/map/admin/AdminLayerListItem.vue
demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_sortablelist.scss
templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_list.html.twig
tests/frontend/unit/__snapshots__/DpAdminLayerList.spec.js.snap

https://demoseurope.youtrack.cloud/issue/DPLAN-12407/Grundkarten-Auge-Icon-und-Bearbeiten-sind-verrutscht-und-da-gibt-keine-Padding-fur-Ubersichtskarte
Lots of spacings and alignments are fixed in the planning documents view:
- table header items are aligned properly
- icons in the table are aligned properly
- spacing above and below items is consistent
- the "Übersichtskarte" heading and the hint are displayed above the select
- the "Kartenebenen" legend is changed to an h2 to better match (and visualize) the logical hierarchy

fix(refs DPLAN-12407): fix spacings and alignments

---

client/js/components/procedure/basicSettings/DpProcedureCoordinate.vue

DPLAN-12484
The layer name was changed [here](https://github.com/demos-europe/demosplan-core/pull/3688), so we need to also change the target name for DpOlMapDrawPoint. 
Verfahren -> Grundeinstellungen -> Verortung des Verfahrens -> You should be able to draw a point.

bug(refs DPLAN-12484): Fix target name for ol map draw point

---

client/js/components/statement/assessmentTable/DpEditSelectedItemsMenu.vue
client/js/components/statement/assessmentTable/DpSelectedItemsStatements.vue
client/js/lib/statement/AssessmentTable.js

[DPLAN-2252](https://demoseurope.youtrack.cloud/issue/DPLAN-2252/Losch-Aktionen-hebt-Sortierung-anhand-der-Filtern-auf-in-A-Tabelle)
**Description:** This PR provides the option to update the hash or leave it unchanged before submitting the form (the issue with the store name was fixed along this PR)

fix(DPLAN-2252): sorting is lost after form submit

---

client/js/components/statement/assessmentTable/EditableText.vue

**Ticket:** [DPLAN-12449](https://demoseurope.youtrack.cloud/issue/DPLAN-12449/Geschwarzte-Stellungnahme-Text-ist-sichtbar-in-Offentlichkeit-Ansicht)
**Description:** This PR fixes an issue where the `<dp-obscure>` tag was not being applied because the `transformObscureTag` function was not triggered. This function should be executed with every update action, otherwise, the `<dp-obscure>` tag will not be transformed as expected.
However, executing it with every update action causes another bug, [DPLAN-12305 Prevent Cursor from Jumping to End of File](https://github.com/demos-europe/demosplan-ui/pull/995). To resolve this, the transformed text should be processed outside the input event to avoid updating the full text directly.
I think it's because `fullText` is a `v-model` of the editor, …

Fix(DPLAN-12449): dp-obscure tag not being applied

---

demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentHandler.php
demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableDocxExporter.php
demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-12514
Description:
Use the correct time zone when embedding the current time within file names.

F dplan 12514 add berlin time to filenames

---

client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue

DPLAN-12380
Changed 'assessmentTable' to 'AssessmentTable' in the Vuex mutation subscription to ensure the toggleView method is called correctly.
Verfahren -> Abwägungstabelle -> Change "Ansicht" -> view should change accordingly
<!--

bug(refs DPLAN-12380): Correct typo in Vuex mutation subscription

---

client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
demosplan/DemosPlanCoreBundle/Controller/Segment/SegmentController.php
demosplan/DemosPlanCoreBundle/Logic/Router.php
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_statement_segments_list.html.twig

https://demoseurope.youtrack.cloud/issue/DPLAN-3304/ADO-Issue-14299-Integration-EWM-Part-1-Aktivierung-der-Aufteilung-Verschlagwortung-und-STN-und-Abschnittsliste-zur-Erwiderung
- Enable going to the details page
- Display meta data
- Go to a detail page of stn
- the details page should be displayed (before this PR it was throwing an error)

I t35963 adjust procedure details page

---

client/js/components/statement/assessmentTable/DpSelectedItemsStatements.vue
client/js/components/statement/assessmentTable/DpTable.vue
client/js/lib/statement/AssessmentTable.js
client/js/store/statement/Statement.js

[DPLAN-2252](https://demoseurope.youtrack.cloud/issue/DPLAN-2252/Losch-Aktionen-hebt-Sortierung-anhand-der-Filtern-auf-in-A-Tabelle)
**Description:** This PR adds the option to pass the current `filterHash` into the `submitForm` method, as there are cases where the `filterHash` should not be updated and should use the current one, especially for the delete action. 
Additionally, the request to route `dplan_assessmenttable_view_table` was missed, even though the tag did not need to be updated, the request should still be made

Fix(DPLAN-2252): issue where the 'remove' action was resetting the sorting option

---

client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListLayer.vue
demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_map.scss

[DPLAN-12522](https://demoseurope.youtrack.cloud/issue/DPLAN-12522/Transparenzeinstellung-ist-verschoben)
**Description:** This PR fixes an issue with the position of the opacity control slider (in the Robobsh, bobsh projects) by adding padding to the toggle opacity control button. In the Robobsh project the button is somehow smaller than in Diplanbau (did not find why..), so adding padding makes it same across these projects. The original PR where the top position was changed is [here](https://github.com/demos-europe/demosplan-core/pull/3663).

Fix(dplan 12522): position of the opacity control slider

---

client/js/store/statement/Fragment.js

[DPLAN-12567](https://demoseurope.youtrack.cloud/issue/DPLAN-12567/Fehler-beim-abwahlen-von-Orga-fur-Datensatz)
`
Description: This PR fixes an issue where NO one department was saved in the fragment. The error was caused by the department field being present in the response, but `data` field was epmty

fix(DPLAN-12567): issue by saving department in fragment

---

client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_statement_segments_list.html.twig

https://demoseurope.youtrack.cloud/issue/DPLAN-12488/Klick-auf-Informationen-anheften-funktioniert-noch-nicht
Pinning statement information in the (new) statement detail view is fixed by making sure all variables are defined: 
- `statementFormDefinitions` need to be prepared in twig to be consumable in vue
- `gdprConsent` and `original` do not exist as statement attributes and were replaced with `consentRevoked` and `submitterAndAuthorMetaDataAnonymized`

fix(refs DPLAN-12488): fix pinning statement information

---

client/js/components/map/admin/MapAdmin.vue
client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
client/js/store/map/ProcedureMapSettings.js
demosplan/DemosPlanCoreBundle/Controller/Map/DemosPlanMapController.php
demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureTemplateResourceType.php
templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin.html.twig

DPLAN-12552
- Use `useGlobalInformationUrl` instead of `featureInfoUrl.global`. It seems like this was renamed. `featureInfoUrl` is not available anymore. 
- Add prop `isMaster` to check if we are in procedure or in master
- Make resource type dynamically depending on procedure or master
Blaupausen -> Planungsdokumente und Planzeichnung -> Startkartenausschnitte -> Everything should be working as expected

bug(refs DPLAN-12552): Distinguish between master and procedure

---

client/js/components/statement/listStatements/ListStatements.vue
templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_statements.html.twig

https://demoseurope.youtrack.cloud/issue/DPLAN-12495/Klick-auf-Neue-Stellungnahme-funktioniert-nicht
Description:
- Display new stn button on stn list based on permissions:
- In ewm it goes to .../import 
- for other projects like diplanrog it should go to ../manual
- Go to diplanrog, the stn should to to create manual stn 
- in EWM it should go as usual
- It is a general template, so it is good to check these 2 projects
- [ x] Link all relevant tickets

F dplan 12495 adjust create statement

---

client/js/components/statement/assessmentTable/DetailView/DetailView.vue

[DPLAN-12564](https://demoseurope.youtrack.cloud/issue/DPLAN-12564)
**Description:** This PR fixes an issue where the details page of STN was empty. The issue was caused by an incorrect reference to the store, it should be `tags` instead of `tag`, as `tag` does not exist.
EIne Stellungnahme erstellen -> zur Detailansicht navigieren -> Seite ist komlett leer

fix(DPLAN-12564): empty detail page of STN

---

client/js/components/statement/assessmentTable/SearchModal/SearchModal.vue

https://demoseurope.youtrack.cloud/issue/DPLAN-2128/SUCHE-erweiterte-Suche-wird-nach-einmaliger-Suche-geloscht
This PR solves that a selection of checkboxes will be lost after submitting an expanded search via the `SearchModal.vue` component. To tackle this issue, the `SearchModal.vue` component can now persist the selection of those checkboxes via the local storage of the browser and load the selection on mounted from there. Also the selection must be resetable hence the local storage including the selected checkboxes will be removed when clicking the reset button.
- checkout branch
- login as FPA (e.g. Tyrion Lannister)
- navigate to assessment table
- click the `Erweiterte Suche`-button and select any checkboxes
- submit -> after the page reload, the selection should be saved
- reset …

bug(refs DPLAN-2128): persist checkbox selection of search modal in local storage

---

demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php

[DPLAN-12536](https://demoseurope.youtrack.cloud/issue/DPLAN-12536/Doppelte-Notifications-fur-erstellen-von-eine-Stellungnahme)
A while ago, no success message was displayed at all. As a fix, a message was added (here: [DPLAN-1995](https://demoseurope.youtrack.cloud/issue/DPLAN-1995/Confirm-Message-fehlt-nach-Speichern-einer-Direkteingabe)) where I would now remove it. After removing it, one message should displayed again.
test in interface

feat (refs DPLAN-12536): remove duplicated success message

---

client/js/components/procedure/SegmentsList/SegmentsList.vue

https://demoseurope.youtrack.cloud/issue/DPLAN-12496/Filterung-bricht-um-wenn-alle-Filter-gesetzt-sind
- with reduced margin, all filter flyout triggers still fit in one line if a filter is selected in each of them
- also, the filter label was vertically aligned to align properly with the filter flyout triggers
- go to segments list
- select a filter in each filter flyout
- make sure all filter flyout triggers are still displayed next to each other:

fix(refs DPLAN-12496): reduce margin

---

client/js/components/document/ElementsAdminList.vue
translations/messages+intl-icu.de.yml

DPLAN-12537
Show text when there no plandocuments.
Verfahren -> Planungsdokumente und Planzeichnung -> Text should be shown if there are no plandocuments

bug(refs DPLAN-12537): Add fallback text for no plandocuments

---

tests/backend/bootstrap.php

This PR removes an attempt to fix the file permission during testing that never really worked and with the new cache folder breaks things
run tests, they should start

chore: custom fix to set permissions is not needed any more

---

config/permissions.yml
demosplan/DemosPlanCoreBundle/Logic/Procedure/ExportService.php

Description: Add Permission to manage who can see cover page (titelblatt) in pricedure zip export file

Add permission to manage Cover page export file

---

.github/dependabot.yml

Like mentioned here: https://github.com/demos-europe/demosplan-core/pull/3172#issuecomment-2233597383 the version of ol should be in sync with the one used by the masterportal. The version of masterportal we are currently using is 2.40.0 which uses ol 9.2.4 hence to prevent updates of this dependency which could be potentially incompatible, this version of ol should be set fixed via the dependabot configuration file.
The downside is we need to track masterportal updates and adjust the dependabot.yml accordingly and I am not sure where and if we should document this (further than in a comment)
Masterportal dependencies can be investigated here: https://bitbucket.org/geowerkstatt-hamburg/masterportalapi/src/master/package.json

chore: sync version of ol used in the masterportal

---

demosplan/DemosPlanCoreBundle/Twig/Extension/FileExtension.php
templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/elements_admin_list.html.twig

DPLAN-564
Default value to use automatic chunk size is 'Infinity', not '0'
Upload huge files e.g. in document section

chore (refs DPLAN-564): allow upload of huge files

---

client/js/components/statement/listStatements/ListStatements.vue

DPLAN-12600
The link was only added to compare old and new details page and should be removed now.
Verfahren -> Stellungnahmen -> Click on three dots -> There should be only a link to "Details und Erwiderungen" and no link to "Detailansicht"

bug(refs DPLAN-12600): Remove link to old details page

---

client/js/components/procedure/SegmentsList/SegmentsList.vue

DPLAN-1967
The overflow-x: auto on the container sets overflow-y to hidden. To solve this, min height is added to the container so flyout has always enough space.
You need a procedure with only one small segment. 
Verfahren -> Abschnitte -> Check fly out

bug(refs DPLAN-1967): Add min height

---

demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
tests/backend/core/Core/Unit/Logic/PermissionsTest.php

[DPLAN-12497](https://demoseurope.youtrack.cloud/issue/DPLAN-12497/Abwagungstabelle-in-der-Ansicht-entfernen)
To remove the assessment table for specific projects I removed the activation of the permission "area_admin_assessmenttable" in the core. Then I enabled the permission only in the projects where needed. 
code review, check different project configuration in interface

feat (DPLAN-12497): remove assessmenttable in specific projects

---

templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/DemosPlanAssessment/view_statement.html.twig

DPLAN-12608
Access to the twig is already restricted with this permission: feature_statement_data_input_orga. Everyone who has this permission is also allowed to view the source statement.

bug(refs DPLAN-12608): Remove permission

---

client/js/components/statement/StatementExportModal.vue

DPLAN-12611
Radio labels have word-break: break-word, but DOCX etc. seems not to count as one word and therefor breaks if there is not enough space.
Verfahren -> Stellungnahmen -> Exportieren -> Click on XLSX -> DOCX and ZIP should not break

bug(refs DPLAN-12611): Set max width

---

config/menus.yml
config/permissions.yml

[DPLAN-12497](https://demoseurope.youtrack.cloud/issue/DPLAN-12497/Abwagungstabelle-in-der-Ansicht-entfernen)
This PR adds a new permission for the subheading "Auswertung" in the side menu.
code review, test the interface of different projects -> is the subheading visible if permission is enabled?

feat (DPLAN-12497): add permission for subheading

---

config/permissions.yml
demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php

[DPLAN-12620](https://demoseurope.youtrack.cloud/issue/DPLAN-12610/Abschnitt-erstellen-funktioniert-nicht)
This PR adds a new permission 'feature_allow_update_on_non_manual_statements' to allow updates on non manual statements. 
code review, assign a non manual statement in a project where the new permission is enabled.

feat (DPLAN-12610): Allow update on non manual statements

---

client/js/components/statement/publicStatementModal/StatementModal.vue
client/js/components/statement/publicStatementModal/StatementModalRecheck.vue
client/js/components/statement/publicStatementModal/formGroups/FormGroupEvaluationMailViaSnailMailOrEmail.vue
client/js/components/statement/publicStatementModal/formGroups/FormGroupMapReference.vue
translations/messages+intl-icu.de.yml

[DPLAN-12516](https://demoseurope.youtrack.cloud/issue/DPLAN-12516/Unnotiger-Leerraum-im-Stellungnahme-Fenster)
Fixes several layout issues in the statement modal:
- extra white space is removed where possible
- the layout is made responsive (this was broken)
- the 'minimize' button (instead of close button) is restored and adjusted: instead of displaying the hint always next to the button, it is displayed as a dismissible inline notification
- semantic html is used in some places to improve accessibility
- some css classes were replaced with tailwind classes (but probably not all)
The best way of reviewing this PR would be to check the statement modal (first tab only in the case of users that are not logged in) in different configurations, for different users, and for different screen …

fix(refs DPLAN-12516): fix statement modal layout

---

templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_original_entry.tex.twig

Description: Adjustment exported Original statement Table width in ZIP form

Adjustment Table width

---

templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/elements_admin_list.html.twig

This is the core PR part to pass a csrf token to a upload form of an addon.
https://github.com/demos-europe/demosplan-addon-bimschg-antrag/pull/36

chore: pass csrf token to addon wrapper

---

demosplan/DemosPlanCoreBundle/ResourceTypes/InvitablePublicAgencyResourceType.php

Description: 
since the last EDT update, we have to check and disallow empty lists for propertyHasNotAnyOfValues. In this case the 'invitedOrgaIdsCondition' has to be returned even with a empty value ( when there are no invited institutions yet ) otherwise the condition will return null.

f DPLAN-12620 adjust InvitablePublicAgencyResourceType :

---

templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/new_public_participation_statement_confirm_entry.html.twig

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-12643/Datei-unter-Stellungnahme-Mitzeichnen-Seite-nicht-verfugbar-und-weiterleitet-zu-Fehlerseite
Description:
Use the correct route to get file entities with related procedure id

fix(refs DPLAN-12643) Add procedureId and change route to retrieve file.

---

client/js/components/statement/splitStatement/AssignedTags.vue
client/js/components/statement/splitStatement/FloatingContextButton.vue

demosplan-ui does only define semantic tokens for tailwind colors, not primitive ones.

fix: use `bg-surface` as `white` is not defined

---

templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_entry.tex.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanCore/pdfexport.tex.twig

https://demoseurope.youtrack.cloud/issue/DPLAN-2197
Reverts demos-europe/demosplan-core#3772
There are missing latex packages at suse. This fix isn't needed for the current release, therefore it can be postponed.

Revert "Adjust File name in pdf export"

---

templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/pageheader.html.twig

https://demoseurope.youtrack.cloud/issue/DPLAN-12622/Als-Fachplanung-kann-ich-aus-der-Offentlichkeitsansicht-nicht-zuruck-in-die-Bearbeitungsansicht-navigieren
The button "Verfahren bearbeiten" was initially linked to the `"area_admin_assessmenttable"` permission but is no longer dependent on it. I have decided to use a different permission that better aligns with the button's purpose.
- The `"area_admin_assessmenttable"`permission was originally set using the setProcedurePermissions method for ownsProcedure (see: demosplan/DemosPlanCoreBundle/Permissions/Permissions.php:528).
- With the removal of the assessment table, this permission has been eliminated from the core and shifted to projects that still use the assesment table.
- Since `"area_admin_assessmenttable"` permission  will …

fix (DPLAN-12622) Adjust permission to display button

---

demosplan/DemosPlanCoreBundle/Logic/Statement/StatementCopier.php

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-12677
Description:
Replacement for https://github.com/demos-europe/demosplan-core/pull/3862 with release as target branch.
We do have to flush the new copied statement here if the original statement has no FileContainers otherwise the new copied statement is already flushed while copying FileContainers in the previous method 'addFilesToCopiedStatement'.

f DPLAN-12677 flush statement without container file while copying:

---

demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
tests/backend/core/Core/Unit/Logic/PermissionsTest.php

Description: Institution Cordinator should not have access to vote statement in every Project (base on conversation with PO), Therefor we can remove this permission for this role from core

Remove a permission that give institute coordinator to vote

---

client/js/components/procedure/admin/DpAddOrganisationList.vue

when permission field_organisation_competence is false, it produced an empty object. in some logic it ws tried to find an attribute field within that object, which lead to an error.
DPLAN-12651

fix(refs DPLAN-12651): Prevent undefined header fields

---

demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php

https://demoseurope.youtrack.cloud/issue/DPLAN-12666/Alte-Informationen-auf-Ubersichtsseite-sollen-bei-EWM-Integration-entfernt-werden
The stats in the Procedure Page are displayed based on this permission feature_statements_statistic_state_and_priority
Due the MVP also having stats (the ones that are in EWM), we do not need the old ones.
Go to a details page of Verfahren and the old stats should not be there

B dplan 12666 remove stats permission

---

demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/10/Version20241022180950.php
demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php

Description: The input/entry number length can have a maximum of 35 characters but it can be sometimes too long, that' why it has to be adjusted

f DPLAN-12711 adjust statement intern id length

---

templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_original_statements.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_statements.html.twig

https://demoseurope.youtrack.cloud/issue/DPLAN-12672
The hook in the statement list should be changed back to `createStatement` as that is how it is used in cypress tests already (and the original statement list should have the same hook).

fix(refs DPLAN-12672): rename datacy hook

---

composer.json
composer.lock

Ticket:
https://demoseurope.youtrack.cloud/issue/BEAA2-10/AP-1-Schnittstellenumsetzung-zwischen-DiPlanBeteiligung-und-mein.berlin.de
Description:
bump the demosplan-addon version to v0.42 merged here: https://github.com/demos-europe/demosplan-addon/pull/126

fix(refs f_BEAA2-10_bump demosplan-addon version v0.42

---

client/js/components/statement/assessmentTable/DetailView/DetailView.vue

DPLAN-12740
ADO 21091
For whatever reason the call for the getter "tags" was changed to "tag". But it has to stay tags

fix(refs DPLAN-12740): Get correct Getter "tags"

---

client/js/components/map/admin/AdminLayerList.vue
config/permissions.yml
demosplan/DemosPlanCoreBundle/ResourceTypes/GisLayerResourceType.php
translations/messages+intl-icu.de.yml

Description: in some projects, a procedure had to have at least one layer, that's means that users supposed not be able to all existing layers. The resource type is adjusted in this pr to check and make sure that users can not anymore delete all layers and introduce a new permission that will be only used in projects where procedure had to have at least one layer.
Note:  we don't have in this case a bulk delete that's why this approach cover not that.

F dplan 12618 check if one layer al least is available

---

client/js/bundles/user/customersettingsmail.js
demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanCustomerController.php
templates/bundles/DemosPlanCoreBundle/DemosPlanUser/customer_settings_update_mail.html.twig

since we are not in a procedure, we can't have a procedureId which is required by the boilerplate component.
An Error Occured only in dev-mode. Bit also in prod-Mode no Boilerplates where shown, So we can remove the code.
On my way I moved something closer to vue
DPLAN-12776

fix(refs dplan-12776): Remove Email Boilerplates in Customer Settings Update mail

---

composer.json
composer.lock
config/services.yml

Ticket:
https://demoseurope.youtrack.cloud/issue/BEAA2-10/AP-1-Schnittstellenumsetzung-zwischen-DiPlanBeteiligung-und-mein.berlin.de
Description:
Update Demosplan-Addon to v0.43 to include an OrgaResourceTypeInterface

fix(refs f_BEAA2-10) update to demosplan-addon v0.43

---

client/js/components/user/CustomerSettings/CustomerSettings.vue
client/js/components/user/CustomerSettings/CustomerSettingsBranding.vue
demosplan/DemosPlanCoreBundle/ResourceTypes/BrandingResourceType.php

it always was supposed to work like so
and it makes more sense.
Now we don't have to pass the data to the component anymore.
Before it worked, but it was'nt possible to save styling-changes if no img where present.
As Support goto customer-settings page and try to change the styling without an uploaded image
DPLAN-12775

fix(refs dplan-12775): Move customerBranding logic to Store

---

client/js/InitVue.js

It looks like the name of the components for written in TS is not accessible like before. So we have to put the name straight away which is even cleaner imho
DPLAN-12776
Part of the vue3-Migration DPLAN-12315 
https://github.com/demos-europe/demosplan-core/pull/1151

fix(refs dplan-12776): Make TS-Components mount

---

client/js/components/assessmenttable/DpNewStatement.vue
client/js/components/button/BackToTopButton.vue
client/js/store/statement/Statement.js
templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig

DPLAN-12767
This is part of the Vue3 Migration https://github.com/demos-europe/demosplan-core/pull/1151
The validation for a dropdown (dpmultiselect used as single select) didn't work. So I decided to swap it with a  simple dpSelect. For that the datastructure had to be changed a little

fix(refs  dplan-12767): Make create statement work again

---

composer.json
composer.lock
symfony.lock

https://www.dev.diplanung.de/DefaultCollection/EfA%20DiPlanung/_workitems/edit/17164
symfony/inflector is not used any more by the code and is unmaintained. It could be deleted entirely

chore (refs AB#17164): remove unused unmaintained symfony/inflector

---

config/packages/nelmio_security.yaml

https://www.dev.diplanung.de/DefaultCollection/EfA%20DiPlanung/_workitems/edit/17164
Ancient IE XSS Protection has been deprecated and needs to be removed https://github.com/nelmio/NelmioSecurityBundle/pull/342
Since nelmio/security-bundle 3.4.0: The "xss_protection" option is deprecated, use Content Security Policy without allowing "unsafe-inline" scripts instead.
Deprecation should be gone

chore: remove deprecated xss_protection

---

templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry_paragraph.tex.twig

Description: Add Backslash to go to next line

Add backslash to create new line

---

demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
demosplan/DemosPlanCoreBundle/ValueObject/Statement/StatementViewed.php

DPLAN-12660
This change improves export performance by 82% by creating bulk report entries instead of single entries
20.9 s → 3.79 s
for the complete export even more
12 min 19 s → 23.2 s
Export statements in ATabelle

chore refs(DPLAN-12660): massively improve performance in docx export

---

demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureHandler.php

The maintenance command should use the new and more reliable ProcedureDeleter that is used and tested in the procedure delete command as well.
Delete procedures and purge them via maintenance command

chore: switch to new ProcedureDeleter

---

client/js/store/map/Layers.js

DPLAN-12814
The Layer didn't know in which projection it was saved, so the request defaulted to the map projection. To fix that, the field in the api request had to be added.

fix(refs DPLAN-12814): Get Projection per Layer in Public Detail

---

client/js/store/statement/Statement.js

DPLAN-12699
This issue is related to the statement-List/a-table refactoring [i_T35963_integrate_project_features](https://github.com/demos-europe/demosplan-core/tree/i_T35963_integrate_project_features)
As FPA goto A-Table -> Table should load.
Adjust permission-Check that municipalities only get requested if they are present. 
May be untestable because an Pagerfanta update crashes the a-table atm.

fix(refs DPLAN-12699): Don't request Municipalities if not enabled

---

client/js/components/procedure/SegmentsList/SegmentsList.vue

https://demoseurope.youtrack.cloud/issue/DPLAN-12460/Bei-Abschnittsliste-mit-wenigen-Eintragen-sind-nach-Klick-auf-drei-Punkte-die-Optionen-abgeschnitten
This PR is a cherry pick from https://github.com/demos-europe/demosplan-core/pull/3793 to add this bugfix to the deployment branch. I have overseen that this fix is missing for the deployment branch it is relevant for.
(cherry picked from commit 878698f01aa917edced7b27b2b4527efc1718973)
Delete the checkbox if it doesn't apply/isn't necessary

bug(refs DPLAN-1967): Add min height (3793)

---

client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue

[DPLAN-12730](https://demoseurope.youtrack.cloud/issue/DPLAN-12730/Original-STN-Anhang-wird-in-Detailansicht-nicht-angezeigt
)
I removed this permission check to show original attachment link. Do you think we need a permission check here? If yes, maybe we need a new permission, because the previous one is not suitable anymore.
code review, check link in interface

feat (DPLAN-12730): show original attachment link

---

client/js/components/map/admin/AdminLayerListItem.vue

https://demoseurope.youtrack.cloud/issue/DPLAN-12817/ROBOBSH-Icons-bei-Kartenebenen-werden-nicht-angezeigt
This PR fixes broken icons in the plan drawing view for an overlay. Simply a `fa` class has been missing, which is needed to render the icons correctly. Also to center the icon within its wrapper some flex classes have been added to it.
- Login as FPA
- navigate to plan drawings settings
- create an overlay
- make sure the icons will be rendered correctly (e.g. when hovering)
https://github.com/demos-europe/demosplan-core/pull/3983 (fix for main branch)

bug(refs DPLAN-12817): fix icons for map layers

---

client/js/components/map/admin/AdminLayerListItem.vue

https://demoseurope.youtrack.cloud/issue/DPLAN-12817/ROBOBSH-Icons-bei-Kartenebenen-werden-nicht-angezeigt
This PR fixes broken icons in the plan drawing view for an overlay. Simply a `fa` class has been missing, which is needed to render the icons correctly. Also to center the icon within its wrapper some flex classes have been added to it.
- Login as FPA
- navigate to plan drawings settings
- create an overlay
- make sure the icons will be rendered correctly (e.g. when hovering)
https://github.com/demos-europe/demosplan-core/pull/3982 (fix for the deployment branch)

B dplan 12817 fix icons in plan drawing view

---

config/permissions.yml
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig

[DPLAN-12809](https://demoseurope.youtrack.cloud/issue/DPLAN-12809/Daten-im-Export-entfernen)
This PR adds a permission to enable or not enable the feature to configure which data will be used in export.
code review, test interface in projects

feat (DPLAN-12809): wrap feature in permission

---

client/js/components/map/admin/AdminLayerList.vue
config/permissions.yml
demosplan/DemosPlanCoreBundle/ResourceTypes/GisLayerResourceType.php
translations/messages+intl-icu.de.yml

Description: there are procedure that have no layers, that's this has to be reverted

Revert "F dplan 12618 check if one layer al least is available (3905)"

---

demosplan/DemosPlanCoreBundle/Entity/Document/Paragraph.php
demosplan/DemosPlanCoreBundle/Logic/Statement/DraftStatementFileHandler.php
demosplan/DemosPlanCoreBundle/Logic/Statement/StatementAnonymizeService.php
demosplan/DemosPlanCoreBundle/Repository/DraftStatementFileRepository.php

https://demoseurope.youtrack.cloud/issue/DPLAN-12733/Stellungnahme-anonymisieren-Fehler-bei-Loschen-von-Anhangen
- The anonymization of attachments means to delete all attachments of original statement
- If you try to delete all attachments from an original statement created by a private user, an error occurs because the files are linked to the user's draft statement.
- More concrete, the error is: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`YOUR_PROJECT_DB`.`draft_statement_file`, CONSTRAINT `FK_XXXXXXXXX` FOREIGN KEY (`file_id`) REFERENCES `_files` (`_f_ident`))
- In order to solve it, this PRs checks if there are draft statements related to the file. If not, …

B dplan 12733 fix entity manager closed

---

demosplan/DemosPlanCoreBundle/Logic/ApiRequest/JsonApiResourceTypeService.php

Ticket:
https://demoseurope.youtrack.cloud/issue/BEAA2-10/AP-1-Schnittstellenumsetzung-zwischen-DiPlanBeteiligung-und-mein.berlin.de
Description:
On create requests there was a messageBag trans key given that was missing.

fix(refs f_BEAA2-10) use an existing trans key.

---

demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureToLegacyConverter.php
demosplan/DemosPlanCoreBundle/Logic/Procedure/ServiceStorage.php
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig

Ticket:
https://demoseurope.youtrack.cloud/issue/BEAA2-10/AP-1-Schnittstellenumsetzung-zwischen-DiPlanBeteiligung-und-mein.berlin.de
Description:
procedure setting fields got introduced here: https://github.com/demos-europe/demosplan-core/pull/3889
handle updates containing the newly added procedure-setting fields.
provide these fields for get requests in legacy array format.

fix(refs f_BEAA2-10) save copyright and alt texts for

---

demosplan/DemosPlanCoreBundle/Entity/User/User.php
tests/backend/core/DemosPlanCoreBundle/Entity/User/SecurityUserTest.php

Description: remove logic exception and set return empty string, if Email Auth code is not set. Because in `portal_profile_2fa.html.twig` we need null value, that user can to set 2fa .

getEmailAuthCode can to return null

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig

[DPLAN-12690](https://demoseurope.youtrack.cloud/issue/DPLAN-12690/Alle-Hilfe-Icons-unter-Grundeinstellungen-sind-nicht-zentriert)
As shown in the ticket, help icons in the base settings view of a procedure were not properly aligned with the text. This PR fixes that.
Go to the base settings view and make sure help icons are aligned properly with the text.

fix(refs DPLAN-12690): fix alignment of help icons

---

client/js/bundles/user/editOrga.js
client/js/components/user/orgaDataEntry/OrganisationDataForm.vue
demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanOrgaController.php
templates/bundles/DemosPlanCoreBundle/DemosPlanUser/edit_orga.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanUser/orga_data_entry.html.twig

DPLAN-12823
On Orga-Edit page (e.g. as FPA)
`/organisation/edit/<orga-id>`
When resetting the page, non-editable should not change (not be cleared)
Other Fields should change to the initial value (not be cleared if there was initial content)
In addition I moved some code. Sorry. That should have been a separate PR. If wanted I can guide through the changes.
The Commits are quite clear to follow.

fix(refs dplan-12823): Reset orga form only for editable fields

---

demosplan/DemosPlanCoreBundle/ResourceTypes/StatementVoteResourceType.php

https://demoseurope.youtrack.cloud/issue/DPLAN-3217/ADO-Issue-15115-Integration-EWM-Part-2-Stellungnahmedetailansicht-aus-EWM-und-dplan-vereinen
Name field of statement vote should be optional on update

fix (DPLAN-3217) Name field on StatementVote is option on update

---

client/js/components/statement/statement/DpVersionHistoryItem.vue
templates/bundles/DemosPlanCoreBundle/DemosPlanCore/html_diff.html.twig

[DPLAN-12607](https://demoseurope.youtrack.cloud/issue/DPLAN-12607/Versionsverlauf-Zuweisung-Name-nicht-zentriert)
- fix spacing around changed content
- unrelated to the bug: use `thead` and `tbody` elements around `tr` elements
Go the statement list, open the version history of a statement. If there are changes, the content should have some spacing around (unlike in the screenshot in the ticket)

fix(refs DPLAN-12607): add margin to version history content

---

package.json
yarn.lock

The new demosplan-ui 0.3.x release includes the following fixes:
- allow passing v-tooltip options to `DpContextualHelp` (needed for [DPLAN-12746](https://demoseurope.youtrack.cloud/issue/DPLAN-12746/Hinzufugen-von-Textbaustein-zu-Mitteilung-Invalid-Prop))
- apply 'sr-only' class to `DpLabel` if `hide` prop is set to `true` (needed for [DPLAN-12808](https://demoseurope.youtrack.cloud/issue/DPLAN-12808/Button-verschoben-Einreichende-suchen))
- fix import of `DpUploadFiles` in `DpUploadModal` (needed for [DPLAN-12907](https://demoseurope.youtrack.cloud/issue/DPLAN-12907/Bild-einfugen-nicht-moglich-Erwiderung-verfassen))
- allow setting `DpButton` `type` prop to 'reset' (needed for [DPLAN-12823](https://demoseurope.youtrack.cloud/issue/DPLAN-12823/Nach-dem-zurucksetzen-von-Orgadaten-nicht-meh …

build: bump demosplan-ui to v.0.3.38

---

client/js/components/statement/DpBoilerPlate.vue

[DPLAN-12746](https://demoseurope.youtrack.cloud/issue/DPLAN-12746/Hinzufugen-von-Textbaustein-zu-Mitteilung-Invalid-Prop)
The `DpContextualHelp` `text` prop was used to pass an object with v-tooltip options, but it expected a string. In https://github.com/demos-europe/demosplan-ui/pull/1084, a new prop `tooltipOptions` was added that can be used to pass both text and other tooltip options. It is now used here to prevent the console error.
Go to the 'Aktuelles' view and create a new message. Try to add a boilerplate text via the text editor. There should be no error in the console.

fix(refs DPLAN-12746): use new tooltipOptions prop

---

client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaLocationAndDocumentReference.vue

the div is needed when there is no location, because without it there is not enough space between this field and the one below

fix(refs DPLAN-3217): re-add div for consistent spacing

---

client/js/components/procedure/DpSimplifiedNewStatementForm.vue
client/js/components/procedure/imageAnnotator/DpConvertAnnotatedPdf.vue
translations/messages+intl-icu.de.yml

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-12526/3-2-Als-Importerin-mochte-ich-meine-Anpassungen-nach-der-OCR-Texterkennung-zwischenspeichern-konnen-um-sicherzugehen-dass-meine
Description: this changes are picked from https://github.com/demos-europe/demosplan-core/pull/3992

F dplan 12526 add statement quicksave button after ocr text recognition

---

client/js/store/statement/Statement.js

[DPLAN-12917](https://demoseurope.youtrack.cloud/issue/DPLAN-12917/STN-werden-nicht-geladen)
The StatementResourceType was renamed to SourceStatementResourceType and handles the SourceAttachment only. For other attachments the GenericStatementAttachmentResourceType was created.
code review, maybe more adjustments needed in frontend

feat (refs DPLAN-12917): show statement in assessmenttable again

---

demosplan/DemosPlanCoreBundle/Entity/User/AiApiUser.php
demosplan/DemosPlanCoreBundle/Entity/User/AnonymousUser.php
demosplan/DemosPlanCoreBundle/Entity/User/FunctionalUser.php

As any functional user needs a default orga this might be called in the parent class and might be overridden by `setDefaultOrgaDepartment()`
run `bin/project dplan:frontend:integrator`

chore: any functional user needs a default orga

---

client/js/components/procedure/DpSimplifiedNewStatementForm.vue

https://demoseurope.youtrack.cloud/issue/DPLAN-12916/Abbrechen-Button-funktioniert-nicht-im-Schritt-Import-bestatigen-und-auch-im-Schritt-Uberprufen
This PR adds a secondary action explicitly for the `DpSimplifiedStatementForm.vue`'s dp-button-row component to redirect the user back to the import center instead of the overview.
- for some reason I still do not understand the `<a>`-tag does not redirect when clicking the secondary button of dp-button-row
- hence a secondary action was added for redirecting back to the import center

feat(refs DPLAN-12916): add function to redirect back to import center

---

demosplan/DemosPlanCoreBundle/Logic/Map/MapHandler.php
demosplan/DemosPlanCoreBundle/Logic/Map/MapService.php
demosplan/DemosPlanCoreBundle/Repository/MapRepository.php

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-12816/ROBOBSH-Stage-Basemap-bleibt-nicht-vorausgewahlt-nach-Speichern-neuer-Kartenlayer
Description: 
adjust condition :
- 'VisibilityGroupId' can be null (default value) or can be an empty string. Layers in the same group can be updated only when 'VisibilityGroupId' is not null and has to be not empty too otherwise the layer does not have any group. That's why the condition has to be adjusted to have the expected behavior.
- the 'getVisibilityGroupId' method is adjusted too : we must retrieve only layers that's belong to the current procedure. Using only the 'visibilityGroupId' to get procedure relevant layers leads to have wrong result and updating layers that's does not belong to the current procedure
Delete the checkbox if it …

f-DPLAN-12816-retain-layers-preselection-after-saving-or-updating-layers

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_flyout.scss

https://demoseurope.youtrack.cloud/issue/DPLAN-12460/Bei-Abschnittsliste-mit-wenigen-Eintragen-sind-nach-Klick-auf-drei-Punkte-die-Optionen-abgeschnitten
This change ensures that the flyout menu is always visible on re-sizable data tables
https://github.com/demos-europe/demosplan-ui/pull/1100

feat(refs DPLAN-12460): add style to always display flyout properly

---

demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php

Trying to build the frontend assets when no package.json is defined leads to an error that breaks automatic addon installation routines

chore: build addon frontend only when it exists

---

composer.json

The package aws/aws-sdk-php contains a lot of aws apis that are not needed. According to https://github.com/aws/aws-sdk-php/tree/master/src/Script/Composer they can be reduced, which shrinks the size of the dependency (and thus the container) by 45 MB.
run composer install and check that vendor/aws/aws-sdk-php/src/data contains only a few subfolders (including s3), not 50+

chore: only load aws s3 sdk api

---

client/js/bundles/core/listDraft.js
client/js/components/statement/publicStatementModal/StatementModal.vue
templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_draft.html.twig

DPLAN-12315
DPLAN-12921
It seems, that the reactivity broke in the statmentModal while upgrading to vue3. I should't have worked before, but it did. Now its not clean, but consistent.
Since I moved a block to a separate method, the changes are not so easy to spot. Sorry for that. 
The main thing I did was using the local `dataToSend` instead of `this.setStatementData` which interacts with the store to prepare the statement data before updating

fix(refs dplan-12315): Send correct data on statement modal edit

---

demosplan/DemosPlanCoreBundle/Logic/Map/MapHandler.php
demosplan/DemosPlanCoreBundle/Logic/Map/MapService.php
demosplan/DemosPlanCoreBundle/Repository/MapRepository.php
tests/backend/core/Map/Functional/MapHandlerTest.php

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-12816/ROBOBSH-Stage-Basemap-bleibt-nicht-vorausgewahlt-nach-Speichern-neuer-Kartenlayer
Description: 
adjust condition :
- 'VisibilityGroupId' can be null (default value) or can be an empty string. Layers in the same group can be updated only when 'VisibilityGroupId' is not null and has to be not empty too otherwise the layer does not have any group. That's why the condition has to be adjusted to have the expected behavior.
- the 'getVisibilityGroupId' method is adjusted too : we must retrieve only layers that's belong to the current procedure. Using only the 'visibilityGroupId' to get procedure relevant layers leads to have wrong result and updating layers that's does not belong to the current procedure
Delete the checkbox if it …

fix-DPLAN-12816-retain-layers-preselection-after-saving-or-updating-layers

---

tests/backend/core/Map/Functional/MapHandlerTest.php

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-12816/ROBOBSH-Stage-Basemap-bleibt-nicht-vorausgewahlt-nach-Speichern-neuer-Kartenlayer
Description: adjust tests

f DPLAN-12816 adjust tests

---

package.json

The Container now is shipped with node 20. So we can require it.
After this is merged, https://github.com/demos-europe/demosplan-core/pull/3785 can be merged.

chore: Bump Node

---

config/packages/rate_limiter.yaml
tests/backend/core/Core/Functional/RatelimitRequestSubscriberTest.php

Raise jwt token rate limit for api requests from 10 to 100 to allow the creation of more categories (institution tagging).
code review, you should be able to create more categories without page reload as before.
https://github.com/demos-europe/demosplan-core/pull/4061

feat (refs DPLAN-12984): Raise jwt token rate limit for api requests

---

client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
config/permissions.yml

Description: Use If condition to access Voting and public area in Statement

Use if condition to access voting and publication area

---

.env
config/parameters_default.yml
demosplan/DemosPlanCoreBundle/EventSubscriber/ProcedureMetricsEmailEventSubscriber.php
demosplan/DemosPlanCoreBundle/Resources/config/GlobalConfig.php

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-12667
Description:
move receiver address into globalconfig - env variable

fix(refs DPLAN 12667) move receiver address into globalconfig - env variable

---

client/js/components/map/admin/AdminLayerListItem.vue
client/js/components/map/admin/MapAdminScales.vue
client/js/components/map/map/DpOlMapLayer.vue
client/js/components/map/map/DpOlMapLayerVector.vue
client/js/components/map/map/DpOlMapScaleSelect.vue
client/js/components/map/map/MapView.vue
client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerList.vue
client/js/components/procedure/DpSimplifiedNewStatementForm.vue
client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaAttachments.vue
client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
client/js/components/procedure/admin/InstitutionTagManagement.vue
client/js/components/procedure/basicSettings/AutoSwitchProcedurePhaseForm.vue
client/js/components/procedure/basicSettings/DpProcedureCoordinateInput.vue
client/js/components/procedure/basicSettings/ProcedureCoordinateGeolocation.vue
client/js/components/procedure/publicindex/map/Map.vue
client/js/components/statement/assessmentTable/DpEditField.vue
client/js/components/statement/assessmentTable/DpEditFieldSingleSelect.vue
client/js/components/statement/assessmentTable/DpFilterModal.vue
client/js/components/statement/assessmentTable/DpMoveStatementModal.vue
client/js/components/statement/assessmentTable/DpSelectedItemsStatements.vue
client/js/components/statement/assessmentTable/StatementReplySelect.vue
client/js/components/statement/assessmentTable/TocView/SearchAndSorting.vue
client/js/components/statement/fragment/SelectDocument.vue
client/js/components/statement/splitStatement/SplitStatementView.vue
client/js/components/statement/statement/DpAutofillSubmitterData.vue
client/js/components/user/DpTableCardList/DpTableCard.vue

DPLAN-12315
DPLAN-12921
even though `deep: false` is the default, we should set it during the migration process so we can easily check if we already checked that occurrence. Otherwise we will get a warning again and again and never know if we can ignore it.

chore(refs dplan-12315): Set deep for watcher explicitly

---

client/js/components/procedure/admin/InstitutionTagManagement/TagList.vue
client/js/components/procedure/admin/InstitutionTagManagement/TagListItem.vue

[DPLAN-12981](https://demoseurope.youtrack.cloud/issue/DPLAN-12981/Editierte-Schlagworte-Kategorie-Schlagwort-Name-wird-richtig-nur-nach-einem-Seitenrefresh-angezeigt)
To display the updated name in non-edit mode, we need to update the `item` prop, as we use it in non-edit mode (while in edit mode, `this.name` is used)

fix(refs DPLAN-12981, #AB17874): update prop on save

---

client/js/components/procedure/admin/InstitutionTagManagement/TagListItem.vue

[DPLAN-13017](https://demoseurope.youtrack.cloud/issue/DPLAN-13017/Geloschte-Kategorie-mit-Schlagworten-verschwindet-erst-nach-page-reload)
see Ticket

fix(refs DPLAN-13017): update list after delete

---

client/fe/webpack/moduleRules.js
client/fe/webpack/plugins.js
package.json
yarn.lock

Since I had to adjust some options, I had to create the PR manually.
For details, why I had to change things see https://webpack.js.org/loaders/sass-loader/#api

chore: Bump Sass-loader to 16.0.3

---

client/js/components/user/DpUserList/DpUserListItem.vue

Description: Use a correct ResourceType in UserListItem Component like in UserList Component

Fix User List Item Load

---

client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
config/permissions.yml

Description: create a new Permission and us if condition to manage access to area and documentation in statement details

Access to area and documentation in statement

---

.github/dependabot.yml

symfony/http-client has the same versions as other core bundles

chore: symfony/http-client has the same versions as other core bundles

---

demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementFromRowBuilderWithZipSupport.php

Description: Add setFiles method to persist files 

Show Attachments in statement Detail

---

demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementFromRowBuilderWithZipSupport.php

Description: Add setFiles method to persist files 

Show attachments in statement detail by zip importer

---

client/js/bundles/user/listUser.js
client/js/components/user/DpCreateItem.vue
client/js/components/user/DpUserList/DpUserFormFields.vue
client/js/components/user/DpUserList/DpUserList.vue
client/js/components/user/DpUserList/DpUserListItem.vue
client/js/components/user/DpUserListExtended.vue
client/js/components/user/DpUserListExtendedItem.vue
config/permissions.yml
demosplan/DemosPlanCoreBundle/Entity/User/Role.php
demosplan/DemosPlanCoreBundle/Entity/User/User.php
demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/UserResourceConfigBuilder.php
demosplan/DemosPlanCoreBundle/ResourceTypes/AdministratableUserResourceType.php

https://demoseurope.youtrack.cloud/issue/DPLAN-13034
- Move to using AdministratableUserResourceType instead of old 1.0 api
- Important things to check: 
- Updating Roles,Department and Orga relationships
- When a user is created, login field is set same as email field
1. Create a user and check that emails has been sent (not possible to test in local)
2. Update user all possible combinations: roles, orga, email.
3. when updating email, check that login is also updated

B dplan 13034 use api2 to create user

---

CHANGELOG.md
client/js/components/document/ElementsAdminBulkEdit/ElementsAdminBulkEdit.vue
client/js/components/map/admin/MapAdminScales.vue
client/js/components/procedure/AdministrationImport/ExcelImport/ExcelImportErrors.vue
client/js/components/procedure/SegmentsBulkEdit/ActionStepper/ActionStepperResponse.vue
client/js/components/procedure/SegmentsBulkEdit/SegmentsBulkEdit.vue
client/js/components/procedure/StatementSegmentsList/SegmentCommentsList.vue
client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue
client/js/components/procedure/admin/DpNewProcedure/CoupleTokenInput.vue
client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
client/js/components/procedure/admin/InstitutionTagManagement/InstitutionList.vue
client/js/components/procedure/admin/InstitutionTagManagement/TagList.vue
client/js/components/procedure/basicSettings/AutoSwitchProcedurePhaseForm.vue
client/js/components/procedure/basicSettings/ExportSettings.vue
client/js/components/procedure/basicSettings/ParticipationPhases.vue
client/js/components/procedure/listSubscriptions/ListSubscriptions.vue
client/js/components/statement/assessmentTable/AssessmentTableFilter.vue
client/js/components/statement/listOriginalStatements/ListOriginalStatements.vue
client/js/components/statement/publicStatementLists/DpPublicStatement.vue
client/js/components/statement/publicStatementModal/StatementModal.vue
client/js/components/statement/publicStatementModal/StatementModalRecheck.vue
client/js/components/statement/splitStatement/SplitStatementView.vue
client/js/components/statement/statement/DpVersionHistory.vue
client/js/components/statement/statement/StatementPublish.vue
demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_flash.scss

[DPLAN-12968](https://demoseurope.youtrack.cloud/issue/DPLAN-12968/ADO-Issue-21840-Admin-Institutionsliste-Institutionen-konnen-durchsucht-werden)
Previously, margin was set via the `flash` class on the root `div` in `DpInlineNotification`. When setting dismissible to true and then dismissing the notification in the interface, the hint icon has no margin. Instead of defining it directly in the component, the margin can now simply be set from outside the component and will be applied to the root `div` (whether it's the notification or the icon):
```
<dp-inline-notification
classs="mt-3 mb-2"
dismissible
:dismissible-key="helpTextDismissibleKey"
:message="helpText"
type="info" />
```
I tested only some usages and found that sometimes, the extra margin was not needed. In other cases I added …

feat(refs DPLAN-12968, #AB21840): set margin outside of component

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig

https://demoseurope.youtrack.cloud/issue/BEAA2-19/Text-zu-Piktogramm-widerspricht-sich-in-Tooltip-und-in-Hinweistext
**Description:** This PR removes the label from the pictogram.

fix(BEAA2-19): remove label from the pictogram

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig

[BEAA2-14](https://demoseurope.youtrack.cloud/issue/BEAA2-14/Piktogramm-wird-nicht-als-Pflichtfeld-angezeigt)
**Description:** This PR adds a required attribute to the pictogram.

fix(BEAA2-14): add required attribute to the fileupload component

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/components/vendor/_a11y-datepicker.scss

https://demoseurope.youtrack.cloud/issue/DPLAN-13108/Zeitraum-Infotext-ist-sichtbar
Description: This PR duplicates the styles from a11y-datepicker (previously added directly in the head > style type=text/css) into css file, due to issues with the Content Security Policy (CSP). The CSP prevents cross-site scripting attacks by blocking the inline execution of scripts and stylesheets.

fix(DPLAN-13108): datapicker css issue

---

demosplan/DemosPlanCoreBundle/Controller/Procedure/AuthorizedUsersController.php
demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureAPIController.php
demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureExportController.php
demosplan/DemosPlanCoreBundle/Controller/Report/DemosPlanReportAPIController.php
demosplan/DemosPlanCoreBundle/Controller/Segment/SegmentsExportController.php
demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementAPIController.php
demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanOrganisationAPIController.php
demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserAPIController.php
demosplan/DemosPlanCoreBundle/Logic/JsonApiActionService.php

https://www.dev.diplanung.de/DefaultCollection/EfA%20DiPlanung/_workitems/edit/17164
InputBag::get should only return scalar values, when an array is needed InputBag::all should be used. Like it or not. See https://github.com/symfony/symfony/issues/44788

chore: fix deprecation in InputBag::get

---

config/services.yml

https://www.dev.diplanung.de/DefaultCollection/EfA%20DiPlanung/_workitems/edit/17164
In symfony 6 the transformer services cannot be lazy as they could not be found otherwise
Any api 1.0 route should work as before

chore: unlazy Transformer services

---

client/fe/webpack/moduleRules.js
client/fe/webpack/plugins.js

two issues in one: The implementation option was set in the wrong scope and for whatever reason the modern-compiler option prevented finishing the process. Although we want to have that option enabled and it worked with that quirk for dev. compiling the prod-assets did not work.

fix: Move Sass-loader settings to the right place

---

demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadProcedureData.php
demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadRolesData.php
demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadUserData.php
demosplan/DemosPlanCoreBundle/DoctrineMigrations/2025/01/Version20250120151616.php

DPLAN-14787
https://www.dev.diplanung.de/DefaultCollection/EfA%20DiPlanung/_workitems/edit/23008
Unfortunately the fixture for the roles was buggy and contained a duplicate entry for the fpa role. This PR deletes the duplicate and provides a migration that fixes the existing database entries. 
As a side effect this leads to significantly smaller log files as this warning was logged on every request.
code review and probably some manual clicking if desired

chore (refs DPLAN-14787): Remove duplicate role entry for planning agency admin

---

demosplan/DemosPlanCoreBundle/Logic/User/UserService.php

Users of a soft deleted orga should not be able to login. It is a rare case but can be used to quickly ban all users of an organisation

chore: add additional check during user login for valid orga

---

config/services.yml
demosplan/DemosPlanCoreBundle/DataCollector/AddonInfoDataCollector.php
templates/bundles/DemosPlanCoreBundle/data_collector/addon_info.html.twig

Provide a new  symfony toolbar entry for installed addons to be easily able to see which addons are installed in which version in the symfony toolbar

chore: provide a symfony toolbar entry for addons

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_list.scss

[DPLAN-12935](https://demoseurope.youtrack.cloud/issue/DPLAN-12935/UI-Formatierung-Listansicht-von-weitere-Einreichende)
**Description:** This PR improves the UX by adding a `' | '` separator instead of the `' / '` to the _Weitere Einreichende der gleichen Stellungnahme_ section.
Log in as the FP-Admin > Procedure > Import > Direct input

fix(DPLAN-12935): improve the UX by changing the separator

---

client/js/components/statement/splitStatement/CardPaneCard.vue
client/js/components/statement/splitStatement/SegmentationEditor.vue

It looks like trailing Whitespaces are swallowed by prosemirror. The option "preserveWhitespace" should handle this and should have been enabled by default, which for some reason wasn't .
Enabling it, makes it better, but don't fix it in whole...

fix: Find the lost whitespace in slicing tagging

---

client/js/components/statement/splitStatement/SegmentationEditor.vue

[DPLAN-14776](https://demoseurope.youtrack.cloud/issue/DPLAN-14776/Nach-Aufteilen-von-eine-Stellungnahme-ist-die-Formatierung-von-Text-komplett-weg)
Description: This PR fixes an issue with text formatting after splitting the statement view. The problem was that after extending `schema.spec.marks`, the standard marks from ProseMirror were overwritten. So found a way to extend it without overwriting the default marks and to added an underline mark as well.
EIne STN mit Formatierung erstellen -> Aufteilen -> Abschnitte durch checken

Fix(DPLAN-14776): formatting issue after the spit statement view - release_ewm

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig

https://demoseurope.youtrack.cloud/issue/DPLAN-14833/automatische-Umstellung-Beteiligungsphasen-keine-Auswahl-der-Phasen-moglich-die-umgestellt-werden-sollen
The prop had been renamed in the component, but the usage was not adjusted

fix(refs DPLAN-14833, #AB5589): use correct prop name

---

client/js/store/core/initStore.js

https://demoseurope.youtrack.cloud/issue/DPLAN-14848/Speichern-von-Institution-Tags-geht-nicht
Without checking the content type, this error occurred:
```
SyntaxError: Failed to execute 'json' on 'Response': Unexpected end of JSON input
```
It seems that this happens when the response body is empty and no content type is set.
- https://github.com/demos-europe/demosplan-core/pull/4221

fix(refs DPLAN-14848): check content type

---

client/js/components/document/DpMapSettingsPreview.vue

https://demoseurope.youtrack.cloud/issue/DPLAN-12498/Nach-zeichnen-von-Geltungsbereich-der-Text-andert-sich-nicht-zu-Geltungsbereich-ist-gezeichnet
Since `features` is an object, checking for its length did not work

fix(refs DPLAN-12498): check for length of object keys

---

demosplan/DemosPlanCoreBundle/Logic/Router.php
demosplan/DemosPlanCoreBundle/Repository/ProcedureRepository.php

The hydration of objects is quite expensive and when a lot of links with procedureIds are generated this PR improves the performance by fetching only the needed property from the database.
In my testcase with only 19 Procedures it improved the overall performance by almost 40%
Any links within a procedure should work

chore: improve router performance

---

client/js/components/tags/TagListEditForm.vue
client/js/components/tags/TagsImportForm.vue
client/js/store/core/initStore.js

Description: There was a problem with displaying messages/errors after merging with the main branch.
- error messages are not being displayed: there was an issue with handling callbacks in initStore: the contentType can be not only `application/json` but also other strings like `application/vnd.api+json`. Therefore, it must be checked if the type contains `'json'` and not just if it equals `'application/json'`
- some code style adjustment

refac(DPLAN-12013): issue with displaying messages from the msgBag

---

client/js/store/core/VuexApiRoutes.js
demosplan/DemosPlanCoreBundle/Controller/AssessmentTable/DemosPlanStatementFragmentUpdateAPIController.php
demosplan/DemosPlanCoreBundle/Controller/Base/APIDocumentationController.php
demosplan/DemosPlanCoreBundle/Controller/Faq/FaqCategoryApiController.php
demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureAPIController.php
demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementAPIController.php
demosplan/DemosPlanCoreBundle/Controller/Statement/TagTopicAPIController.php
demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanDepartmentAPIController.php
demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanOrganisationAPIController.php
demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanRoleAPIController.php
demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserAPIController.php

https://www.dev.diplanung.de/DefaultCollection/EfA%20DiPlanung/_workitems/edit/19470
In ingress context routes are not allowed to have / suffix as the requests will be redirected to /
In not ingress context everything should work as before

chore (refs AB#19470): routes are not allowed to have / suffix

---

CHANGELOG.md
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig

DPLAN-12779
Move location item directly under internal item to make saving more intuitive for the user and create less error messages.
Verfahren -> Grundeinstellungen -> Verortung des Verfahrens should be second item under Intern

feat(refs DPLAN-12779,#AB21087): Move location in basic settings

---

client/js/components/procedure/SegmentsList/FilterFlyout.vue
client/js/components/procedure/SegmentsList/FilterFlyoutCheckbox.vue
client/js/components/procedure/admin/InstitutionTagManagement/InstitutionList.vue
client/js/store/procedure/FilterFlyout.js

[DPLAN-12969](https://demoseurope.youtrack.cloud/issue/DPLAN-12969/ADO-Issue-21841-Admin-Institutionsliste-Institutionen-konnen-nach-Schlagworten-gefiltert-werden)
This PR adds the option to have filter options applied with an 'OR' conjunction within a filter category (i.e. within a filter flyout) by adding the `memberOf` property to the filter category. In DpFilterFylout.vue, the property will then be added to each selected filter option.
When applying selected filter options and updating the filter query in the store, a filter group will be added to the query:
```
filterQuery: {
[group_id]: {
group: {
conjunction: 'OR'
}
}
}
```
This filterQuery is then used in the BE request for fetching the filtered invitableInstitutions.
If you would like to test this in the interface
- log in as …

feat(refs DPLAN-12969, #AB21841): allow grouping filter options with 'OR' conjunction

---

eslintrc.js

We don't want to check addons and local modules in core.

chore: Extend eslint config

---

client/js/components/procedure/admin/InstitutionTagManagement/InstitutionList.vue
client/js/components/procedure/admin/InstitutionTagManagement/InstitutionTagManagement.vue

DPLAN-12969
We need to call the institution tag categories again after applying a filter to get all available tags, because the filter request also updates the institution tag category store.
Login as Mandatenadmin -> Institutionen verschlagworten -> Apply filter -> Check other categories if there are still filter options (tags) available -> Click Zurücksetzen and check if filter options are still valid

feat(refs DPLAN-12969,#AB21841): Fix tags in filters 

---

client/js/components/procedure/admin/InstitutionTagManagement/InstitutionList.vue

[DPLAN-12969](https://demoseurope.youtrack.cloud/issue/DPLAN-12969/ADO-Issue-21841-Admin-Institutionsliste-Institutionen-konnen-nach-Schlagworten-gefiltert-werden)
With the previous operator, applying filter options from different dropdowns simultaneously did not work; now it does.

fix(refs DPLAN-12969, #AB21841): use correct operator

---

client/js/components/procedure/admin/InstitutionTagManagement/InstitutionList.vue

DPLAN-14923
When resetting we need to filter out the group entries and only store the condition entries in the applied filter query.
Login as Mandantenadmin -> Institutionen verschlagworten -> Play around with applying filters and deselecting applied filters again

bug(refs DPLAN-14923): Fix resetting filter

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
templates/bundles/DemosPlanCoreBundle/Extension/fileupload.html.twig

[DPLAN-14938](https://demoseurope.youtrack.cloud/issue/DPLAN-14938)
- pass correct `maxuploadsize` to `fileupload.html.twig`
- fix the doc block, since parameters were not in correct order

fix(refs DPLAN-14938): display correct file size for pictogram upload

---

client/js/components/user/DpOrganisationList/DpOrganisationFormFields.vue
client/js/components/user/DpOrganisationList/DpOrganisationList.vue
client/js/components/user/DpOrganisationList/DpOrganisationListItem.vue

[DPLAN-14736](https://demoseurope.youtrack.cloud/issue/DPLAN-14736/Orga-Filter-funktioniert-nicht-richtig)
- in the mein berlin addon additional field, after requesting the dropdown options once, there is not really any need to request them again without reloading the page
- when filtering the organisation list, the list items are destroyed and mounted again, so the request was fired 10 times (for each list item once) with each click on a filter checkbox, leading to a 'too many requests' error when changing the filters a lot
- now, after requesting the dropdown options in the addon component once, they are emitted to the organisation list component which is not re-mounted when filtering. the organisation list component then passes them down via prop back to the addon component. if …

fix(refs DPLAN-14736): reduce number of requests

---

client/js/store/map/Layers.js

DPLAN-14849
Add confirm message for deleting layers in checkResponse. 
Verfahren -> Planungsdokumente und Planzeichnung -> Kartenebenen definieren -> Add a new layer eg `https://sgx.geodatenzentrum.de/wms_topplus_open?SERVICE=WMS` -> Delete layer -> there should be a confirmation message

bug(refs DPLAN-14849): Add confirm notification for deleting layers

---

client/js/components/user/CustomerSettings/CustomerSettingsBranding.vue
client/js/components/user/CustomerSettings/CustomerSettingsSupport.vue

DPLAN-12673
- Support: Get contacts after deleting to refresh support list without having to refresh the whole page.
- Additionally setting a new branding logo or deleting the old did not work. Fixes: Remove logo hash from attributes. Only file id in relationships is needed, otherwise BE rejects request. Also update branding before saving and unset file after deleting.
- Order some attributes
Login as Mandantenadmin -> Plattform-Einstellungen 
- Delete support contact -> contact should be removed without refreshing the page
- Add new logo and save -> should work
- Delete logo -> should be removed without refreshing the page

bug(refs dplan-12673): fix customer settings

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig

DPLAN-14947
The arguments to create the fileupload component where improperly set. To avoid further confusion named arguments can be used.

chore: use named arguments to fix incorrect fileupload params

---

templates/bundles/DemosPlanCoreBundle/Extension/fileupload.html.twig

Current documentation on twig fileupload function is a bit misleading. Added named arguments usage

chore: improve fileupload twig function documentation

---

composer.json
composer.lock
demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
demosplan/DemosPlanCoreBundle/Logic/StatementSynchronizer.php
demosplan/DemosPlanCoreBundle/Validator/StatementValidator.php

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-14943/Kommentar-in-Erwiderung-ladt-unendlich
HowToTest:
Even assignment of Statements did not work via api. should work now
Description:
parentStatementOfSegment should not be asserted by the DEFAULT Group as this group gets used for segments as well.
Therefore a different group was assigned to parentStatementOfSegments.
This group was added to the places where only base statement entities get validated.
bumps demosplan-addon to v0.48 https://github.com/demos-europe/demosplan-addon/pull/136

f_DPLAN-14943 alter statement validation. Do not assert parentStatementOfSegment is Null by default Group

---

.github/workflows/reviewdog.yml

chore: ubuntu 20.04 as a runner is deprecated

---

client/js/components/procedure/admin/InstitutionTagManagement/InstitutionList.vue
client/js/components/procedure/admin/InstitutionTagManagement/TagList.vue
demosplan/DemosPlanCoreBundle/Entity/User/InstitutionTag.php
demosplan/DemosPlanCoreBundle/Entity/User/InstitutionTagCategory.php
demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/InstitutionTagCategoryResourceConfigBuilder.php
demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/InstitutionTagResourceConfigBuilder.php
demosplan/DemosPlanCoreBundle/ResourceTypes/InstitutionTagCategoryResourceType.php
demosplan/DemosPlanCoreBundle/ResourceTypes/InstitutionTagResourceType.php

[DPLAN-14634](https://demoseurope.youtrack.cloud/issue/DPLAN-14634/ADO-Issue-22463-Admin-Institutionsliste-Filteroptionen-konnen-nach-Schlagwortkategorien-angepasst-werden)
- instead of displaying the categories and tags in a random order, it seems more intuitive to sort them by creationDate
- while sorting by the user is not possible in the interface, this way we give them the possibility to create their desired order by adjusting the order in which they create categories and tags
- also, in the tag list, after creating a category, it is displayed at the top of the list now, so it's easier to confirm that it has indeed been created

feat(refs DPLAN-14634, #AB22463): sort categories + tags by creationDate

---

client/js/components/shared/TextContentRenderer.vue

DPLAN-14953
We should sanitize the statement text before rendering it to avoid Cross Site Scripting.
Login as Datenerfasser -> Verwalten -> Verfahren -> Import xlsx file from the ticket as Abschnitte -> Go to the imported statement -> Click on Mehr anzeigen on the statement text -> Text should be shown and no errors in console

bug(refs DPLAN-14953): Sanitize statement text

---

client/js/components/statement/StatementExportModal.vue
client/js/components/statement/listStatements/ListStatements.vue

DPLAN-11952
Determine if a confirmation dialog should be shown for the export action.
This is required if the selected export type is either 'docx' or 'zip'.
const shouldConfirm = ['docx', 'zip'].includes(this.active);

bug(refs DPLAN-119521): confirm conditionally

---

package.json
yarn.lock

**Ticket:** [DPLAN-14634](https://demoseurope.youtrack.cloud/issue/DPLAN-14634/ADO-Issue-22463-Admin-Institutionsliste-Filteroptionen-konnen-nach-Schlagwortkategorien-angepasst-werden)
The new demosplan-ui version contains
- new icons (`dots-three`, `mapPin`, `mapPinSolid`)
- new `isDisabled` prop for `DpLabel`
- a fix to allow keyboard navigation in `DpAnonymizeText`

chore(refs DPLAN-14634, #AB22463): bump demosplan-ui from v0.3.45 to v0.3.47

---

demosplan/DemosPlanCoreBundle/EventListener/DoctrineLoggerListener.php
demosplan/DemosPlanCoreBundle/Logic/OzgKeycloakUserDataMapper.php

In case a user is logged in via an identity provider we do not have any passwords in the database Along the way two deprecations are fixed.

chore: silence user has no password logmessage

---

tests/frontend/unit/StatementExportModal.spec.js

`StatementExportModal` was changed recently, this fixes the test. 
Related PR 
https://github.com/demos-europe/demosplan-core/pull/4350

tests: Fix test for StatementExportModal

---

package.json
yarn.lock

changes in demosplan-ui:
- ariaLabel prop can now be passed to DpFlyout if the flyout trigger is only an icon
- icon 'faders' has been added
- primary and secondary button in DpButtonRow can be disabled separately
- translations can be passed to DpPager via prop labelTexts
- several small layout fixes

chore(refs DPLAN-14634, #AB22463): bump demosplan-ui from v0.3.47 to v0.3.48

---

client/js/components/statement/assessmentTable/ExportModal.vue
config/permissions.yml
demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php

[DPLAN-14868](https://demoseurope.youtrack.cloud/issue/DPLAN-14868/ADO-Issue-23356-Excel-Export-aller-Informationen-aus-Abwagungstabelle)
Enable xlsx export for specific project. Therefore a new permission is needed for "potentialAreas" and a permission check for "cluster.name" to add or remove this field from export.
code review, test in interface of the specified projects if the export works how intended.

feat (DPLAN-14868): xlsx export assessmenttable

---

CHANGELOG.md
client/js/components/tags/TagListEditForm.vue
translations/messages+intl-icu.de.yml

[DPLAN-15055
](https://demoseurope.youtrack.cloud/agiles/141-245/current?issue=DPLAN-15055)
**Description:** This PR improves the UX and adds a confirmation message before deleting a Tag/Topic.

fix(DPLAN-15055): display a confirm message before deleting a Tag/Topic

---

client/js/components/tags/TagsImportForm.vue
demosplan/DemosPlanCoreBundle/Resources/public/files/tag_topics_import_template.csv

https://demoseurope.youtrack.cloud/issue/DPLAN-15068/Add-Beispieldatei-fur-Schlagwort
The user should have a template file that describes how to import the tags - topics
- Go to Verfahren > Schlalwort
- There should be a link called BeispielDatei and when clicking , a csv should be downloaded as a template

feat DPLAN-15068 Add template for tag topic import

---

CHANGELOG.md
client/js/components/tags/TagListEditForm.vue
client/js/components/tags/TagsList.vue

[DPLAN-15035](https://demoseurope.youtrack.cloud/issue/DPLAN-15035/Fehlermeldung-wenn-man-ein-Schlagwort-nicht-andert-und-auf-Checkmark-klickt)
**Description:** This PR fixes an issue with saving the unchanged Tag/Topic title.
- check on the FE if the title attribute has been changed and make an update request only if there are any changes.
Auf edit Icon von einem Schlagwort klicken -> nichts ändern -> auf Checkmark klicken -> Fehlermeldung

fix(DPLAN-15035): issue with saving the unchanged Tag/Topic title

---

demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php

DPLAN-14978
During automatic phase change via maintenance command the event was not dispatched and no report entries written. Main change is 2e508f3b91cb8df1be6748a3fbe6da2364123b81, the other changes only add logging and ease access to the phase object
Trigger automatic phase change via maintenance service, phases should still change

 chore (refs DPLAN-14978): create report entries and dispatch events 

---

client/js/components/statement/listStatements/ListStatements.vue

**Description:** ListStatements: refactor a parameter in the statement request: `attachment` has been changed to `genericAttachments` on the BE side.

refactor parameters in the statement request

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/_settings.font-awesome.scss
demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_map.scss
demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_nav.scss
demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_procedurelist.scss
demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_sidemenu.scss
demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_skeleton-box.scss
demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_statement-meta-box.scss
demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_support.scss
demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_tiptap.scss
demosplan/DemosPlanCoreBundle/Resources/client/scss/components/vendor/_a11y-datepicker.scss
demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_box.scss
demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_button.scss
demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_modal.scss
demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_wizard.scss
demosplan/DemosPlanCoreBundle/Resources/client/scss/utility/_color.scss
package.json
stylelint.config.js
yarn.lock

we that we could run `yarn lint:scss` in the ci as required check
`yarn lint:scss` should now run without errors.
Maybe its necessary to clear the yarn cache before.
I had to adjust the stylelint.config to match the corrents version options.
All content-changes are generated with `yarn lint:scss --fix` (except of the no-lint-entry)

chore: Bump Stylelint@16.14.1 and run lint --fix

---

demosplan/DemosPlanCoreBundle/Command/MaintenanceCommand.php
demosplan/DemosPlanCoreBundle/Controller/Platform/FileController.php

The maintenance service is quite noisy on stdout. Only show the execution and changes and log more
run bin/project dplan:maintenance

chore: lower stdout noise in maintenance command, improve logging

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_sidemenu.scss

[DPLAN-15097](https://demoseurope.youtrack.cloud/agiles/141-63/current?settings&tab=allgemeines&issue=DPLAN-15097)
**Description:** This PR solves the issue with the layout by sidemenu: using 'inset' inside the 'padding' was incorrect, so removed inset and use spacing direct with padding.

fix(DPLAN-15097): sidemenu layout issue

---

client/js/components/statement/listStatements/ListStatements.vue

[DPLAN-12263](https://demoseurope.youtrack.cloud/agiles/141-63/current?settings&tab=allgemeines&issue=DPLAN-12263)
**Description:** This PR fixes an issue where the item was still displaying in the list after deleting it. 
The problem is related to reactivity: the `statementsObject` varible updates properly, but the computed value `items()` that transforms the `statementsObject` does not detect the change. I tried different ways to trigger the reactivity, but there were always some problems. The only solution without issues was to fetch the items by page after the delete action.

fix(DPLAN-12263): the item was still displaying in the list after deleting it

---

client/js/store/map/ProcedureMapSettings.js

In some circumstances - not understood by now - the request fails to load the map settings in the admin area. If so, no map is displayed. To prevent error on the side.
This doesn't fix the issue, that the map is not displayed when the request fails. Without informations, we can't display the map.
And hence we get an 404 from the Backend
ado: 22818
DPLAN-14901
https://www.dev.diplanung.de/DefaultCollection/EfA%20DiPlanung/_workitems/edit/22818

fix(refs DPLAN-14901): Catch mapSettings-Request

---

demosplan/DemosPlanCoreBundle/Logic/Export/DocxExporter.php
demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-14956/BOB-SH-ROBOB-Prod-und-Stage-Exporter-Fehler-durch-Sonderzeichen-STX-alle-Produkte-mit-AWT
Description:
remove STX (start of text) EOT (end of text) special chars from STN/Segment texts before exporting them.
Basically from every caller of Html::addHtml instead where just trans keys get passed.
Otherwise Html::addHtml fails on loadXml.

f_DPLAN-14956 remove STX (start of text) special chars from STN/Segment texts before exporting them.

---

client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
client/js/components/report/DpReportListing.vue

DPLAN-14909
For some reason, sometimes, when both assignee and place changed, only place where send. Because it happens soemtimes, I think it is some sort of race condition between the request and an update of the initial segment. Because I monitored that the initial segment gets updated aswell even though, It should not at that very moment.
To prevent all that, I decided to bypass the vuex-json-api and update the resourcetype "manually".
in the segmentslist, when changing plce and assignee, it always should send both.
Hence the bug appears just randomly, its really hard to test.

fix(refs  dplan-14909): Always send assignee and place in pair

---

client/js/components/procedure/admin/InstitutionTagManagement/InstitutionList.vue

[DPLAN-15179](https://demoseurope.youtrack.cloud/issue/DPLAN-15179/Filter-konnen-nicht-zuruckgesetzt-werden-Institutionen-verschlagworten)
- reset button is no longer disabled when filters are applied; this was fixed by ensuring that `appliedFilterQuery` is an array only when empty, and an object when not empty
- on reset, applied filters are also removed from storage, so when reloading the page, filters are not re-applied
- login as customer admin
- go to "Institutionen verschlagworten"
- filter the list and try to reset the applied filters - it should now work without problems and list should remain unfiltered after reloading the page

fix(refs DPLAN-15179): reset filters in localStorage

---

client/js/components/faq/DpFaqItem.vue

DPLAN-15149
or
https://www.dev.diplanung.de/DefaultCollection/EfA%20DiPlanung/_workitems/edit/XXXXX
The deleteFaqItem method was updated to push the deleteAction function into the queue to ensure reactivity.
delete an item from faq category
- [x ] Run `yarn lint`

Bug(refs DPLAN-15149) faq item delete

---

demosplan/DemosPlanCoreBundle/Repository/OrgaRepository.php

Description: get only accepted planning offices

f DPLAN-15186 get only accepted planning offices

---

demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-15167/DEGES-Westendbrucke-Verfassungsdatum-bei-DOCX-Exporten-mittig-statt-rechtsbundig
Description: remove duplicated line

f DPLAN- 15167 remove duplicated line

---

demosplan/DemosPlanCoreBundle/Repository/TagTopicRepository.php

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-15064/Nutzung-einer-Blaupause-mit-thematischen-Schlagworten-funktioniert-nicht
Description:
The setter should be inside the loop instead outside to set all topics and tags instead only the last one

DPLAN-15064 fix placement of setter

---

client/js/components/procedure/SegmentsList/FilterFlyout.vue
client/js/components/procedure/admin/InstitutionTagManagement/InstitutionList.vue

[DPLAN-15170](https://demoseurope.youtrack.cloud/issue/DPLAN-15170)
- after reloading the page, the selection of filter flyouts made by the user via the 'more filters' flyout is still visible
- filter options from those flyouts that are applied will remain applied after reloading the page
- if filter options from a filter flyout are selected and applied, that filter flyout cannot be hidden via the 'more filters' flyout, since it would not be clear which filters are applied. instead, the checkbox is disabled. also, the count of selected options is now displayed in the 'more filters' flyout behind each category label.

fix(refs DPLAN-15170, #AB22463): persist flyout and filter option selection

---

client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaFinalEmail.vue

https://demoseurope.youtrack.cloud/issue/DPLAN-15211
- I remove emailDefaultText varible and set default email body to emailBodyText directly. 
- In this way, behaviour is consistent to how default emailSubject is set

fix DPLAN-15211 Set default email body

---

demosplan/DemosPlanCoreBundle/Command/FilesListCommand.php

DPLAN-3415
This command lists all files known to the given adapter local or s3. Handy for debugging
run bin/project dplan:files:list local|s3

chore: provide a command to list known files

---

client/js/components/tags/TagsImportForm.vue

DPLAN-15021
to display the uploaded file, so the user get a visual effect that the upload was successfull
To test this: It should be possible to upload a csv file with tags (at /verfahren/<procedure-id>/schlagworte)
and the uploaded file should be displayed before it gehts imported.

chore(refs DPLAN-15021): Enhance upload tags form

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_list_masters.html.twig
templates/bundles/DemosPlanCoreBundle/UI/inline-notification.html.twig

DPLAN-15148
Add some spacing between icon and text for inline notifications. Also add top spacing between button and notification. 
Login Mandantenadmin -> Blaupausen -> check spacing of the notification if there are no blue prints.

bug(refs DPLAN-15148): Add spacing for inline notifications

---

.reviewdog.yml

Eslint fails during reviewdog run, update the command to match `yarn lint`

chore: use current eslint command to fix reviewdog

---

package.json
yarn.lock

[DPLAN-15169](https://demoseurope.youtrack.cloud/issue/DPLAN-15169/Nicht-moglich-um-ein-Bild-zu-einem-Kapitel-zu-hinzufugen)
Contains a fix for the image upload in DpEditor.

chore(refs DPLAN-15169): bump demosplan-ui from v0.4.6 to v0.4.7

---

client/js/InitVue.js

[DPLAN-15169](https://demoseurope.youtrack.cloud/issue/DPLAN-15169/Nicht-moglich-um-ein-Bild-zu-einem-Kapitel-zu-hinzufugen)
This is needed to make tiptap/vue3 NodeViewWrapper work (used in demosplan-ui/DpResizableImage), which uses the new api.
- Login as FPA
- Go to Verfahren > Planungsdokumente und Planzeichnung
- Edit an existing category or create one first
- In the edit view, scroll down and click the "create new chapter" button
- In the new view, try to upload a picture to the editor - this should work without errors

fix(refs DPLAN-15169): enable vue 3 render function api

---

demosplan/DemosPlanCoreBundle/EventSubscriber/TusUploadEventSubscriber.php

In case of an error or found virus during upload only the id is reset and an invalid hash is sent. We should also remove the temporary hash
code review might be easiest. At the frontend side you may assess, what happens, when no hash is sent back from the upload file. I could not find any misbehaviour

chore: do not send a not existing hash to the frontend

---

demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadElementsData.php
tests/backend/base/FunctionalTestCase.php
tests/backend/core/Document/Functional/ParagraphServiceTest.php

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-14783
Description:
I had errors running the tests/backend/core/Document/Functional/ElementsServiceTest.php
that lead to fixing the LoadElementsData which then let the tests/backend/core/Document/Functional/ParagraphServiceTest.php fail. Adjusted the tests to match the now seemingly correct results.
Changed the createdDate comparison test as it fails for previously cached elements. 
fix the LoadElementsData Paragraph:Element and Paragraph:Procedure relation setup to match the Element:Procedure relation for its parentElement of category paragraph. Adjust prev. failing tests.
related PR: https://github.com/demos-europe/demosplan-core/pull/4463

DPLAN-14783 set relations coorectly in LoadElementsData fixture setup

---

demosplan/DemosPlanCoreBundle/Logic/Document/ParagraphService.php

DPLAN-15242
Null as return is also allowed.
Additionally set string as parameter type and remove now unnecessary docblock

feat (refs DPLAN-15242): null is a valid return type

---

demosplan/DemosPlanCoreBundle/Logic/Statement/StatementSubmissionNotifier.php
templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/new_statement_confirm_email.html.twig

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-15329/BLP-Adressdaten-in-Einreichungsbestatigungsemail-falsch
Description: 
adjust statement confirm mail:
- add house number in the template
- adjust street and postalcode order

F dplan 15329 adjust statement confirm mail

---

templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig

DPLAN-15298
Deleted obscure option in DpEditor in NewStatement component since it should just be available in segements. 
Create new stn and take a look at the icons
https://github.com/demos-europe/demosplan-core/pull/4421

b(refs-DPLAN-13110) delete obscure option in new statement 

---

client/js/components/procedure/StatementSegmentsList/SegmentCommentsList.vue
client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
client/js/components/statement/DpClaim.vue

[DPLAN-15292](https://demoseurope.youtrack.cloud/issue/DPLAN-15292/Vollbild-Abschnitte-endlose-laden-beim-speichern-von-Kommentare)
**Description:** This PR fixes the main issue where comments are not updated in the UI: register a dependency on the length of the `comments` data array in the computed variable comments so that when the value (`this.segment?.relationships?.comments?.data`) changes, Vues reactivity system triggers a recomputation of the computed property
- fix some lila messages by adjusting parameters in the request 
- fix some vue console warnings

fix(DPLAN-15292): comments are not updated in the UI

---

tests/backend/core/Statement/Functional/SegmentsByStatementsExporterTest.php

DPLAN-14783
Mainly but not only adding testcoverage for DPLAN-14783
https://github.com/demos-europe/demosplan-core/pull/4445

feat (refs DPLAN-13111): Adding tests to cover censoring on export

---

demosplan/DemosPlanCoreBundle/Logic/StatementSynchronizer.php

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-4237/STN-Nr-wird-doppelt-vergeben
Description:
set NextValidExternalIdForProcedure on stn sync instead ofstrictly setting its source STN value
will become in targetProcedure that already holds a M2 id now
If you couple a procedure with a token obtained by an hearing-agency-procedure and you have your own statements created  within that same procedure before the hearing-agency starts to sync theirs - multiple STNs with the same externalId will be created since we strictly set the externalId of the source Statement.
I am not certain this issue is the root cause of this ticket - but this hearing-agency sync-feature got introduced before the ticket got created - and that makes it possible at least.

DPLAN-4237 set NextValidExternalIdForProcedure on stn sync instead ofstrictly setting its source STN value

---

composer.lock
templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/includes/assessment_table_pageheader.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_pageheader.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_list_survey_comments.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_new_member_list_mastertoeblist.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_survey_form.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/includes/administration_publicagency_pageheader.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/DemosPlanAssessment/cluster_detail.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_original_statements.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_statements.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanUser/includes/mastertoeblist_pageheader.html.twig

**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-12672/DiplanROG-neue-Stellungnahme-Hook-zurucksetzen
**Description:** This PR updates `data-cy` values:  ad to each each `subnav` item a data-cy attribute, to use it for testing purposes.
**Changes to the existing hooks (testers have been informed):**
createStatement --> listStatements:createStatement
listStatements:statementList --> listOriginalStatements:list
statement.new --> listOriginalStatements:createStatement
**Assessment table:**
assessmentTable --> assessmentTable:view
assessmentTableOriginal --> assessmentTable:viewOriginal
createStatement --> ssessmentTable:createStatement

use meaningful data-cy names instead of loop values

---

templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_pageheader.html.twig

[DPLAN-12672](https://demoseurope.youtrack.cloud/issue/DPLAN-12672/DiplanROG-neue-Stellungnahme-Hook-zurucksetzen)
**Description:** Adjust the page header hook by removing the redundant ':item' segment.

refac(DPLAN-12672): adjust base page header hook

---

client/js/components/procedure/basicSettings/DpProcedureCoordinate.vue

This is neccessary to interact with 3rd-Party systems/addons that require this field too

fix: Require location always.

---

composer.json
composer.lock
config/services.yml
demosplan/DemosPlanCoreBundle/Logic/User/OrgaService.php

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-15131/alt-EA5226-ADO-10592-DiPlanBeteiligung-ubernimmt-beim-Erstellen-eines-Beteiligungsverfahrens-den-Geltungsbereich-und-zeigt-diese
Description:
bump demosplan-addon version to include a orgaService Interface
linked pr: https://github.com/demos-europe/demosplan-addon/pull/138

DPLAN-15259  bump addon auto-install versions

---

client/js/components/user/DpCreateItem.vue
client/js/components/user/DpUserList/DpUserFormFields.vue
client/js/components/user/DpUserList/DpUserListItem.vue

[DPLAN-15376](https://demoseurope.youtrack.cloud/issue/DPLAN-15376/User-hinzufugen-Wenn-man-zuerst-Institution-Abteilung-und-Rolle-wahlt-wird-die-Rolle-nur-nach-Seitenrefresh-angezeigt-und-Form)
**Description:** This PR fixes an issue where the user information (such as department or role) for a newly added user was displayed only after the page reload.
- DpCreateItem: after creating a new user, update the store with the new user and its relationship
- DpUserFormFields: since `localUser` was added in the created hook, the actual data with its relationships was not available. A watcher on user was added to detect updates
- DpUserListItem: it seems that calling `state.initial[this.user.id]` from the state is redundant, as `DpUserListItem` already receives an actual user via props

feat(DPLAN-15376):  display user information (such as department or role) for a newly added user

---

package.json
yarn.lock

[DPLAN-15320](https://demoseurope.youtrack.cloud/issue/DPLAN-15320/Die-Organisationen-Liste-ladt-nicht) and others
The new version contains
- a spacing fix for the flyout trigger in DpFlyout/DpResettableInput
- an update of vue-sliding-pagination that is compatible with vue 3
- a new component DpConfirmDialog

chore(refs DPLAN-15320, #AB9149): bump demosplan-ui v0.4.11

---

client/js/components/tags/TagListEditForm.vue

**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-15263/Custom-confirm-Dialog-anstelle-des-nativen-Dialogs-window.confirm
**Description:** Update core to use new DpConfirmDialog, which replaces the native window.confirm functionality, as it is not accessible in certain situations (for example, when a user clicks to close all alert messages).

refac(DPLAN-15263): update the core to use the new custom dialog

---

client/js/components/procedure/basicSettings/DpBasicSettings.vue

This pull request includes a change to the `DpBasicSettings.vue` file to improve the validation and submission process of the configuration form. The main adjustments involve moving the `dpValidateAction` call to a different part of the code to ensure proper validation before form submission.

chore: validate fields before triggering addon calls

---

client/js/components/procedure/SegmentsList/CustomSearch.vue
client/js/components/statement/listStatements/CustomSearchStatements.vue

DPLAN-15396
- Remove handleSearch from toggleAllFields, because it is not needed and sets the searchTerm falsly after resetting
- Add handleSearch to handleChange, because we need to update items list after changes
- Use current main from demosplan-ui
- Verfahren -> Stellungnahmen -> Use search -> Resetting the search should show whole list and remove search term from search input
- Verfahren -> Abschnitte:
- Copy paste a word into search input -> Search should work
- Search for something -> Click settings in search field -> toggle all fields -> List should be updated
https://github.com/demos-europe/demosplan-ui/pull/1236

bug(refs DPLAN-15396): Fix custom search

---

client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaLocationAndDocumentReference.vue

DPLAN-15421
Saving button should also be enabled if we already have an element set and only change the document or paragraph. Also refactor logic for better understanding.
Verfahren -> Stellungnahmen -> Detailansicht -> Bearbeiten -> Orts- und Dokumentenbezug -> select different elements, documents and paragraphs

bug(refs DPLAN-15421): Enable saving button for documents

---

client/js/components/assessmenttable/DpNewStatement.vue
client/js/store/statement/AssessmentTable.js
templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig

[DPLAN-15379](https://demoseurope.youtrack.cloud/issue/DPLAN-15379/Beim-wahlen-von-ein-Planungsdokument-Uncaught-in-promise-TypeError-this.options-is-undefined)
- it seems the update of `this.values` via `v-model` is not completed in the `@input` handler, so we now use the updated value directly that is emitted by `DpMultiselect`
- before, `this.values.element.id` always contained the previously selected element id or `undefined` (if no element had been selected before)

fix(refs DPLAN-15379): use updated data for checks

---

client/js/components/map/admin/AdminLayerListItem.vue
demosplan/DemosPlanCoreBundle/DoctrineMigrations/2025/04/Version20250409062943.php

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-15372/Produktion-BB-Bauleitplanung-Kartenlayer-lassen-sich-ggf.-nicht-einblenden-und-nicht-editieren-26426
DescriprionÄ:  set visibility group id to null when unset overlays

f-DPLAN-15372 set visibility group id to null when unset overlays

---

package.json
yarn.lock

With the new version,
- DpButton emits blur, focus, and mousedown events
- it is possible to set an input width for DpSearchField
- the colCount for an empty DpDataTable is fixed

chore: bump demosplan-ui from v0.4.12 to v0.4.13

---

client/js/components/statement/splitStatement/CardPane.vue
client/js/components/statement/splitStatement/CardPaneCard.vue
client/js/components/statement/splitStatement/SegmentationEditor.vue
client/js/components/statement/splitStatement/SplitStatementView.vue

In Vue 3, the .native event modifier has been removed (see https://v3-migration.vuejs.org/breaking-changes/v-on-native-modifier-removed).
- To be able to remove its usages, we need to emit the corresponding event from the component that we place the handler on
- Focus events were also added to allow for keyboard navigation
- The segmentation editor can't be focused, but we get an eslint vuejs-accessiblity warning due to `'vuejs-accessibility/mouse-events-have-key-events'` that I did not manage to disable for the corresponding lines, so I added the event listeners instead
- Some events have been renamed to match our conventions
- In CardPaneCard, DpButtonIcon has been replaced with DpButton, and unless it's used in an Addon (edit: it is), I think we can now remove the component from …

fix(refs #AB9149): remove obsolete .native modifier

---

client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementPublicationAndVoting.vue
client/js/components/statement/voter/StatementVoter.vue

DPLAN-15488
Editable list now emits the delete and showUpdateForm events directly and not via parent.
Verfahren -> Stellungnahmen -> Detailansicht -> Bearbeiten -> Editing and deleting votes should work

bug(refs DPLAN-15488): Fix editable list

---

templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_statements.html.twig

DPLAN-15495
We only want to link to the import center if `feature_simplified_new_statement_create` is enabled. Otherwise, we need the old view for creating statements.
Verfahren -> Stellungnahmen -> Neue Stellungnahme -> You should get to the "old" create new statement view and not the import center.

bug(refs DPLAN-15495): Fix path for new statement

---

package.json
yarn.lock

The new version contains
- a fix for tooltips in DpEditor
- a new prop `openDirection` for DpMultiselect
- several dependency updates

chore: bump demosplan-ui from v0.4.13 to v0.4.14

---

client/js/components/statement/splitStatement/SideBar.vue
client/js/components/statement/splitStatement/TagSelect.vue

**Description:** Vue-Multiselect automatically positions the dropdown where there is the most space. The multiselect is inside a scrollable container, and sometimes this causes the dropdown to appear above (because the dropdown menu is absolutely positioned, the container does not scroll it, but simply clips it)
I tried different approaches: adding a min-height or removing the absolute positioning, but there were always issues and none were perfect. I settled on having the first six dropdowns open downward (since the dropdowns max-height is 300 px). I know it is not the ideal solution, but I find it better than the others...
Additional PR in UI is provided

fix(DPLAN-15284): splitStatement: dropdown menu open direction

---

demosplan/DemosPlanCoreBundle/Entity/Procedure/Procedure.php

Error in symfony toolbar indicated this problem.
No migration needed, because this is doctrine only and was never modeled.

fix: inverse side does not exists

---

client/js/components/document/ElementsAdminItem.vue

[DPLAN-12612](https://demoseurope.youtrack.cloud/issue/DPLAN-12612/Kapitelbezogene-Kategorien-sollten-keine-Toggle-haben-weil-die-Kategorien-kapitelbezogen-sind) 
This PR removes the toggle option for custom categories that are only chapter based, not for whole documents.

fix(refs DPLAN-12612): remove toggle for chapter based doc categories

---

client/js/components/document/ElementsAdminItem.vue

Misunderstood Ticket [DPLAN-12612](https://demoseurope.youtrack.cloud/issue/DPLAN-12612) (see comments there). The wrong toggle was removed.

Revert "fix(refs DPLAN-12612): remove toggle for chapter based doc categories"

---

client/js/components/procedure/admin/InstitutionTagManagement/InstitutionTagManagement.vue

DPLAN-15569
In Vue 3, the way slots are handled has changed compared to Vue 2. Specifically, Vue 3 enforces stricter rules for component structure and slot usage. Wrapping DpTabs in a <slot> was necessary to show the list.
Institutionen verschlagworten, look if the list is rendered.
- [ x] Run `yarn lint`
- [ x] Run `yarn test`
- [ x] Link all relevant tickets
- [ x] Move the tickets on the board accordingly

fix(refs DPLAN-15569) Wrap DpTab in a slot

---

demosplan/DemosPlanCoreBundle/Logic/Statement/DraftStatementService.php

DPLAN-15199
This PR fixes an issue where institution coordinators were unable to download PDFs of statements.
The problem was caused by an unhandled exception when trying to get file information for screenshots
that might be missing or invalid. The fix adds proper exception handling and null checks.
I tried hard to create a Test, but DraftStatementService needs to be refactored beforehand.
1. Login as an institution coordinator (I-Ko)
2. Submit a statement, save as draft
3. Release the statement
4. Reject the statement and release again
5. Try to download the statement as PDF - should work now

fix(refs DPLAN-15199): catch and handle exception when screenshot info is missing

---

demosplan/DemosPlanCoreBundle/DataGenerator/Factory/CustomFields/CustomFieldConfigurationFactory.php
demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureDeleter.php
demosplan/DemosPlanCoreBundle/Services/Queries/SqlQueriesService.php
tests/backend/core/Procedure/Functional/ProcedureDeleterTest.php

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-15567/Delete-custom-fields-of-procedure-as-part-of-deleting-a-procedure
- This PR implements functionality to delete custom fields associated with a procedure when that procedure is deleted. Custom fields are now properly cleaned up, preventing orphaned data from remaining in the database.                                                                                                                                                   - The implementation adds a new method to `ProcedureDeleter` that uses a new method in `SqlQueriesService` to delete database records based on multiple conditions, which allows for more precise deletion operations. …

Feat dplan 15567 delete custom fields related to procedure

---

client/js/components/statement/publicStatementLists/DpPublicStatementList.vue
templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_draft.html.twig

DPLAN-15595
Added a new prop hasTabs to enable a different layout when tabs are needed. This allows components to switch between standard and tabbed layouts dynamically. 
login as In-Sa and take a look at "Entwürfe" -> tabs, and "Freigaben" -> no tabs
https://github.com/demos-europe/demosplan-core/pull/4616
- [ x] Run `yarn lint`
- [ x] Run `yarn test`
- [ x] Link all relevant tickets
- [ x] Move the tickets on the board accordingly

B DPLAN-15595 add prop for different usecases

---

client/js/components/procedure/admin/InstitutionTagManagement/TagListItem.vue

[DPLAN-14565](https://demoseurope.youtrack.cloud/issue/DPLAN-14565)
Switched edit and trash buttons in the template of TagListItem.vue so that edit appears first.

fix(refs DPLAN-14565): switch trash and edit buttons

---

client/js/components/map/publicdetail/Map.vue

After refactoring DpAutocomplete in demosplan-ui, we now should use modelValue when using it

refactor(refs DPLAN-15262): Use modelvalue for autocomplete

---

demosplan/DemosPlanCoreBundle/ResourceTypes/CustomerResourceType.php

- Reduces minimum length for base layer names from 5 to 1 characters so that valid short layer names like 'web' can be used

fix(DPLAN-15610): allow short layer names

---

client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue

[DPLAN-15590](https://demoseurope.youtrack.cloud/issue/DPLAN-15590/Die-gewahlte-Konfigurierbare-Abschnittsfelder-sind-nicht-sichtbar-beim-hooveren-auf-das-oder-unter-Option-Selektor)
Description:

Fix(DPLAN-15601): no custom fields displayed on the page reload

---

templates/bundles/DemosPlanCoreBundle/DemosPlanUser/portal_user.html.twig

[DPLAN-15434](https://demoseurope.youtrack.cloud/issue/DPLAN-15434/Meine-Daten-Zeilen-verschoben)
Sets the full-width parameter to true so that the profile content takes the full screen-width (otherwise the participation_area_skeleton.html.twig renders an aside-element on the left side).
- [ x ] Link all relevant tickets
- [ x ] Move the tickets on the board accordingly

fix(refs: DPLAN:15434): remove indentation of profile data on big screens

---

demosplan/DemosPlanCoreBundle/Logic/Map/CoordinateJsonConverter.php

Ticket: https://demoseurope.youtrack.cloud/tickets/DS-43/BOM-Fehlermeldung-bezuglich-Umgriff
Description: JSON_FORCE_OBJECT converts JSON arrays to PHP arrays, and JSON objects to associative arrays, in this case a we have to decode jsons by default weil a numeric arrays are expected and not associative arrays.

f DS-43 remove JSON_FORCE_OBJECT flag : 

---

translations/messages+intl-icu.de.yml

[DPLAN-15552](https://demoseurope.youtrack.cloud/agiles/141-63/current?settings&tab=allgemeines&issue=DPLAN-15552)
**Description:** This PR adjusts the warning message for the TagRecommendationTab component. The previous message was unclear: when a tag existed, it incorrectly stated that no tags had been created for the segment. It now clearly informs the user that there are no recommendations for the selected tag, or if there are no tags, we will show the previous text. additional PR in a Addon provided.

ref(DPLAN-15552): adjust text

---

.github/workflows/reviewdog.yml

This pull request updates the `.github/workflows/reviewdog.yml` file to include the `composer.lock` file in the list of files monitored by the workflow to let dependabot PRs trigger the ci.
* [`.github/workflows/reviewdog.yml`](diffhunk://#diff-0858429e63b8667fbf7cc466f8e90dfb43cd7c6ef824edd6c17a0df649745f7dR9): Added `composer.lock` to the list of file patterns that trigger the workflow.

chore: run reviewdog on dependabot prs

---

client/js/components/procedure/StatementSegmentsList/SegmentsRecommendations.vue

[DPLAN-15291](https://demoseurope.youtrack.cloud/agiles/141-63/current?settings&tab=allgemeines&issue=DPLAN-15291)
Description: This PR fixes an issue with the toggle-all function in the segments list. The problem appeared after the Vue 3 migration. Unfortunately, using the ref with dynamic keys do not work as expected in Vue 3. Use ref="segment" within the loop instead, which sets `this.$refs.segment` to an array of component instances.
- while technically still allowed, Vue 3 does not recommend using dynamic keys like :ref="'segment' + idx' inside v-for, use a static ref name instead.

Fix(dplan 15291): toggle all does not work

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_boilerplate_group.html.twig

On smaller screens when the btns stack vertically.
[DPLAN-15188](https://demoseurope.youtrack.cloud/issue/DPLAN-15188/Keine-Padding-zwischen-Gruppe-anlegen-und-Abbrechen-wenn-kleinere-Window)
Adds an additional wrapper-div to the buttons to implement flexbox independently from the 'layout__item' class.

fix(refs: DPLAN:15188): Add spacing between btns

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-14775
Description: this fix belongs to https://github.com/demos-europe/demosplan-core/pull/4480. This adjustement was by mistake missed after https://github.com/demos-europe/demosplan-core/pull/4480 was picked.

f-DPLAN-14775 add missing twig adjustement

---

client/js/components/procedure/imageAnnotator/DpImageAnnotator.vue
client/js/components/procedure/imageAnnotator/DpLabelModal.vue

[DPLAN-15489](https://demoseurope.youtrack.cloud/issue/DPLAN-15489/PDF-Import-Nicht-moglich-um-Boxen-zu-wahlen-oder-bearbeiten-oder-hinzufugen)
**Description:** This PR fixes issue with OpenLayers interactions and the issue with `this.$refs.labelModal.toggle() is undefined`. These issues appeared after migration to vue3.
- wrap OpenLayers interactions in markRaw so that: Vue won’t convert them into Proxies, OL’s instanceof checks and internal state stay intact, otherwise `this.map.addInteraction(this.currentInteraction) `silently fails.
- fix the issue with `this.$refs.labelModal.toggle() is undefined` by adding the` <template>` tags to the component.

Fix(dplan-15489): openLayers interaction issue

---

composer.json
composer.lock
demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementTagController.php
demosplan/DemosPlanCoreBundle/Event/Tag/UpdateTagEvent.php

Description: Add new Event to cover update Tag in TopicalTagAddon

New Event to cover update Tag in topicalTag Addon

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig

This PR fixes a typo in a hook name. Related PRs in projects and addons are available.

fix: adapt hook name

---

client/js/components/procedure/StatementSegmentsList/StatementSegment.vue

[DPLAN-15675](https://demoseurope.youtrack.cloud/issue/DPLAN-15675/Nicht-zugewiesen-wird-nicht-beim-hooveren-auf-ein-Tooltip-angezeigt)
set a customField to 'Nicht zugewiesen' and check the tooltip

fix(refs DPLAN-15675): show not assigned in tooltip

---

demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementTagController.php

Description: Trigger Event when method is Post

Use Event in Post Method

---

client/js/components/user/DpOrganisationList/DpOrganisationList.vue

Load branding/cssvars for orgas to display the saved values
DPLAN-15558
The saved branding data where not displayed, so it was not possible to see what colorsettings where saved.
Ass support goto orga-edit and set branding colors. see if they get displayed after saving and after reloading the page. For both: pending and "accepted" orgas

fix(refs DPLAN-15558): Load branding/cssvars for orgas

---

demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php

Ticket: https://demoseurope.youtrack.cloud/tickets/DS-82/Zip-Ex-Import-RO-EWM
Description: preserve marked text

f-DPLAN-82 preserve marked text

---

tests/backend/core/Core/Unit/Logic/Segment/RpcBulkEditor/SegmentBulkEditorServiceTest.php

We adjusted the way how we store custom fields. We sort first the custom field values per id, and then store them in the column custom_fields of the segment table. Consequently, this test started to failed. this pr is to fix the test

fix: Fix failing test

---

package.json
yarn.lock

General maintenance task - no specific ticket. After merge of #4592 this dependency is unused.
Remove unused vuejs-datepicker dependency from package.json. The project has already migrated to a11y-datepicker via @demos-europe/demosplan-ui, making vuejs-datepicker redundant. No code references to vuejs-datepicker remain in the codebase.
- Verify that no references to vuejs-datepicker exist in the codebase
- Run `yarn dev:diplanbau` to ensure build still works
- Check that date picker functionality still works in the application

Remove unused vuejs-datepicker dependency

---

demosplan/DemosPlanCoreBundle/Logic/Document/ElementsService.php
demosplan/DemosPlanCoreBundle/Repository/ParagraphRepository.php

https://demoseurope.youtrack.cloud/issue/DPLAN-15650/Verfahren-kann-nicht-erstellt-werden
I removed two flush calls, redundant persist calls. In copyParagraphsOfElement I think we can use the new created paragraph entities directly. Until now I can't reproduce the Deadlock exception on this branch. I can well imagine that the deadlock exception could still occur. But perhaps less frequently?
run locally bin/project dp:maintenance to start the maintenance task, then create a procedure via web interface
- [] Move the tickets on the board accordingly

feat (refs DPLAN-15650): Remove error prone flushes.

---

demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement_detail_statement_data.html.twig

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-15328/BLP-Einreicherdaten-in-STN-immer-editierbar-machen
Description: 
- make submitter data always editable : submitter fields in 'assessment_statement_detail_statement_data.html.twig' have to be always editable
- adjust statement update condition : not manual statement can be updated too
- email address will not be editable

feat(refs dplan 15328): make submitter data always editable

---

demosplan/DemosPlanCoreBundle/Logic/Import/Statement/ExcelImporter.php

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-15765/Abschnittsimport-Upoload-gibt-Fehlermeldung
Description: 
use Symfony's string component to provide Unicode handling, including whitespace and normalization functions:
Many "invisible" or "special" characters can find their way into Excel ".xlsx" cell data, especially with copy-paste, imports, or exports between various systems and formats which causes errors while uploading segments, that's why the tags titles strings have to be cleaned before be used and added.

f DPLAN-15765 use Symfony's string component to provide Unicode handling, including whitespace and normalization functions

---

client/js/bundles/map/publicDetailDiplanKarte.js

`DpPublicSurvey` has been removed in `main`, but it was used in a new file on `f_tryout_diplankarten`. After merging `main` into `f_tryout_diplankarten` the build was therefore broken. The usage of DpPublicSurvey is removed in this PR.

fix: remove obsolete component

---

demosplan/DemosPlanCoreBundle/Logic/Statement/Exporter/StatementArrayConverter.php
tests/backend/core/Statement/Export/StatementArrayConverterTest.php

https://demoseurope.youtrack.cloud/issue/DPLAN-15776/Obwohl-STN-Dateien-hat-wurden-die-Dateinamen-nicht-im-Originalstellungnahme-Export-angezeigt
Display filenames when exporting original statement in csv
Also this fix works for exporting stn segements on excel

fix DPLAN-15776: Display FileNames when exporting Original stn as csv, also Stn as excel

---

client/js/components/map/publicdetail/DiplanKarteWrapper.vue

DPLAN-15778
1. Open diplanfest an login as Hannes Rudzkam (Private User)
2. Open a procedure and visit the tab "Interaktive Karte"
3. Klick at the Button "Reden Sie mit!" -> Modal opens
4. Close the modal and check if the map shifted down under the button
There should be no layout shifts in the end

fix(refs: DPLAN-15778): Prevent layout shift when modal closes

---

demosplan/DemosPlanCoreBundle/Repository/EmailAddressRepository.php

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-11632/BOB-SH-Bauleitplanung-Prod-bestimmte-Mailadresse-kann-in-einem-Verfahren-nicht-gespeichert-werden-T36900
Description: 
Case insensitive email address comparison:
- array_diff is case-sensitive, therefore the already existing email from input could not be found and so it appears in array_diff which causes an unique constraint error when updating.
- this is done while sorting email addresses too otherwise emails with corresponding value will be incorrectly omitted from the return which causes errors too.

f-DPLAN-11632 Case insensitive email address comparison

---

client/js/components/map/admin/LayerSettings.vue
client/js/components/procedure/SegmentsList/SegmentsList.vue
client/js/components/statement/listOriginalStatements/ListOriginalStatements.vue
client/js/components/statement/listStatements/ListStatements.vue
client/js/components/user/DpTableCardList/DpTableCardListHeader.vue
client/js/components/user/DpUserListExtended.vue
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_master.html.twig

[DPLAN-15771](https://demoseurope.youtrack.cloud/issue/DPLAN-15771/ADO-Issue-29551-Funktion-zur-Auswahl-aller-Layer-beim-Einbinden-von-WMS-Diensten.)
This PR deals with the map layers options. So far, it was possible to choose or deselect single layers. This PR activates the 'selectAll' and 'unselectAll' options, so that all available layers can be handled in one go. 
It also adjusts:
- the ordering of component attributes in accordance with the Vue.js Style Guide
- the custom event names to camelCase
Choose a STN --> go to 'Planungsdokumente und Planzeichnung' --> 'Kartenebenen definieren' --> edit 'Grundkarten' --> 'Layer' dropdown menu. Apart from being able to select/deselect single layers, it should also be possible to select/deselect all layers at once.
- [ x ] Run `yarn lint`
- [ x …

feat(refs DPLAN-15771, #AB29551): add selectAll to layers

---

tests/backend/core/Document/Functional/ElementsServiceTest.php

No specific ticket - test infrastructure improvement
Fix occasionally failing elements test by improving test reliability and removing timing dependencies.

chore: fix occasionally failing elements test

---

demosplan/DemosPlanCoreBundle/Controller/Document/DemosPlanDocumentController.php

- Replace missing template rendering with proper 404 redirect when access to public paragraph documents is forbidden

fix: redirect to 404 instead of missing template

---

package.json
yarn.lock

New version contains these changes:
- `data-dp-validate-topic` option can be passed to dpValidateMixin
- BREAKING: `'select-all'` event in `DpDataTable` is renamed to `'selectAll'`, `'select-all'` and `'unselect-all'` events in `DpMultiselect` are renamed to `'selectAll'` and `'deselectAll'`

chore: bump demosplan-ui from 0.4.16 to 0.4.17

---

tests/frontend/unit/DpBulkEditStatement.spec.js

for some - for me not understandable - reason, one of 4 tests breaks with a "dynamic import" error
```
RUNS  tests/frontend/unit/DpBulkEditStatement.spec.js
/srv/www/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2145
err = err instanceof Error ? err : new Error(String(err));
^
Error: TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING_FLAG]: A dynamic import callback was invoked without --experimental-vm-modules
at /srv/www/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2145:42
```
DPLAN-15256

chore(refs DPLAN-15256): skip breaking FE Test

---

client/js/components/procedure/StatementSegmentsList/SegmentLocationMap.vue

[DPLAN-15821](https://demoseurope.youtrack.cloud/issue/DPLAN-15821/Abschnitte-Ortsmarkierung-wird-nur-nach-einem-Seitenrefresh-angezeigt)
This PR fixes the updateStore function by spreading the updatedAttributes object. Now the changes are made correctly in the vuex store and the polygon changes show immediately. 
1. Navigate to "Erwiderungen verfassen" in a statement with segments.
2. Click the pin icon on a segment to open the "Ortsbezug" modal.
3. Change or add a polygon, save it and close the modal.
4. Open the modal again and check if your changes show.

fix(refs DPLAN-15821): add spread operator to updateStore

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig

This fix addresses an oversight from the previous implementation of DPLAN-15554 where the `data-dp-validate-topic` attribute was missing from the "Informationen zum Verfahren" fieldset.
- create new "Verfahren", delete "Ansprechperson" in "Informationen zum Verfahren" and save
- https://github.com/demos-europe/demosplan-core/pull/4655

fix(refs: closed DPLAN-15554) Adding data-dp-validate-topic attributes to form fieldsets

---

package.json
yarn.lock

DPLAN-15854
The new version of diplan-karten is needed, to add the information of the local reference to a statement. The diplan-karten updates from 0.6.1 to 0.7.2 
1. Open diplanfest and open a procedure
2. In the tab "Interaktive Karte" the map should be loaded

feat(refs: DPLAN-15854): update diplan-karten from 0.6.1 to 0.7.2

---

client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue

[DPLAN-1987](https://demoseurope.youtrack.cloud/issue/DPLAN-1987) Nummerierungen können bei Aufteilung nicht in Abschnittstext übernommen werden
**Description:** This PR fixes an issue with the styling of lists in the statements segments list by adding c-styled-html class to the dp-edit-field component.

fix(DPLAN-1987): add c-styled-html class to dp-edit-field

---

demosplan/DemosPlanCoreBundle/Validator/ProcedureInCoupleAlreadyUsedConstraintValidator.php

No specific ticket - test infrastructure improvement
Fix race condition in test that occurs when a relationship is not loaded yet, ensuring tests run reliably without timing dependencies.

chore: fix race condition in test when relationship is not loaded yet

---

demosplan/DemosPlanCoreBundle/Logic/MailService.php

The `_ms_error_message` field in the MailSend entity was not being populated when mail sending failed. This change ensures that both error code and error message from mail transport exceptions are properly stored in the database for debugging purposes.
- Store exception message and code in MailSend entity when transport fails  
- Clear error fields on successful mail sending
- Improve error tracking for failed mail delivery
1. Review the changes in `demosplan/DemosPlanCoreBundle/Logic/MailService.php`
2. Verify that `setErrorCode()` and `setErrorMessage()` are called in exception handlers
3. Check that error fields are cleared on successful mail sending
4. Test mail sending failures to ensure errors are properly stored in the database

fix: Populate _ms_error_message field with actual mail error details

---

templates/bundles/DemosPlanCoreBundle/DemosPlanUser/unregistered_publicagency_list.html.twig

[DPLAN-11742](https://demoseurope.youtrack.cloud/issue/DPLAN-11742) Unregistrierte Insti: Klick auf entfernen -> Uncaught DOMException: Document.querySelectorAll: '[id=] [data-form-actions-added]' is not a valid selector
**Description:** This PR fixes a console issue that occurred when deleting an unregistered public agency.
- to be able to remove the form's hidden field (FormAction.js), an ID is required: the ID `unregisteredPublicAgencyList` has been added to the form in the `unregistered_publicagency_list.html.twig` file.

fix(DPLAN-11742): console issue when deleting an unregistered public agency

---

templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_list.html.twig

[DPLAN-12599](https://demoseurope.youtrack.cloud/issue/DPLAN-12599/Hinweise-zur-Karte-Text-nach-speichern-automatisch-mit-viel-Whitespace)
After saving a description for a map, the typed in text was getting indented towards the middle of the page. This PR removes the whitespace before and after the variable input.
Log in as admin --> go to 'Planungsdokumente und Planzeichnung' - 'Kartenbeschreibung festlegen' --> add a description --> text indentation should stay the way you typed it.

fix(refs dplan-12599): Remove whitespace in map description

---

demosplan/DemosPlanCoreBundle/Logic/User/UserHandler.php

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-16032
Description:
Fixed handleWipeSelectedDepartments and handleWipeSelectedOrgas methods
to properly handle elementsToAdminister array parameter by using
$requestData->all() instead of $requestData->get().
This resolves the "non-scalar value" error when multiple items are
selected for deletion operations.

fix(DPLAN-16032): use all() instead of get() for array parameters in UserHandler

---

client/js/store/map/Layers.js

[DPLAN-16053](https://demoseurope.youtrack.cloud/issue/DPLAN-16053/ADO-31431-Integration-ROG-Hinterlegter-Text-im-Kontexhilfe-wird-nicht-angezeigt)
This PR adds 'contextualHelp' to the fields of the API call made in the Layers vuex store so that DpPublicLayerList.vue can actually access the data.
1. Create a procedure with at least one map layer.
2. Navigate to 'Planungsdokumente und Planzeichnung' > edit 'Kartenebenen' > edit 'Overlays'
3. Write something in the contextual help field and save.
4. Switch to 'Oeffentlichkeits/Institutionenansicht' and unfold 'Kartenebenen' on the left.
5. There should be a small '?' symbol next to the edited layer.
6. Hover over the '?' and check if your text shows.

fix(refs: DPLAN-16053): add contextualHelp to fields of API call

---

config/packages/rate_limiter.yaml

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-15970/PDF-Import-Wenn-man-ungefahr-100-PDFs-importiert-sind-die-importierte-PDFs-nur-nach-einem-Seitenrefresh-sichtbar
Description:
Prevents 'Too Many Requests' errors when uploading large numbers of files during import operations. The previous limit of 100 requests per 30 days was insufficient for bulk file operations in EWM.
Fix already applied via vim edit to EWM-Dev.
You can try to upload 2 batches of files exceeding 100 together. (ask if you need testfiles)
Do not upload for than 92 files at once - this triggers a different error.

fix(DPLAN-15970): increase JWT token rate limit from 100 to 500 requests

---

docker/demosplan-production/nginx.conf.template

This pull request updates the Nginx configuration template to enhance compression and caching for static assets, improving performance and resource handling. The key changes include adding new MIME types for compression, introducing caching rules for static files, and ensuring proper headers are set for specific file types.
* Updated the `gzip_types` directive to include `application/font-woff2` and `application/vnd.api+json` MIME types, enabling compression for these file types.
* Enhanced the static file handling section:
- Added MIME type headers for `.woff2` and `.js` files.
- Introduced caching rules:
- Images (`.jpg`, `.jpeg`, `.png`, `.gif`) are cached privately for 1 year with an immutable directive.
- Other static assets (`.css`, `.js`, `.woff2`) are cached publicly for 1 year …

chore: add caching to nginx

---

client/js/components/user/DpCreateItem.vue
client/js/components/user/DpOrganisationList/DpOrganisationFormFields.vue
client/js/components/user/DpOrganisationList/DpOrganisationList.vue
client/js/components/user/DpOrganisationList/DpOrganisationListItem.vue
client/js/components/user/DpUserList/DpUserFormFields.vue
client/js/components/user/DpUserList/DpUserListItem.vue
tests/frontend/unit/DpBulkEditStatement.spec.js

[DPLAN-16033](https://demoseurope.youtrack.cloud/issue/DPLAN-16033) Neue Orga erscheint nur nach einem Seitenrefresh
**Description:** This PR fixes several issues:
- pending organisations list was not updating correctly after deleting an organisation
- pagination of the pending organisations list was broken
- newly added NON-pending organisations did not appear in the “All Organisations” list
**Fixes:**
- fetch pending organisations after deleting an organisation
- include the page property in `pendingOrganisationList` request
- improve UX by displaying a skeleton-box during state updates
- remove the pending-status check before emitting the 'get-items' event so newly added organisations appear in the “All Organisations” list
- fix some lint warning in this PR: _Custom events must be …

Fix(dplan-16033): several issues on the organisation list page

---

client/js/bundles/procedure/administrationStatementSegmentsList.js
client/js/components/procedure/Shared/SimilarStatementSubmitters/SimilarStatementSubmitters.vue
translations/messages+intl-icu.de.yml

[DPLAN-15860](https://demoseurope.youtrack.cloud/issue/DPLAN-15860/Weitere-Einreichende-sind-nur-nach-einem-Seitenrefresh-geloscht)
After deleting a 'weitere einreichende Person', the change was only visible after a manual reload of the page. The problem was that the SimilarStatementSubmitters was not registered in the store entry point of the parent component StatementSegementList.
This PR also adds the confirmation alert window with a translation for this case.
Logged in as an admin, go to 'Abschnitte - Bearbeiten' or 'Stellungnamhen - Details und Erwiderung- Bearbeiten'--> add an entry to 'Weitere Einreichende der gleichen Stellungnahme' --> delete the entry --> there should be a confirmation alert window, success pop up and the component should re-render.

fix(refs dplan-15860): Rerender automatically after deleting a SimilarStatementSubmitters entry

---

client/js/components/map/map/DpOlMap.vue
client/js/components/map/publicdetail/DiplanKarteWrapper.vue
client/js/components/statement/assessmentTable/DpMapModal.vue
client/js/lib/map/transformFeature.js
tests/frontend/unit/transformFeature.test.js

DPLAN-16035
This is sort of a interim fix until diplan-karte can handle projection settings from outside.
diplan-karte uses a different projection then the parent app. And since some of the settings in the parent app are stored in the database and not jet configurable in the interface for the project, where diplan-karte is used, its easiest to transform the geoJson.
as "privatperson" try to make some drawings for a statement and then save as draft. goto the drafts list and see if you can see the drawing in the map modal there. 
It also should work to go back to the publick detail with "edit statement" and still/gain see the drawing.
(this may only works for the region, defined as map_public_extent in the project-settings)

fix(refs dplan-16035): Transform geojson for diplan-karte

---

client/js/components/faq/DpFaqItem.vue

[DPLAN-15946](https://demoseurope.youtrack.cloud/issue/DPLAN-15946) Fehlermeldung beim Ändern des Status in "Häufige Fragen"
**Description:** This PR fixes an issue where changing the FAQ’s status caused an error.
-  send/save only relevant data: 'id', 'type' and 'attributes' instead of the entire FAQ object

Fix(DPLAN-15946): Fix(DPLAN-15946): error while changing the FAQ’s status

---

client/js/components/document/ElementsAdminList.vue

[DPLAN-16101](https://demoseurope.youtrack.cloud/issue/DPLAN-16101/Fehler-wenn-man-importierte-Dokumente-loscht)
This PR modifies the bulkDelete() method to first filter out all child elements whose parents are also selected for deletion, since the backend automatically deletes all (grand-)children of parent elements. This way, there is no call for a child element to be deleted twice.
1. Log in as an admin and navigate to documents in a procedure.
2. Upload a zip file with subfolders (test file is linked in ticket). 
3. Bulk delete folder with a subfolder.

fix(refs: DPLAN-16101): filter elements before delete 

---

demosplan/DemosPlanCoreBundle/Application/ConsoleApplication.php
demosplan/DemosPlanCoreBundle/Command/Data/RemoveUserDataCommand.php
demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementController.php
tests/backend/core/Core/Unit/Faker/Provider/ApproximateLengthTextTest.php

Description: resolve critical PHPStan errors causing fatal exceptions
- Replace deprecated Faker textCloseToLength() with text() method
- Fix PHPDoc annotation format from /* to /** for proper parsing
- Replace deprecated Monolog addError() with error() method
- Update test assertions to use standard Faker text() method

fix: resolve critical PHPStan errors 

---

demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php
demosplan/DemosPlanCoreBundle/Command/Data/RemoveUserDataCommand.php
demosplan/DemosPlanCoreBundle/Controller/Document/DemosPlanDocumentController.php
demosplan/DemosPlanCoreBundle/Entity/Statement/StatementFragment.php
demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/AssessmentTableServiceOutput.php
demosplan/DemosPlanCoreBundle/Logic/TransformMessageBagService.php
tests/backend/core/Core/Functional/TransformMessageBagServiceTest.php

Description: The changes affect console commands, session handling, data removal operations, statement fragment processing, and assessment table output generation.
- Fix Symfony Console Helper type annotation for QuestionHelper
- Add EntityManagerInterface imports and type casts for Doctrine ORM operations
- Replace deprecated getFlashBag() with getBag('flashes') and proper type handling
- Add null safety checks and instanceof validation for Laravel Collection operations
- Fix polymorphic call warnings with proper FlashBagInterface type annotations
- Add type-safe session bag handling with fallback for incompatible types
Resolves 15+ critical PHPStan level 1 errors that would cause fatal PHP exceptions:
- Undefined method calls on wrong interfaces
- Null pointer exceptions in collection …

Fix: resolve PHPStan errors preventing runtime exceptions

---

package.json
yarn.lock

Bumps demosplan-ui to the newest 0.4.x version.
- DpEditableList now has a closeOnSuccess prop
- keyboard navigation for ActionMenu.js has been improved
- DpProgressbar now shows a blue bar (instead of green), and the percentage can be hidden
- DpAutocomplete can now have an icon-only search button inside the input

chore(refs DPLAN-16080): bump demosplan-ui from v0.4.19 to v0.4.22

---

client/js/components/procedure/publicindex/DpSearchProcedureMap.vue

[DPLAN-16080](https://demoseurope.youtrack.cloud/issue/DPLAN-16080/Suchschlitz-nicht-schon-in-Mobilansicht)
- to avoid the placeholder in the autocomplete input being cut off on small screens, we can now use a (smaller, icon-only) search button attached to the input
- at the same time, the placeholder is moved outside of the input and displayed above it as a label, while (the shorter) 'search' is displayed as the placeholder in the input (these changes are implemented in demosplan-ui)
Go to the index page and check that the search input looks and works fine both on small and larger screens

fix(refs DPLAN-16080): use search button in DpAutocomplete for small screens

---

client/js/components/map/map/DpOlMap.vue

when passing the mapOrder straight, it will cause caps because the mapOrder gets synced with the treeOrder. Means the first Layer mapOrder may be 101. OpenLayers don't like it. So we have to sort upfront and just pass the index for ordering

fix: Pass order without gaps

---

demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedurePhase.php

- Fix typed property initialization error in ProcedurePhase entity
- Initialize $permissionSet with default value to prevent Doctrine proxy access errors
The `ProcedurePhase::$permissionSet` property was typed as `string` but accessed before initialization when Doctrine created proxy objects. This caused the error:
```
Typed property demosplan\DemosPlanCoreBundle\Entity\Procedure\ProcedurePhase::$permissionSet must not be accessed before initialization
```
Added default value initialization to the property declaration:
```php
protected string $permissionSet = ProcedureInterface::PROCEDURE_PHASE_PERMISSIONSET_HIDDEN;
```
This ensures the property is always initialized, even when Doctrine creates proxy objects without calling the constructor.
- …

Fix ProcedurePhase:: initialization

---

client/js/components/procedure/AdministrationImport/ExcelImport/ExcelImportErrors.vue
client/js/components/statement/publicStatementModal/StatementModal.vue
demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_progress-bar.scss
demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_statement.scss
demosplan/DemosPlanCoreBundle/Resources/client/scss/utility/_display-visibility.scss
translations/messages+intl-icu.de.yml

[DPLAN-16085](https://demoseurope.youtrack.cloud/issue/DPLAN-16085/STN-Offentlichkeits-Mobilansicht-Reiter-Layout-ist-kaputt)
The layout of the header navigation in StatementModal for not logged-in users was broken. This PR implements a mobile version of it --> instead of a 3 step-header, only the current step is rendered in the header (with a modified progress bar component). For navigating to the previous steps, 'Zurück'-buttons were added (also on big screens).
It solves the 'missing padding between buttons' part of this layout-bug-ticket:
DPLAN-16082: https://demoseurope.youtrack.cloud/issue/DPLAN-16082/Keine-Padding-auf-rechter-linker-Seite-beim-Beteiligung-in-Offentlichkeitsansicht
Click on the 'Reden Sie mit' button --> check the layout and the functionality of the 3-steps …

fix(refs dplan-16085):  Add mobile version of StatementModal nav

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_map.scss
templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_public_participation_detail.html.twig

DPLAN-16083
After marking a location on map a popup opens on the marked position. This popup is too small in mobile view, so that the user cannot see the button to switch back to the statement modal. This change fix the style.
1. Open diplanbau or diplanrog and login as a private user
2. Open a procedure and switch to mobile view
3. Switch to mark location tab and mark a location on the map
4. Check if the popup is shown and you can see the all content of it including the Button
5. Check if the small triangle points nearly at the position where the location was clicked
6. Check if the Button text now explains more understandable what happens when the Button is clicked.

fix(refs: DPLAN-16083): change location popup style for mobile

---

client/js/components/faq/DpFaqItem.vue

[DPLAN-15946](https://demoseurope.youtrack.cloud/issue/DPLAN-15946) Fehlermeldung beim Ändern des Status in "Häufige Fragen"
**Description:** This PR fixes an issue where saving the available groups caused an error.
-  send/save only relevant data: 'id', 'type' and 'attributes' instead of the entire FAQ object

Fix(DPLAN-15946): error while saving the available groups on the FAQ page

---

demosplan/DemosPlanCoreBundle/Logic/OzgKeycloakUserDataMapper.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OzgKeycloakAuthenticator.php

- Fixes issue where newly authorized users needed to click login twice
- Moves user creation logic out of deferred UserBadge closure to execute synchronously
- Removes intermediate flush() calls to ensure atomic user+role assignment
The problem was a race condition in the authentication flow where:
1. User creation happened inside a deferred UserBadge closure
2. Authentication validation occurred before user+role assignment was complete
3. First login failed because user existed without roles
4. Second login succeeded because roles were assigned by then
1. **OzgKeycloakAuthenticator**: Move user creation logic outside UserBadge closure for synchronous execution
2. **OzgKeycloakUserDataMapper**: Remove intermediate flush() calls to ensure atomic persistence
- **YouTrack**: DPLAN-1880

fix(DPLAN-1880): Fix double-login requirement for newly authorized users

---

client/js/lib/core/libs/touchFriendlyUserbox.js

[DPLAN-16094](https://demoseurope.youtrack.cloud/issue/DPLAN-16094/Mobilansicht-Stellungnahmen-zum-Verfahren-Link-funktioniert-nicht)
This PR removes the click fallback that was causing the flyout to close immediately. Most of the ticket was already addressed in the linked PR.
1. log in as private person, click on a procedure and enter mobile view.
2. click on 'stellungnahmen zum verfahren' and see if the flyout opens.
3. click outside the flyout and see if it closes.
#4937

fix (refs: DPLAN-16094): remove click listener

---

demosplan/DemosPlanCoreBundle/Entity/Procedure/Procedure.php
demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedurePhase.php
demosplan/DemosPlanCoreBundle/Repository/ProcedureRepository.php

Description: 
initialize $key property before accessing
- Add default value 'configuration' to $key property to prevent uninitialized access
- Remove default parameters from constructor to make key and step required
- Resolves "Typed property must not be accessed before initialization" error

Fix DPLAN-16144  initialize $key property before accessing

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_map.scss
demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_tabs.scss

[DPLAN-16082](https://demoseurope.youtrack.cloud/issue/DPLAN-16082/Keine-Padding-auf-rechter-linker-Seite-beim-Beteiligung-in-Offentlichkeitsansicht)
This PR changes some SCSS to add a bit of padding and an area for scrolling to the mobile view of the public detail section.
Select a procedure and check out the mobile view, either logged out or as a private person.

fix (refs: DPLAN-16082): add padding to mobile view

---

package.json
yarn.lock

Bumps demosplan-ui to the newest 0.5.4 version.
- DpFlyout: add position prop to control flyout positioning
- DpResettableInput: fix slot detection logic for fragments and text nodes
- DpAccordion: Remove default submit behaviour and adjust styles
- DpEditableList: ensure Vue 3 v-model works correctly under compat mode
- BREAKING: Remove DpFormRow
- https://github.com/demos-europe/demosplan-core/pull/4963
- https://github.com/demos-europe/demosplan-core/pull/4968
- https://github.com/demos-europe/demosplan-ui/pull/1325
- https://github.com/demos-europe/demosplan-core/pull/4977

chore(refs DPLAN-16160): bump demosplan UI from v 0.5.3 to v0.5.4

---

demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedurePhase.php

Ticket
Description:  
PHP 7.4 introduced typed properties, and with them came the requirement that typed properties must be initialized before being accessed.
Initialize DateTime properties with lazy initialization in getters using isset() checks

Fix DPLAN-16144 Fix PHP 7.4+ typed property initialization issues

---

demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedurePhase.php
tests/backend/core/Document/Functional/ElementsServiceTest.php

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-16144/Nicht-moglich-um-Verfahren-zu-hinzufugen
Description: 
Problem: Direct property access ($sourcePhase->startDate) on Doctrine-hydrated objects that bypass the constructor, leaving typed properties uninitialized.
Solution: Changed to use getters ($sourcePhase->getStartDate()) which have the isset() safety checks to initialize properties if needed.
a little bit more explanation why this has to be fixed : 
Why this matters with PHP typed properties:
1. With default values: PHP considers the property "initialized" because it has a default value assigned at declaration time. Direct access works fine.
2. Without default values: PHP considers these "uninitialized" until explicitly assigned. Accessing them before assignment throws the …

Fix DPLAN-16144 Change direct property access to use getters in copyValuesFromPhase

---

client/js/components/procedure/admin/InstitutionTagManagement/ClientSideTagFilter.vue
client/js/components/procedure/admin/InstitutionTagManagement/InstitutionList.vue
client/js/components/procedure/admin/InstitutionTagManagement/OrganisationTable.vue

[DPLAN-15898](https://demoseurope.youtrack.cloud/issue/DPLAN-15898/Das-Institutionen-verwalten-zurucksetzen-Button-setzt-die-Suche-nicht-zuruck-und-der-Button-bleibt-ausgegraut)
The button "Zurücksetzten" in the should set back not only the filters but also the applied search. This PR activates the button after a search was applied and sets it back when the button is clicked.
1. Login to diplanbau as a user with fp-admin role and choose a procedure with added institutions or add some by your own
2. Switch to "Institutionen verwalten" and type something into the searchfield
3. The search text should be deletable through the x button at the searchfield and the "Zurücksetzen" button is inactive
4. Apply a search -> The search results are visible in the Table and the "Zurücksetzen" button is …

fix(refs: DPLAN-15898): add search reset on organisation and institution list

---

CHANGELOG.md
client/js/components/procedure/basicSettings/AutoSwitchProcedurePhaseForm.vue
demosplan/DemosPlanCoreBundle/DoctrineMigrations/2025/08/Version20250803194156.php
demosplan/DemosPlanCoreBundle/DoctrineMigrations/2025/08/Version20250805123542.php
demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedurePhase.php
demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureSettings.php
demosplan/DemosPlanCoreBundle/Logic/Procedure/ServiceStorage.php
demosplan/DemosPlanCoreBundle/Repository/ProcedureRepository.php
translations/messages+intl-icu.de.yml

DPLAN-16177
- Fix time-based procedure phase switching functionality
- Resolve issues with automated phase transitions based on scheduled dates
- Changed the interface from time picker to text field to avoid complex bugs and gain flexibility
- Updated procedure phase switching logic
- Enhanced date validation and scheduling
- Improved error handling for phase transitions
DPLAN-16177

fix: Time based procedure phase switch (refs DPLAN-16177)

---

demosplan/DemosPlanCoreBundle/Repository/UserRepository.php

- Remove redundant null check in update method where NoResultException is already handled
- Add null check in wipeUserData method to prevent operations on non-existent users
- Update type annotation to reflect nullable User return type
- **UserRepository::update()**: Removed redundant try-catch for NoResultException as it's handled by generateObjectValues
- **UserRepository::wipeUserData()**: Added null check before wiping user data to prevent operations on non-existent users
- Updated type annotation for better code clarity

Fix null safety issues in UserRepository

---

demosplan/DemosPlanCoreBundle/EventListener/ExpirationTimestampRequestListener.php
demosplan/DemosPlanCoreBundle/EventSubscriber/LogoutSubscriber.php
demosplan/DemosPlanCoreBundle/Logic/User/OzgKeycloakLogoutManager.php

https://demoseurope.youtrack.cloud/issue/DPLAN-14969/ADO-Issue-23560-Rechtzeitige-Ankundigung-Ausloggen-damit-gespeichert-werden-kann
Validate that when prod env and not keycloak set up, then skip the lifetimestamp expiration token

F dplan-14969 validate keycloak in env

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_procedurelist.scss

[DPLAN-16180](https://demoseurope.youtrack.cloud/issue/DPLAN-16180)
This PR increases the specificity of the CSS selectors for the checkmark icon, so that it is displayed correctly again after the Tailwind 4 update.
1. Login as private person and go to the homepage.
2. Look at a procedure in the procedure list - there should be no checkmark icon.
3. Hover over the left side of a procedure and check the checkbox.
4. The procedure should now appear light grey and have a checkmark icon.

fix(refs:DPLAN-16180): increase icon css specificity

---

client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue

[DPLAN-16010](https://demoseurope.youtrack.cloud/issue/DPLAN-16010/Fehlermeldung-in-Konsole-wenn-man-auf-das-MID-in-Erfolgspopup-nach-dem-Erstellen-von-STN-klickt-Uncaught-in-promise-TypeError)
This PR adds a check for the API response in the mounted hook to make sure data is there before using it.
Create a new STN --> click on MID in the success popup --> check the console for 'Uncaught (in promise) TypeError: can't access property "attributes", response is undefined error.'

fix(refs DPLAN-16010): Add check for data before using it

---

client/js/components/user/DpOrganisationList/DpOrganisationList.vue

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-16340/Organisationliste-ladt-nicht
Description: 
orgaFields is defined as an object where each property is already a joined string (e.g., Customer: orgaFieldsArrays.Customer.join()). But a join() is called again on orgaFields.Customer, which it's already a string, not an array. Same with the other calls

f DPLAN-16340 remove join on strings

---

client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
client/js/components/procedure/admin/AdministrationCustomFieldsList.vue

Either return `undefined` or, if no value is returned anyway, use `.forEach()` instead.
This fixes 2 eslint errors.

style: always return value from Array.map()

---

client/js/components/procedure/admin/InstitutionTagManagement/TagListItem.vue

[DPLAN-16246](https://demoseurope.youtrack.cloud/issue/DPLAN-16246/Schlagworte-verwalten-Icons-sind-nach-links-verrutscht)
The tailwind class for the grid columns failed because the syntax was not longer correct in tailwind 4. This PR changes the class to use the correct syntax, as seen [here](https://tailwindcss.com/docs/grid-template-columns#using-a-custom-value) in the tailwind docs.
log in as Mandantenadmin > go to institution tags page > edit tags page > check if icons are on the same line as headings

fix(refs:DPLAN-16246): fix TW class syntax

---

client/js/components/map/admin/AdminLayerList.vue
client/js/components/procedure/admin/AdministrationMemberList.vue
client/js/components/procedure/admin/DpAddOrganisationList.vue

[DPLAN-16193](https://demoseurope.youtrack.cloud/issue/DPLAN-16193/Falsches-Buttonstil-Institution-hinzufugen-und-bei-Kartenebenen)
Some buttons in the "Kartenebenen definieren" dialog and the "Institution hinzufügen" dialog has a wrong style. This PR changes the style of the buttons to the design as it is in our figma design template.
1. Login as admin and change to open a procedure
2. Change to "Kartenebenen definieren" and "Institution hinzufügen"
3. Check in each dialog, if the buttons at the bottom of the dialog have rounded borders and a pill like style

fix(refs DPLAN-16193): change buttons in layer and organisation lists

---

client/js/components/map/admin/LayerSettings.vue

This PR fixes linting errors connected to the changes made in the PR listed below.
1 warning remains - using a self-closing button-tag is bad practice and can lead to rendering problems in some browsers.
[DPLAN-15846](https://demoseurope.youtrack.cloud/issue/DPLAN-15846/ADO-30421-Veraltete-Layer-automatisch-erkennen-und-Nutzer-informieren): https://github.com/demos-europe/demosplan-core/pull/5068

chore(refs dplan-15846): Fix linting errors in LayerSettings

---

client/js/components/procedure/admin/DpAddOrganisationList.vue

[DPLAN-16415](https://demoseurope.youtrack.cloud/issue/DPLAN-16415)
In "Institution hinzufügen" dialog, the add and the cancel button where not in one line and had different size. This PR changes the cancel button in position and size, by making a dp-button of it.
1. Login as admin and open a procedure.
2. Go to "Institutionen verwalten" and from there to "Institution hinzufügen".
3. Check if the button at the bottom are in the same line and have nearly the same size

fix(refs DPLAN-16415): change cancel button in add organisation dialog

---

client/js/components/procedure/admin/NewBlueprintForm.vue

[DPLAN-16206](https://demoseurope.youtrack.cloud/issue/DPLAN-16206/Blaupause-Name-verschwindet-sobald-man-Blaupause-auswahlt-oder-Verfahrenstrager-E-Mail-eingibt)
When adding a new blueprint, name input was cleared after choosing a template blueprint or typing in an e-mail address. This PR adds a v-model to the name input, that prevents the field from being cleared. 
1. Login as admin and open the Blueprint list
2. Click on the add blueprint button
3. Type in a name in the input field and check if the name is still there, when a template blueprint is chosen or an e-mail address was written into the e-mail input field

fix(refs DPLAN-16206): put v-model to name input

---

client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue

[DPLAN-16226](https://demoseurope.youtrack.cloud/issue/DPLAN-16226/E-Mail-Verfahrenstrager-wird-geloscht-wenn-ich-Verfahrenstyp-oder-Blaupause-wahle)
This PR adds v-model to the email address DpInput in DpNewProcedure, so that the email input doesn't get reset on changing other values in the form.
create a new procedure --> type in an email address:
1. change 'Verfahrenstyp' --> the typed in email should persist
2. change 'Blaupause --> if the saved Blaupause email address is not an empty string, the typed in address will be overwritten by the one from the Blaupause

fix(refs dplan-16226): Add two-way data binding to email input in DpNewProcedure

---

client/js/components/statement/publicStatementModal/StatementModal.vue

[DPLAN-16022](https://demoseurope.youtrack.cloud/issue/DPLAN-16022/Gesetzter-Haken-in-STN-Entwurf-wird-nicht-gespeichert)
For the value of r_makePublic checkbox, the frontend expects a string value, but when loading previously saved statement drafts, was receiving a boolean value. This PR converts backend boolean to expected string format during draft loading.
1. log in as a private person 
2. create and save a statement draft (check this checkbox: 'Ich möchte, dass meine Stellungnahme bei DiPlanBeteiligung online für andere Beteiligte einsehbar ist, damit diese meine Stellungnahme mitzeichnen können. Mein Name wird dabei nicht genannt.') 
3. go to saved drafts and check if the checkbox setting is saved in the draft

fix(refs dplan-16022): Use string values for checkbox in StatementModal

---

client/js/components/procedure/admin/AdministrationMemberList.vue
client/js/components/procedure/admin/InstitutionTagManagement/OrganisationTable.vue

[DPLAN-16190](https://demoseurope.youtrack.cloud/issue/DPLAN-16190/Wenn-man-eine-Institution-loscht-bekommt-man-das-Erfolgspopup-zweimal)
When deleting institutions from the institution list in the "Institutionen verwalten" dialog, the success message appears two times instead of one. Solving this behavior leads to an error message, when deleting another institution from the list. This PR solves both behaviors, by completely reset the selection after deleting an element.  
1. Login as admin and choose a procedure
2. Go to "Institutionen verwalten" dialog and add some institutions
3. Select some of the institutions and click on the delete button
4. Check if there is only one success message
5. Try the same with the select all checkbox and delete all visible and checked entries
6. Check if …

fix(refs DPLAN-16190): add reset of selection after deleting elements

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_email.html.twig

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-16398/BOB-SH-Bauleitplanung-Prod-Stage-Mit-jedem-Speichern-einer-Einladungsmail-wird-die-TOB-Liste-neu-angehangt-T36935
Description:
improve email footer replacement with smart spacing to avoid having duplicated footer in emails.
- Remove existing footer (marked by '---------') before adding new content
- Skip br/br spacing when replacing existing footer to prevent extra whitespace
- Add br/br spacing only when appending to email text without existing footer
- Ensures clean email formatting for TÖB invitation text updates

f DPLAN-16398 improve email footer replacement

---

client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
yarn.lock

[DPLAN-16049](https://demoseurope.youtrack.cloud/issue/DPLAN-16049/Overflow-Fehler-Seitenleisten-Element-verlasst-Containergrenzen)
When answering a statement and switching to edit mode, the last point of the metadata menu overflows the metadata box, when scrolling to the bottom. This depends on how much data follows after this box or how large the screen is. This PR extends the height of the menu container, to prevent items from the menu from overflowing the border of the metadata box. 
1. Login as admin and open a procedure with statements
2. Go to segments and edit a segment
3. Switch to edit mode and check if the menu of the metadata box does not overflow the bottom border, even if there is a lot of data following or switching to the mobile view.

fix(refs DPLAN-16049): change height of metadata menu container

---

client/js/components/document/ElementsList.vue

[DPLAN-16342](https://demoseurope.youtrack.cloud/issue/DPLAN-16342) Die Planungsdokumenten bleiben beim Laden in Öffentlichkeitsansicht
**Description:**  Tis PR fixes an issue with the displaying the documents tree list:
- the `listToTree` function was trying to modify the Vuex object directly, which caused an error
- create a copy of the object first so it can be modified safely

fix(DPLN-16342): issue by displaying documents tree list

---

client/js/components/statement/assessmentTable/DpTable.vue

[DPLAN-16414](https://demoseurope.youtrack.cloud/issue/DPLAN-16414/Undefined-fur-eine-datacy-Hook-index)
`index` had been accidentally removed, so the data-cy attribute always ended in `undefined`. This PR restores the `index`.

fix(refs DPLAN-16414): provide index again

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_proceduresearch.scss

After the tailwind 4 migration, the specificity order of styles has changed, and `c-proceduresearch__heading` was also overriding the padding for `o-page__padded`, which it was not intended to do. I restored the previous styling so the heading on the index page is aligned with the content again.

fix: reset padding only for layout__item

---

templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement_detail_statement_data.html.twig

[DPLAN-16535](https://demoseurope.youtrack.cloud/issue/DPLAN-16535) Falsche Verfahrensschritte in STN-Detailansicht nach dem ich eine Institution STN eingereicht habe
**Description:** This PR fixes an issue with displaying an incorrect phase.
The permission check (`field_show_internal_procedure_phases_in_dropdown`) was stopping the display of the internal phase instead of the external one when a statement was submitted by an institution. I could not find any usage of this permission, it was removed in this [commit](https://github.com/demos-europe/demosplan-core/commit/3d8804e3649c42dd6a9314f7fa4222f8d19a7577). 
As I see it, the permission check for creating a new STN [was removed there as well](https://github.com/demos-europe/demosplan-core/commit/3d8804e3649c42dd6a9314f7fa4222f8d19a7577#d …

fix(DPLAN-12528): incorrect phase

---

client/js/store/statement/Fragment.js

[DPLAN-16347](https://demoseurope.youtrack.cloud/issue/DPLAN-16347) Wir zeigen keine Datensätze obwohl eine STN schon diese hat
**Description:** This PR fixes an issue where fragments were not displayed.
The [first PR](https://github.com/demos-europe/demosplan-core/pull/5167) has to be changed!
- destructing `{ data: responseData }` --> it creates a new variable called 'responseData' from the data property of the response, but somehow it does not work on the server (maybe some differences in the configuration), so refactor it and rename the variable to test it on the server

fix(DPLAN-16347): unable to display fragments - v2

---

client/js/components/statement/publicStatementModal/StatementModal.vue
config/services.yml
demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureHandler.php
tests/backend/core/Procedure/Functional/ProcedureHandlerTest.php

After merge of several release branches sonarcloud complains
- Fix critical cognitive complexity issue in DemosPlanProcedureController by refactoring boilerplateListAction method
- Remove duplicate property definitions in StatementModal.vue
- Fix useless variable assignments in ProcedureHandler.php
- SonarCloud quality gate should pass
- Existing functionality should remain unchanged
- No breaking changes to public APIs
Resolves 5 SonarCloud violations that were causing the quality gate to fail.

Fix SonarCloud quality gate violations

---

templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/single_document_admin_edit.html.twig

[DPLAN-16320](https://demoseurope.youtrack.cloud/issue/DPLAN-16320/Beim-bearbeiten-von-Planungsdokument-nach-dem-hochladen-wird-das-hinzugefugte-Name-nicht-angezeigt-oder-wir-haben-ein-falsches)
- for v-model to work in Vue 3, we need to use modelValue
- DpInput has been updated to not support value anymore
Go to 'Planungsdokumente und Planzeichnung' --> upload new document --> click on edit in the list --> check if the 'Angezeigter Name' has the title rendered

fix(refs dplan-16320): Use modelValue for DpInput in single-document_admin_edit

---

client/js/components/statement/publicStatementModal/StatementModal.vue
client/js/components/statement/publicStatementModal/StatementModalRecheck.vue

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-16042/Ado-Issue-32485-Ruckmeldung-zu-Stellungnahme-steuerbar
Description: 
- Add publicParticipationFeedbackEnabled prop to StatementModalRecheck component
- Update v-if condition to check both statementFeedbackDefinitions.length > 0 AND publicParticipationFeedbackEnabled
- Pass publicParticipationFeedbackEnabled prop from StatementModal to StatementModalRecheck component
- Ensures feedback block is only displayed when procedure setting is enabled
The feedback section in the statement recheck modal now properly respects the proceduresettings.publicParticipationFeedbackEnabled setting, preventing the feedback UI from appearing when the feature is disabled at the procedure level.

f DPLAN-16042 : Add proceduresettings.publicParticipationFeedbackEnabled check to feedback block

---

client/css/tailwind.css

[DPLAN-16591](https://demoseurope.youtrack.cloud/issue/DPLAN-16591/Design-Cookiebanner-kaputt)
The styles for the cookie banner were not applied, and importing them fixed this.
There should probably be a (better) way of fixing this in dp-consent, but I couldn't find it in the given time.
- in the project's parameters.yml, set `piwik_enable` to `true`
- this should be enough to display the cookie banner, otherwise go to (chrome) dev tools -> Application -> Cookies -> delete dp-consent cookie or clear all cookies
- the styles for the cookie banner should be applied again (most notably, the buttons should have an outline and colors again)

fix(refs DPLAN-16591): import cookie banner styles

---

package.json
yarn.lock

This PR adds the same prosemirror package resolutions as in demosplan-ui to avoid errors with segment creation. Without the resolutions, different conflicting versions of prosemirror packages are installed.

fix: add prosemirror resolutions

---

demosplan/DemosPlanCoreBundle/Logic/Map/MapExtentValidator.php
demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureMapSettingResourceType.php
tests/backend/core/Map/Unit/MapExtentValidatorTest.php
translations/messages+intl-icu.de.yml

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-16735/Startkartenausschnitt-boundingBox-muss-vollstandig-innerhalb-der-Kartenbegrenzung-mapExtent-liegen
Description: 
Ensures that the initial map viewport (Startkartenausschnitt/boundingBox) is fully contained within the map boundaries (Kartenbegrenzung/mapExtent). The validation is triggered when either value is updated via the ProcedureMapSetting API.
- Add MapExtentValidator service to validate coordinate boundaries
- Integrate validation into ProcedureMapSettingResourceType
- Throw InvalidArgumentException with German error message when validation fails
- Support both flat array and structured coordinate formats

fix DPLAN-16735 Add validation for map extent boundaries
