demos-europe/demosplan-core

.github/dependabot.yml

The last version which is supported for vue2 is portal-vue^2.1.7 (which is the one we are using) hence this dependency should be added to dependabot.yml unless we migrate to vue3 in the near future.

add portal-vue dependency to dependabot.yml

---

.github/workflows/reviewdog.yml

Reviewdog should be configured to run with current php8.1 to be compatible with composer.lock

feat: use php 8.1 for reviewdog

---

.github/dependabot.yml

Unfortunately, we're not quite ready yet to make the jump to Symfony 6. To keep Dependabot for PHP usable, we should remove these from it's tracking list in order to not fill up our limit of open PRs.
Check the added ignore rule against the documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore

ci: Disallow updates to Symfony 6

---

demosplan/DemosPlanCoreBundle/Logic/FileService.php

The current requestStack may not always have files attached, like in tests. Therefore, we need to be a bit more cautious about null pointer exceptions here. The php 8 feature is used by purpose, as we are able to use php 8.1 in following releases.
run FileService test

feat: be more cautious about the existence of files in request

---

client/js/components/procedure/admin/NewBlueprintForm.vue
client/js/components/procedure/basicSettings/DpEmailList.vue

https://yaits.demos-deutschland.de/T30796
- When not persisting the form but adding extra email addresses: these were removed from the form if in another DpSelect of that form was used to set a new value there.
- Somehow the watcher caused this problem. This led to a confusing data architecture because the initEmails prop and the emails data prop were updated at the same time when in fact initEmails should only contain an array of already persisted emails. This was fixed by removing the watcher, set the default emails data prop to an empty array and fill the data prop with the read-only initEmails prop on mounting the component.
However, it remains unclear why the initEmails were changed when setting a new value in a unrelated DpSelect. This PR fixes the Problem for now but the underlying …

fix(refs T30796): Prevent newly added e-Mails in Email-List to get overwritten

---

client/setup/webpack/moduleRules.js
package.json
yarn.lock

**Ticket:** https://yaits.demos-deutschland.de/T30430
the v0.0.6 release of demosplan-ui did not contain the actual code of that release, as we confused the "prepublish" with the appropriate "prepare" npm lifecycle hook. Until the next release fixes that, this PR requires an interim branch in which demosplan-ui moves webpack, webpack-cli and style-dictionary within its dependencies (leading to a temporarily bloated "yarn.lock" but things will settle as the 0.0.7 npm version of demosplan-ui comes along). 
See https://docs.npmjs.com/cli/v9/using-npm/scripts
also, in a8080d6c27f the two @demos-europe modules were mistakenly designated to be included with babel-loader. This makes no sense as they are already bundled as umd.
Remove node_nodules, clear yarn cache, install, and build. Open any …

Temporarily use GitHub version of demosplan-ui v0.0.6

---

client/js/components/procedure/AdministrationImport/ExcelImport/ExcelImport.vue
client/js/components/procedure/DpSimplifiedNewStatementForm.vue
client/js/components/procedure/SegmentsBulkEdit/SegmentsBulkEdit.vue
client/js/components/statement/publicStatementModal/StatementModal.vue
client/js/components/statement/publicStatementModal/formGroups/FormGroupCitizenOrInstitution.vue
client/js/components/statement/publicStatementModal/formGroups/FormGroupCountyReference.vue
client/js/components/statement/publicStatementModal/formGroups/FormGroupEvaluationMailViaSnailMailOrEmail.vue
client/js/components/statement/publicStatementModal/formGroups/FormGroupMapReference.vue
client/js/components/statement/voter/StatementVoter.vue
templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/single_document_admin_edit.html.twig
templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/single_document_admin_new.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T29004
Adjust `DpRadio` usages after refactoring its label prop in https://github.com/demos-europe/demosplan-ui/pull/48

refactor(refs T29004): pass label props as object

---

demosplan/DemosPlanCoreBundle/Resources/config/config_dev_container.yml

Since the clam setup in the current dev environment is rather brittle disabling the virus scanning on uploads, while technically a security risk, makes it easier to debug and use the remainder of the file upload processes. This should only be a temporary fix and developers should be aware that they can cause harm on their systems if they use testfiles for uploading which contain malware of any kind.
Uploads on the local dev environment work as expected.

build: Disable virus scan in dev environment

---

demosplan/DemosPlanCoreBundle/Command/Db/MigrateCommand.php

Project migrations need to be performed in two parts. The project migrations up to Version 20220914133419 contains all migrations that needs to be executed before the core migration rollup is performed.
you might perform `bin/<project> dplan:migrate` on an old database that has outstanding migrations before core migration rollup

feat: ensure that project rollup migrations are performed

---

demosplan/DemosPlanCoreBundle/Resources/config/packages/test/fos_elastica.yaml

Our configuration to disable elasticsearch in tests needs to be updated to be compatible to ES7
Elasticsearch 7 does not have any types any more so these ones need to be skipped in the configuration file
reviewdog action should not throw an error regarding elasticsearch configuration /update/ Reviewdog won't run as no php files are touched /update/

feat: update test configuration to Elasticsearch 7 syntax

---

translations/messages+intl-icu.de.yml

**Ticket:** https://yaits.demos-deutschland.de/T30833
Translation for confirmation after adding tags via cvs was missing. 
Go to Verfahren -> Schlagworte and upload an cvs file. You should see the confirmation text on the notification instead of only the key.

bug(refs T30833): Add translation for key

---

templates/bundles/DemosPlanUserBundle/DemosPlanUser/unregistered_publicagency_list.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T29194
Some time ago all references for publicagency were changed to invitable_institution. This one was forgotten.
Go to Verfahren -> unregistrierte Institutionen verwalten and look if the translation key was translated correctly.

bug(refs T29194): Change translation key

---

package.json
yarn.lock

Now that we have it on npm, we can use it! This might also fix some "strange" behavior in dev environments as demosplan-ui is not build when installing anymore.
`yarn install` and stuff should work as expected.

Use demosplan-ui 0.0.7

---

client/setup/config.js

Some CSS classes required for DpStickyElement were purged because the lib that sets them is located inside demosplan-utils. Until we move the latter into demosplan-ui we have to tell purgeCss to also look for CSS classes in demosplan-utils.
**How to test it**
After building, when scrolling down the assessment table, the side menu should stay fixed to the top of the page (instead of having a random offset top).

Do not purge demosplan-utils generated css selectors

---

demosplan/DemosPlanCoreBundle/Controller/Segment/DraftsInfoController.php

**Ticket:** https://yaits.demos-deutschland.de/T30824
As it was previously uncaught which lead to no readable message being added to the message bag.
This is based on an incident, but I decided to fix it on `main` as that project is going to be updated with `main` very soon anyaway.
I think a code review should suffice here.

fix(refs T30824): catches LockedByAssignmentException

---

demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadProcedureData.php

Prod fixtures are used to create databases from scratch. ExportFieldsConfiguration where introduced and never reflected in prod fixtures.
create a new database and populate it with prod fixtures

fix: ExportFieldsConfiguration needs to be set on new procedures

---

.github/dependabot.yml

The update to 3.x requires us to use Symfony 6, which we will not in the next couple of weeks. So we're deactivating the update for the moment.
- Dependabot already alerted us to the update #{511}

feat: halts jsrouting on 2.8.x

---

demosplan/DemosPlanCoreBundle/Controller/AssessmentTable/DemosPlanAssessmentTableController.php
demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
demosplan/DemosPlanCoreBundle/Services/HTMLFragmentSlicer.php
demosplan/DemosPlanCoreBundle/Twig/Extension/HeightLimitExtension.php
templates/bundles/DemosPlanStatementBundle/DemosPlanAssessment/view_statement.html.twig
tests/backend/core/Core/Unit/Utilities/Twig/HeightLimitExtensionTest.php

**Ticket:** https://yaits.demos-deutschland.de/T30834
**Ticket:** https://yaits.demos-deutschland.de/T30853
Description: it was not possible to add (submit) a new statement with a long text. The slicer caching has to be fixed.
Note : this fix this problem in both projects bobsh and planfest.
bobsh : 
-  Procedure
- AT 
- New statement 
- fill out and save
planfestsh : 
- Login 
- Procedure 
- Have your say ('Reden Sie mit')
- Save statement as draft
- Go to draft folder
- Release statement 
- Institution releases 
- Submit statement

F_(ref:30834) fix slicer caching

---

client/js/lib/procedure/CreateProcedure.js

**Ticket:** https://yaits.demos-deutschland.de/T30455
https://yaits.demos-deutschland.de/T30939
In BobHH Boundingbox-Informations for a new Procedure get fetched by an API-Call. If the response fails for whatever reason,it still should be possible to create the Procedure. (since to bounds can be set manually later on)
Try to create a procedure in BobHH with a failing API-Request for the Boundingbox (I Know - hard to test)
This is just a copy/paste-PR from the old Repos
https://github.com/demos-europe/demosplan/pull/8542
https://github.com/demos-europe/demosplan/pull/8543

fix(refs T30455, T30939): Handle unset bounds

---

templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/public_detail.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T30875#725835
Description: 
- the description of the phases with his belonging contextHelp tooltip are showing different descriptions due to the user role
- when no user is logged in or he is logged as citizen he only see the public phase and public contextHelp tooltip
- when user is logged as institution he can see two different phase names and contextHelp tooltip content, the public and the intern phase naming and contextHelp tooltip content
- the support role is able to add new contextHelp keys with other content
- important: if there is a key for contextHelp tooltip in database and the support does not add the same key in the application, he wont see any contextHelp tooltip.
- Different cases:
- 1.) Go to the Startpage, dont login and …

Fix(refs:T30875): Contexthelp is showing not the expected key description

---

demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OsiAuthenticator.php

OSI Authenticators need to implement AuthenticationEntryPointInterface, as otherwise the call to any page throws an error. Not sure, which route might be the best to redirect to. Home at least seems to work, otherwise `gateway_url`  might be a valid candidate
Code review.

Fix osi authenticator

---

client/js/components/user/CustomerSettings/CustomerSettings.vue

One big issue was, that the Branding got requested only beccause
the permission "field_sign_language_overview_video_edit" was enabled
during investigationg this. I refactored the code a little, to hopefully make it better readable and to not send empty fields
**Ticket:** https://yaits.demos-deutschland.de/T30808
in bob-sh as support, try to open the "plattformeinstellungen" 
You may doublecheck if the page still works in other projects.
While this fixes, that the page can be visited again, it also reveals a bunch of new errors thrown from demosplan-ui. They have to be fixed in a separate PR.
Picked from https://github.com/demos-europe/demosplan-core/pull/592

fix(refs T30808): Check Permissions for Branding propperly

---

client/js/components/map/map/DpOlMap.vue

**Ticket:** https://yaits.demos-deutschland.de/T31010
As "support" Goto
-> /einstellungen/plattform (Plattform-Einstellungen) 
The Map should load without errors
(there may be other Errors in the Console, but they are not related to this Bug)
There are circumstances, where we don't get a maxExtend. Instead of an empty Array we receive `undefined` which was not expected.

fix(refs T31010): Catch undefined maxExtend

---

client/js/components/document/ElementsAdminList.vue
client/js/components/statement/publicStatementLists/DpPublicStatement.vue
demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
demosplan/DemosPlanCoreBundle/Resources/config/permissions.yml
templates/bundles/DemosPlanStatementBundle/DemosPlanStatement/includes/listentry_content.html.twig
templates/bundles/DemosPlanStatementBundle/DemosPlanStatement/new_public_participation_statement_confirm_entry.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T30938
There aren't paragraphs and location in statements in every project, so we need a permission for it.
Login as citizen, go to a procedure and write a statement. There should be no option for paragraphs or location. 
https://github.com/demos-europe/demosplan-project-teilhabe/pull/10
https://github.com/demos-europe/demosplan-project-robobsh/pull/15
https://github.com/demos-europe/demosplan-project-regio/pull/18
https://github.com/demos-europe/demosplan-project-planfestsh/pull/15
https://github.com/demos-europe/demosplan-project-diplanbau/pull/53
https://github.com/demos-europe/demosplan-project-bobsh/pull/16
https://github.com/demos-europe/demosplan-project-bobhh/pull/21
https://github.com/demos-europe/demosplan-project-bimschgsh/pull/19 …

bug(refs T30938): add permission for paragraphs in statements

---

client/js/components/procedure/admin/AdministrationProceduresList.vue
demosplan/DemosPlanCoreBundle/ResourceTypes/AdminProcedureResourceType.php
demosplan/DemosPlanCoreBundle/Resources/client/scss/utility/_width.scss
demosplan/DemosPlanProcedureBundle/Logic/ProcedureService.php
demosplan/DemosPlanStatementBundle/Repository/StatementRepository.php
translations/messages+intl-icu.de.yml

**Ticket:** https://yaits.demos-deutschland.de/T30865
Count normal statements of procedure to allow showing a count of normal statements in procedure-list, additionally to count of original-statements.
In the list of the procedures, should be two counts of statements now, including a tooltip, which discripe

fix (refs T30865): Count normal statements of procedure

---

demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php

Ticket: https://yaits.demos-deutschland.de/T30990
In most cases we store texts with already escaped special chars in the database to avoid any later problems. But in some rare cases and for reasons I don't, some special chars make their way into the database. Without the here added line of code (which is present in most if not all other docx exports) those will break the docx generation as that is based on a xml file.
How to review/test
Exporting all statements as a zip with individual docx files should now also produce working docx files for statements with xml breaking special chars (for example '&') in their texts.

fix (refs T30990): Escape any special chars for output

---

demosplan/DemosPlanCoreBundle/Controller/Document/DemosPlanDocumentController.php

Ticket:
https://yaits.demos-deutschland.de/T25542
It is possible to create statements via route: .../public/paragraph/...
For the statement modal the key ```planningDocumentsHasNegativeStatement```
is needed in order to show the radio button 'Fehlanzeige'
This key was only present via the route: .../public/detail/... and the logic to set this key was simply copied over to be used
for the .../public/paragraph/... route as well.
See related ticket

feature (refs T25542): include negativeReport on publicParagraph Route

---

demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadProcedureData.php
demosplan/DemosPlanCoreBundle/Entity/Document/Elements.php

Ticket:
https://yaits.demos-deutschland.de/T30671
Description:
regarding MainStory (refs T30524): https://yaits.demos-deutschland.de/T30524
Adds migration to alter the procedure master-templates elements (Planungskategorien) to match the ones received via a cockpit-msg.
regarding (refs TT29526): https://yaits.demos-deutschland.de/T29526
Adjust the map-section shown for a procedure created via cockpit-msg by mapping the given coords to the coords used for our EPSG3857 projection.
regarding (refs TT29527): https://yaits.demos-deutschland.de/T29527
Two tests indicated that the service-type has to be provided as a lower-key string. This should not be necessary but since I am not 100% sure on this one - this got adjusted on BE-side in XtaGisLayerManager.php -> setMessageGisValues()
The changes …

feature (refs T30671): cockpit related tasks - adjust planningDocumentCategories - address bugs

---

client/js/components/document/ElementsAdminList.vue
client/js/components/document/ElementsList.vue

**Ticket:** https://yaits.demos-deutschland.de/T27479
The given objects in the change event for node selection have changed (in DpTreeListNode), so they also need to be changed in the methods listening to that event. 
Also some refactoring.
Go to Verfahren -> Dokumente and select some documents. There should be a bulk edit header appear, where you can delete or publish the documents. 
https://github.com/demos-europe/demosplan-ui/pull/73

bug(refs T27479): Fix bulk edit for documents

---

client/js/components/statement/originalStatementsTable/OriginalStatementsTableItem.vue

**Ticket:** https://yaits.demos-deutschland.de/T31094
While the mutation is called in the event handler, it was nowhere imported. This breaks the whole thing.
In the "Originalstellungnahmen" view, find a statement that is long enough to have the "Mehr anzeigen +" button below the statement text. This button should be functional.

Add missing mutation to original statements view

---

demosplan/DemosPlanCoreBundle/Addon/Registrator.php

The auto-generation info was lacking a newline and thus broke the loading as the format of the saved yaml was not parsable anymore.

fix: Repair addons.yaml format

---

demosplan/DemosPlanCoreBundle/Logic/Consultation/BulkLetterExporter.php

Ticket:
https://yaits.demos-deutschland.de/T25539
Description:
the date gets displayed
as ### if not enough space is provided
to fit in the dateString.
Despite having set a default width - the date
cell needs to be told again about its Width.
Adjusted its alignment to match the others.

feature (refs T25539): display actual date instead of ### in xlsx export

---

demosplan/DemosPlanStatementBundle/Logic/StatementService.php

Ticket:
https://yaits.demos-deutschland.de/T26712
Description:
adjust prev fix to match new es aggregations structure.
( https://github.com/demos-europe/demosplan-core/pull/73 )
probably changed due to an es update. 
I checked bimschgsh, robobsh, blp - the old structure is not in use anymore.

feature (refs T26712): put empty filters back to es aggregations

---

client/js/components/map/map/DpOlMap.vue

**Ticket:** https://yaits.demos-deutschland.de/T31159
Map wasn't loading when the procedure extent was empty, because we didn't check for empty arrays.
Go to Verfahren -> Grundeinstellungen -> Verortung. You should see the map and be able to use the search.

bug(refs T31159): Add check for empty array

---

demosplan/DemosPlanCoreBundle/Logic/Export/DocxExporter.php

**Ticket:** https://yaits.demos-deutschland.de/T31218
The default output encoding of PhpWord is en_US which leads to issues in post processing as they don't have all the beautiful umlauts.
In the future, we might need to make this dependent on the application or project locale, but for now, setting it to german should be enough.
Export to a docx, open in M$ Word, be happy about the correct language setting. Or just move on with life.

feat(refs T31218): Fix docx encoding

---

demosplan/DemosPlanCoreBundle/Controller/Admin/DemosPlanAdminController.php
demosplan/DemosPlanCoreBundle/Controller/Forum/DemosPlanReleaseController.php

Ticket:
https://yaits.demos-deutschland.de/T25516
Description:
add bom at start of csv file in order to make MS-excel display umlauts correctly.
Tried a few things like ```mb_convert_encoding``` within the setEscaper Callback for every word... 
but in the end only this did the trick.
Unfortunately you need to have MS-Excel in order to test this.

feature (refs T25516): add bom at start of csv file in order to make MS-excel display umlauts correctly

---

client/js/components/statement/assessmentTable/Fragment.vue

**Ticket:** [https://yaits.demos-deutschland.de/Txxyyzz -->](https://yaits.demos-deutschland.de/T25930)
**Description:**
- boilerplate is missing in tiptap in consideration
- added link button, too, like in the screenshot in ticket
- go to AT in `Datensätze` and claim a `Datensatz` and go to the section `Begründung`, look to the options if you would like to write or edit something
*important:* 
- the vue error you will see here is because assignee id is null and its fixed in another PR
- so, if you would like to test it, you need an existing claimed `Datensatz`, because the other PR is not merged yet
- https://github.com/demos-europe/demosplan-core/pull/737

Fix(refs:T25930): Add boilerplate and link-button in tiptap for consideration

---

client/js/components/procedure/admin/AdministrationProceduresList.vue
translations/messages+intl-icu.de.yml

**Ticket:** https://yaits.demos-deutschland.de/T31258
Showing both numbers (statement and originalStatement count) by default turned out to be not  understandable. To improve this, original statements are now only shown within a tooltip that is triggered when hovering the numbers. Hiding the original statements by default is the better option as users are mostly interested in this metric.
Checkout, build the frontend, visit admin area with procedures list.

Improve display of statement count

---

client/js/bundles/faq/faqlist.js

**Ticket:** https://yaits.demos-deutschland.de/T31169
As we moved the file from demosplan-ui into core again, the way it has to be imported has changed.

Use correct import syntax

---

templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/shared/v1/assessment_statement_detail_statement_text.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T25931
**Description:** 
- in detail view of a statement, if you would like to edit the statement of a claimed statement, in tiptap the option  `Durchstreichen` is missing and `Als hinzugefügt markieren` and  `Als entfernt markieren` are not needed here
- because there should be the same options like if you claim and edit the statement without using the detailview
- go to AT, claim a statement, go to detailview and edit this statement

fix(refs:T25931): Add strikethrough and remove insertAndDelete

---

client/js/components/map/map/DpOlMap.vue
composer.lock
demosplan/DemosPlanCoreBundle/Logic/ApiRequest/ResourceType/DplanResourceType.php
demosplan/DemosPlanCoreBundle/ResourceTypes/StatementAttachmentResourceType.php
demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php

**Ticket:** https://yaits.demos-deutschland.de/T31096
**Description:**
- in AT in the tab `Originalstellungnahme` you couldnt see the `Originalstellungnahme-Anhang`, only the `weitere Anhänge`
- in FE in store the relationship were in Singular, it should be in Plural because in the rules of JSON.API it requires this way
stops filtering attachments of original statements by skipping
the condition within the ```getAccessCondition``` of
the ```StatementResourceType``` when called from
the ```StatementAttachmentResourceType```.
Activate the needed permission to include
STN-attachments via api.
- now you can see the original attachment in the AT in the first assessment table view, too, before switching the tab to the original statement
**How to review:**
- go to AT, click to …

feature (refs T31096): Show statement attachments in originalSTNView

---

client/js/components/statement/originalStatementsTable/OriginalStatementsTable.vue
client/js/store/statement/Statement.js
templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/dhtml/v1/assessment_table_original_view.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T25837
Pagination got broken over time (the fix borrows heavily from assessment table). Selecting Statements across pages makes no sense within the orig-stn-list as the "bulk edit" pattern of showing the number of selected items above the list is not implemented here. As we currently are fading out these views, there is no need in tweaking them more than needed.
- There should be a working pagination within the orig stn list
- Selection should not persist within the orig stn list

Make pagination + selection work within orig-stn-list

---

client/js/components/user/DpUserFormFields.vue

**Ticket:** https://yaits.demos-deutschland.de/T29716
**Description:** This PR fixes an issue with `orga` relationships after vuex store update. Once the `saveAction` method is triggered in the **DpUserFormFields** component (`module: user, action: update, url: /1.0/user/{id}`), the response we get overrides the store and `orga` lost `allowedRoles` from the relationships. 
An additional check was added for that case. It checks if `orga` has `allowedRoles` property in the relationships, if not it re-fetches organization with the `allowedRoles`
**How to review/test**
login with Demos Support > take user from the list > select a new organisation/role > click on save button

fix(T29716): missing relationships in store after update

---

yarn.lock

**Ticket:** https://yaits.demos-deutschland.de/T31311
As v0.0.11 fixes T31311, demosplan-ui is bumped to that version.
Some dependencies were upped in demosplan-ui as well, thats why there is more than one change within `yarn.lock`. i deem them all uncritical anyhow.
After building demosplan-core with the new version, go to assessment table, create/edit one recommendation text, save or abort (hereby closing the editor instance), edit another (or the same) recommendation text again. use the boilerplate icon - it shoud open a modal. no errors should appear within the console.
https://github.com/demos-europe/demosplan-ui/pull/95

fix(refs T31311): bump demosplan-ui

---

client/js/components/statement/listStatements/ListStatements.vue

**Ticket:** https://yaits.demos-deutschland.de/T29992
- if a user hasn't claimed a statement, they should not be allowed to delete it
- previously, only styling was applied in that case, but deleting the statement was still possible
Go to the statement list and try to delete a statement that is assigned to you as well as a statement that is not assigned to you. The former should be possible, the latter should not.

fix(refs T29992): disable button if statement is not claimed

---

demosplan/DemosPlanCoreBundle/Logic/Consultation/BulkLetterExporter.php

Ticket:
https://yaits.demos-deutschland.de/T31210
Description:
dont exclude email-address in authorizedUsersExport for all Guests - just if chosen to anonymize.
you can hand in a statement as a guest -> choose anonymous -> it should be anonymized within the export.
For non-anonymized statements the email address should be shown within the export.

feature (refs T31210): include email in authorizedUsersExport

---

demosplan/DemosPlanAssessmentTableBundle/Logic/AssessmentTableServiceStorage.php
demosplan/DemosPlanCoreBundle/Controller/Base/BaseController.php
demosplan/DemosPlanCoreBundle/Logic/CoreHandler.php
demosplan/DemosPlanCoreBundle/Logic/EntityContentChangeDisplayHandler.php
demosplan/DemosPlanCoreBundle/Logic/LegacyFlashMessageCreator.php
demosplan/DemosPlanMapBundle/Logic/MapHandler.php

Ticket: 
https://yaits.demos-deutschland.de/T31171
Description:
Only use the MessageBagInterface
- There seems to be a mismatch by dependency injection - which lead to
different instances of the Messagebag.
(One getting filled - another empty one goes
to the TransformMessageBagService)
The flash messages should appear again.
An easy one that was not working for instance is to bulk copy an original statement without choosing one. 
Bimschg-Antrag Repo: https://github.com/demos-europe/demosplan-plugin-bimschg-antrag/pull/2
Statement-Similarity Repo: https://github.com/demos-europe/demosplan-plugin-statement-similarity/pull/2

feature (refs T31171): show flash messages again

---

demosplan/DemosPlanAssessmentTableBundle/Logic/AssessmentTableServiceStorage.php
demosplan/DemosPlanCoreBundle/Controller/Base/BaseController.php
demosplan/DemosPlanCoreBundle/Logic/CoreHandler.php
demosplan/DemosPlanCoreBundle/Logic/EntityContentChangeDisplayHandler.php
demosplan/DemosPlanCoreBundle/Logic/LegacyFlashMessageCreator.php
demosplan/DemosPlanCoreBundle/Logic/MessageBag.php
demosplan/DemosPlanMapBundle/Logic/MapHandler.php
demosplan/DemosPlanStatementBundle/EventSubscriber/OrganisationUpdateSubscriber.php

Ticket:
https://yaits.demos-deutschland.de/T31171
Description:
Deletes the static self reference from the MessageBag as it is fortunately not needed anymore.
Removed the static method for adding messages and changed the caller of this method to use the proper method instead
by injecting the MessagBagInterface.
Everything should work as before.

F t31171 delete static self reference from message bag

---

demosplan/DemosPlanCoreBundle/Permissions/Permissions.php

`Permissions` lacked a hook `setProcedurePermissionsetWrite` that is used in every childclass and better should be defined in parent
code review

chore: add missing override hook to permissions

---

client/js/components/statement/assessmentTable/DpEditFieldMultiSelect.vue
templates/bundles/DemosPlanStatementBundle/DemosPlanStatement/includes/fragment_statement_form.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T31303
To better differentiate between options and optgroups, the latter are displayed bold, as we already do it within the assessment table.
Go to "Stellungnahme in Datensätze aufteilen", watch "Schlagworte" Multiselect.

Make optgroup appear bold 

---

demosplan/DemosPlanCoreBundle/ResourceTypes/HashedQueryResourceType.php

**Ticket:** https://yaits.demos-deutschland.de/T31312
The resource type seems to have been non-functional since it was created (during a refactoring). Opening it like it is done in this PR is fine, as it can only be accessed via `UserFilterSetResourceType`, that already contains checks to limit access via permission check, the user that created the filter and the procedure in which the filter was created.

fix(refs T31312): Allow access to hashedQuery via API

---

demosplan/DemosPlanStatementBundle/ValueObject/CountyNotificationData.php

**Ticket:** https://yaits.demos-deutschland.de/T31308
Properties in classes extending from `ValueObject` must be set to `protected` for the `@method` tag to work.
Also used PHP 8+ syntax for properties to keep the code modern.

fix (refs T31312): use correct access modifier in value object

---

client/js/components/statement/assessmentTable/DpFragmentsSwitcher.vue
client/js/components/statement/assessmentTable/DpTable.vue
client/js/store/statement/Filter.js

**Ticket:** https://yaits.demos-deutschland.de/T31314
selectedFilterOptions are only fetched when the filter modal is opened for the first time (we implemented this to improve initial loading speed). to show the info despite this, we can grab the filters from the assessmentTable store, where it is persisted as passed via twig/prop into DpTable.
Build, find a procedure where there are fragments with both states "new" and "editing", go to procedure dashboard, find the "Datensätze nach Status" chart, click on the link for "new" or "editing" filter.
In the assessment table which opens then, the UI which reads "Die Suche ergab X Treffer in Y Datensätzen" should show up.

Also use initial filters to show fragment toggle

---

demosplan/DemosPlanCoreBundle/Resources/config/bundles.php

Description:  the templates are moved under DemosPlanCore
related PRs:
- Teilhabe : https://github.com/demos-europe/demosplan-project-teilhabe/pull/13
- regio: https://github.com/demos-europe/demosplan-project-regio/pull/22
- robobsh: https://github.com/demos-europe/demosplan-project-robobsh/pull/23

Fix: remove DemosPlanFaq from configs yaml

---

demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanAssessmentController.php
templates/bundles/DemosPlanStatementBundle/DemosPlanAssessment/view_statement.html.twig

https://yaits.demos-deutschland.de/T31331
Originally the statement entity was converted into an associative array in the backend and the field
`feedback` overridden with the corresponding
translation value before passing the array into the twig file.
However, `getStatement` did no
longer return the array representation of the statement but the statement object instead, which caused a bug. Returning the object is fine, because
we want to handle objects in the backend and avoid unnecessary conversions.
As it would be very bad practice to write a translation value into the `feedback` property of the (now object) statement (as
it may be persisted by accident after refactorings), the approach was changed and the logic determining flags and translation values was moved into the twig file, as …

fix (refs T31331): move UI-logic into twig

---

demosplan/DemosPlanCoreBundle/DataFixtures/ORM/DemosFixture.php
demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadProcedureData.php
demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadProcedureData.php
demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadUserData.php

The better we get in using dependency injection and private services the more important it gets to drop the usage of the container an the dynamic service fetching. 
The Fixtures did not use DI in every cases and thus the tests where broken
Run any test it should not complain about inlined or removed services

fix: fixtures should use proper Dependency Injection instead of container

---

templates/bundles/DemosPlanUserBundle/DemosPlanUser/includes/mastertoeblist_pageheader.html.twig

https://yaits.demos-deutschland.de/T31401
The translation key was simply unknown. Since we already have a translation key to display "Master-TöB-Liste", the fix simply is to use the already existant translation key instead of the old unused one.
- Login as Institutions-Koordination (Arya Stark)
- Navigate to http://bobhh.dplan.local/app_dev.php/mastertoeblist
- The translation key should now be translated correctly (see also screenshot)

bug(refs: T31401): fix wrong translation in master toeb list

---

.env
demosplan/DemosPlanCoreBundle/Resources/config/config_dev_container.yml
demosplan/DemosPlanCoreBundle/Resources/config/packages/old_sound_rabbit_mq.yaml
demosplan/DemosPlanCoreBundle/Resources/config/parameters_default.yml

**Ticket:** https://yaits.demos-deutschland.de/T31375
Rabbitmq parameters are consolidated into `rabbitmq_dsn` to be able to use a single environment variable `RABBITMQ_URL` to define the rabitmq dsn.
Define a valid `RABBITMQ_URL` env var in your `.env.local` and e.g. import a docx file

feat (refs T31375): use env var to connect to rabbitmq

---

demosplan/DemosPlanStatementBundle/Logic/StatementService.php

Ticket:
https://yaits.demos-deutschland.de/T31310
Description:
This branch has already been merged into main - but this change is needed in release.
This just picks the changes and move them into release as well.
addShould does not accept an array of or conditions - they need
to be added separately.
robobsh ->Abwägungstabelle filtern -> Datensatz
you should get results again.

feature (refs T31310): addShould does not

---

demosplan/DemosPlanCoreBundle/Controller/AssessmentTable/DemosPlanAssessmentTableController.php
demosplan/DemosPlanCoreBundle/Controller/Document/DemosPlanDocumentController.php
demosplan/DemosPlanCoreBundle/Entity/File.php
demosplan/DemosPlanCoreBundle/Entity/Report/ReportEntry.php
demosplan/DemosPlanCoreBundle/Entity/Statement/StatementMeta.php
demosplan/DemosPlanCoreBundle/Logic/EntityContentChangeRollbackVersionService.php
demosplan/DemosPlanCoreBundle/Logic/ZipExportService.php
demosplan/DemosPlanCoreBundle/ValueObject/LegacyResult.php
demosplan/DemosPlanProcedureBundle/Logic/ProcedureToLegacyConverter.php
demosplan/DemosPlanReportBundle/Logic/ReportMessageConverter.php
demosplan/DemosPlanStatementBundle/Logic/DraftStatementService.php
demosplan/DemosPlanStatementBundle/Logic/ElasticSearchService.php
demosplan/DemosPlanStatementBundle/Logic/StatementFragmentService.php

Phpstan found several issues about variables that are checked for null that are not described to be null. Some of them could be resolved by adding null to return type hints. Might be best to be reviewed commitwise
Might be best to be reviewed commitwise. Run phpstan to see the effects

Fix phpstan issues with isset

---

composer.json

Since we're not adding dependencies very often
and do our own research on what they need when we
configure them, there is no need for this
plugin to run and check if it can help us.
> Since 1.15.0, this library also provides a composer plugin that automatically installs well-known PSR implementations if composer dependencies require a PSR implementation but do not specify which implementation to instal

build: Disallow discovery composer plugin

---

demosplan/DemosPlanCoreBundle/Addon/FrontendAssetProvider.php
demosplan/DemosPlanCoreBundle/Addon/Registrator.php
demosplan/DemosPlanCoreBundle/Command/Addon/AddonBuildFrontendCommand.php

Addons should not store absolute paths as currently the configuration needs to be compatible with multiple environments with different paths. Therefore the path needs to be relative
install addon 

feat: use relative path in addon to be compatible with different environments

---

client/js/components/statement/assessmentTable/TocView/AssessmentTableGroup.vue

https://yaits.demos-deutschland.de/T31539
- Since the event names for adding and removing statements from the selection the logic to trigger the edit menu of AssessmentTableFilter.vue was broken. By adding the correct event names the edit menu appears now when selecting a single or multiple statements.
- Login as FPA user
- Navigate to a-table
- Select a single or multiple Statements
- The edit menu should trigger now and these statements should be exportable as a docx file

bug(refs: T31401): fix edit menu does not trigger when selecting single statements in a-table

---

demosplan/DemosPlanCoreBundle/EventSubscriber/UserLoginSubscriber.php

**Ticket:** https://yaits.demos-deutschland.de/T31518
Field `last_login` was not updated any more after upgrading the symfony authentication system
login via login form and the field should be updated

fix (refs T31518): Use Event that is triggered on manual login

---

tests/backend/core/Map/Functional/MapCapabilitiesLoaderTest.php

This PR removes a useless import in a class that leads to a parse error
run `MapCapabilitiesLoaderTest.php`

fix: remove bogus import in Test

---

demosplan/DemosPlanCoreBundle/Command/Db/MigrateCommand.php

A blank was missing between the configuration and the classname that lead to the error, that the rollup
migrations for the project where not performed

fix: avoid syntax error in migrate command

---

client/js/bundles/procedure/administrationNew.js
client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
client/js/store/procedure/NewProcedure.js

https://yaits.demos-deutschland.de/T23632
- To enable the communication between the upload component and DpNewProcedure, which inherits the AntragX upload component, a store has been introduced to dynamically determine if the name field is required when creating a new procedure. This field is only required when no AntragX file is being uploaded since the procedure name will be extracted from there. The problem is that the name can only be extracted after submitting the form but to submit the form the name field was required.
- Now the store holds the state weather or not the name field is required. The decision for a store has been made because I simply do not like to $root emit events since this is an easy way to lose the ability to read easily through the code and also the $root pattern …

bug(refs T23632): enable automatic name extraction in bimschg antrag x

---

templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/public_index_globalnewslist.html.twig

**Ticket:** https://yaits.demos-deutschland.de/Txxyyzz -->
**Description:** This PR presents small changes in the `public_index_globalnewslist.html.twig` file in order to apply required design in the DiPlanbau project.
- place link into the` <span>` tag
- add new class _o-page__news--item_ to a div

Feat_(T31035): adjust design: global news list - diplanbau

---

client/js/components/map/publicdetail/Map.vue

**Ticket:** https://yaits.demos-deutschland.de/T30632
Creating the layersource was removed for hidden layers because of performance, but we also need the layer sources for hidden layers. Otherwise when updating the map fields right after loading the page (eg with drawing in the map) we get an error, because not all print layers have a source.
Login as FPA and create a layer with print, but otherwise hidden and one that is not hidden (under Verfahren -> Planunterlagen und Planzeichnung -> Kartenebenen definieren).
Then login as Privatperson and go to the public site of the procedure. You should be able to draw something in the map immediately without having to change the layers first.

bug(refs T30632): Create baselayers always with layersource

---

client/js/components/statement/assessmentTable/DpBulkEditFragment.vue
client/js/components/statement/assessmentTable/DpBulkEditStatement.vue
translations/messages+intl-icu.de.yml

**Ticket:** https://yaits.demos-deutschland.de/T31512
Description: if you would like to edit the considerationadvice in AT, it says in the edit part consideration and this is confusing
- go to AT, click a checkbox of a statement, go to `Bearbeiten`

Fix(refs:T31512): Replace consideration with considerationadvice

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_card.scss

Instead of adding a margin to the expanded item to show its box shadow (which otherwise is overlapped from following items), positioning it relative solves this problem, too. The negative left margin and reduced right padding ensure the item stays within its vertical axis even with added box-shadow.
Login as a support user in projects that use `DpTableCard`, and click on a card. It should stay in place also in expalded state.

Add styles to fix layout jump

---

demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/03/Version20230301094921.php

**Ticket:** https://yaits.demos-deutschland.de/T31604
Description: "Web Atlas" was not replaced with "basemap" in all procedure templates. 
This was due to the fact that different urls are used for "Web Atlas", but only one was checked in https://github.com/demos-europe/demosplan-core/pull/578.
Anyway, this PR should catch every url with "webatlas" in it.
First: Find a older procedure template with a "Web-Atlas" as map (hint: not all have the name "Web-Atlas", so check if the url contains "webatlas".)
Then execute the migration.
And finally check the founded procedure template again. You should don't find any occurrences of "webaltas" in other procedure templates.
You could also check the database. In the ticket is a statement to find occurrences.
Delete the checkbox if it doesn't …

bug (refs T31604): fix occurrences of "Web-Atlas" in blueprints by replacing them with "basemap"

---

client/js/components/user/CustomerSettings/CustomerSettings.vue

<!-- **Ticket:** https://yaits.demos-deutschland.de/T31701
Description: in the `getRequestPayload` in the return it should be `include` instead of `includes` otherwise there are no relationships in the payload and we get undefined for the requested attributes
- login as support and go to the platform settings

Fix(refs:T31701): platform settings are not loading

---

demosplan/DemosPlanCoreBundle/Entity/User/Orga.php

Thus, validation is not possible in this case.
code review is probably best, as login via OSI with an organisation with an emaillist as `$ccEmail2` would trigger the case

fix (refs T31730): cc email addresses may be a list of emails

---

client/js/bundles/news/newsAdminEdit.js
client/js/bundles/news/newsAdminNew.js
client/js/bundles/procedure/administrationMemberEmail.js
client/js/bundles/procedure/administrationSendEmail.js
client/js/bundles/procedure/administrationUnregisteredPublicagencyEmail.js
client/js/bundles/statement/assessmentStatement.js
client/js/bundles/user/customersettingsmail.js
client/js/components/procedure/SegmentsBulkEdit/SegmentsBulkEdit.vue
client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
client/js/components/statement/DpBoilerPlateModal.vue
client/js/components/statement/assessmentTable/DetailView/DetailViewFinalEmailBody.vue
client/js/components/statement/assessmentTable/DpBulkEditFragment.vue
client/js/components/statement/assessmentTable/DpBulkEditStatement.vue
client/js/components/statement/assessmentTable/TiptapEditText.vue
templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/shared/v1/assessment_statement_detail_statement_text.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_edit.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_new.html.twig
templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/administration_member_email.html.twig
templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/administration_send_email.html.twig
templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/administration_unregistered_publicagency_email.html.twig
templates/bundles/DemosPlanUserBundle/DemosPlanUser/customer_settings_update_mail.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T31795
BoilerplateModal in DpEditor was replaced by slots and therefore the ui form rows in twig files were replaced directly with dpEditor and the needed slots. 
See also https://github.com/demos-europe/demosplan-core/pull/875

bug(refs T31795): add slots for boilerplate

---

demosplan/DemosPlanStatementBundle/Logic/StatementFragmentService.php

Some functional tests are skipped due to the need of elasticsearch which is not available in CI.
Copy and clustering of StatementFragments should work as before

feat: Avoid call to elasticsearch to fix tests

---

demosplan/DemosPlanCoreBundle/Command/FrontendIntegratorCommand.php

OpenAPT specification only needs to be created on development builds. This also may help in Problems with production asset dumps

feat: create OpenAPI Data only on development builds

---

demosplan/DemosPlanAssessmentTableBundle/Logic/AssessmentTableViewMode.php
demosplan/DemosPlanCoreBundle/Command/Addon/AddonBuildFrontendCommand.php
demosplan/DemosPlanCoreBundle/Command/Data/DataProviderCommand.php
demosplan/DemosPlanCoreBundle/Constraint/ClaimConstraint.php
demosplan/DemosPlanCoreBundle/Constraint/ConsistentOriginalStatementConstraint.php
demosplan/DemosPlanCoreBundle/Constraint/CorrectDateOrderConstraint.php
demosplan/DemosPlanCoreBundle/Constraint/FormDefinitionConstraint.php
demosplan/DemosPlanCoreBundle/Constraint/MatchingFieldValueInSegments.php
demosplan/DemosPlanCoreBundle/Constraint/MatchingSubmitTypesConstraint.php
demosplan/DemosPlanCoreBundle/Constraint/OriginalReferenceConstraint.php
demosplan/DemosPlanCoreBundle/Constraint/PrePersistUniqueInternIdConstraint.php
demosplan/DemosPlanCoreBundle/Constraint/ProcedureAllowedSegmentsConstraint.php
demosplan/DemosPlanCoreBundle/Constraint/ProcedureInCoupleAlreadyUsedConstraint.php
demosplan/DemosPlanCoreBundle/Constraint/ProcedureMasterTemplateConstraint.php
demosplan/DemosPlanCoreBundle/Constraint/ProcedureTemplateConstraint.php
demosplan/DemosPlanCoreBundle/Constraint/SimilarStatementSubmittersSameProcedureConstraint.php
demosplan/DemosPlanCoreBundle/Constraint/UserWithMatchingDepartmentInOrgaConstraint.php
demosplan/DemosPlanCoreBundle/DependencyInjection/Configuration/MenusTreeBuilder.php
demosplan/DemosPlanCoreBundle/Doctrine/Generator/UuidV4Generator.php
demosplan/DemosPlanCoreBundle/EventSubscriber/NonAuthorizedAssignRemoveSubscriber.php
demosplan/DemosPlanCoreBundle/Logic/Logger/ApiLogger.php
demosplan/DemosPlanCoreBundle/Permissions/Permission.php
demosplan/DemosPlanCoreBundle/Resources/config/GlobalConfig.php
demosplan/DemosPlanProcedureBundle/Constraint/ExclusiveProcedureOrProcedureTypeConstraint.php
demosplan/DemosPlanProcedureBundle/Constraint/ProcedureTypeConstraint.php
demosplan/DemosPlanStatementBundle/ValueObject/DraftStatementListFilters.php

**Ticket:** https://yaits.demos-deutschland.de/T27388
This PR fixes some  simple and safe to apply return type deprecations
Load any page and see the amount of deprecations drop in the symfony toolbar

chore (refs T27388): fix simple and safe return type deprecations

---

client/js/components/statement/publicStatementModal/StatementModal.vue

https://yaits.demos-deutschland.de/T31791
- The loadtime is required for the flood control and expects a unix timestamp.
- Unfortunately the loadtime was not set when submitting the new statement form as a guest user.
- Since the form data is set via the vuex store, a mutation has to be added to the form submit function.
- The form data gets reset after submit so it is fine to simply set the loadtime via a mutation but not resetting it manually again.
- Checkout branch
- Use the statement modal on public detail as guest user
- Verify the form field `r_loadtime` has been set correctly (is not empty when submitting the form)

Bug(refs: T31791): fix loadtime not in form request

---

templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/public_index_globalnewslist.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T31666
- the globalnews section shouldnt be shown if there no news exist
- go to `Startseite`
- look to the globalnews section with `Aktuelle Meldungen` and `Alle Meldungen` , if there are no any news
- if there are existing news, login as `Redakteur` (or new role in DiplanBau `Mandanten-Aministration`) and deactivate the status of the news in `Verwalten` -> `Portal-Mitteilungen` -> `Portal-Mitteilungen verwalten`

Feat(refs:T31666): Dont show globalnews title and section if no news exists

---

demosplan/DemosPlanCoreBundle/Logic/Factory/PercentageDistributionFactory.php
demosplan/DemosPlanCoreBundle/Resources/config/services.yml
demosplan/DemosPlanCoreBundle/ValueObject/PercentageDistribution.php

**Ticket:** https://yaits.demos-deutschland.de/T30254
Description: Added a PercentageDistributionFactory and implement the PercentageDistributionInterface on PercentageDistribution.php to make the PercentageDistribution value object accessible and creatable in addons.
- Other PR #{https://github.com/demos-europe/demosplan-core/pull/958}

feature (refs T30254): Make PercentageDistribution value object availabe in addons

---

demosplan/DemosPlanCoreBundle/Resources/config/parameters_test.yml

Description: - this parameters yaml was by mistake moved to demospipes addon, the addon related parameters are moved from here. The Rest parameters should stay in core

F add parameters_test yaml

---

templates/bundles/DemosPlanCoreBundle/DemosPlanAdmin/statistics.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T31509
All spaces were removed from the template in an attempt to shrink html in case large amounts of entries are in the procedurelist. however that one space has to stay there.
The visual inconsistency within the header is not fixed by this PR.

fix(refs:T31509): add space

---

jest.config.js

After moving the config.js (part of the webpack config) we forgot to adjust the path from the jest.config.
see https://github.com/demos-europe/demosplan-core/pull/890

fix: Adjust path to Jest config

---

demosplan/DemosPlanReportBundle/Logic/ProcedureReportEntryFactory.php

**Ticket:** https://yaits.demos-deutschland.de/T31622
**Ticket:** https://yaits.demos-deutschland.de/T16953
The user id is not nullable for report entries. So even if we don't really have a user and use the default fallback name, we still have to set the user id to at least empty string. This little fix should take care of both tickets.
You can locally set the phases of a procedure to participation and the end date to yesterday. Then log out and call the URL for the maintenance task for the local project.

fix (refs T31622, T16953): fix user id in report entry

---

client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
translations/messages+intl-icu.de.yml

[Ticket](https://yaits.demos-deutschland.de/T31984)
This PR prevents the user from unintentionally deleting an unsaved text by synchronizing the local statement in `StatementMeta.vue` (which also emits the local statement when saving only metadata) with the statements from store. The editor automatically updates the state of statements in the store when registering an input. This only occurs when a statement has not been segmented already.
- navigate to detail view of statement
- select statement without segments
- click edit and claim statement
- edit the text of the editor
- use the upper save button for metadata
- reload page and confirm that the text in the editor was saved too
- check if a statement with segments still works like before 
Delete the checkbox if it doesn't apply/isn't …

bug(refs: T31984): prevent unintentional deletion of editor text

---

demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php

We previously skipped updating the actual code when an addon was marked for reinstallation. This should now happen as expected.

fix: Update the addon's code on reinstall

---

demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/03/Version20230324132250.php
demosplan/DemosPlanCoreBundle/Logic/JwtRouter.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/AiApiUserProvider.php

**Ticket:** https://yaits.demos-deutschland.de/T31926
The AiApiUser is currently created by constructor, but should not be persisted or stored in the database. However, the addon-specific permission evaluation checks properties that lead to persist problems when creating the user. To prevent this, it was decided to save the AiApiUser in the database via core migration. The user should now be fetched via the database and the addon-specific permission checks should hopefully work again.
Hint: The migrations are in the linked PR's
You could run the migrations and check if they works.
But to test if the bug is fixed with this PR we have to install these changes on dev.
https://github.com/demos-europe/demosplan-project-ewm/pull/41 closed …

feat (refs T31926): move ai api user to database

---

client/js/components/procedure/AdministrationImport/AdministrationImport.vue

**Ticket:** https://yaits.demos-deutschland.de/T31929
Loading the '"default" Tabs/Components on the import page and then add some addons later on triggered a rerendering of the already loaded components, which broke the dpDatepicker and had potential to brake other things aswell.
To prevent that now the Tabs only get rendered after the addon-request is fulfilled. In premature obedience, to make it scalable, I already added a promisall resolving...  
As FPA goto
/verfahren/<procedure-id>/import#StatementFormImport
check if the Datepicker for Einreichungsdatum/Verfassungsdatum works

fix(refs T31929): Optimize addon loading

---

client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
client/js/components/statement/DpClaim.vue

**Ticket:** https://yaits.demos-deutschland.de/T32028
**Fixing the bug**
Inside StatementMeta, the statement obj persists its initial state, which it also bubbles back up onSave. So, when loading the view with unassigned statement, and then assigning it, the local statement in StatementMeta still has the unassigned state which is applied to the outer state then, leading to the buggy behavior.
To work around this, we can either only pass the data into StatementMeta which is actually needed by this component, or we can fix it afterwards (this version) - which is a little ugly but as most data is needed within StatementMeta, it is still the better choice.
**Button cleanup**
The claim component generates a link element. To wrap that within a button is not html5 conform, also the link is not …

Fix unclaiming of statement

---

templates/bundles/DemosPlanUserBundle/DemosPlanUser/edit_orga.html.twig
templates/bundles/DemosPlanUserBundle/DemosPlanUser/orga_data_entry.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T31858
There is no practical way of hiding the buttonRow based on permissions - the appearance of form elements is already controlled by twig project overrides. So, to hide the buttonRow for ewm, it is moved within the inner template. Here, it can then be hidden via block, too.
Nothing should change except for EWM. There should be no buttons anymore when visiting the "Daten der Orga" view anymore.
https://github.com/demos-europe/demosplan-project-ewm/pull/44

Hide button row

---

client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue
client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue

**Ticket:** https://yaits.demos-deutschland.de/T28146
There is no reason to show a disabled editor, at all. It is more helpful to just show the text.
The border and padding is applied to add structure to the view. It borrows the style from the StatementMeta box.
In ewm, go to the statement list and open a statement that is not segmented already. unassign it. The statement text should be rendered in a bordered box, without the editor ui.

Show statement as text when not in edit mode

---

demosplan/DemosPlanCoreBundle/Resources/config/parameters_default.yml

When no SAML is configured the default configuration needs to meet some basic requirements. These are set so that the exception would not be thrown anymore.
clear cache and find no info about the exception in an uncalled listener any more

fix: avoid exception in uncalled listener

---

client/js/components/procedure/AdministrationImport/AdministrationImport.vue

**Ticket:** https://yaits.demos-deutschland.de/T31998
Somehow the invoking of setActiveTabId got lost
during the refactoring of the component. Anyhow,
here we go again.
Go to import, craft a manual statement via "Direkteingabe" tab. Submit the form. After reloading the page, the same tab should be selected.

fix(refs T31998): restore setActiveTabId

---

demosplan/DemosPlanCoreBundle/EventSubscriber/ParametersProviderSubscriber.php

Ticket:
https://yaits.demos-deutschland.de/T31926
Description:
use new Response instance for method processRequestParameters
instead of null

feature (refs T31926): use new Response instance to prevent null value

---

demosplan/DemosPlanCoreBundle/EventSubscriber/ParametersProviderSubscriber.php

Ticket:
https://yaits.demos-deutschland.de/T31926
Description:
change method of EventSubscriber from private to public.

feature (refs T31926): change method of EventSubscriber from private to public.

---

demosplan/DemosPlanCoreBundle/Permissions/Permissions.php

**Ticket:** https://yaits.demos-deutschland.de/T32003
The permissions for "Institutionen verschlagworten" should only enabled for diplanbau.
You could check if you can tagging institutions only in DiPlanBau.
https://github.com/demos-europe/demosplan-project-diplanbau/pull/77

fix (refs T32003): disable permissions for institution tagging

---

client/js/components/procedure/DpSimplifiedNewStatementForm.vue
client/js/components/procedure/admin/AuthorizedUsersList.vue
client/js/components/statement/statement/DpAutofillSubmitterData.vue

**Ticket:** https://yaits.demos-deutschland.de/T31969
This PR removes the pattern validation for all "city" form input fields. It was once introduced in DpAutofillSubmitterData without overthinking ux aspects, and has since spread into other form
fields that ask for a city.
It does not add value for users to restrict the input for the "city" field based on assumptions that can prove wrong anytime. It will do little harm to remove the restriction (which will eventually lead to a typo going unnoticed) but it will cause massive trouble for users failing for a too-restrictive validation.
It should be possible to input all characters into the "city" field.

Remove pattern validation for city

---

demosplan/DemosPlanCoreBundle/ResourceTypes/SimilarStatementSubmitterResourceType.php
demosplan/DemosPlanStatementBundle/Logic/StatementService.php

**Ticket:** https://yaits.demos-deutschland.de/T32013
Description: submitters of the same statement are not saved, the resourcetype had to be adjusted

F T32013 submitters of the same statement are not saved

---

composer.lock

Ticket:
Description:
update composer.lock due to changes in demosplan-addon

feature (refs T30254): update composer.lock

---

demosplan/DemosPlanCoreBundle/DependencyInjection/ServiceTagAutoconfigurator.php
demosplan/DemosPlanCoreBundle/Logic/Rpc/RpcMethodSolverInterface.php

**Ticket:** https://yaits.demos-deutschland.de/T31511
Description: use RpcMethodAddonSolverInterface instead RpcMethodSolverInterface to autoconfigurate services.

F_T31511 make statement splitting possible

---

templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_footer.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T31920
- this is for override the footer for `diplanbau`
- https://github.com/demos-europe/demosplan-project-diplanbau/pull/78

Feat(refs:T31920): Change style header and footer

---

demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserAuthenticationController.php
templates/bundles/DemosPlanUserBundle/DemosPlanUser/alternative_login.html.twig

This PR adds a possibility to login via external identity provider in development environments on top on login via form.
set `gateway_url` to something like `/connect/keycloak_ozg` and find a (unstyled) link to the external idp

feat: provide link to external identity provider

---

demosplan/DemosPlanCoreBundle/Repository/SegmentRepository.php

Ticket:
Description:
change SegmentRepository usage of SegmentsManager to Segment::class instead
as the SegmentsManager does not exist anymore. Segments got included into the core.

feature (refs T30254): change SegmentRepository usage of SegmentsManager

---

demosplan/DemosPlanCoreBundle/Logic/ApiRequest/Transformer/BaseTransformer.php

Ticket:
Description:
remove an unnecessary method
this method was called and gets removed from addon demospipes: https://github.com/demos-europe/demosplan-addon-demospipes/pull/61
the interface got changed in demosplan addon: https://github.com/demos-europe/demosplan-addon/pull/43

feature (refs T30254): remove an unnecessary method

---

demosplan/DemosPlanDocumentBundle/Logic/DocumentHandler.php

**Ticket:** https://yaits.demos-deutschland.de/T32124
Planners may not be able to view published documents in the case when only specific organisations are allowed to view documents
You need to have only categories published that are also only allowed to be accessed by specific organisations

fix (refs T32124): Always show published documents to owning orga

---

demosplan/DemosPlanCoreBundle/Logic/MenuBuilder/MenuBuilder.php

**Ticket:** https://yaits.demos-deutschland.de/T32046
We knew something like extras would be needed at some point, so we established it as an option. But at least for now, we can keep it a bit more simple which is exactly what this commit does.
This part of the new sidemenu was never used before.

fix (refs T32046): simplify sidemenu item extras

---

client/js/components/procedure/basicSettings/DpAllowedSenderEmailList.vue

- The BE needs the allowedSenderAddresses as array not as a string hence this has been adjusted so.

fix request format for extra email addresses

---

demosplan/DemosPlanUserBundle/Logic/UserMapperDataportGatewayHH.php

We sometimes have the situation that a user can't log in to the production system and everything we see in the logs seems to be ok. So I'm adding this with the hopes that seeing the actually used strings as well as the result might help us understand that better.

minor (refs T31740): adds logging

---

client/js/components/procedure/basicSettings/DpAllowedSenderEmailList.vue

- The procedureId may not be sent within the request body due to invalidity and hence must be removed from there.

fix invalid request data for extra email addresses

---

client/js/components/user/DpUserFormFields.vue

https://yaits.demos-deutschland.de/T31995
- This was a race condition like scenario caused by the if-else block of the computed `allowedRolesForOrga`
- To prevent this, DpMultiselect should only be rendered if `organisations[this.currentUserOrga.id]` is existant in any form (with value or empty string but not undefined)
- Login as Lisa Bauer
- navigate to /users/list
- make sure the fields are filled
- make sure there is no console error about undefined values

Fix(refs T31995): no institution data displayed in form fields

---

composer.lock

Ticket:
Description:
update composer.lock due to changes in demosplan-addon

feature (refs T30254): update composer.lock due to changes in demosplan-addon

---

client/js/components/procedure/Shared/SimilarStatementSubmitters/SimilarStatementSubmitters.vue

**Ticket:** https://yaits.demos-deutschland.de/T32110
Before, the state was simply not persisted. This PR persists the state locally.
After adding, editing or removing a SimilarStatementSubmitter, and then clicking another tab, the current state should be reflected correctly.

Persist SimilarStatementSubmitter state locally

---

client/js/components/procedure/basicSettings/DpBasicSettings.vue

- This is now an addon component and therefore should be removed from the core also this is throwing an error since the component does not exist anymore in the core
This was overseen in https://github.com/demos-europe/demosplan-core/pull/1179 and hence the import was removed in this PR from the basic settings

fix: remove DpAllowedSenderEmailList.vue from DpBasicSettings

---

demosplan/DemosPlanCoreBundle/Permissions/Permissions.php

**Ticket:** https://yaits.demos-deutschland.de/T31959
Description: adjust core permissions
- remove area_organisations_applications_manage from core. This permission will be enabled for the CUSTOMER_MASTER_USER only in the projects where it is allowed

F_T31959 adjust core permissions

---

client/js/bundles/procedure/administrationEdit.js
client/js/components/procedure/basicSettings/DpBasicSettings.vue

https://yaits.demos-deutschland.de/T32259
AddonWrapper needs to be imported in DpBasicSettings.vue and not in the entrypoint.
https://github.com/demos-europe/demosplan-addon-maillane/pull/25

fix(refs T32259): AddonWrapper needs to be imported in DpBasicSettings

---

client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue

**Ticket:** https://yaits.demos-deutschland.de/T30572
The secondary button actually resets the form fields to the value that was last saved, it discards unsaved changes.
To reflect this, instead of "Abbrechen" the new label "Änderungen verwerfen" is applied. It has been chosen because:
- it explicitly says what the button is doing
- it is already used in similar places within demosPlan
Even if "Verwerfen" is shorter, there is a chance that users might assume the whole texts to be removed when clicking the button.
In the statement detail view in ewm, both below the metabox fields and below the editor of the (not already segmented) statement text, the secondary button should read "Änderungen verwerfen".

Use correct button label

---

demosplan/DemosPlanCoreBundle/Resources/config/permissions.yml

**Ticket:** https://yaits.demos-deutschland.de/T32219
Fix for **Ticket:** https://yaits.demos-deutschland.de/T30866
Needed Permissions are not exposed for using in FE.
Fields should be available an editable for customer master user now.
Story PR: https://github.com/demos-europe/demosplan-core/pull/1102

fix (refs T30866): Permissions needs to be available by exposing them.

---

demosplan/DemosPlanCoreBundle/Addon/AddonRoutingLoader.php

Avoid error when addons do not have Controllers folder
install an addon without the folder or review code

chore: only add addon controllers if addons have them

---

templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/components_entry.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T28356
The website for some software components is unknown. There should be no link displayed then.
Go to Impressum -> Lizenzhinweise -> hier and check if the components with unknown websites have no link.

bug(refs T28356): Software components with no url

---

demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php

Clearing the cache in-process vs clearing the cache out-of-process yields slightly different results for the next command. In the latter way, the current application state does not affect the cache state.
Changing this is a bit of a gamble as I have seen varying results but it seems that it makes the cache state for the frontend asset build a little more reliable and thus reduces the friction during addon installation.

feat: Clear cache out of band

---

client/js/components/procedure/SegmentsBulkEdit/SegmentsBulkEdit.vue

- Sonarcloud shows major issue because of double data propöerty
- just remove it to fix it, because it already exists

Fix: Remove double data property

---

demosplan/DemosPlanCoreBundle/Resources/config/services.yml

Description:  
there are no need to add a defintion to this interface in the services yaml.

F_remove unnecessary interface defintion

---

demosplan/DemosPlanCoreBundle/Logic/FileService.php
demosplan/DemosPlanCoreBundle/Resources/config/services.yml

Ticket:
https://yaits.demos-deutschland.de/T32200
Description:
Sentry pointed to a method call on null regarding the FileService::client property.
These changes hopefully help to initialize the client when used in an addon context.
Sentry log: File could not be saved
`
Call to a member function addRequest() on null #0 /data/app/bobhh/demosplan/DemosPlanCoreBundle/Logic/FileService.php(478): demosplan\DemosPlanCoreBundle\Logic\FileService->virusCheck(Object(Symfony\Component\HttpFoundation\File\File)) #1 /data/app/bobhh/demosplan/DemosPlanCoreBundle/Logic/FileService.php(432): demosplan\DemosPlanCoreBundle\Logic\FileService->saveFile(Object(demosplan\DemosPlanCoreBundle\Entity\File), Object(Symfony\Component\HttpFoundation\File\File), true) #2 …

feature (refs T32200): avoid null as param client in FileService in addonContext

---

demosplan/DemosPlanCoreBundle/Resources/config/services.yml

**Ticket:** https://yaits.demos-deutschland.de/T31336
Correct spelling of referenced service. It have to start with a capital letter.
The error message should no longer arise: 'You have requested a non-existent service "demosplan\DemosPlanCoreBundle\Permissions\permissions".'

fix (refs T31336): correct spelling of referenced service.

---

client/js/components/addon/AddonWrapper.vue
client/js/components/statement/originalStatementsTable/OriginalStatementsTable.vue
client/js/components/statement/publicStatementLists/DpPublicStatement.vue
client/js/components/statement/publicStatementLists/DpPublicStatementList.vue
client/js/components/statement/statement/DpAutofillSubmitterData.vue
client/js/components/user/DpCreateItem.vue
package.json
yarn.lock

**Ticket:** https://yaits.demos-deutschland.de/T32012
- this is for the preparation from vue 2 to vue 3 migration
- here there was a warning, that the v-bind attribute was in a wrong order
- it needs to be in the first place or directly after v-if, v-for, eg.
**this PR will be merged into the integration branch: `f_vue3_compat_mode_setup`**
- https://github.com/demos-europe/demosplan-core/pull/1240

Feat(refs:T32012): order v bind vue3 migration

---

demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php

**Ticket:** https://yaits.demos-deutschland.de/T32244 & https://yaits.demos-deutschland.de/T32245 
The DemosPlanStatementBundle and DemosPlanSurveyBundle was moved to core. This PR removes some leftover use cases.
code review
https://github.com/demos-europe/demosplan-core/pull/1217
https://github.com/demos-europe/demosplan-core/pull/1197

fix (refs T32244 & T32245): Remove old use statements of moved bundles.

---

client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue

https://yaits.demos-deutschland.de/T32449
This is the frontend part for https://github.com/demos-europe/demosplan-project-ewm/pull/55. This PR adds a permission check in the StatementSegmentsList to render the statement text if the permission `area_statement_segmentation` is not granted to the current user.
https://github.com/demos-europe/demosplan-project-ewm/pull/55

fix(refs T32449): load statement text instead if permission is not granted for segments

---

client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue

https://yaits.demos-deutschland.de/T32034
Also the fetching of segments data should only be fired, when the current user has the permission for segments. Otherwise the response would throw an console error. And also the loading state would not been set to false which prevented the statement text to be rendered instead. To make this component more resilient a finally block has also been added to the fetch function for segments

fix(refs T32449): remove access to segments for ahb

---

client/js/components/user/citizenRegisterForm/CitizenRegisterForm.vue
client/js/components/user/orgaRegisterForm/OrgaRegisterForm.vue
demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanOrgaController.php
demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserController.php
demosplan/DemosPlanCoreBundle/Logic/SessionHandler.php
demosplan/DemosPlanUserBundle/Logic/UserHandler.php
templates/bundles/DemosPlanUserBundle/DemosPlanUser/citizen_register_form.html.twig
templates/bundles/DemosPlanUserBundle/DemosPlanUser/orga_register_form.html.twig
translations/messages+intl-icu.de.yml

**Ticket:** https://yaits.demos-deutschland.de/T32414
This PR adds a csrf token to citizen and organization registration to avoid forms being misused for spam
register an organization and replay post request via browser or curl. With this patch no new organization should be added 

refs T32414: add csrf token to registration

---

client/js/components/statement/assessmentTable/ConsolidateModal.vue
client/js/components/statement/assessmentTable/CopyStatementModal.vue
client/js/components/statement/assessmentTable/DpMoveStatementModal.vue
client/js/components/statement/assessmentTable/TiptapEditText.vue

**Ticket:** https://yaits.demos-deutschland.de/T32012
- vue3 removed the modifier prop and native
- these can be removed without any problem
***- this PR will be merged into the integration branch `f_vue3_compat_mode_setup`***

Feat(refs:32012): Remove prop and native modifier - migration to vue3

---

client/js/components/document/DpMapSettingsPreview.vue
client/js/components/procedure/SegmentsList/CustomSearch.vue
client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
client/js/components/procedure/basicSettings/DpProcedureCoordinate.vue
client/js/components/procedure/imageAnnotator/DpImageAnnotator.vue
client/js/components/procedure/imageAnnotator/DpLabelModal.vue
client/js/components/procedure/splitStatement/SplitStatementView.vue
client/js/components/statement/DpBoilerPlateModal.vue
client/js/components/statement/assessmentTable/DpFilterModal.vue
client/js/components/statement/assessmentTable/DpMapModal.vue
client/js/components/statement/publicStatementLists/DpPublicStatement.vue
client/js/components/statement/segments/DpRecommendationModal.vue
client/js/components/statement/statement/DpVersionHistory.vue
client/js/components/statement/statement/DpVersionHistoryDay.vue

**Ticket:** https://yaits.demos-deutschland.de/T32012#761740
- <template> tags with no special directives are now treated as plain elements and will result in a native <template>
element instead of rendering its inner content
- remove <template> if no directives and not necessary any more
- in one commit there was a problem, that the template looks unnecessary because the slot name spelling, which shall reference to the slot of the template, was deprecated
- instead of `slot="name"` use `v-slot:name` or the more shortened way `#name` 
- ***this PR will be merged into the integration branch `f_vue3_compat_mode_setup`***
- https://github.com/demos-europe/demosplan-core/pull/1240

Feat(refs:T322012): vue3 migration - usage of template tag/element

---

client/js/components/map/map/DpOlMapDrawFeature.vue
client/js/components/map/map/DpOlMapEditFeature.vue
client/js/components/procedure/StatementSegmentsList/SegmentLocationMap.vue

**Ticket:** https://yaits.demos-deutschland.de/T32505
Center the map around all drawings and zoom to the combined extent. For that, first we need to get the extent from each layer and then combine them into one extent. After that the map can be fitted to the combined extent.
Go to Verfahren -> Abschnitte -> Erwiderungen verfassen and click on the "Ortsbezug" button. Make some drawings (line, point, polygon), close it and open it again. The map should be centered around the drawings and zooming in (all drawings should be seen).

bug(refs T32505): center map

---

client/js/components/procedure/DpSimplifiedNewStatementForm.vue

https://yaits.demos-deutschland.de/T32450
- Replace key `toeb` with `institution` but keep all other init values
- The key institution was not set correctly if there are init values. If there are, we need to keep all initial values but `toeb` which must be renamed to `institution`
- Navigate to convert pdf view (from overview eg)
- Click on institution and make sure it still works

Fix(refs: T32450) make radio buttons reactive without clicking in the form

---

demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadCustomerData.php

This PR adds basic map information to the production customer fixtures to avoid a blank map at the start page. 
You may load prod fixtures, but code review might suffice

feat: add default map to prod fixtures

---

demosplan/DemosPlanCoreBundle/Command/Db/MigrateCommand.php

Before performing the database rollup in core demosplan we needed to make sure that the database is in any project in a consistent state. This is not necessary anymore. In fact, on every migration any project migrations later than the rollup migration was downmigrated and after the core migrations reapplied. This PR sets an end to this, as rollup is already performed in most of the existing projects.
Perform `dplan:migrate -vvv` and notice that no project migrations are down migrated

feat: remove rollup migration preparation code

---

demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/DplanAuthenticator.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/LoginFormAuthenticator.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OsiHHAuthenticator.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OsiHHStaticAuthenticator.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OsiSHAuthenticator.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OsiSHStaticAuthenticator.php

The visibility of `getCredentials` may be tightened, as it is only used within class context
code review should be best, phpstan can help

chore: reduce authenticator method visibility

---

demosplan/DemosPlanCoreBundle/Resources/config/services.yml

Ticket:
https://yaits.demos-deutschland.de/T32200
Description:
avoid null for parameter client in FileService when injecting the fileServiceInterface.

feature (refs T32200): avoid null for parameter

---

package.json

Specific version is not needed anymore.

Remove specific version for demosplan-ui

---

demosplan/DemosPlanCoreBundle/Addon/AddonRoutingLoader.php

`pwd` might be different depending on how the code is triggered. This PR makes this a bit more robust
Code review or try to call a addon route in browser directly after cache clear

chore: fix addon route path as it may be called differently

---

demosplan/DemosPlanCoreBundle/Logic/Export/DocxExporter.php
demosplan/DemosPlanCoreBundle/Twig/Extension/ProcedureExtension.php
templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/export.tex.twig
templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/export_anonymous.tex.twig
templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/export_condensed.tex.twig
templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/export_condensed_anonymous.tex.twig
templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/export_fragments_anonymous.tex.twig
templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/export_original.tex.twig

**Ticket:** https://yaits.demos-deutschland.de/T28477
Description: 
In the pdf and the doc export, the procedure name is incorrect displayed. Twigs filters are added to display it correctly in the pdf export. 
For the docx export, the quotes conversion while retrieving procedure name is disabled. The htmlspecialchars method has now ENT_NOQUOTES as flag parameter which prevent to encode quotes

F T28477 incorrect display of the title when exporting statements

---

composer.json
composer.lock

Description: 
- not all adjustements made in demosplan are compatible with this branch that's why the dependency version has to be specified
- adjust composer.lock

F adjust dependency version

---

demosplan/DemosPlanCoreBundle/Resources/config/services.yml

**Ticket:** https://yaits.demos-deutschland.de/T32606
This error raises after some changes for a fix in an addon: there are no class that implements DemosEurope\DemosplanAddon\Contracts\ResourceType\UserResourceTypeInterface
In the code this UserResourceTypeInterface is already implemented by the UserResourceType.
I'm not sure with this, but I hope the adjustment in the services.yml to map UserResourceTypeInterface with UserResourceType fixes this error.
code review

feat (refs T32606): Adjust services.yml for UserResourceTypeInterface

---

demosplan/DemosPlanCoreBundle/Logic/Statement/ElasticSearchService.php

When elasticsearch is in an ivalid state count of null triggered an php error
code review might be best. Otherwise stop eleasticsearch and call a procedure

chore: avoid error when elasticsearch has some issues

---

client/js/components/procedure/DpSimplifiedNewStatementForm.vue
client/js/components/procedure/imageAnnotator/DpConvertAnnotatedPdf.vue

https://yaits.demos-deutschland.de/T32601
This PR is part of EWM 3.1
- The simplified new statement form component was updated in an addon and must be synced here with the state.
This is mainly intended to reduce the maintenance efforts because the simplified statement form had to be duplicated in addons
- The `values.submitter.date` prop will be passed from data to FE if existant (correct box recognition setup) hence we can use this value to automatically fill in the form field value when confirming the pdf import

feat(refs T32601): automatically use dates in pdf import confirmation view

---

client/fe/config/config.js

**Ticket:** https://yaits.demos-deutschland.de/T32785
The components for this css were moved to an addon, but the styles are still in core and need to be loaded. Safelist.deep includes the selector's children.
Split a statement and see if the styles were loaded.

bug(refs T32785): Add css selector to savelist

---

config/services.yml
config/services_autowire.yml

**Ticket:** https://yaits.demos-deutschland.de/T32606
Description: resrouce types interfaces have to be set public

fix T32606 resrouce types interfaces have to be set public

---

demosplan/DemosPlanCoreBundle/EventSubscriber/TusUploadEventSubscriber.php

**Ticket:** https://yaits.demos-deutschland.de/T32858
In order to avoid dangling file data is prevented renaming, simply allow overwriting.
Test to upload a csv, especially the one described in the ticket.

fix (refs T32858): Allow overwriting filenames on tus upload

---

demosplan/DemosPlanCoreBundle/Resources/config/packages/monolog.yaml
demosplan/DemosPlanCoreBundle/Resources/config/parameters_default.yml

**Ticket:** https://yaits.demos-deutschland.de/T32438
The number of logfiles to keep before they are deleted should be configurable on server basis.
code review is best

chore: make the number of logfiles to keep configurable

---

config.webpack.js
templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base_oeb.html.twig

Before, the getBundleAndRelatedChunkSplits always returned two entrypoins (css.css and publiccss.css) when being asked for css.css only. that led to those styles being included twice. The reason was that strpos('css.css', 'publiccss.css') returns true... well.
After running `yarn dev:<project>` and then navigating into the planning area of demosPlan, the styles should not only look good (as they always do), but there should be only one css file included in the html.

Use distinct filenames for css entry points

---

demosplan/DemosPlanCoreBundle/Logic/Maps/GetCapabilitesRpcMethodSolver.php

**Ticket:** https://yaits.demos-deutschland.de/T32871
Description: The rpc-map-get-capbilities-schema.json path was wrong und had to be adjusted

F T32871 new map layer cannot be created

---

client/js/components/map/map/DpOlMap.vue

**Ticket:** https://yaits.demos-deutschland.de/T32940
- if you click to fullscreen the chosen scale view shall be shown in fullscreen
- the bug is that it shows always the full map content in fullscreen
- remove the function here, which contains a force of a recalculation of the map viewport, 
- so that the fullscreen view cannot be forced to show another view than the chosen view when fullscreen is not clicked

Fix(refs:32940): incorrect view by fullscreen

---

demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/DplanAuthenticator.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/LoginFormAuthenticator.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/WeakPasswordCheckerBadge.php
demosplan/DemosPlanCoreBundle/Security/HTTP/EventListener/WeakPasswordCheckerEventListener.php

**Ticket:** https://yaits.demos-deutschland.de/T32782
Check password only when authentication is valid. Otherwise a notification may be shown even on invalid password. The password is now validated by using symfonys UserBadge system.
Code review or try to login with existing user but invalid, too short password like `wer` 

feat (refs T32782): simplify WeakPassword check

---

demosplan/DemosPlanCoreBundle/Permissions/PermissionResolver.php

**Ticket:** https://yaits.demos-deutschland.de/T32934
Checking permissions of addons, creates a huge amount of php requests which leads to very low performance.
This logic can modified to directly request via sql and combine these into a few requests.
Get to the list of Statements. This should be take less than two seconds.

fix (refs T32934): Improve performance on check permissions

---

client/js/components/map/map/DpOlMapScaleSelect.vue

https://yaits.demos-deutschland.de/T32938
- This is a refactoring of this component combined with a bugfix.
- The dropdown didn't show the map's current scale when a map with another scale has been opened before
- To solve this the current scale value will not be set after zooming in or out of the map but when a map has been openend and the data of the current view is finished loading. This means everytime we zoom in or out or even just open the map in the sidemenu, the current scale will be evaluated by using the `loadend` OL event
-> Naivagate to statement details -> open map component and make sure the correct scale is visible in the dropdown -> open another map and make also the the scale updates (if needed)

bug(refs T32938): fix dropdown does not show correct value

---

client/js/components/statement/publicStatementModal/StatementModal.vue

**Ticket:** https://yaits.demos-deutschland.de/T30969
As MultistepNav was renamed to DpMultistepNav in demosplan-ui, we need to rename it here, too
Needs to be merged first:
https://github.com/demos-europe/demosplan-ui/pull/248

refactor: rename MultistepNav

---

demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/06/Version20230601095828.php

**Ticket:** https://yaits.demos-deutschland.de/T32934
The sql query to fetch statements was not able to use an database index, which lead to degraded performance
call a page with 100 Statements

feat (refs T32934): Improve performance on Assessment Table by adding database index

---

package.json

Set required node engine to 16 since this is the lowest Version for some dependencies

chore: Bump required node engine

---

demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/DplanAuthenticator.php
demosplan/DemosPlanUserBundle/Logic/UserMapperDataportGatewayHH.php

**Ticket:** https://yaits.demos-deutschland.de/T32954
User object of the second user should not be saved in session as it leads to excessively large database entries.
Login as a simulated osi fhhnet toeb and planner user and switch orgas. You should not be logged out

feat (refs T32954): Do not save user object in session

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_link.scss

Without this fix, in bobhh the :hover declaration of the base link took precedence, coloring the hovered link blue.

fix: also define color for hover state

---

client/js/components/document/DpMapSettingsPreview.vue
client/js/components/map/map/DpOlMapLayer.vue
templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/elements_admin_list.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T32104
Map attribution should also be shown in the map settings overview map.

feat(refs T32104): show attribution in map overview

---

demosplan/DemosPlanCoreBundle/Logic/Export/DocxExporter.php
demosplan/DemosPlanCoreBundle/Logic/Export/PhpWordConfigurator.php
demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php

**Ticket:** https://yaits.demos-deutschland.de/T31218
This consolidates the language settings to be used on more PhpWord
instances throughout the codebase. In addition, documents are
generated with a clean proof read and grammar state to improve
loading performance in MS Word.

Fix Language for PhpWord generated Docx exports

---

demosplan/DemosPlanCoreBundle/Application/DemosPlanKernel.php

**Ticket:** https://yaits.demos-deutschland.de/T27388
RouteCollectionBuilder was deprecated in favor of RoutingConfigurator
Call any route, one deprecation should be gone

chore: update deprecated RouteCollectionBuilder

---

client/js/components/procedure/DpSimplifiedNewStatementForm.vue

https://yaits.demos-deutschland.de/T33015
- Since I forgot that the datepicker only accepts the format 'DD.MM.YYYY', the implementation of passing the correct value format was missing and added now.

bug(refs T33015): check if authored date is valid when converting pdfs

---

client/js/components/map/map/DpOlMapLayer.vue
client/js/components/map/publicdetail/Map.vue
demosplan/DemosPlanCoreBundle/Logic/Map/MapService.php
templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_public_participation.html.twig
translations/messages+intl-icu.de.yml

**Ticket:** https://yaits.demos-deutschland.de/T33162
Change the placeholfer for the current year from {year} to {currentYear}. It's more meaningful and {currentYear} is already used in the database, which also causes the error that {currentYear} was not replaced because the modified code assumed {year}.
code review
check the web interface of diplanbau, it should now show 2023 instead of {currentYear} in the copyright of maps.

feat (refs T33162): fix year replacement of copyright

---

docker/php8.1-cli-development/zshenv

Debugging via cli `php-xdebug` does not work any more out of the box but needs a specific PHP_IDE_CONFIG env var
try to debug via console

chore: add missing env var to allow cli debugging

---

composer.json

phpcompatibility/php-compatibility was introduced as a test and is not really needed. I would prefer to lower the amount of vendors and remove this dependency until we really need it

chore: remove vendor that is not needed

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_tabs.scss

the active/hover styles were overridden in diplanbau in such a way that there was no chance spotting the currently active tab. also, pointer.
in the export modal of the "classic" assessment table, the tabs for docx / pdf should clearly indicate active state.

fix: tweak export tab colors

---

client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaAttachments.vue

**Ticket:** https://yaits.demos-deutschland.de/T33031
If the statement is not editable we don't need to show the component for upload, but only the attachments already uploaded.
Couple a procedure and transfer a statement to VHT. On the detail site, you shouldn't see the upload files function, but only the attachments already uploaded.

bug(refs T33031): Hide upload files when editable is false

---

demosplan/DemosPlanCoreBundle/Logic/Statement/DraftStatementService.php

Ticket:
https://yaits.demos-deutschland.de/T32342
Description:
Resets the rejected flag on draft-statements when submitting them.
Also deletes a potential rejectedReason.
login as a 'Institutions-Sachbearbeitung' choose any procedure and create a new statement. Hand in this statement.
login as the 'Institutions-Koordination' corresponding to the prior chosen 'Institutions-Sachbearbeitung' (same organisation)
choose the procedure where you handed in the statement and go to 
'Stellungnahmen zum Verfahren' -> 'freigaben der Organisation' 
and reject the statement you just handed in.
login as a 'Institutions-Sachbearbeitung' choose same procedure and go to
'Stellungnahmen zum Verfahren' -> 'Meine Entwürfe' and hand in the rejected statement again.
login as the 'Institutions-Koordination' …

feature (refs T32342): delete rejected flag&Reason when submitting draftStatement(s)

---

client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_segmentlist.scss

This corrects some margin-top in fullscreen mode, as well as a strangely misplaced icon.
in ewm, go to the "Erwiderungen verfassen"-view of a statemet  that already has segments.
- the button which opens the edit mode should be not padded strangely. it should look this way:
- proceed to fullscreen mode. there should not be any margin-top above the light blue area

F remove fs margin

---

demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanAssessmentController.php

**Ticket:** https://yaits.demos-deutschland.de/T31372
Goto `statement/new/manual/<procedure-id>` and create a new manual statement. You should now see a confirm-message

fix(refs T31372): Add Missing Confirmmassge when creating a manual STN

---

templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_entry.tex.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/statement_macros.tex.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry.tex.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry_paragraph.tex.twig

**Ticket:** https://yaits.demos-deutschland.de/T33172
In verwalten > Abwägungstabelle > STN wählen mit Einzeichnungen > PDF-Export (Hoch- oder Querformat) and Public Detail > Stellungnahmen zum Verfahren > Entwurfsordner etc > STN wählen mit Einzeichnungen > Download als PDF the {currentYear} placeholder will not be replaced by a year value like 2023. 
The changes in the twig files should fix this. I'm not sure about the list_export_entry.text.twig. I don't know where it is used. But nothing is replaced there either.
You could export statements with drawings (Einzeichnungen). On dev the procedure (Test_Export) holds already some statements with drawings. For verwalten > Abwägungstabelle > STN wählen mit Einzeichnungen > PDF-Export (Hoch- oder Querformat) I used the role …

fix (refs T33172): Replace '{currentYear}' with an actual value. (PDF export)

---

demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php

**Ticket:** https://yaits.demos-deutschland.de/T33109
Flush similar statement submitter on create a new statement, to ensure added submitters, will be stored in DB.

fix (refs T33109): Fix adding of similar statement submitters

---

client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_segmentlist.scss
yarn.lock

**Ticket:** https://yaits.demos-deutschland.de/T33153
To get rid of the bug, the version of demosplan-ui which contains the fix (0.1.4) must be used.
As this version also contains a change that depends on [other core changes, these changes](https://github.com/demos-europe/demosplan-core/pull/1436) are cherrypicked here, too.
And "while we're at it", a [nifty little styling fix](https://github.com/demos-europe/demosplan-core/pull/1507) is cherrypicked as well.
`yarn install`, `yarn ewm:dev`, watch it.

Bump demosplan-ui plus some cherrypicks

---

client/js/components/procedure/SegmentsList/SegmentsList.vue
client/js/components/procedure/StatementSegmentsList/StatementSegment.vue

**Ticket:** https://yaits.demos-deutschland.de/T33256
In the segments-list and the "erwiderungen-Ansicht" the Layout should stay as expected even if the content of the segment has looong words.

fix/refs T33256): Break segments overflow

---

client/js/InitVue.js
client/js/VueConfigLocal.js

**Ticket:** https://yaits.demos-deutschland.de/T32012 
For some reason we initiallized vuex a couple of times.
In the End we don't have to init it at all because the vuex-json-api-lib does it for us.
In vue3 initializing it more than once throws an error. That didn't happen in vue2

chore(refs T32012): Remove unnecessary Use of vuex

---

demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php

If the entity is a segment, it now uses the submit date from the parent statement and not its own date.
**THIS IS A RECREATION OF #1491**

fix (refs T33142): uses parent statement submit date

---

client/js/components/statement/publicStatementModal/StatementModal.vue

For some reasons, the good old wy to check against OK doesn't work on one instance. checking against 200 is better anyway

fix: Change check for response status

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig

Twig block base_side is not used any more, therefore it can be deleted
search for block base_side

chore: remove unused twig block

---

client/fe/config/config.js
client/fe/webpack/moduleRules.js
config.webpack.js
demosplan/DemosPlanCoreBundle/Resources/client/scss/_settings-color.dplan.scss
demosplan/DemosPlanCoreBundle/Resources/client/scss/core_style.scss
package.json
templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base_oeb.html.twig
yarn.lock

**Ticket:** https://yaits.demos-deutschland.de/T27594
This PR includes tailwind within demosplan. 
To test it, just run `yarn install`, followed by a `yarn dev:<project>`.
| build | time |
| --- | --- |
| no postcss-loader | 16s |
| with postcss-loader <- this was the status quo | 19s |
| no postcss-loader, with demosplan-ui | 26s |
| with postcss-loader, with demosplan-ui | 43s |
| with postcss-loader, with demosplan-ui, skip 3rd party css | 30s |
| **with postcss-loader, with demosplan-ui, skip 3rd party css, add sass-embedded** | **21s** |
So, at the moment this adds 2 seconds to the build.
- https://github.com/demos-europe/demosplan-ui/pull/294

Change config to use tailwind

---

composer.json
composer.lock

We want to use a distinct version of the addon contracts to be safe about the code used.
run `composer update demos-europe/demosplan-addon` and be sure that v0.1 is installed
https://github.com/demos-europe/demosplan-documentation/pull/34

chore: use distinct addon contract version

---

composer.json
composer.lock

lcobucci/clock was upgraded to a version that is not compatible with php 8.1 any more
run composer install on a machine that has php 8.1

chore: downgrade incompatible library

---

client/js/components/procedure/AdministrationImport/AdministrationImport.vue
demosplan/DemosPlanCoreBundle/Addon/FrontendAssetProvider.php

**Ticket:** https://yaits.demos-deutschland.de/33234
The addon hook configurations do not yet provide permission information. If we were to evaluate those, we should filter the scripts in the RPC method instead of loading all scripts on the users' machine and evaluating on the client side.
In addition, previously no import tabs would have been loadable from addons at all if the excel import were disabled.
Yes, I know this PR adds a TODO. Please be gentle with me. I created a [matching Ticket](https://yaits.demos-deutschland.de/T33332).

fix(refs T33234): Remove incorrect late permission evaluation

---

demosplan/DemosPlanCoreBundle/EventSubscriber/TrustedProxiesSubscriber.php

**Ticket:** https://yaits.demos-deutschland.de/T27388
Request::HEADER_X_FORWARDED_ALL has been deprecated and needs to be replaced by the single constants it merged so far
code review

chore (refs T27388): upgrade request header deprecation

---

demosplan/DemosPlanCoreBundle/Logic/DefaultTwigVariablesService.php
demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
demosplan/DemosPlanCoreBundle/Permissions/ResolvablePermissionCollection.php

**Ticket:** https://yaits.demos-deutschland.de/T33234
Addon permissions are not configured in the classic array way the core permissions are evaluated in. Thus, all addon permissions, while having been marked as exposed, were dropped when building the frontend permission list.
This change is only a rudimentary solution to exposing the addon permissions as the correct way would be to redo the permission checking in the frontend to include addon names and eventually use something more akin to hasPermission(name, context) with the context being core or an addon name

feat(refs T33234): Add rudimentary support for exposing addon permissions

---

demosplan/DemosPlanCoreBundle/Logic/DefaultTwigVariablesService.php
demosplan/DemosPlanCoreBundle/Permissions/PermissionResolver.php

**Ticket:** https://yaits.demos-deutschland.de/T33234
We cannot evaluate the permissions via the db without an existing user and need to revert to evaluating directly with edt

fix: Allow complete permission evaluation without valid user

---

config/permissions.yml
tests/backend/core/Core/Unit/Logic/PermissionsTest.php

Description: 
remove the permission 'feature_export_statement_with_datasheet': this permission ist not used and the datasheets related logic is already moved from core, it will be used as an addon in the relevant projects.

fix remove unused permission

---

client/js/components/map/map/DpOlMapEditFeature.vue

**Ticket:** https://yaits.demos-deutschland.de/T33391
- Return empty string instead of null if we don't need any tooltip classes, because otherwise v-tooltip gets internal errors
- Return 1 for z-index if all elements have z-index auto and stop recursion if outer element is reached (html)
Go to Verfahren -> Planungsdokument und Planzeichnung -> Verfahren verorten. The tooltip for the edit map features (eg Auswählen und bearbeiten) should work (switch between the different tooltips) and there should be no warnings or errors in the console.

bug(refs T33391): Fix z-index for tooltip

---

yarn.lock

v0.1.6 contains some utility class changes that are needed to un-break things.
Things should just work as before, but the search ui above the login list should not look broken anymore.

Bump demosplan-ui to v0.1.6

---

demosplan/DemosPlanCoreBundle/Repository/ProcedureRepository.php

Ticket: https://yaits.demos-deutschland.de/T33424
Request keys are always set with value null which leads to an user set that is unnecessary. Moreover it lead to weird exceptions on one (and only one) environment. This way it is cleaner anyhow.
Save procedure phases in procedure detail settings

chore (refs T33424): avoid unnecessary user set

---

demosplan/DemosPlanCoreBundle/Logic/OzgKeycloakUserDataMapper.php

**Ticket:** https://yaits.demos-deutschland.de/T33375
Citizen role needs to be renamed in keycloak as the / otherwise infers with the role extraction logic
code review might be easiest

fix (refs T33375): Login as citizen via keycloak

---

demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/06/Version20230601095828.php

When performing the migration on a just created database the index already exists. Obviously there are other cases as well, where the migration fails due to already existing constraint. We need to check the existence before creating it.
This PR alters an existing migration as it already leads to problems on multiple environments.
You may manually delete the Migration Version20230601095828.php from the migrations database and perform migrations

chore: only try to add constraint when it does not exist

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T33457
**Description:** After enabling Tailwind in demosplan-core and refactoring our handcrafted utility classes, the `cf` class was replaced with the `flow-root` class, which does not function correctly in this context. However, it looks like everything is working fine without these two classes. So, the flow-root class was removed.
Verwalten > Grundeinstellungen > Einstellung einklappen

Fix:(T33457): permanently expanded basic settings

---

client/js/components/faq/DpFaqItem.vue
client/js/components/procedure/AdministrationImport/AdministrationImport.vue
client/js/components/procedure/SegmentsList/SegmentsList.vue
client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
client/js/components/statement/assessmentTable/AssignEntityModal.vue
client/js/components/statement/assessmentTable/ConsolidateModal.vue
client/js/components/statement/assessmentTable/DpBulkEditFragment.vue
client/js/components/statement/assessmentTable/DpBulkEditStatement.vue
client/js/components/statement/statement/SelectStatementCluster.vue
client/js/components/user/DpUserList/DpUserFormFields.vue
composer.lock
demosplan/DemosPlanCoreBundle/Addon/FrontendAssetProvider.php
demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
demosplan/DemosPlanCoreBundle/Logic/DefaultTwigVariablesService.php
demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php
demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php
demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
demosplan/DemosPlanCoreBundle/Permissions/PermissionResolver.php
demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
demosplan/DemosPlanCoreBundle/Permissions/ResolvablePermissionCollection.php
translations/messages+intl-icu.de.yml
yarn.lock

Squashed commit of the following:
commit f5d366ebc8b3a1f1e5311d758da5c3c49fea1fae
Author: graupnerdemos <graupner@demos-deutschland.de>
Date:   Mon Jun 19 17:51:16 2023 +0200
fix: Allow complete permission evaluation without valid user (#1565)
We cannot evaluate the permissions via the db without an existing user
and need to revert to evaluating directly with edt
commit 8b948b3a2a3d0453c130a0cba5955d7f90e3d4e7
Author: graupnerdemos <graupner@demos-deutschland.de>
Date:   Mon Jun 19 16:33:21 2023 +0200
feat(refs T33234): Add rudimentary support for exposing addon permissions (#1564)
Addon permissions are not configured in the classic array way the core permissions
are evaluated in. Thus, all addon permissions, while having been marked as exposed,
were dropped when building the frontend …

chore: Backmerge of release_ewm_3.0

---

yarn.lock

**Ticket:** https://yaits.demos-deutschland.de/T33500
After merging back an old release, the version of demosplan-ui went to 0.1.4 which does not yet have tailwind.
yarn install, yarn dev:<project>, everything should be fine.

fix(refs T33500): bump demosplan-ui to latest version

---

client/js/lib/procedure/charts/BarPieChart.js

**Ticket:** https://yaits.demos-deutschland.de/T33506
Due to a refactoring in the backend, the statementStatusData json contains elements without all needed properties. To quickfix the issue, those items are filtered out. However, it seems like this needs further investigation.
The procedure dashboard should show some charts.

fix(refs T33506): filter out errorous items

---

client/js/lib/procedure/DPWizard.js
demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_wizard.scss

As the tailwind display classes are configured to use !important, the jQuery show() method is now overruled by them. To keep the fix local, the show() and hide() functions were substituted with custom functions which apply the !important.
The wizard (in "Grundeinstellungen" of a procedure) should show up and work "as intended".

Use higher specificity for showing elements within wizard

---

composer.lock

to avoid composer inconsistencies:
`Problem 1
- lcobucci/clock is locked to version 3.1.0 and an update of this package was not requested.
- lcobucci/clock 3.1.0 requires php ~8.2.0 -> your php version (8.1.12) does not satisfy that requirement.
Problem 2
- lcobucci/clock 3.1.0 requires php ~8.2.0 -> your php version (8.1.12) does not satisfy that requirement.
- lexik/jwt-authentication-bundle v2.19.0 requires lcobucci/clock ^1.2|^2.0|^3.0 -> satisfiable by lcobucci/clock[3.1.0].
- lexik/jwt-authentication-bundle is locked to version v2.19.0 and an update of this package was not requested.`
Without this change there should be an error while trying to run `composer i` on `main`. With it, there should not be.

chore: updates lcobucci dependency

---

templates/bundles/DemosPlanCoreBundle/DemosPlanCore/error.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanNews/public_newsdetail.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T33542
**Description:**  This PR adds a webpack entry point to the public news detail and error pages.

Fix(T33542): missing user menu

---

client/js/components/core/DpEditor/libs/handleWordPaste.js

**Ticket:** https://yaits.demos-deutschland.de/T33353
This has been already fixed in the new demosplan-ui dependency. But as that is not yet really included in this older branch, we add the fix like this to the core.

fix (refs: T33353): adds fix to core

---

composer.json

We need to set platform requirements to ensure that vendor dependencies remain compatible with php 8.1 even when composer update is performed on a php 8.2 machine. Otherwise problems like #1617 will occur.

chore: fix platform requirements syntax

---

client/js/components/map/admin/LayerSettings.vue

**Ticket:** https://yaits.demos-deutschland.de/T33451
**Description:** This PR adds a method called `findProjectionInOptions` which checks if options contain the current projection. The previous check was always false because it attempted to check a value in the array of objects and the projection has consistently been set to EPSG:25832.

Fix(T33451): issue with the projection being set to EPSG:25832

---

demosplan/DemosPlanCoreBundle/Logic/ZipExportService.php

**Ticket:** https://yaits.demos-deutschland.de/T33554
Description: ZipExportService should return void, but return int.
just check it in browser

feature (refs T33554): fix procedure export

---

client/js/components/map/publicdetail/controls/legendList/DpLayerLegend.vue
client/js/components/procedure/AdministrationImport/ExcelImport/ExcelImport.vue
client/js/components/procedure/AdministrationImport/StatementPdfImport/StatementPdfImport.vue
client/js/components/procedure/DpSimplifiedNewStatementForm.vue
client/js/components/procedure/SegmentsList/SegmentsList.vue
client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaAttachments.vue
client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaAttachmentsLink.vue
client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
client/js/components/statement/fragmentList/Fragment.vue
client/js/components/statement/listStatements/ListStatements.vue
client/js/components/statement/originalStatementsTable/OriginalStatementsTableItem.vue
client/js/components/statement/publicStatementLists/DpPublicStatement.vue
client/js/components/statement/publicStatementModal/StatementModal.vue
demosplan/DemosPlanCoreBundle/Controller/Platform/FileController.php
demosplan/DemosPlanDocumentBundle/Tools/ServiceImporter.php
templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/includes/single_document_file_upload.html.twig
templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/paragraph_admin_edit.html.twig
templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/paragraph_admin_new.html.twig
templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/single_document_admin_new.html.twig
templates/bundles/DemosPlanMapBundle/DemosPlanMap/map_public_participation_detail.html.twig
templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/public_detail_form_statement.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T30158
Description:  
- use fileProcedureAction instead fileAction to access files.
- add bool parameters 'strictCheck' which define if a procedureId is available and has to be checked if true ( here is fileProcedureAction used ) or not if false ( here is fileAction used ).
- adjust route name in twigs and add procedure Id for routing

fix (ref:T30158) Define Statements files accessibility 

---

templates/bundles/DemosPlanCoreBundle/DemosPlanUser/orga_data_entry.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T33576
If users click on the input label, at least the input should be focused - this way they won't experience it as a bug if the cursor turns to a pointer when hovering labels.
As a planner org, go to "Daten der Organisation". When clicking the Label for the orga slug, the respective input field should be focused.

fix(refs T33576): use correct id

---

demosplan/DemosPlanCoreBundle/DoctrineMigrations/migration.tpl

Check of the database platform via getName() is deprecated. 
code review or create a new migration and check the deprecations

chore: fix deprecation in migration template

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_toggle.scss

**Ticket:** https://yaits.demos-deutschland.de/T33575
**Description:** This PR fixes an issue with the table when a row is expanded.
After some refactoring an `!important` declaration was added to the `display:block` property in the `is-active `and `is-visible` classes, which causes an issue when `is-active` is added to the `table-row`, because it has higher priority. 
it was necessary to add also the `!important` declaration to the '.table-row' class to fix the bug.

fix(T33575): issue with the table when a row is expanded

---

client/js/components/core/DpEditor/libs/handleWordPaste.js

**Ticket:** https://yaits.demos-deutschland.de/T33353
For some reason, the way it works atm on main doesn't worked here (#1628). So we had to adjust the fix a bit.
Paste Text from Word (not office365) into some editor (e.g. "Textbausteine Anlegen"). All blank spaces should be preserved.
As a Dev, this can't be tested, only reviewed since there is no real word on linux.

fix(refs T33353): Change way of replacing \n\r with blanks

---

demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OzgKeycloakAuthenticator.php

**Ticket:** https://yaits.demos-deutschland.de/T33621
SecurityUser needs to be used in Authentication, otherwise, the `User` will be persisted in the session which may be too big to be stored in the default Blob column size
code review might be best as you need to login via keycloak

chore (refs T33621): use SecurityUser in Authentication

---

demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php

**Ticket:** https://yaits.demos-deutschland.de/T33506
(Related Ticket: https://yaits.demos-deutschland.de/T32108)
Fix statement status data by adding missing necessary 'freq' key.
Also only add only $aggregations['status'] which is useful for the User, defined in form_options.yml
I do not understand, where some key-value-pairs are came from. like '1' : '1' or '0' : '0' for example.
I just filter these, but actually I would prefer to understand where and why they come from. Is there a deeper problem with ES or something?

fix (refs T33506): Fix statement status data by adding missing necessary 'freq' key.

---

demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementController.php
demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserAuthenticationController.php

Rector somehow did not recognize some routes in 87fb6a68. These are restored here. I revised any changes of the commit and restored what was deleted.
manual code review might be best, you may also want to compare the changes in the controllers

chore: restore routes that where swallowed by refactoring

---

demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/07/Version20230706091408.php

**Ticket:** https://yaits.demos-deutschland.de/T32796
Set Migration for ProcedureMessage Table in relation with XBeteiligung's Entity
check Migration File or run it
- {PR-number1} (https://github.com/demos-europe/demosplan-addon-xbeteiligung-async/pull/2)

feature (refs T32796): create Migration for procedureMessage Table

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_map.scss

This PR fixes the 2px jump of the "Geltungsbereich" and "Planzeichnung" buttons.
.btn assigns `border: 1px solid transparent;`, so if the `border` shorthand specifies the color only, this actually means `border: none $dp-color-highlight initial;`, at least to my understanding.
Buttons should have consistent sizing when activated and deactivated.

Prevent 2px jump of button

---

client/js/components/map/admin/LayerSettings.vue
yarn.lock

**Ticket:** https://yaits.demos-deutschland.de/T33640
To avoid fetching the getCapabilities while typing in url field. We have to wait until the input is done, so the chance that there is a valid url is more likely.
This change only works with  demosplan-ui@0.1.8  or higher, that including the "@bubble"-event in dpInput
(see changes in yarn.lock)
as FPA go to `/verfahren/<procedure-id>/verwalten/gislayer/neu`.
start typing a URL in the url-Field. You should not get Errors while typing
- Other PR1 https://github.com/demos-europe/demosplan-ui/pull/356

fix(refs T33640): update getcapabilities-url @blur, not @input

---

demosplan/DemosPlanCoreBundle/Security/HTTP/EventListener/WeakPasswordCheckerEventListener.php

Ticket:
https://yaits.demos-deutschland.de/T32782
Description:
The CheckPassportEvent has many different listeners which do not belong to our Code.
They use priorities from 2000 down to 0. On login failure an Exception is thrown preventing further events being triggered.
Our own listener needs to be called last - only after successful login - to check for weak passwords - so a negative priority was added.
try to log in with an existing user and a wrong pw... check the flashbag messages.

feature (refs T32782): check for weak passwords only after succesful login

---

demosplan/DemosPlanCoreBundle/Logic/Statement/DraftStatementService.php

Ticket:
https://yaits.demos-deutschland.de/T32960
Description:
Also create a draftStatementVersion of the original draftStatement 
when updating the draftStatement the first time 
in order to show the original data to the author as well - when looking at the versions.
slack question: https://demosdeutschland.slack.com/archives/C04122AUGE7/p1688720607061929
write a draft statement somewhere and navigate to 'your drafts' -> edit the statement and check the versions of it.

feature (refs T32960): Also create a version of the original draftSTN on first update

---

demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php

I removed two unused properties from the StatementService.
Check if the properties are still used

feat: Remove unused properties in StatementService.php

---

config/packages/security.yaml

In the context of pre login check for testusers `User` objects are used instead of `SecurityUser` objects. We need to automatically update their passwords in order to be able to change testuser passwords to something known.
Code review or set `alternative_login_testuser_defaultpass` to something new, update a user's password with the md5 hash of it, clear the cache and visit the login page. The user should appear in the login list

chore: upgrade passwords during test login

---

demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/07/Version20230706091408.php
demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/07/Version20230711125038.php

**Ticket:** https://yaits.demos-deutschland.de/T32796
Set Migration for ProcedureMessage Table in relation with XBeteiligung's Entity
check Migration File or run it
- {PR-number1} (https://github.com/demos-europe/demosplan-addon-xbeteiligung-async/pull/2)

feature (refs T32796): remove procedure from procedure_message table

---

composer.lock

Ticket:
https://yaits.demos-deutschland.de/T32776
Description:
updates the composer.lock to get the newest version 0.5 of demosplan-addon

feature (refs T32776): update composer.lock

---

demosplan/DemosPlanCoreBundle/Entity/User/User.php

Fix a leftover that was introduced by automatically converting the constraints to php assertions. It lead to duplicate validation of a field and ultimately blocked login via keycloak
code review or try to login via keycloak locally

chore: fix leftover from rector that leads to duplicate validation

---

demosplan/DemosPlanCoreBundle/Logic/ApiRequest/ResourceType/DeletableDqlResourceTypeInterface.php
demosplan/DemosPlanCoreBundle/Logic/JsonApiActionService.php
demosplan/DemosPlanCoreBundle/ResourceTypes/GlobalNewsResourceType.php
demosplan/DemosPlanCoreBundle/ResourceTypes/InstitutionTagResourceType.php
demosplan/DemosPlanCoreBundle/ResourceTypes/PlanningDocumentCategoryResourceType.php
demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureNewsResourceType.php
demosplan/DemosPlanCoreBundle/ResourceTypes/SignLanguageOverviewVideoResourceType.php
demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php

So far to handle JSON:API deletion requests it was required to check permissions inside the `delete` method manually. This however is error-prone, as the necessity is not explicit enough and was in fact already forgotten in `ProcedureNews-` and `SignLanguageOverviewVideo` resource types.
This commit adds a new method
(`getRequiredDeletionPermissions`) that must be implemented by deletable resource types, making the need to define the needed permissions more explicit.
The new method was used in the `ProcedureNews`- and `SignLanguageOverviewVideo` resource types to check for editing permissions, which should be sufficient for their use-cases.
The usage of the new `getRequiredDeletionPermissions` method was added in a way, that prevents the
`BeforeResourceDeletionEvent` event from being …

fix: add missing JSON:API deletion permission check

---

client/js/components/statement/assessmentTable/DetailView/DetailView.vue

**Ticket:** https://yaits.demos-deutschland.de/T33720
**Description:**  The missing import of DpBoilerPlateModal has been added to the DetailView component.

Fix(T33720): missing import of DpBoilerPlateModal

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_edit-field.scss

This restores a correct spacing between the select element and the save/abort controls.

fix: adapt padding to larger select spacing

---

client/js/components/procedure/publicindex/DpSearchProcedureMap.vue
client/js/components/shared/NotifyContainer.vue

**Ticket:** https://yaits.demos-deutschland.de/T33134
**Description:** This PR adds an aria status role (role=”status”) for the better accessibility, as well as changes the default value of the `this.isVisible` variable to resolve a bug where the role was only visible after changing the tab

Fix(T33134): improve accessibility

---

demosplan/DemosPlanCoreBundle/Entity/User/SecurityUser.php
demosplan/DemosPlanCoreBundle/Logic/User/CurrentUserService.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/DplanAuthenticator.php

**Ticket:** https://yaits.demos-deutschland.de/T33737
The SecurityUser should only be used during login process. Afterward it should be swapped with the real user entity so that it could be used later on via injection of the TokenStorage
This is an alternative approach to #1740 to fix the root problem
Login should work as well as the problem described in ticket

chore refs (T33737): Real user object should be stored in Token

---

client/css/index.css
client/fe/webpack/moduleRules.js
config.webpack.js
package.json
stylelint.config.js
tailwind.config.js
yarn.lock

**Ticket:** https://yaits.demos-deutschland.de/T27593
To be able to make full use of all the cool [Tailwind 3 features](https://tailwindcss.com/blog/tailwindcss-v3), it is necessary to make Tailwind run in the demosplan build, instead of just purging a "complete" Tailwind Css file. There are two main reasons to do so:
1. There is no practical way of having Tailwind render all of its css. The possible combinations of [breakpoints, pseudo-elements, and pseudo-selectors](https://tailwindcss.com/docs/hover-focus-and-other-states) would lead to a filesize that is simply not manageable.
2. Purging a huge pile of Css is way slower than just letting Tailwind do its job on a chosen set of source files.
The Tailwind config requires the demosplan-ui Tailwind config and makes some necessary tweaks. …

Include Tailwind as postCss plugin

---

demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadProcedureData.php

**Ticket:** https://yaits.demos-deutschland.de/T33843
To avoid confusion and additional setup time, we add a simple base gisLayer to the master template via prod fixtures. In the future, this layer will be by default available in the master template and all inheriting templates and procedures.
I have not yet tested this with a new DB!

fix(refs T33843): add gisLayer to master template

---

client/js/components/procedure/admin/DpAddOrganisationList.vue
demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureAPIController.php
demosplan/DemosPlanCoreBundle/Logic/ApiRequest/ResourceLinkageFactory.php

**Ticket:** https://yaits.demos-deutschland.de/T33148
Adjust request structure to specification and fix use of ToManyResourceLinkage::createFromArray(), to allow 
add multiple agencies to one procedure in one request.

fix(refs T33148): Send Batch to add multiple Toeb to toeblist

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_tiptap.scss

**Ticket:** https://yaits.demos-deutschland.de/T33838
**Description:** This PR fixes the list style issue by adding specific styling for `o`l and `ul` tags.
(When the list-style property of the `ol` tag is set to the `initial` value, it displays rounded bullet points. Therefore, was necessary  to set it to the `decimal` value separately)

Fix(T33838): the list style issue 

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/_base.dplan.scss
demosplan/DemosPlanCoreBundle/Resources/client/scss/_settings-fonts.dplan.scss

In an effort to syncronize the styling of DiPlanBeteiligung and DiPlanPortal, this PR removes the ancient, global `letter-spacing` from demosplan-core. Legibility of the fonts that are used in active projects are not improved by this increased letter-spacing, so there is no reason to have it around.
Things just should look a little more sense, now.
- https://github.com/demos-europe/demosplan-project-teilhabe/pull/40

Remove ancient letter spacing

---

client/js/components/map/admin/LayerSettings.vue

**Ticket:** https://yaits.demos-deutschland.de/T33917
The lookup if the current projection is actually in the list of available projections happened before the available projections were properly filtered. Now it happens after, which should fix this bug after newly saving the gis layer.
Proper credit: I was just the hands while @salisdemos was directing me.
With a current database, you can try to reproduce the bug in the linked ticket with/without this fix. Otherwise a code review might be enough.

fix(refs T33917): fixes the lookup of available projections

---

demosplan/DemosPlanCoreBundle/EventListener/DemosPlanResponseListener.php
demosplan/DemosPlanCoreBundle/Logic/EntityContentChangeService.php
demosplan/DemosPlanCoreBundle/Logic/User/CurrentUserService.php
demosplan/DemosPlanCoreBundle/Repository/UserRepository.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/DplanAuthenticator.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OzgKeycloakAuthenticator.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/AiApiUserProvider.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/ApiUserProvider.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/SamlUserProvider.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/SecurityUserProvider.php
templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/public_paragraph_document.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_draft.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_released_group.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T33736
**Ticket:** https://yaits.demos-deutschland.de/T33711
Authentication is done with the special SecurityUser, not with the User
entity. One of the reasons is that the objects gets serialized
in the session between requests and the doctrine entity with all its dependencies
may be huge to serialize. Therefore, we use the special SecurityUser that has only
those properties that are needed for authorization. During the request it
is swapped by the User entity.
During this PR we discovered that the implementation of `supportsClass` need to return a boolean but returned a string, which eventually worked beforehand. Likewise, a sub request does not reliably provide the current user for `app.user` in twig, `currentUser` is always available.
Copy …

chore (refs T33736, T33711): Fix SecurityUser in session

---

demosplan/DemosPlanCoreBundle/Entity/User/SecurityUser.php

**Ticket:** https://yaits.demos-deutschland.de/T33711
**Ticket:** https://yaits.demos-deutschland.de/T33736
Salt is deprecated in symfony 5.4 but still used to compare whether user changed during login as a safety measure. As long as this feature is used by symfony we need to provide the salt, as older users might still have the salt field filled
After merging #1769 it occurred that some users could not login any more. These where the ones with a salt set. 
Set a salt to a user (like Walter West in test database) and try to login

fix (refs T33736, T33711): SecurityUser needs to provide real salt

---

config/parameters_default.yml
demosplan/DemosPlanCoreBundle/Logic/OzgKeycloakUserDataMapper.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OzgKeycloakAuthenticator.php
demosplan/DemosPlanCoreBundle/ValueObject/OzgKeycloakUserData.php

Keycloak group role string needs to be configurable to be able to grant different permissions to different projects.
Code review or add a new client to keycloak and try to grant different roles as in other client

chore: keycloak group role string needs to be configurable

---

templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement_detail_statement_data.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T34156
**Description:** This PR fixes an issue with the name in the AT (Abwägungstabelle) not being completely displayed.

Fix(T34156): name is not displayed completely (AT)

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_at.scss

**Ticket:** https://yaits.demos-deutschland.de/T34174
**Description:** This PR fixes the issue with lists and their numbering by adding styling for both `ul` and `ol` tags in the AT (Abwägungstabelle). The problem was that the initial value for `ol` did not work as expected, displaying bullets instead of numbers. As a solution, this PR sets the appropriate styling for each tag to resolve the numbering problem.

Fix(T34174): issue with lists and their numbering

---

demosplan/DemosPlanCoreBundle/Entity/User/AnonymousUser.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/ApiUserProvider.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/SecurityUserProvider.php

**Ticket:** https://yaits.demos-deutschland.de/T3419
The login field of the AnonymousUser was set to its user name which lead to confusion during the jwt authentication for not logged in users. The `SecurityUserProvider` searches for the login of a user and could not find anything if username is given
reproducer is given in ticket

chore (refs T34194): fix anonymous user login

---

demosplan/DemosPlanCoreBundle/Entity/User/AiApiUser.php
demosplan/DemosPlanCoreBundle/Entity/User/AnonymousUser.php
demosplan/DemosPlanCoreBundle/Entity/User/FunctionalUser.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/AiApiUserProvider.php

**Ticket:** https://yaits.demos-deutschland.de/T34139
`AiApiUser` needs to be attached to a database user as it is needed by doctrine actions. Moreover, addon permissions are checked directly via database and therefore a database user needs to exist anyhow
Along the way code duplication in FunctionalUsers is reduced and Addon interfaces used.
try to import a pdf

chore (refs T34139): fix connection to data services

---

client/js/components/statement/assessmentTable/DpSelectedItemsStatements.vue

**Ticket:** https://yaits.demos-deutschland.de/T34175
- the computed  `selectionContainsUnclaimedFragments` cannot be used in every project, only in projects where the permission `area_statements_fragment` is activated
- so the error said for this computed function:  `Reduce of empty array with no initial value`

Fix(refs:34175): docx export is empty

---

demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanCustomerController.php
templates/bundles/DemosPlanCoreBundle/DemosPlanUser/customer_settings.html.twig

By using Symfony's router to generate the url to be displayed as final imprint url we can be much more sure that the displayed url will be the one users would be expecting there.
**Ticket:** https://yaits.demos-deutschland.de/T34274

fix(refs T34274): Safely generate imprint route

---

yarn.lock

Description: To fix this [bug](https://yaits.demos-deutschland.de/T34111) need to upgrade demosplan-ui to the latest version, which is 0.1.11

upgrade demosplan-ui to the latest 0.1.11 version

---

yarn.lock

**Description:** It should remain ` "@demos-europe/demosplan-ui@^0"` instead of the specific version `"@demos-europe/demosplan-ui@^0.1.11"` in the **yarn.lock** file. It should be same as in the package.json file.

update yarl.lock file with the right version of the demosplan-ui

---

demosplan/DemosPlanCoreBundle/Permissions/Permissions.php

Ticket:
https://yaits.demos-deutschland.de/T34299
Description:
disable core permission 'field_statement_polygon' and restore previous behavior by adding this permission for each project.
Special cases:
https://github.com/demos-europe/demosplan-project-teilhabe/pull/42
https://github.com/demos-europe/demosplan-project-ewm/pull/81
Normal replicas:
https://github.com/demos-europe/demosplan-project-bimschgsh/pull/52
https://github.com/demos-europe/demosplan-project-blp/pull/64
https://github.com/demos-europe/demosplan-project-bobhh/pull/66
https://github.com/demos-europe/demosplan-project-bobsh/pull/46
https://github.com/demos-europe/demosplan-project-diplanbau/pull/162
https://github.com/demos-europe/demosplan-project-diplanbimschg/pull/8 …

feature (refs T34299): disable core permission 'field_statement_polygon'

---

demosplan/DemosPlanCoreBundle/Repository/DraftStatementRepository.php
templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/versions_of_statement.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T34286
**Description:** This PR fixes the problem with dates in the statement versions. It employs the `createdDate` for the last item within the `draftStatementVersions` array to display the `createdDate` instead of using `versionDate`.
- issue with sorting by `createdDate` has also been resolved (BE)

Fix:(T34286) incorrect time in the statement versions

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_edit-field.scss
demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_tiptap.scss

**Ticket:** https://yaits.demos-deutschland.de/T34314
While moving to tailwind we lost the default styles for ul/ol. Since we only want to add them in placecs, we need them and not globally and then reset them, we have to find all the places where they are lost now. here are two...
--> statement_fragments-list
--> "split statement"

fix(refs T34314): Re-Add list styles for proseMirror / fragments

---

client/js/components/procedure/basicSettings/AutoSwitchProcedurePhaseForm.vue
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig

https://yaits.demos-deutschland.de/T34082
https://github.com/demos-europe/demosplan-ui/pull/443
- add missing Hooks/Selectors & E2E Props.

chore (refs T34082): add missing Hooks/Selectors & E2E Props.

---

yarn.lock

**Ticket:** https://yaits.demos-deutschland.de/T34173
**Description:** Demosplan-ui has to be updated to be able to test a bug.

upgrade demosplan UI (version "0.1.12")

---

client/js/components/map/publicdetail/Map.vue

**Ticket:** https://yaits.demos-deutschland.de/T34144
we tried to remove jQuery here and replaced ajax with (under the hood) axios.
(@see 43ad166fab54583ac4147b19071b3ab815381925)
that didn't work out because axios doesn't have a syncronous flag like ajax. Without that, we run into a stacked trap of race conditions which can't be resolved easily without rebuilding huge parts of this file.
Since I don't have a better solution, I roleback the changes from once.
https://diplanrog-dev.demos-europe.eu/verfahren/f96129bb-56c2-4b62-96e4-f52628adefc6/public/detail -> "test layer" should load. (there should appear getMap-Requests from https://geodienstelandesplanungstage.bob-sh.de/mapproxy/lep)

fix(refs T34144): Make Request syncronouse again

---

client/js/bundles/procedure/administrationDashboard.js
client/js/components/procedure/DpDashboardTaskCard.vue

**Ticket:** https://yaits.demos-deutschland.de/T31187
The component is too specific to keep in demosplan-ui
Removes `DpDashboardTaskCard.vue` from `demosplan-ui`:
- https://github.com/demos-europe/demosplan-ui/pull/445

refactor(refs T31187): move DpDashboardTaskCard to demosplan

---

client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
client/js/components/statement/assessmentTable/EditableText.vue
client/js/components/statement/assessmentTable/Fragment.vue

**Ticket:** https://yaits.demos-deutschland.de/T24040
Tiptap is our current implementation for DpEditor, however it makes no sense to reflect that in the naming of an application specific component.

Rename component to use agnostic name

---

client/js/components/map/publicdetail/Map.vue

**Ticket:** https://yaits.demos-deutschland.de/T33908
use set extent to stay within the allowed area of the map
The delete flag has the effect, that the panning and zoomout in the map handles the mapExtent diffferently than our expectations.
as FP-A set the "Kartenbegrenzung" to a narrow space. (/verfahren/<procedure-id>/verwalten/globaleGisEinstellungen)
then goto the public Detail and try to zoom out / pan out that area. That should not work anymore

fix(refs T33908):  Prevent map from panning/zooming out of extent

---

client/js/components/user/samlLoginForm/SamlLoginForm.vue
demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_form.scss

- as the icon in DpResettableInput has changed height, this needs to be adapted in the corresponding css
- DpFormRow applies a padding on each child, which led to a weird button spacing on the login button. this is corrected by simply removing DpFormRow which is not needed here anyway, as the form fields are each on their own line.
- The X icon in the search field in ewm procedurelist should be aligned correctly
- The "Anmelden" button on the login page should have equal padding to the left and right

fix: correct some rather small padding issues

---

demosplan/DemosPlanCoreBundle/Controller/Admin/DemosPlanAdminController.php
demosplan/DemosPlanCoreBundle/Controller/Forum/DemosPlanReleaseController.php

Ticket:
https://yaits.demos-deutschland.de/T29719
Description:
The EscaperExtension can not be found and therefore no csv files can be downloaded.
This is not a fix for the bug described in the ticket - it just fixes csv exports per se
Try to download the file mentioned in the ticket - should work again.
Fix for the ticket: https://github.com/demos-europe/demosplan-core/pull/1875

feature (refs T29719): fix for csv exports

---

demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/08/Version20230830135400.php
demosplan/DemosPlanCoreBundle/Entity/User/Orga.php

The id of an organization is saved as gw_id to be able to cope with orgachanges. When logging in from external identity providers this id might be longer than 36 chars.
Login via an idp with an id more than 36 Chars

chore: External orga id from identity provider can be longer than 36 chars

---

yarn.lock

Something got mixed up, so yarn.lock is not in sync with the actual module resolution anymore. if `yarn install` does not result in the current yarn.lock resolutions, it will try to change yarn.lock which fails if `--frozen-lockfile` is set.

fix: commit the yarn.lock changes manually

---

Jenkinsfile

Use the new shiny more lightweight demosplan-base container for ci tests. This will (hopefully) reduce memory and cpu footprint on the ci workers

chore: use base container for ci tests

---

client/js/components/procedure/StatementSegmentsList/SegmentLocationMap.vue

**Ticket:** https://yaits.demos-deutschland.de/T34442
If there are no features (aka drawings) in the map, we shouldn't try to get the extent of these features. 
Go to Verfahren -> Abschnitte -> Erwiderungen verfassen -> Ortsbezug. There should be no warnings in the console when opening the map with no drawings.

bug(refs T34442): Only center map again if there are features

---

client/js/components/procedure/StatementSegmentsList/StatementSegment.vue

This is a minor ui fix. Before, icons within the two upmost buttons were misaligned:
This is fixed now:

fix: make icons appear centered within buttons

---

client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_flyout.scss

as these are basically tertiary buttons, this should be communicated visually.

fix: use subtle buttons in statement detail view

---

client/js/components/procedure/StatementSegmentsList/StatementSegment.vue

https://yaits.demos-deutschland.de/T34564
We shall not check for segment relationships here anymore but if we have an addon enabled. The data prop async components is representing this state hence the check was adjusted accordingly.
(I could not test this locally properly since the segmentation does not work locally atm, however if i checked several existing segments, the icon appears for all of them)

bug (refs T34564): enable recommendation icon in editor

---

client/js/components/procedure/StatementSegmentsList/StatementSegment.vue

Ticket: https://yaits.demos-deutschland.de/T34578
- We can use the `recommendation:insert` event for toggeling the modal
- Update event name according to styleguide
You need:
- Addon demospipes
- Addon segment-oracle
- local pipeline 
Then go to Verfahren -> Abschnitte -> Erwiderung verfasse -> Editor -> Ähnliche Erwiderung einfügen and try to insert some recommendations from 'Vorschläge zu Schlagworten' und 'Vorschläge zu inhaltlicher Ähnlichkeit'. After clicking on insert the modal should close and the recommendation should be shown in the editor.

bug(refs T34578): Close modal after insert

---

demosplan/DemosPlanCoreBundle/Utilities/DemosPlanPath.php

**Ticket:** https://yaits.demos-deutschland.de/T34629
dplan may be used as a library. In this case the path to the project root needs to be adjusted.

feat: when used as a library the project path differs

---

demosplan/DemosPlanCoreBundle/Command/Data/DeleteProcedureCommand.php

**Ticket:** https://yaits.demos-deutschland.de/T32997
This is a rather risky and hacky solution for deleting a procedure with everything related to it. It is meant as an interim solution while we are working on a more stable way of deleting all related parts in the system preferably with Doctrine.
We need this solution to clean everything pertaining to customers that had to be deleted. Since we are not able to cleanly delete statements or procedures or some other related things via our repositories, this direct approach in SQL has been chosen to accomplish the task in a somewhat timely manner.
I feel somewhat confident that I got most if not all entries I have to delete. But I might have missed something.
I tested it with multiple procedures in an older Prod-DB-Dump and it seemed to work …

Delete procedure and all related things command (via SQL)

---

.env
config/packages/old_sound_rabbit_mq.yaml
config/parameters_default.yml

We need to be able to use environment variables during deployment to set configurations. This is also suggested as a [symfony best practice](https://symfony.com/doc/current/configuration.html#config-env-vars)

feat: allow rabbitmq_dsn to be overridden by env var

---

demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureTypeController.php
demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureTypeService.php

A previous attempt to pass objects into
twig files that use the same properties
as the resources returned by the generic
web API did not establish itself. The
attempt is thus rolled back,
simplifying code logic.
As the `ProcedureTypeResourceType` does
not apply any aliases or special
property permissions, no adjustment of
the twig files is necessary.

refactor: avoid entity wrapping for twig

---

demosplan/DemosPlanCoreBundle/Entity/Sessions.php

**Ticket:** https://yaits.demos-deutschland.de/T3458
The data in the session table is no longer stored as a medium blob but as a blob by symfony default. This entity is defined to help doctrine to create the correct field size during database setup.
As a side effect this PR reduces the number of entries that are generated during doctrine migrations diff
create a new database (be sure to change the database name before!) with `bin/<project> dplan:db:init --create-database` and find a sessions table. 

chore (refs T34581): Define Entity to ensure field length

---

demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
demosplan/DemosPlanCoreBundle/Entity/Statement/StatementFragment.php

This PR fixes a deprecation on trim on null which made several commands very verbose
code review and e.g. populate elasticsearch

chore: fix deprecated trim on null

---

composer.lock
config/parameters_default.yml
config/parameters_test.yml
demosplan/DemosPlanCoreBundle/Resources/config/GlobalConfig.php
demosplan/DemosPlanCoreBundle/Services/SubdomainHandler.php
tests/backend/core/Procedure/Functional/SubdomainHandlerTest.php

**Ticket:** https://yaits.demos-deutschland.de/T34644
subdomains_allowed was an attempt not to take over all malicious subdomains. The approach is unfortunately too static and can be replaced by searching for the subdomain in the customer table. If the entry exists, the subdomain can be used.

feat (refs T34644): remove subdomains_allowed

---

client/js/components/procedure/basicSettings/DpBasicSettings.vue
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T34626
This is needed to allow addons to hook into this spot in the procedure settings in all projects. The explanation text is now also in the addons, so I only copied over the addon wrapper itself. I also changed the div class to match the ones around it. Lastly, the import of the AddonWrapper in the DpBasicSettings.vue was outdated and is now fixed.
I think the addon-permissions are not properly working atm, at least not for me. So just a code review might be easiest.

feat(refs T34626): adds addon wrapper to core template

---

client/js/components/procedure/basicSettings/DpBasicSettings.vue

**Ticket:** https://yaits.demos-deutschland.de/T34969
- Hook name changed
- We don't need permission request here, because it is handled in the addon
- Label and tooltip was moved to the addon
- Install maillaine Addon
- Go to Verfahren -> Grundeinstellungen. You should see "Berechtigte Absenderadressen für den E-Mail-Import" and the button for adding addresses.

bug(refs T34969): Fix addon hook for maillaine in basic settings

---

composer.json
composer.lock

**Ticket:** https://yaits.demos-deutschland.de/T34626
The new version 3.0 changed the public surface of the library which would force us to rebuild parts of our zip exports. For the moment we roll the dependency back as we don't have currently the time to do so.
Without this rollback, procedure exports should not work and instead throw an error. With this rollback, they should work again.
- Update-PR #1582

fix(refs T34626): rolls back maennchen/zipStream

---

client/js/components/map/admin/DpAdminLayerListItem.vue
client/js/store/map/Layers.js

**Ticket:** https://yaits.demos-deutschland.de/T34708
We need to set the value as `newOrder` here to be able to set the children in `client/js/store/map/Layers.js:142`.
Go to Verfahren -> Planungsdokumente und Planzeichnung -> Kartenebenen definieren and create some folders and layers. You should be able to move the layer and folders and nest them.

bug(refs T34708): Fix moving list items

---

demosplan/DemosPlanCoreBundle/Repository/EmailAddressRepository.php

The table does not exist anymore and having it still in the delete query here produces an error that prevents the orphan removal to correctly work.
Without this fix, the orphan email removal in the MaintenanceTask should fail with an error.

fix: removes gdpr email addresses from orphan email removal

---

yarn.lock

**Description:** Upgrade release branch with the new version of demosplan-ui (0.1.15).

upgrade demosplan-ui to v0.1.15 (release)

---

client/js/components/procedure/AdministrationImport/AdministrationImport.vue

**Ticket:** https://yaits.demos-deutschland.de/T30049
- Only show tabs for import center if there is content for the tabs
Disable all import functions (pdf, excel, direkteingabe, email). There should be no tabs in the import center and no error in the console.

bug(refs T30049): Add import center for project

---

client/js/components/statement/assessmentTable/DpFilterModal.vue

**Ticket:** https://yaits.demos-deutschland.de/T34738
Since refactoring DpMultiselect option is now a property of props. 
Verfahren -> Abwägungstabelle -> Filter. You should see the list with user specific filters (first drop down).

bug(refs T34738): Fix user filter sets

---

client/js/components/procedure/basicSettings/ExportSettings.vue

**Ticket:** https://yaits.demos-deutschland.de/T34691
There was a wrong trans key used for selecting all elements. 
Verfahren -> Grundeinstellunge -> Daten im Export. There should be the correct translation for selecting all elements.

bug(refs T34691): Fix wrong trans key

---

config/permissions.yml
demosplan/DemosPlanCoreBundle/Permissions/Permissions.php

**Ticket:** https://yaits.demos-deutschland.de/T34770
Authenticated AI user needs to be able to access procedures even if they are in phases with the procedureset hidden (like configuration)
Try to import a pdf in a hidden internal procedurephase

chore (T34770): allow authenticated ai user to access procedure in hidden phases

---

demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/DplanAuthenticator.php

**Ticket:** https://yaits.demos-deutschland.de/T34763
If it is not possible to automatically recognise whether an organisation or department has been changed, the user is redirected to a page on which this must be specified. This PR fixes the mechanism behind it.

chore: restore orga/department change verify page

---

tests/backend/core/Core/Unit/Logic/PermissionsTest.php

After introducing the ProcedureAccessEvaluator the permission test system was not updated to reflect the change in infrastructure
run project permissiont test

chore: fix permission test setup after introducing ProcedureAccessEvaluator

---

config/packages/dev/monolog.yaml

Default is info, so less is logged which improves performance in dev mode. When a more verbose logging is needed parameter symfony_loglevel may be used to lower the loglevel.

chore: use global loglevel in dev logs

---

composer.json
tests/backend/bootstrap.php

As phpstorm runs tests via docker (compose) as root user file permissions are screwed up that leads to error when visiting the browser after performing a project test
core review or visit the browser after performing a project test

chore: set user and group for generated cache and log files to current user

---

demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/09/Version20230925135949.php

**Ticket:** https://yaits.demos-deutschland.de/T32796
procedure_id was modeled as a unique foreign key which does not make sense as we need to be able to save multiple messages to one procedure
code review or modify procedure twice

chore (refs T32796): fix faulty unique index on procedure_message.procedure_id

---

translations/messages+intl-icu.de.yml

**Ticket:** https://yaits.demos-deutschland.de/T34759
**Description:** This PR adds translation key for an empty statement list.

Fix(T34759): add translation key for an empty statement list

---

demosplan/DemosPlanCoreBundle/Addon/AddonDoctrineMigrationsPass.php
demosplan/DemosPlanCoreBundle/Application/DemosPlanKernel.php

**Ticket:** https://yaits.demos-deutschland.de/T30599
When a folder src/DoctrineMigrations exists in the addon it is added to the doctrine migrations path. The namespace of the migration needs to match the psr4 addon namespace
create a Migration in src/DoctrineMigrations and run bin/<project> doctrine:migrations:status and you should see the migration

feat (refs T30599): allow addons to have their own DoctrineMigrations

---

demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedurePerson.php
demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php

**Ticket:** https://yaits.demos-deutschland.de/T43766
Description: 
- add new method 'addSimilarStatementSubmitters' : it to add a new section which contain the  Similar Statement Submitters section
- adjust methods return types and remove uneeded parameters

F adjust methods parameters und returntypes

---

client/js/components/procedure/StatementSegmentsList/StatementSegment.vue

**Ticket:** https://yaits.demos-deutschland.de/T34841
**Description:** This PR fixes an issue with two icons in the modal window. They were not being displayed because the `activeId` was only updated after clicking on the tab. Therefore, set the `activeId` value when clicking on the `toggleRecommendationModal` button.

Fix(T34841): issue with displaying the icons

---

demosplan/DemosPlanCoreBundle/Controller/Segment/SegmentController.php
demosplan/DemosPlanCoreBundle/Logic/OzgKeycloakUserDataMapper.php

Ticket:
https://yaits.demos-deutschland.de/T34758
Description:
Rename KeyCloak role-map to use 'Mandanten' instead of 'Plattform'
as identifier for Role::CUSTOMER_MASTER_USER
left-over commit - not topic related in SegmentController:
Adds an Exception variable to catch clauses in order to get info about what happened.

feature (refs T34758): Rename KeyCloak role-map 

---

client/js/components/procedure/SegmentsList/SegmentsList.vue
demosplan/DemosPlanCoreBundle/Logic/ApiRequest/JsonApiEsService.php
demosplan/DemosPlanCoreBundle/Logic/Segment/RpcBulkEditor/RpcSegmentIdLoader.php
demosplan/DemosPlanCoreBundle/Traits/DI/ElasticsearchQueryTrait.php

**Ticket:** https://yaits.demos-deutschland.de/T34793
**Description:** 
BE: Creates a new RPC route.
FE: Adjusts the request/response for the RPC route in the `SegmentsList` component.
Here is a discussion in [Slack](https://demosdeutschland.slack.com/archives/CUZTNDTUH/p1695659882787459)

Fix(T34793): segment id performance 

---

config/packages/security.yaml
config/parameters_default.yml
demosplan/DemosPlanCoreBundle/Controller/Base/BaseController.php
demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserAuthenticationController.php
demosplan/DemosPlanCoreBundle/EventSubscriber/LogoutSubscriber.php

**Ticket:** https://yaits.demos-deutschland.de/T34685
Symfony security system is used to log out user instead of building custom logout. Code is mostly only moved to listener, the part with `oauth_keycloak_logout_route` is new. A bug is fixed that caused the part of `saml_idp_slo_url` to always be true.
code review might be best, normal login should still work

feat: logout from keycloak during local logout

---

demosplan/DemosPlanCoreBundle/Entity/MailSend.php
demosplan/DemosPlanCoreBundle/Entity/Map/GisLayer.php
demosplan/DemosPlanCoreBundle/Entity/Procedure/Boilerplate.php
demosplan/DemosPlanCoreBundle/Entity/Procedure/BoilerplateGroup.php
demosplan/DemosPlanCoreBundle/Entity/Procedure/Procedure.php
demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureBehaviorDefinition.php
demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureCoupleToken.php
demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureType.php
demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureUiDefinition.php
demosplan/DemosPlanCoreBundle/Entity/Procedure/StatementFieldDefinition.php
demosplan/DemosPlanCoreBundle/Entity/Procedure/StatementFormDefinition.php
demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
demosplan/DemosPlanCoreBundle/Entity/Statement/Tag.php
demosplan/DemosPlanCoreBundle/Entity/User/Customer.php
demosplan/DemosPlanCoreBundle/Entity/User/InstitutionTag.php
demosplan/DemosPlanCoreBundle/Entity/User/Orga.php
demosplan/DemosPlanCoreBundle/Entity/User/OrgaType.php
demosplan/DemosPlanCoreBundle/Entity/User/Role.php
demosplan/DemosPlanCoreBundle/Entity/User/User.php

**Ticket:** https://yaits.demos-deutschland.de/T34912
Doctrine relationship require the type of the target entity (e.g. `@ORM\ManyToOne(targetEntity="demosplan\DemosPlanCoreBundle\Entity\User\Orga")`). According to the Doctrine documentation, the string must be given as class-name, which means the fully qualified name is required. Still, Doctrine does some guessing and thus can process the simple name too (e.g. `@ORM\ManyToOne(targetEntity="Orga")`), but the EDT implementation needs to process the `targetEntity` value too and is not capable of this.
To allow EDT to work with the relationship annotations/attributes the simple names are replaced with fully qualified names.

refactor: use fully qualified name for relationships

---

client/js/components/procedure/StatementSegmentsList/StatementSegment.vue

Pass Id to Tooltipcontainer parameter instead of DOM-Object.
The Tooltip-Directive only can handle querySelectables
**Ticket:** https://yaits.demos-deutschland.de/T34961

fix(refs: T34961): Pass ID as Tooltip container param

---

demosplan/DemosPlanCoreBundle/Addon/AddonRegistry.php
demosplan/DemosPlanCoreBundle/Addon/Composer/PackageInformation.php
demosplan/DemosPlanCoreBundle/Addon/Registrator.php
demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php

Addons may be enabled during installation by using the option `--enable`.
Along the way some improvements in the installation process where introduced, you may review commit wise.
I voted against tests in this specific case as the commands main task is to cope with infrastructure and configuration.
code review or install an addon and enable it directly

chore: add option to enable addon during installation

---

demosplan/DemosPlanCoreBundle/Addon/AddonManifestCollectionWrapper.php
demosplan/DemosPlanCoreBundle/Command/Addon/AddonListCommand.php
tests/backend/core/Core/Functional/AddonListCommandTest.php

This PR provides a Command to list all installed addons.
An AddonManifestCollectionWrapper needed to be created as static methods are not testable.
In this case it is valid to have AddonManifestCollection::load static, as it is needed during kernel boot
code review or run `bin/<project> dplan:addon:list` 

feat: introduce addon list command

---

demosplan/DemosPlanCoreBundle/Addon/AddonRegistry.php
tests/backend/core/Core/Functional/AddonRegistryTest.php

This PR adds two helper methods to get installed and enabled addons. These ones can be used later on to improve DX and addon handling
code review, run tests

chore: add helper methods for installed and enabled addons

---

client/js/components/procedure/imageAnnotator/DpImageAnnotator.vue

Ticket:
https://yaits.demos-deutschland.de/T35031
Description:
the current redirect conditions always redirected to the procedure_dashboard.
Changed the condition to rather redirect to procedure_import instead if the import permission is granted.
ewm->import->überprüfen->save
you should be redirected back to the import instead the procedure dashboard.
BE-Part for 'import bestätigen' : - https://github.com/demos-europe/demosplan-addon-demospipes/pull/113

F t35031 adjust redirect after pdf import

---

templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/send_notification_email_for_unsubmitted_draft_statements.html.twig
translations/messages+intl-icu.de.yml

Ticket:
https://yaits.demos-deutschland.de/T33642
Description:
Fixes a new line feed just before a full stop.
And removes empty spaces surrounding the translation.
Set a procedure to end for institutions in exactly one week ahead in time.
log in with a member of that orga and write a draft statement.
use the link `http://diplanbau.dplan.local/app_dev.php/maintenance/x7hndcVlpJIH15fEsgNNssd3?frequency=daily` to send the mails and check mailhog.
This PR replaces the prior forgotten old diverged PR https://github.com/demos-europe/demosplan-project-diplanbau/pull/149
other related PR: https://github.com/demos-europe/demosplan-project-diplanbau/pull/175
looks in mailhog:
`Hallo Welcome Page,
im Verfahren "MailTestVerfahrenEndetIn7Tagen" endet in
7 Tagen
(25.10.2023)
eine Beteiligungsphase. …

feature (refs T33642): fix faulty new line and out of place empty space

---

package.json
yarn.lock

https://github.com/demos-europe/demosplan-ui/blob/main/CHANGELOG.md

chore: Bump demosplan-ui from 0.2.0 to v0.2.1

---

client/js/components/user/CustomerSettings/CustomerSettingsSupport.vue
translations/messages+intl-icu.de.yml

They have to be unique by design. however we can't validate them with a propper error message
in the Backend, so we check before saving. As a safety net the Be will throw a generic error
if this check here is insufficient.
**Ticket:** https://yaits.demos-deutschland.de/T35059
As mandatenAdmin Goto `/einstellungen/plattform` and try to create two customerContacts with the same title.

fix(refs T35059): Catch ununique Titles before sending them to the BE

---

demosplan/DemosPlanCoreBundle/Event/Procedure/PostProcedureUpdatedEvent.php

Ticket:
https://yaits.demos-deutschland.de/T35088
Description:
DateTime objects were not taken into account when calculating the changes via a reflectionClass - as DateTime properties are private. Implemented a special treatment for DateTime objects.
Install addon -> change any startDate / endDate of a procedure and check the procedure_message table for a new entry.
other missing relevant procedure properties regarding an update were added here: https://github.com/demos-europe/demosplan-addon-xbeteiligung-async/pull/13

feature (refs T35088): regard DateTime Objects when calculating changes to procedures

---

demosplan/DemosPlanCoreBundle/Controller/Platform/EntrypointController.php
demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OzgKeycloakAuthenticator.php
templates/bundles/DemosPlanCoreBundle/DemosPlanUser/login_idp_error.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T34808
Redirect user to distinct error page after Identityprovider login error to ease the handling and enhancement of the error. This way common twig/vue and symfony mechanisms could be used to build an information page about what happened
call <projectURL>/idp/login/error

chore (refs T34808): redirect to distinct error page after idp login error

---

demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadCategoryData.php
demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadMailTemplateData.php
demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadMigrationVersionData.php
demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadProcedureData.php
demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadProcedureTypeData.php
demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadRolesData.php
demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadUserData.php
demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/ProdFixture.php

**Ticket:** https://yaits.demos-deutschland.de/T30599
The prod fixtures need to provide a role for the data user so that a user could be created. Moreover, the prod fixtures are not deprecated, this is cleaned up as well.

chore: add data user role to fixtures

---

demosplan/DemosPlanCoreBundle/Validator/ValidCssVarsConstraintValidator.php

**Ticket:** https://yaits.demos-deutschland.de/T35168
In a comment in Branding entity it is explicitly stated that value might be null. 
> For future reference: null is for all intents and purposes equivalent to ''. Both mean that there is no set of cssvars.
Hence we need to loosen validation a bit

chore refs T35168: css var value might be null as stated in entity

---

composer.lock
demosplan/DemosPlanCoreBundle/ValueObject/FileInfo.php

**Ticket:** https://yaits.demos-deutschland.de/T35051
demosplan-addon has a new version (v.0.10). This version contains the FileInfoInterface. This PR implements the interface to
the corresponding value object and adjusts the composer.lock.
code review

feat (T35051): implement the FileInfoInterface and adjust composer lock

---

.github/workflows/reviewdog.yml

Once an aeon ago, it was requested that Reviewdog should not run on Draft PRs. Which - since we use draft PRs mainly for communicating upcoming changes early on - could be changed by making the job conditional.

feat: Disable reviewdog on draft prs

---

translations/messages+intl-icu.de.yml

***Ticket: https://yaits.demos-deutschland.de/T34497***
###Desription:
- the trans key was missing in core and it doesnt need to be overwritten in the diplan project
- so in the projects it can be removed

Fix(refs:34497): add introduction trans key to core

---

client/js/bundles/user/listOrgas.js
client/js/components/user/DpOrganisationList/DpOrganisationList.vue
demosplan/DemosPlanCoreBundle/ResourceTypes/OrgaResourceType.php

- we don't want to access the customer directly from the orga. Its deprecated
- and we should define explicitly which fields we want to get from the Backend
- even if that means listing all fields.
As Mandaten-Admin / Support The Page `/organisation/list` should work like before but without the purple warnings

refactor: Declare fields when fetching orgas and use the proper rels

---

demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanAssessmentController.php

Add Missing Confirmmassge when creating a manual STN
(cherry picked from commit 7abdf5a027ad949c1940437a2d93d703654c1337)
**Ticket:** https://yaits.demos-deutschland.de/T31372

fix(refs T31372): Add confirm message to confirm mstn (#1529)

---

client/js/components/statement/publicStatementModal/StatementModal.vue
client/js/components/statement/publicStatementModal/formGroups/FormGroupEvaluationMailViaSnailMailOrEmail.vue
client/js/components/statement/publicStatementModal/formGroups/FormGroupPostalAndCity.vue

**Ticket:** https://yaits.demos-deutschland.de/T33137
**Description:** This PR fixes the notification issue and enhances accessibility by:
- resolving the problem of duplicating invalid fields
- removing all notifications/errors after clicking on _'Ich möchte anonym Stellung nehmen.'_
- introducing a `'statement.r_getFeedback === 'on''` check for required fields, which validates the fields only when the `'getFeedback'` field is activated."
**Linked PRs**
[PR](https://github.com/demos-europe/demosplan-ui/pull/622) in demosplan-ui

Fix(T33137): accessible notifications

---

client/js/components/procedure/DpSimplifiedNewStatementForm.vue

**Ticket:** https://yaits.demos-deutschland.de/T35342
The property for submitter's city was wrong. We get `ort` from the backend.

bug(refs T35342): Use the correct property for submitter city

---

.github/dependabot.yml

its tiny
for interested Persons https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

fix: Type-o in dependabot.yml

---

demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementSpreadsheetImporter.php

**Ticket:** https://yaits.demos-deutschland.de/T35366
Description: errors while import with additional columns, assertion has to be removed.

F T35366 errors while import with additional columns

---

demosplan/DemosPlanCoreBundle/DataGenerator/CustomFactory/FactoryBase.php
demosplan/DemosPlanCoreBundle/Entity/User/FunctionalUser.php

**Ticket:** https://yaits.demos-deutschland.de/T17360
Statements could not be generated any more as validation has tightened
run bin/<project> dplan:data:generate:statement

T17360: fix generate statement command as functional user has no id

---

client/js/components/support/DpSupport.vue

**Ticket:** https://yaits.demos-deutschland.de/T35369
If You don't have the Permission to edit customer contacts,
the api doesn't return `visible` as attribute since you only
receive visible contacts. That means it doesn't work to filter
by that state and it's not only unnecessary but results in empty lists.
as "Mandanten admin" create some entities in "inhaltlicher support" (`/einstellungen/plattform`). set some to visible and other to not-visible.
Log out. check if You only see the visible ones on the page `/informationen`

fix(refs T35369) Display contact cards for none admins

---

demosplan/DemosPlanCoreBundle/EventSubscriber/CsrfSubscriber.php
templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/csrf.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_edit.html.twig
tests/backend/core/Core/Functional/CsrfSubscriberTest.php
translations/messages+intl-icu.de.yml

**Ticket:** https://yaits.demos-deutschland.de/T35309
All HTML post forms must be provided with csrf protection. 
protection. On the one hand this is best practice, on the other hand it is required by the BSI and by customers.
After this PR all forms must include `{{ include('@DemosPlanCore/DemosPlanCore/includes/csrf.html.twig') }}`. Initially only a dev message is triggered, later on the check could be activated
run tests, post any form and see the dev message. Adding or editing a procedure news should not trigger the message

chore refs T35309: add csrf protection listener

---

demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureTypeService.php

**Ticket:** https://yaits.demos-deutschland.de/T35314
I wondering why this was not happening earlier but on create or update a ProcedureType additional fields will be added which invalidates the form. This fix keep the logic but avoid creating a additional field.
Additional cleanup will be done in a separate PR.
Update and Create a ProcedureType.

feat (refs T35314): fix invalid form on update/create ProcedureType

---

client/js/components/support/DpSupportCard.vue

Show office hours only if there are office hours to avoid console errors. Appeared if you create a contact without office hours (the big text field).

bug: Only show office hours if there are office hours

---

demosplan/DemosPlanCoreBundle/Logic/Segment/RpcBulkEditor/RpcSegmentsBulkEditor.php
demosplan/DemosPlanCoreBundle/Repository/SegmentRepository.php

**Ticket:** https://yaits.demos-deutschland.de/T35348
Description: 
The error message when adding text while editing sections suggests that there's a syntax error in your DQL (Doctrine Query Language) query. It expects a closing parenthesis but got an other character instead. This usually occurs due to malformed DQL. The $recommendationText variable might contain a value that is breaking the query syntax that's why we have to bind it to make sure that if the content of this variable is supposed to be a string literal in the query, it is properly escaped or handled.

F t35348 error message when adding text while editing sections

---

tests/frontend/unit/DpPublicStatement.spec.js

Required prop `procedureId` was missing in jest test for DpPublicStatement.

chore: Add required prop to test

---

.github/dependabot.yml

Maybe dependabot is confused by the slash in @sentry package names.

Fix sentry pattern for dependabot grouping

---

config/permissions.yml
demosplan/DemosPlanCoreBundle/ResourceTypes/DepartmentResourceType.php

**Ticket:** https://yaits.demos-deutschland.de/T35396
Description: 
The departement resource type is not available while filter segments by assignee. A new permission was added to make the departement resource type available while segment by assignee filter

f_T35396 fix assignee filter

---

demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php

**Ticket:** https://yaits.demos-deutschland.de/T35482
Description: 
- use statementInterface instead of segmentInterface: 
the parameter 'segmentOrStatement' could be a segment or a statement.  The Segment entity is already a child of StatementInterface otherwise the Statement entity implement not the Segment Interface that's why we have to use the parent class here to make both entities valid.  
- adjust name of method: method name was false
test with export file or code review
- https://github.com/demos-europe/demosplan-project-ewm/pull/98

feature (ref 35482): statement interface instead of segment interface

---

demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/AssessmentTableServiceOutput.php
demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php

Ticket:
https://yaits.demos-deutschland.de/T35367
Description:
The exported xls file contained a unix timestamp instead of a readable
formatted date string. This change formats this value so it is the same as the other date value
present within the export (d.m.Y)
get an up to date regio db, check out branch and download the xls statement(s) as described within the ticket.
The date value should look like `01.11.2023` instead of the unix timeStamp - lokal exampleExport:
[Abwägungstabelle-10-11-2023-14 07.xlsx](https://github.com/demos-europe/demosplan-core/files/13320402/Abwagungstabelle-10-11-2023-14.07.xlsx)
this Pr replaces https://github.com/demos-europe/demosplan-core/pull/2304

feature (refs T35367): Used the same logic to format the authoredDate as pdfExporter does

---

demosplan/DemosPlanCoreBundle/Command/Db/MigrateCommand.php

Small quality of life improvement: A migration named "on" is saved into a database when generating a new database based on fixtures, probably due to a bug in doctrine. This version is removed from the list of executed versions to avoid confusion.
code revoew or create a new database based on fixtures and see migrations list. After running `bin/<project> dplan:doctrine:migrations` it should be gone. 

chore: remove useless non-existing migration

---

templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/public_elements_list.html.twig

https://yaits.demos-deutschland.de/T34709
- The button was not properly included in the corresponding warpper component
- The class `elements__grid-grow` prevent a proper adjustment of the button hence was replaced with `flow-root` to easily adjust the download button at the end of the container
- The download button class list was added float-right to align it
- checkout
- find a plan with planning documents
- navigate to the procedure's public detail view and make sure the download buttons are consistently aligned in relation to each other:

fix(refs: T34709): adjust button placement on public detail document view

---

demosplan/DemosPlanCoreBundle/Services/Map/GetFeatureInfo.php

https://yaits.demos-deutschland.de/T35297
- The gfi response contains a link to a pdf which should be accessible from the UI directly. This commit prevents the purging of a clickable link in the resulting html like table response
In the corresponding PR is a full depth how-to-test section.
regio-PR #(https://github.com/demos-europe/demosplan-project-regio/pull/87)

feat(refs: T35297): prevent link from being purged from gfi response

---

demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php

**Ticket:** https://yaits.demos-deutschland.de/T35610
Description: 
- use statementInterface instead of segmentInterface: 
the parameter 'segmentOrStatement' could be a segment or a statement.  The Segment entity is already a child of StatementInterface otherwise the Statement entity implement not the Segment Interface that's why we have to use the parent class here to make both entities valid.  
- adjust name of method: method name was false
test with export file or code review

feature (ref 35610): use statementinterface except segmentinterface

---

demosplan/DemosPlanCoreBundle/Addon/Registrator.php
demosplan/DemosPlanCoreBundle/Command/Addon/AddonListCommand.php
tests/backend/core/Core/Functional/AddonListCommandTest.php

This PR enhances the addon list command to show versions. These are derived from the composer.json file in the addon and saved in addons.yml file during installation
run `bin/<project> dplan:addon:list` 

chore: add version to addon list command

---

.github/dependabot.yml

I used a not existing option... 
see: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups

fix: Use correct Option to exclude pacakges from pattern

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_master.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T34935
Move tooltip, so it can float right outside of label.
Go to Verfahren -> Blaupause -> Grundeinstellungen. Tooltip of "Email Verfahrensträger" should align right with the other tooltips.

bug (refs T34935): Move tooltip outside of label

---

client/js/components/user/DpOrganisationList/DpOrganisationList.vue

https://yaits.demos-deutschland.de/T34613
This PR fixes:
- Rejected orga statuses should be filtered out if the corresponding checkbox has been selected
- checkout
- login as support user
- navigate to `/organisation/list`
- select a filter checkbox 
- make sure the selected checkbox results in a list where none of the statuses (of the selection) shows a `zurückgewiesen` status here: 

fix(refs: T34613): add orga status filter

---

client/js/components/statement/assessmentTable/FilterModalSelectItem.vue

**Ticket:** https://yaits.demos-deutschland.de/T34273
We need to give true for selection controls to show the beforeList slot.
To test this locally, you need to install the linked demospipes version and update demosplan-ui. 
Verfahren -> Stellungnahmen -> Aufteilen -> Abschnitt bearbeiten -> Click in Schlagwort suchen. There should be the option "Schlagwort oder Thema anlegen" and this should work.

bug (refs T34273): Add prop selection controls to filter modal

---

client/js/components/user/DpOrganisationList/DpOrganisationList.vue

**Ticket:** https://yaits.demos-deutschland.de/T34613
Only filter for orga status if the filter is active. Otherwise we want all orgas. 
- login as support user
- navigate to `/organisation/list`
- select a filter checkbox 
- make sure the selected checkbox results in a list where none of the statuses (of the selection) shows a `zurückgewiesen` status
- remove filter -> make sure all orgas are shown, especially the ones that were filtered out before with the status "zurückgewiesen"
https://github.com/demos-europe/demosplan-core/pull/2373

bug (refs T34613): Fix filter orga status

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_boilerplate.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_master.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T35632
In some cases csrf token is already set in BE via symfony forms.
For this cases the additional csrf in template is removed with this PR.
Creation of Boilerplatetext and procedure template should work with this PR and should not without this one.

feat (refs T35632): duplicate csrf token usage leads to error

---

client/js/components/user/CustomerSettings/CustomerSettingsSupport.vue
demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/11/Version20231129120204.php
demosplan/DemosPlanCoreBundle/Entity/User/SupportContact.php
demosplan/DemosPlanCoreBundle/Repository/EmailAddressRepository.php
demosplan/DemosPlanCoreBundle/ResourceTypes/CustomerContactResourceType.php
demosplan/DemosPlanCoreBundle/ResourceTypes/CustomerLoginSupportContactResourceType.php

**Ticket:** https://yaits.demos-deutschland.de/T35528
Description: 
- Using the EmailAddress causes many issues which do not meet the users expectations ( use the same emails for many support contact ). that's why the email address property have to be of type a string, not any more a relation to EmailAddress and with no unique constraint.
- The entity 'SupportContact' and the table 'support_contact' are adjusted.
- The resource Types a re adjusted.

F T35528 make support contact work the same support email

---

demosplan/DemosPlanCoreBundle/EventSubscriber/CsrfSubscriber.php

Ticket:
https://yaits.demos-deutschland.de/T35690
Description:
rollback changes in CsrfSubscriber due to b8389403b3e8389c72597373449e9e8f2ae84e32
replacement: https://github.com/demos-europe/demosplan-core/commit/b8389403b3e8389c72597373449e9e8f2ae84e32
original: https://github.com/demos-europe/demosplan-core/pull/2419

feature (refs T35690): rollback changes in CsrfSubscriber due to 

---

composer.json

Composer version constraints can be built in multiple ways. The current `||` could not be interpreted correctly by phpstorm to automatically set the php version. It might be a bug there, but changing the constraint from logical or to and does not make any harm, so I think we could support here and change the way we define the constraint.

chore: change composer php constraint syntax

---

composer.lock

Ticket:
https://yaits.demos-deutschland.de/T33578
Description:
update composer.lock to demosplan-addon v0.13

feature (refs T33578): update composer.lock to demosplan-addon v0.13

---

client/fe/webpack/moduleRules.js

As tailwind uses the dot for selector names, we have to tell that to purgeCss.

Allow dots in selectors for purgeCss

---

package.json

As its de facto the Version we need.

chore: Bump required node Version to 18.13.0

---

demosplan/DemosPlanCoreBundle/Logic/Elements/RpcElementsListReorderer.php

**Ticket:** https://yaits.demos-deutschland.de/T35881
If you reordering elements in "Planungsdokumente und Planzeichnung", this will not be saved.
This is the case because: getConfigPath builds a path for the config directory, so 'config' is twice in the path, was caused a failure to get the content of a schema json file.
I removed the config in the relative path string. Now the rearrangement should be saved again.
reorder elements in "Planungsdokumente und Planzeichnung"

fix: T35881 fix path to fix reordering of elements

---

demosplan/DemosPlanCoreBundle/Logic/ZipImportService.php

File names and paths should not contain spaces to avoid errors in file actions like virus scan
https://yaits.demos-deutschland.de/T35878

F t35878 fix spaces in filenames

---

demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
demosplan/DemosPlanCoreBundle/ResourceTypes/AbstractStatementResourceType.php

**Ticket:** https://yaits.demos-deutschland.de/T35885 
https://yaits.demos-deutschland.de/T35896
Description: Because attachment files stored in parent of statement, we should call it except statement. In file container entity, files stored with statement parent ID as an entity_id.
Browser or code review

feature (ref 35885): use statement parent id except statement id

---

demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php

This quality of life PR takes the required action in 99% of the installation cases as default and enables the addon immediately after installation. The new option `no-enable` only installs the addon without enabling it
install an addon via `bin/<project> dplan:addon:install` and choose the addon to install. Then check addons/addons.yaml, whether the addon is activated

chore: automatically enable addon during installation

---

client/js/components/procedure/admin/AdministrationProceduresList.vue
demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureListController.php

**Ticket:** https://yaits.demos-deutschland.de/T26430
Description: Change the method of route from GET to POST, because of the error 401 (Long URL) for export all of procedures
export all procedures in UI or Code review

feature (ref 26430): chnage method of route from get to post

---

package.json
yarn.lock

This PR bumps the `demosplan-u`i to the current version 0.3.4

chore: bump demosplan-ui v0.3.4

---

client/js/components/statement/assessmentTable/DpSelectedItemsStatements.vue
client/js/lib/statement/AssessmentTable.js
client/js/lib/statement/AssessmentTableOriginal.js

**Ticket:** https://yaits.demos-deutschland.de/T35949, https://yaits.demos-deutschland.de/T35898
**Description:** [After refactoring the DpApi method](https://github.com/demos-europe/demosplan-ui/pull/506), which now includes stringification of the body, some adjustments are needed in the core since body `stringify()` is no longer required there.

B(T35949): adjustments in core for DpApi method

---

client/js/components/map/admin/LayerSettings.vue

**Ticket:** https://yaits.demos-deutschland.de/T35897
**Description:** This PR fixes the issue with the fetch request that occurs after refactoring externalApi method from axios to fetch. All processing that depends on the text being read from the URL should be in the final 'then' clause of the fetch.

Fix(T35897): no layer available after fetch capabilities

---

client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue

https://yaits.demos-deutschland.de/T35941
The reactivity was an issue when updating a statement or recommendation text, the change was only visible when re-loading the page hence the component will be forced to remount with the updated data. It was not possible to establish a proper reactivity with the statement or recommendation store objects due to a lot of internal processing of the texts. Since this problem disappears when the component remounts (e.g. on page reload) I decided it would be a valid solution 
- Enhances the behavior of the component after statement text or recommendation text has been adjusted
- Adds a loading spinner when updating one of the editors
- Adds styling to loading spinner to keep the design and not break the view while loading
- checkout branch
- navigate to …

fix(refs T35941): enable editor to update after save

---

demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
demosplan/DemosPlanCoreBundle/Logic/Import/Statement/ExcelImporter.php
demosplan/DemosPlanCoreBundle/Validator/PrePersistUniqueInternIdConstraintValidator.php

**Ticket:** [T35878](https://yaits.demos-deutschland.de/T35878)
Bug of Story:[T33577](https://yaits.demos-deutschland.de/T33577)
statement->getInternId() was always return the internId of the related original statement, which is "correct for the application-logic but leads to wrong results on validate data of a specific statement obviously because the data of a different statement was returned.
Using the "Beteiligungs-Import" (ZipImport) to import a Zip wich statements also has internIds("Eingangsnummern").
In [T35878](https://yaits.demos-deutschland.de/T35878) is a Zip, which covering this case.
Please merge in case of approve.

Fix validation of unique statement.internId per procedure

---

templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T35874
**Description:** This PR fixes an issue where the procedure name is long or the screen width is small, allowing the name to wrap onto the next line.

fix(T35874): add white space wrapping for the procedure name

---

client/js/components/procedure/StatementSegmentsList/StatementSegment.vue

**Ticket:** https://yaits.demos-deutschland.de/T35990
**Description:** The badge component had excessive space on the right. It was changed from 320px to 24px.

Fix(T35990): badge position

---

client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue

**Ticket:** https://yaits.demos-deutschland.de/T36011
- the type was incorrect, so the segment was unclaimable

fix(refs:T36011): the resourceType was incorrect

---

demosplan/DemosPlanCoreBundle/Application/Header.php

http2 Standard needs headers to be lowercase. We should adopt this standard. https://httpwg.org/specs/rfc7540.html#HttpHeaders

chore: update headers to match http2 standard

---

demosplan/DemosPlanCoreBundle/Command/Addon/AddonBuildFrontendCommand.php

DX PR to allow frontend assets to be build for a specific addon in a given environment. Might be useful to specifically build addon assets in dev mode. Moreover when the addon name is skipped all enabled addons are suggested to be chosen of

chore: show addons to build frontend for. Allow env to be passed

---

demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php

**Ticket:** https://yaits.demos-deutschland.de/T36035
Description: remove second call for delete entity in statementResourceType

feature (ref 36035): remove second calling method

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_split_statement.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T35883
We don't need the title in the addon. It is only used as page title. If we include it as a prop, the title is added automatically as an attribute to the outer div of the addon component and displayed as tooltip on hover, because the component has no title prop.
Verfahren -> STN aufteilen -> The statement text shouldn't show a tooltip on hover

bug(refs T35883): Remove unnecessary title prop

---

demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php

**Ticket:** https://yaits.demos-deutschland.de/T36053
On coping a original statement (due to submit a draftStatement), the related files, were missing on coping the statement from the original statement.
Create and submit a new statement within attachements/files.
All of them should be appearing on the created original statement as well as on the "normal" statement.

F t36053 files on statement copy

---

client/js/components/statement/originalStatementsTable/OriginalStatementsTableItem.vue

**Ticket:** https://yaits.demos-deutschland.de/T36027
**Description:** Refactor the code to follow the same logic as in the `DpAssessmentTableCard` component (`line: 469 - 470`):
utilize `statement.elementId` to identify the corresponding element in the elements list from the `assessmentTable` store.
`statement.elements` often lacks a value, either being an empty array or containing only one item. This adjustment is made to minimize the use of IF checks as well.

fix(T36027): issue with elements in the OriginalStatementsTableItem component

---

demosplan/DemosPlanCoreBundle/Repository/SegmentRepository.php

Pre-T35348 the text was passed directly into the DQL query, which required quoting it. After the corresponding fix that passes the text value as DQL parameter, this quoting is no longer necessary and in fact results in quotes added to the text itself.

fix (refs T36081): remove unnecessary quoting

---

demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserController.php

Ticket:
https://yaits.demos-deutschland.de/T35857
Description:
adjust userSettings E-mail notification checkbox state for first visitors
of the settings-page
linked PR:
closed as this sprint is fine for deployment
https://github.com/demos-europe/demosplan-core/pull/2583

feature (refs T35857): adjust userSettings E-mail notification checkbox state for first visitors

---

client/js/components/map/publicdetail/Map.vue

**Ticket:** https://yaits.demos-deutschland.de/T36141
As dpApi moved from axios to fetch, params are not added to the request url automagically. As we already have a method to serialize request params of a get request, this can be used.
Request params for the request described in the ticket should be included again.

fix(refs T36141): serialize request params

---

demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php

Newest tag should be show last as the list will grow over time, and it might be inconvenient to scroll up a lot
beginn to install an addon via `bin/<project> dplan:addon:install --github` and find the most recent tag in the second step below

chore: sort addon tags during install via GitHub

---

demosplan/DemosPlanCoreBundle/ValueObject/Statement/DraftStatementListFilters.php

`DraftStatementListFilters` should not implement `ParameterBagInterface` and only use get and has as this is misleading and might even confuse dependency injection
call to draft statement list should work as before

chore: remove useless and misleading Interface

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_boilerplate.html.twig

To improve usability, the checkbox to chose which categories to display a boilerplate in is checked by default now, if only one category exists.
In projects with only one boilerplate category enabled, create a new boilerplate entry. The checkbox should be preselected.
When editing boilerplates, the checkbox should reflect the state saved before.

Select checkbox by default if only 1 boilerplate category is present

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_styled-html.scss

**Ticket:** https://yaits.demos-deutschland.de/T18750
We want empty p tags inside the editor to have the same height as non empty ones for the sake of presentation.
Verfahren -> Abwägungstabelle -> edit statemente text -> Add some empty lines and save -> the empty lines should be displayed

bug(refs T18750): Add min height for editor p tags

---

demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/01/Version20240130051137.php
demosplan/DemosPlanCoreBundle/Entity/Procedure/Procedure.php

**Ticket:** [T36196](https://yaits.demos-deutschland.de/T36196) ([T33120](https://yaits.demos-deutschland.de/T33120))
Fix error on persist newly created phase key, caused by limitation of length of DB-field.
Selection of "Erneute frühzeitige Beteiligung Öffentlichkeit" for the public participation phase should not longer lead to an error.
- https://github.com/demos-europe/demosplan-project-blp/pull/82

Fix new phases of procedure

---

demosplan/DemosPlanCoreBundle/Twig/Extension/LatexExtension.php
tests/backend/core/Core/Unit/Utilities/Twig/LatexExtensionTest.php

**Ticket:** [T35998](https://yaits.demos-deutschland.de/T35998)
Add strike-through to handling html tags, using keyed array  to map html to latex to improve readability and adjust test.
Implementation of marked text on export a statement as PDF will be another PR.
Export a statement wich includes strike-through as format as PDF.

allow strike-through in pdf

---

client/js/store/procedure/SplitStatementStore.js

**Ticket:** https://yaits.demos-deutschland.de/T36246
While checking for overlapping segments we need to exclude the start and end char, because they can be the same for different segments.

bug(refs T36246): Allow char start and char end to be the same

---

templates/bundles/DemosPlanCoreBundle/DemosPlanUser/includes/mastertoeblist_pageheader.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T36190
Description: Removed extra link. The link redirects to the same page that it is appeared.

feature (ref 36190): remove extra link in header

---

demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanMasterToebController.php
demosplan/DemosPlanCoreBundle/Exception/SubmittedStatementsOnMergeOrganisationsException.php
demosplan/DemosPlanCoreBundle/Repository/MasterToebRepository.php
translations/messages+intl-icu.de.yml

**Ticket:** https://yaits.demos-deutschland.de/T36221
Orgas should only be merged if no statement has been submitted from them. As this will anyway not happen in prod instances (only when testing), a simple error message is shown in that case, instead of the "Ein Fehler ist aufgetreten"-Page.
- When trying to merge an organisation, which has already submitted statements (or has saved draftStatements), the above error message should show up. 
- When merging orgas, which do not have statements or draftStatements attached, everything should work as before.

fix(refs T36221): throw error if statements present

---

config/parameters_default.yml
demosplan/DemosPlanCoreBundle/Application/FrontController.php
tests/backend/core-application/app/config/config_test.yml
tests/backend/core-application/src/Application/FrontController.php

Reimplement changes of https://github.com/symfony/recipes/pull/724/files to our customized frontcontrollers
Browsercalls as well as commands should work as before

chore: modernize frontcontrollers to match symfony 5.x

---

demosplan/DemosPlanCoreBundle/Twig/Extension/LatexExtension.php
tests/backend/core/Core/Unit/Utilities/Twig/LatexExtensionTest.php

**Tickets:** (more or less)
[T36015](https://yaits.demos-deutschland.de/T36015)
[T35998](https://yaits.demos-deutschland.de/T35998)
PDF-Export an Statement wich includes highlighted text.
Very close to #2650

allow highlighted text in pdf export

---

client/js/store/procedure/SplitStatementStore.js
client/js/store/procedure/storeHelpers/SplitStatementStore/HTMLIdxToProsemirrorIdx.js

**Ticket:** https://yaits.demos-deutschland.de/T36258 
**Ticket:** https://yaits.demos-deutschland.de/T36246
- While checking for overlapping segments we need to exclude the start and end char, because they can be the same for different segments.
- Add 'br' tag to allowed nodes for prosemirror. We also need to transform 'br' tags to prosemirror positions. 
- Additionally exclude 'br' from markRegex, because otherwise it will be included due to 'b' tag and it will be transformed double (once as node and once as mark).
Cannot be tested locally

bug(refs T36258): fix slicing tagging

---

templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T36269
**Description:** Remove the mark as insert and delete functions from the editor on the new statement page.

ref(T36269): remove the insert and delete functions from the editor

---

client/js/components/procedure/basicSettings/AutoSwitchProcedurePhaseForm.vue

**Ticket:** https://yaits.demos-deutschland.de/T36196
**Description:** Procedure phases with the write permission should have auto-switch activated by default. Here is a list of the [procedure phases](https://github.com/demos-europe/demosplan-project-blp/blob/main/app/Resources/DemosPlanCoreBundle/config/procedure/procedurephases.yml) in blp project.
[Thread](https://demosdeutschland.slack.com/archives/C8M7GFXTP/p1706551936339009) in Slack

fix(T36196): procedure phase with write permission should have auto-switch activated by default

---

client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
client/js/lib/procedure/CreateProcedure.js

**Ticket:** https://yaits.demos-deutschland.de/T36189
Moving the saveBtn declaration outside of the fn declaration led to it being undefined as CreateProcedure() runs before the vue component is mounted which contains the markup.
When selecting the procedure "Bergedorf113" in the "New proceuder" view, the Planungsanlass should be displayed.

fix(refs T36189): show "planungsanlass"

---

client/js/components/news/DpNewsAdminList.vue
client/js/components/statement/assessmentTable/DpBulkEditStatement.vue

**Ticket:** https://yaits.demos-deutschland.de/T36230
Add a check response for DpApi call, so the user does not get a validation message when the api call was not succesfull.
Verfahren -> Aktuelles -> Toggle Status -> There should be an error message if the api call was not successfull

bug(refs T36230): check response api call

---

demosplan/DemosPlanCoreBundle/Entity/User/User.php
demosplan/DemosPlanCoreBundle/Logic/OwnsProcedureConditionFactory.php
demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
demosplan/DemosPlanCoreBundle/Logic/ProcedureAccessEvaluator.php
demosplan/DemosPlanCoreBundle/Logic/Statement/NonAuthorizedAssignRemover.php

Enhance the `OwnsProcedureConditionFactory` implementation, so that it can not only create conditions to match unknown users against a known procedure, but also to match unknown procedures against a known user. Logically the comparison is the same in both cases, but their implementation differs significantly.
Keeping the implementations as close together as possible avoids divergences, like were already present in
`ProcedureService::getAdminProcedureConditions`. The matching logic in this method behaved very similar to the one executed via `ProcedureAccessEvaluator::isOwningProcedure` (which uses `OwnsProcedureConditionFactory`), but was not exactly the same, causing a bug. Hence, `isOwningProcedure` was selected as "truth" and the logic in `getAdminProcedureConditions` was dropped. …

fix (refs T30474): reduce inconsistent code duplication

---

package.json
yarn.lock

chore: Update demosplan-ui to v0.3.6

---

demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php

**Ticket:** https://yaits.demos-deutschland.de/T36454
Description:  convert paramater to string: the value of $formattedStatement[$attributeKey] can be type int that's why it have to be converted

f T36454 convert paramater to string

---

demosplan/DemosPlanCoreBundle/ResourceTypes/SignLanguageOverviewVideoResourceType.php

Ticket:
https://yaits.demos-deutschland.de/T36452
Description:
adjust ResourceType::getProperties return type to also allow ResourceConfigBuilder

fix (refs T36452): adjust ResourceType::getProperties return type to also allow ResourceConfigBuilder

---

client/js/components/statement/publicStatementModal/StatementModal.vue

Ticket:
https://yaits.demos-deutschland.de/T36342
Description:
New PR pointing to release...
Old one was approved here https://github.com/demos-europe/demosplan-core/pull/2714
disable the option to add planningDocuments when negative report is selected
The file documentation/benutzerhandbuch/verfahrenstraeger/verfahren-einrichten/planungsdokumente.md points out that
`warning Hinweis Die Kategorien Gesamtstellungnahme, Fehlanzeige und Planzeichnung können nicht mit Dokumenten versehen werden.`

fix (refs T36342): disable element.assign when negative report is selected

---

demosplan/DemosPlanCoreBundle/ResourceTypes/CustomerLoginSupportContactResourceType.php

**Ticket:** https://yaits.demos-deutschland.de/T36461
Description: Fix wrong naming of function `isCreatable`. Base on parent should be `isCreateAllowed`
login as mandanten Admn, in Platform setting, try to create, edit, delete the field: Kontakt für fehlende Berechtigungen

feature (ref 36461): fix wrong naming for function in resourcetype

---

demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php

**Ticket:** https://yaits.demos-deutschland.de/T36467 
Description: adjust parameters type: the method 'setSimilarStatementSubmitters' need an doctrine array collection parameter not an array

f T36467 Error when deleting other submitters of the same statement

---

config/permissions.yml
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T32892
Description: created new procedure, should have required field of contact person, because of that we need a new permission to set default value of that
set new procdure and if not set contact person under information of procedure in procedure setting, user can not save it.

feature (ref 32892): set permission to required contact person

---

demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php

**Ticket:** https://yaits.demos-deutschland.de/T36440
Description: check whether similar statement submitters even exist before adding text

f T36440 Additional submitters should only be displayed if they have been specified

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T36474
**Description:**  This update adds the `data-dp-validate-error-fieldname` attribute to mandatory fields on the administration page, improving error validation

fix(T36474): improve error validation on the administration page

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T36473
**Description:** Enhance user experience by implementing a clear indicator to highlight mandatory field.

fix(T36473): add an indicator for the mandatory field

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T36509
- Remove empty html comment which is breaking the site if the permission is not enabled
- Add twig whitespace control to trim any whitespace before or after the tag (`{%- ... -%}`)
Verfahren -> Grundeinstellungen -> Informationen zum Verfahren -> Menu should be on the right side and more topics and save button should appear beneath "Informationen zum Verfahren"

bug(refs T36509): Remove empty comment which is breaking the site

---

client/js/components/support/DpSupportCard.vue

**Ticket:** https://yaits.demos-deutschland.de/T35058
**Description:** To avoid breaking the layout, add the `break-words` class to handle/display too long email addresses.

Fix(T35058): long emails break the layout

---

config/packages/monolog.yaml
config/packages/nelmio_security.yaml
config/parameters_default.yml
config/services.yml

There is no need to have these huge amount of different channels. Finally we need to log everything to stderr in container context, this simplification is a step towards it.
ADO AB#14019
do anything in dev and prod mode and follow logs or code review

chore: simplify logger

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_unregistered_publicagency_email.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T36557
Description: Adjustment the name of twig.

feature (ref 36557): fix the address of include twig

---

client/js/components/support/DpSupportCard.vue
client/js/components/user/CustomerSettings/CustomerSettingsSupport.vue

**Ticket:** https://yaits.demos-deutschland.de/T35058
Description: use class break-words to handle big inserted data in support fields
as client administrator, the large inserted data in Content Support should remain in the frame
in the information page, the large inserted data should no longer be the size of the frame

feature (ref 34305): use break class to handle big insert data

---

client/js/components/support/DpSupportCard.vue
client/js/components/user/CustomerSettings/CustomerSettingsSupport.vue

**Ticket:** https://yaits.demos-deutschland.de/T35058
Description: use class break-words to handle big inserted data in support fields
as client administrator, the large inserted data in Content Support should remain in the frame
in the information page, the large inserted data should no longer be the size of the frame

feature (ref 35058): adjustment long data issue in release

---

client/js/lib/map/GisLayerEdit.js
templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_edit.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_new.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T23768
- Fix regex pattern for opacity. Period is a special character in regex and needs to be escaped (double escape because backslash is a special character in twig and needs to be escaped). Remove redundant pipe that causes error
- Disable opacity settings for base maps, because the opacity should always be 100%. 
Verfahren -> Antragsunterlagen -> Kartenebenen definieren -> Neue Kartenebene oder Kartenebene bearbeiten -> If Grundkarte is selected opacity should be disabled and 100%. Also check if regex for opacity is applied correctly when selecting Overlay (you should be able to put 0-100 in with two decimals (`.` or `,`).

bug(refs T23768): Disable opacity for base map

---

client/js/components/map/publicdetail/Map.vue

**Ticket:** https://yaits.demos-deutschland.de/T36457
Although this is an edge case we have to handle it: if a layer that is set as print layer becomes disfunctional (maybe because the service is discontinued), it must not break the frontend.
Set a non-working layer as print layer, try to draw in the public detail map -> it should work.

fix(refs T36457): prevent corrupt layers from breaking draw fn

---

client/js/components/map/map/DpOlMap.vue
client/js/components/statement/assessmentTable/DpMapModal.vue

**Ticket:** https://yaits.demos-deutschland.de/T36055
When using DpOlMap without this._options.procedureExtent being set to true, the default extent set in map_max_boundingbox should be used. This extent has to be set via props.
See ticket for reproduction steps.

fix(refs T36055): correctly fallback to defaultMapExtent

---

templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_public_participation_detail.html.twig

Ticket:
https://yaits.demos-deutschland.de/T15681
Description:
Only show legend of layer if the layer is enabled and contains a legend file
previously only the layer contains file check was active.
Verfahren->Planunterlagen und Planzeichnung->Planzeichenerklärung hochladen->
either:
you upload a legend and switch to the public-view and check if the legend box gets displayed... go back and delete the legend and check again...
or:
you edit a baselayer -> attach a legend file and then check the public view depending on the layer being set to enabled or disabled. The legend box should only show up - if the layer contains a legend and is enabled.

fix (refs T15681): Only show legend of layer if the layer is enabled and contains a legend file

---

demosplan/DemosPlanCoreBundle/Logic/HttpCall.php
tests/backend/core/Core/Functional/HttpCallTest.php

HttpClient needs to be a bit more robust regarding the configuration params, spaces should be trimmed

chore: trim Proxy params

---

composer.lock
demosplan/DemosPlanCoreBundle/Entity/User/User.php

Ticket:
https://yaits.demos-deutschland.de/T30474
Description:
Use interfaces instead of entities as method parameters in core-entities implementing demosplan-addon interfaces.
update composer.lock due to changes in demosplan-addon
https://github.com/demos-europe/demosplan-addon/pull/93

fix (refs T30474): Use interfaces instead of entities as method parameters in core-entities implementing demosplan-addon interfaces

---

client/js/bundles/procedure/publicIndexNoMap.js

**Ticket:** https://yaits.demos-deutschland.de/T36464
Some projects may prefer not to filter procedures
when loading the public index page. This is now supported via dropping a `data-default-selected="all"` on the select element. In future iterations, other keys may be used to set another default filters.
When loading the public index page in a project that uses `publicIndexNoMap.js` for its view, applying `data-default-selected="all"` to the select element with the id `filterPhases` should lead to no option being selected automagically.

Allow for opting out of default filter of procedures on public_index 

---

templates/bundles/DemosPlanCoreBundle/DemosPlanUser/includes/mastertoeblist_pageheader.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T36387
Description: set a link for master toeb list changes in top of master toeb list page

feature (ref 36387): set master toeb list changes link

---

client/js/components/procedure/admin/AdministrationProceduresList.vue

**Ticket:** https://yaits.demos-deutschland.de/T36396
Cherrypicked from https://github.com/demos-europe/demosplan-core/pull/2620
Dates should correctly reflect the Day the procedures were created.

Fix(refs:36153): use the correct access for the dates (#2620)

---

client/js/store/statement/Statement.js
demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/StatementResourceConfigBuilder.php

**Ticket:** https://yaits.demos-deutschland.de/T36582z
Description:
- Set ToOneRelationshipConfigBuilderInterface in the $element. It was configured to ToManyRelationshipConfigBuilderInterface. When the $element is null, it breaks. Now it does not.
Context:
- Abwägungstabelle does not load because the Procedure has Statements with no PlanungsDokumenten
- The PlanungDokumenten are this _st_element_id FK in the statement table. When _st_element_id is null, the Abwägungstabelle does not load
- This happens because element is defined as ToManyRelationshipConfigBuilderInterface but in reality it should be  ToOneRelationshipConfigBuilderInterface.
- Go to Bebauungsplan Nr. 3 Supermarkt Kleinstadt-West Verfahren
- Click on "new"
- The Abwägungstabelle should load now
Delete the checkbox if it …

bug (ref T36592) Adjust "element" in include for API request so EDT can understand and match the entity

---

demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/StatementResourceConfigBuilder.php

Same as this PR only for release: https://github.com/demos-europe/demosplan-core/pull/2794
**Ticket:** https://yaits.demos-deutschland.de/T36582z
Description:
- Set ToOneRelationshipConfigBuilderInterface in the $element. It was configured to ToManyRelationshipConfigBuilderInterface. When the $element is null, it breaks. Now it does not.
Context:
- Abwägungstabelle does not load because the Procedure has Statements with no PlanungsDokumenten
- The PlanungDokumenten are this _st_element_id FK in the statement table. When _st_element_id is null, the Abwägungstabelle does not load
- This happens because element is defined as ToManyRelationshipConfigBuilderInterface but in reality it should be  ToOneRelationshipConfigBuilderInterface.
- Go to Bebauungsplan Nr. 3 Supermarkt Kleinstadt-West …

bug (ref T36592) Adjust ToOneRelationshipConfigBuilderInterface for element

---

demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php

**Ticket:** https://yaits.demos-deutschland.de/T36600
Description: Save data like (user name, department name, orga name, zip code, city) in statement vote to can show them in statement detail page
as an Institute vote the statement, and then you should, can see the info about voter in statement detail.

feature (ref 36600): set some missed columns

---

client/js/components/procedure/basicSettings/AutoSwitchProcedurePhaseForm.vue
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T36196
By passing the permission into AutoSwitchProcedurePhaseForm, we do not need to maintain a list of keys
within the component. this is less error-prone, in case phases are added or removed later.
In the basic settings view (blp), select "Verfahrensschritt Institutionen" >  Verfahrensschritt "erneute öffentliche Auslegung". The checkbox "Verfahrensschritt automatisch umstellen" should be checked and disabled automatically, as it is for other write-procedurePhases.
- https://github.com/demos-europe/demosplan-core/pull/2652

Check all write phases in AutoSwitchProcedurePhaseForm

---

demosplan/DemosPlanCoreBundle/Permissions/Permissions.php

Ticket:
https://yaits.demos-deutschland.de/T36617
Description:
prevent a permission check via onKernelEvent before permissions are initialized.
https://demosdeutschland.slack.com/archives/CDYHJ0P41/p1709540989391119?thread_ts=1709298531.199759&cid=CDYHJ0P41

fix (refs T36617): prevent a permission check via onKernelEvent before permissions are initialized.

---

config/permissions.yml
templates/bundles/DemosPlanCoreBundle/DemosPlanUser/portal_profile.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T36588
Description: Institution_Sachbearbeitung and Fachplaner-Sachbearbeiter (PLANNING_AGENCY_WORKER and PUBLIC_AGENCY_WORKER) should not have a save/cancel option in my data form, because of that I created a new permission and use that in every project
go to mein Daten and check these roles have those options or not

feature (ref 36588): create a permission for profile edit

---

demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php
demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php

**Ticket:** https://yaits.demos-deutschland.de/T36711
In real application problems occurred with nested html that let the docx exporter explode. By purifying the text we can avoid those problems and still keep the formatting.
code review might be best as no reproducer could yet be found

chore refs T36711: purify text to avoid errors in docx export

---

demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_switcher.scss

**Ticket:** https://yaits.demos-deutschland.de/T36638
The surrounding container seems to not apply a margin anymore, so there is no need for the negative margin anymore.
should look like this:

fix(refs T36638): remove obsolete negative margin

---

demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php

Ticket:
https://yaits.demos-deutschland.de/T36528
Description:
Adds similar stn submitters to statement list docx export(s)
The FE allert still needs to be done:
logic present in: ```client/js/components/statement/listStatements/ListStatements.vue Zeile 50 showHintAndDoExport```
needs to be implemented to ```client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue Zeile 71 mit @click.prevent```
How To Test:
- [  ] Move the tickets on the board accordingly

F t36528 add similar stn submitters to statement list export

---

demosplan/DemosPlanCoreBundle/Controller/Help/DemosPlanHelpController.php
templates/bundles/DemosPlanCoreBundle/DemosPlanHelp/help_admin_contextual_help_list.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T36718
- when no checkbox selected and delete button clicked, there is an error message
- after reload the page the same error message shouldnt appear again

Fix(refs:T36718): wrong message after click delete and reload

---

Jenkinsfile

**Ticket:** https://yaits.demos-deutschland.de/T36496
At some point, the default directory for yarn caches got moved from ~/.cache/yarn to /usr/local/share/yarn. This led to the shared cache directory no longer containing the yarn caches and subsequently to a massive increase in inode usage during CI builds of several distinct branches.
- Check the Jenkins Builds for this branch
- Check that on the builder server, /var/cache/demosplanCI/yarn exists

build(refs T36496): Configure yarn cache dir for CI

---

client/js/components/document/ElementsList.vue
demosplan/DemosPlanCoreBundle/Entity/Document/Elements.php
demosplan/DemosPlanCoreBundle/ResourceTypes/PlanningDocumentCategoryResourceType.php

**Ticket:** https://yaits.demos-deutschland.de/T27465
- only documents with the attribute `visible` set to `true` should be displayed in the list
- normally, this is filtered in the backend, but if the user `hasPermission('area_admin_single_document')`, documents are not
filtered, so all documents are displayed
- since we can't currently filter the relationships of a resourceType via json api request, we decided to add a new relationship
`visibleDocuments` that is now used instead of `documents`

fix(refs T27465): display only documents that should be visible

---

client/js/components/statement/publicStatementModal/StatementModalRecheck.vue

**Ticket:** https://yaits.demos-deutschland.de/T36753
As not logged in user, write a statement a proceed to the "recheck"-view in the statement modal. There, the statement text should be displayed and readable.

fix(refs T36753): use full width to display the stn text

---

demosplan/DemosPlanCoreBundle/Logic/Statement/StatementFilterHandler.php

**Ticket:** https://yaits.demos-deutschland.de/T26867
Description: the permission 'feature_documents_category_use_paragraph' is used while creating a new document category to check if it's chapter related which can not be the case in planfest (there are nor chapter in this project). The same permission can be used too while getting the available filters to make sure that's chapter are not included.

f T26867 remove chapter (kapitel) from statement filter

---

client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
client/js/store/statement/Statement.js

getting the proper include fixes finishing the loading process because now the field-name matches the include name. With that the code enters the relevant condition.
**Ticket:** https://yaits.demos-deutschland.de/T36689
See Ticket to reproduce the bug(fix)

fix(refs T36689): document attribute name has to be without s

---

demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanAssessmentController.php

**Ticket:** https://yaits.demos-deutschland.de/T15290
Description: the method (`remmemberFilters`) used just in two methods  `getStatementFragmentListAction` and `getStatementFragmentListArchiveAction` in the `DemosPlanAssessmentStatementFragmentController`, this `else` in the method save session and used it in another page. For example, if we set filter in Datensätze and then go to Datensätze-Archive, the filter applies the wrong value in the new page.
login as an FP-FB and set filter in Datensätze then go to Datensätze-Archive, filter should not run in new page.

feature (ref 15290): remove session between pages.

---

demosplan/DemosPlanCoreBundle/Logic/Statement/StatementFragmentService.php

**Ticket:** https://yaits.demos-deutschland.de/T15938
Description: Export PDF from data records archive (Datensätze-Archive) has some missed Variable like (Tag, County, …). I used just right key for right value.

feature (ref 15938): use right key to show variable in pdf export

---

client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue

**Ticket:** https://yaits.demos-deutschland.de/T36528
To be consistent, we want to have confirm messages for all stn-docx-exports. There was one missing on the stn-detail page.
this here is implemented like here https://yaits.demos-deutschland.de/T35722 // https://github.com/demos-europe/demosplan-core/pull/2433

feat(refs T36528): add message to confirm export.

---

package.json

As this would delete the local git repo when running "yarn install", the "preinstall" hook cancels the installation. This is implemented as a oneliner to not have to think about a good place for the bash script. As we do not have the "docker" cli in the container, "cat proc/mounts" is used to determine if the specific volume is mounted.
When running "yarn install" from within the container with demosplan-ui mounted as volume, the installation process should fail with this error:
When the volume is not mounted, "yarn install" should run as usual.

abort "yarn install" if demosplan-ui is mounted in container

---

client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
client/js/components/statement/assessmentTable/EditableText.vue

**Ticket:** https://yaits.demos-deutschland.de/T36652
The fix applied in #2521 introduced the side effect that the ref="recommendation" was undefined while the loading state was applied to the EditableText instance, and so, the `field` property was not correctly filled within the payload of the entityTextSaved event. As the bug originates in a change in dpApi, #2521 is partially rolled back. Instead, the params in dpApi.get() are now serialized, with the result that the `shortened` attribute is present in the response and the code in client/js/components/statement/assessmentTable/EditableText.vue:355 runs so that and everything is updated as intended.
In the assessment table, statement text and recommendation should both be editable and display the correct values after saving. also, the …

fix(refs T35941): rollback partial fix, serialize params

---

client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
client/js/components/statement/assessmentTable/EditableText.vue

**cherry picked from commit 40a4f0eb6d9599fc0a7078f293ca04a581d8c820**
The fix applied in 2521 introduced the side effect that the ref="recommendation" was undefined while the loading state was applied to the EditableText instance, and so, the `field` property was not correctly filled within the payload of the entityTextSaved event. As the bug originates in a change in dpApi, 2521 is partially rolled back. Instead, the params in dpApi.get() are now serialized, with the result that the code in
client/js/components/statement/assessmentTable/EditableText.vue:355 runs and everything is updated as intended.
**Ticket:** https://yaits.demos-deutschland.de/T35941

fix(refs T35941): rollback partial fix, serialize params (2847)

---

client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue

**Ticket:** https://yaits.demos-deutschland.de/T36635
**Description:** To improve the UX and provide information about invalid fields, add the prop called `dataDpValidateErrorFieldname`. This prop is needed for the `dpValidate` mixin to display the correct error message with the invalid fields.
[PR in demosplan-ui](https://github.com/demos-europe/demosplan-ui/pull/783)

Fix(T36635): improve error validation for DpMultiselect component

---

client/js/components/procedure/SegmentsList/FilterFlyout.vue
demosplan/DemosPlanCoreBundle/Logic/Segment/RpcSegmentFacetsProvider.php

**Ticket:** https://yaits.demos-deutschland.de/T27469
Description:
It is possible to filter by unassigned segments. This needs adjustments in the FE and in the BE.
The BE uses Elastic Search with Facets to group by assignee ids. Given that filtering segments by assignee = NULL is not possible using Facets, there is the need of the FE to send a particular filter using "IS NULL".
The BE is supposed to tell FE what filter was selected based on the assignee id. Given that there is not assigneeId, a new meta field was introduced in the RPC request to let the FE know that unassigned filter was selected.
- Go to Regio > select a Prcoedure (Verfahren), and then Abschnitten
- Select Bearbeiter*in filter (in each filter should be the number of segmenter corresponding to the filter)
-- Select an …

feat (refs T27469): Filter by unassigned segments.

---

templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/pageheader.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig

**Ticket:**  https://yaits.demos-deutschland.de/T36849
- `flow-root` unexpectedly overwrote the display property (to `block`) which is desired in most projects, but not in all of them
- it is replaced with 'block' and passed to the pageheader as a variable, so in projects that display the link inline, we can just use the pageheader template as is
- vertical margin of the link has been adjusted so it aligns properly with the procedure title in projects that display link and procedure title inline

fix(refs T36849): display link inline

---

templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/pageheader.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig

**Ticket:** https://yaits.demos-deutschland.de/T36849
- as there can be several links next to each other when a user is logged in, the procedure title cannot be displayed inline because the links take up more space than the actionbox (width-map-toolbar), breaking the layout
- we decided to keep the layout consistent among all projects and always display the procedure title below the link(s)

fix(refs T36849): display procedure title below link(s)

---

demosplan/DemosPlanCoreBundle/Controller/Platform/FileController.php
templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/includes/item/files.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_cluster_detail_statement_data.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement_detail_statement_data.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_edit.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_global_edit.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_list.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_master.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/includes/public_statement.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/DemosPlanAssessment/view_statement.html.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/includes/listentry_content.html.twig

For improved security we should use `core_file_procedure` instead of `core_file` whenever possible. I checked the remaining calls of `core_file` and adjusted them if they are in procedure context. I tested all the cases in the interface
code review or check the cases in the interface

Harden file downloads

---

client/js/components/addon/AddonWrapper.vue

As the addonWrapper should not occupy any space within the rendered layout by itself (maybe if no addons are registered with it), the wrapping div can eventually be removed.
Things should work as before, with and without installed addons.

Remove wrapping div from addonWrapper

---

demosplan/DemosPlanCoreBundle/Logic/User/UserService.php

There is no need to implement a security feature when we can use an existing method that uses php core hash method. Logic is changed slightly, now a user is created with a 10 char password just like any other user that is created and not 128 chars, as before. This should be sufficient. 

chore: use existing password create function

---

client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
client/js/components/statement/assessmentTable/EditableText.vue

The fix applied in 2521 introduced the side effect that the ref="recommendation" was undefined while the loading state was applied to the EditableText instance, and so, the `field` property was not correctly filled within the payload of the entityTextSaved event. As the bug originates in a change in dpApi, 2521 is partially rolled back. Instead, the params in dpApi.get() are now serialized, with the result that the code in
client/js/components/statement/assessmentTable/EditableText.vue:355 runs and everything is updated as intended.
(cherry picked from commit 40a4f0eb6d9599fc0a7078f293ca04a581d8c820)
Co-authored-by: spiess-demos <40452344+spiess-demos@users.noreply.github.com>
(cherry picked from commit cf58250a13dc6c6b950f0576452a1b39ce1d6d7c)
**Ticket:** …

fix(refs T35941): rollback partial fix, serialize params (2847) (2859)

---

composer.lock

**Ticket: ** https://demoseurope.youtrack.cloud/issue/DPLAN-3274/5-2-Part-1-Durchgangsnummer-zu-Verfahrensschritten-hinzufugen
update demosplan-addon v0.29

feat (DPLAN-3274): update demosplan-addon v0.29

---

demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php

Description: Phpstan level 1 :
```
Line   DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php  
------ -------------------------------------------------------------------- 
143    Call to private method addSimilarStatementSubmitters() of class     
demosplan\DemosPlanCoreBundle\Logic\Segment\SegmentsExporter.       
------ --------------------------------------------------------------------                                                                                
[ERROR] Found 1 error
```
bin/projectname dp:phpstan -l 1

feature: change method from private to protected

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig

allow only numbers and not `0`
https://demoseurope.youtrack.cloud/issue/DPLAN-11392/Falsche-Reaktion-beim-Eintragen-ungultiger-Daten-im-Feld-fur-Durchgangsnummer
In "Grundeinstellungen" try to change the iterator (Durchgangsnummer). For internal and external only numbers should be valid and `0` should be unvalid

fix(refs DPLAN-11392): Add Pattern to iterator input

---

client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_statement_segments_list.html.twig

**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-3217
We want to have only one statement detail view. Here following fields from the old twig template (`templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement_detail_statement_data.html.twig`) are added to the combined vue component:
-  `submitterRole`: Shows if statement is submitted by citizen or institution. Slightly changed logic from old template: Now only shows translation for citizen or institution and not institution name, because we already have an extra field for institution name.
-  help text for submitter name if submitter is anonymous 
- add more logic for submitter/author name: Field is also disabled if submitter is anonymous. Make submitter value and event name …

feat(refs DPLAN-3217): Merge statement detail views

---

composer.lock
demosplan/DemosPlanCoreBundle/Repository/ProcedurePhaseRepository.php

**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-11355/DiPlanBeteiligung-generiert-korrekte-XBeteiligung-Nachrichteninhalte-fur-die-Raumordnung
This will add two new functions to the ProcedurePhaseRepository for getting a procedure by a given phase id.
Code Review
- [demosplan-addon](https://github.com/demos-europe/demosplan-addon/pull/100)
- [demosplan-addon release v0.30](https://github.com/demos-europe/demosplan-addon/pull/101)

feat (DPLAN-11355): get procedure by phase id

---

demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTablePdfExporter.php
demosplan/DemosPlanCoreBundle/Logic/Statement/DraftStatementService.php
demosplan/DemosPlanCoreBundle/Twig/Extension/LatexExtension.php
templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_entry.tex.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_entry_condensed.tex.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_original_entry.tex.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry_paragraph.tex.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry_public_citizen.tex.twig
tests/backend/core/Core/Unit/Utilities/Twig/LatexExtensionTest.php

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-1924/Munchen-Prod-PDF-Export-eingereichter-STN-in-Bestatigungsmail-wird-falsch-dargestellt
Description:
See https://github.com/demos-europe/demosplan-core/pull/2905
Create draft statements icluding lists with text longer than 7cm.
download your drafts as pdf....
hand them in to get a proper stn and download that as pdf...

F (refs dplan 1924) change default ul latex pdf line width (#2929)

---

demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
demosplan/DemosPlanCoreBundle/Repository/ProcedureRepository.php

**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-11355/DiPlanBeteiligung-generiert-korrekte-XBeteiligung-Nachrichteninhalte-fur-die-Raumordnung, https://demoseurope.youtrack.cloud/issue/DPLAN-11398/Es-wird-eine-XBeteiligung-Update-Nachricht-vor-Create-Nachricht-erstellt
These changes are needed to avoid that the ProcedurePhase Entity will be as updated in onFlush events.
Code Review
- https://github.com/demos-europe/demosplan-addon-xbeteiligung-async/pull/20

feat (DPLAN-11355): trigger no update for procedure phases during procedure creation

---

demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTablePdfExporter.php
templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_entry_anonymous.tex.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_entry_anonymous_condensed.tex.twig
templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_fragments_anonymous.tex.twig

**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-1924/Munchen-Prod-PDF-Export-eingereichter-STN-in-Bestatigungsmail-wird-falsch-dargestellt

F dplan 1924 adjust anonymous export templates

---

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_send_invitation_email.html.twig

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-11404/BLP-Hausnr.-aus-Daten-der-Organisation-wird-nicht-in-Hinweistext-an-Email-ubernommen
Description:
add Orga.Address.HouseNumber to eMail-invitation templates in addition to the street property
login as 'Institutions-Koordination' and add a housenumber to the organisation details.
goto 'Institutionen verwalten' (add one if there is none yet) and send an invitation... check the preview text.

fix (refs DPLAN-1140): add Orga.Address.HouseNumber to eMail-invitation templates in addition to the street property

---

package.json
yarn.lock

When reworking TagSelect to use demosplan-ui instead of directly using vue-multiselect in https://github.com/demos-europe/demosplan-addon-demospipes/pull/88, removing the dependency was forgotten as it seems. This is done here.

chore: remove vue-multiselect as direct dependency

---

client/js/components/procedure/basicSettings/AutoSwitchProcedurePhaseForm.vue
client/js/components/procedure/basicSettings/DpBasicSettings.vue
client/js/components/procedure/basicSettings/ParticipationPhases.vue
client/js/lib/procedure/AdministrationMaster.js
templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
tests/frontend/unit/ParticipationPhases.spec.js

https://demoseurope.youtrack.cloud/issue/DPLAN-11402/Hinweis-Grundeinstellungen-Angaben-der-Rechte-zu-Verfahrensschritten-fehlen
https://demoseurope.youtrack.cloud/issue/DPLAN-11403/Layout-in-Grundeinstellungen-nicht-einheitlich
To fix the Bug, I hat to move the logic from twig and wrapper to a dedicated Component.
Goto Grundeinstellungen and change the phases. See if the Permission text is displayed and makes sense.

fix(refs dplan-11402, dplan-11403):  Refactor logic to display Permissions for selected Phase

---

demosplan/DemosPlanCoreBundle/Logic/Procedure/PrepareReportFromProcedureService.php

**Ticket:** [DPLAN-11392](https://demoseurope.youtrack.cloud/issue/DPLAN-11393/Durchgangsnummer-und-Anderungen-werden-nicht-im-Protokoll-berucksichtigt)
Fix detection of change of public phase of procedure to ensure report entry will be created.

feat (DPLAN-11392): fix detection of change of public phase change
