demosplan/DemosPlanCoreBundle/Resources/static/js_licenses.json, demosplan/DemosPlanCoreBundle/Resources/static/php_licenses.json, licenses/js_licenses.txt, licenses/php_licenses.txt, licenses/system.txt
Vendor licenses needs to be updated by `bin/<project> dplan:vendorlist:update`
=> Update vendor licenses

demosplan/DemosPlanCoreBundle/Resources/config/packages/fos_elastica.yaml
**Ticket:** https://yaits.demos-deutschland.de/T30885
Wrong format caused by "magic"merge
=> fix broken ES configuration, caused wrong format, caused by merge

templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/includes/actionbox.html.twig
https://yaits.demos-deutschland.de/T30892
- Add Hook/Selector.
=> chore (refs T30892): Add Hook/Selector.

client/js/InitVue.js, client/js/store/core/NotificationStoreAdapter.js
https://yaits.demos-deutschland.de/T30968
- Add NotificationStoreAdapter to client/js/store.
- remove this file from demosplan-ui.
=> chore (refs T22614): Add NotificationStoreAdapter to client/js/store.

yarn.lock
https://yaits.demos-deutschland.de/T27479
- Since demosplan-ui v0.0.9 contains the fix for this bug, the release branch needs to be updated accordingly
https://github.com/demos-europe/demosplan-ui/pull/73
(PR has already been reviewed and is already merged in main)
=> bug(refs T27479): update demosplan-ui to implement the fix

.gitignore, addons/.gitignore, demosplan/DemosPlanCoreBundle/Addon/AddonAutoloading.php, demosplan/DemosPlanCoreBundle/Addon/AddonBundleGenerator.php, demosplan/DemosPlanCoreBundle/Addon/AddonInfo.php, demosplan/DemosPlanCoreBundle/Addon/AddonManifestCollection.php, demosplan/DemosPlanCoreBundle/Addon/AddonRegistry.php, demosplan/DemosPlanCoreBundle/Addon/Composer/PackageInformation.php, demosplan/DemosPlanCoreBundle/Addon/FrontendAssetProvider.php, demosplan/DemosPlanCoreBundle/Addon/LoadAddonInfoCompilerPass.php, demosplan/DemosPlanCoreBundle/Addon/ManifestConfiguration.php, demosplan/DemosPlanCoreBundle/Addon/Registrator.php, demosplan/DemosPlanCoreBundle/Application/DemosPlanKernel.php, demosplan/DemosPlanCoreBundle/Command/Addon/AddonBuildFrontendCommand.php, demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php, demosplan/DemosPlanCoreBundle/Command/CoreCommand.php, demosplan/DemosPlanCoreBundle/Exception/AddonException.php, demosplan/DemosPlanCoreBundle/Permissions/Permissions.php, demosplan/DemosPlanCoreBundle/Resources/config/services.yml, tests/backend/core-application/app/config/config_test.yml
Installing and loading Addons in demosplan is a tedious multistep process.
Some actions happen on the file system, some in Composer, some in Symfony.
Of the actions in Symfony, some need to occur during the container compile
step, some always and some after.
Previously, all of this was more or less mangled into the AddonRegistry
and the AddonInstallFromZipCommand. This commit is a step towards cleaning
things up and making the process a little more understandable and in
consequence hopefully also more maintainable.
As of now, to install an addon zip bundle (installation via pure
composer package is still not fully implemented), the AddonInstallFromZipCommand
has the logic for
- unarchiving the zip to the addons cache (which, as a reminder, is only
responsible for storing zipped addons and …
=> Refactor addon registration and installation

client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue, client/js/components/statement/assessmentTable/Fragment.vue, templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig, templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/shared/v1/assessment_statement_detail_statement_text.html.twig, templates/bundles/DemosPlanStatementBundle/DemosPlanStatement/includes/fragment_statement_form.html.twig
https://yaits.demos-deutschland.de/T30977
- adjust obscure props with Permission in Editor.
=> F t30977 edit permission components in demosplan UI

demosplan/DemosPlanProcedureBundle/Logic/SubmitterExporter.php
Ticket:
https://yaits.demos-deutschland.de/T31162
Description:
changed the order of columns to match the required ones.
Adjusted the alignment to match the others and look more uniform.
=> feature (refs T64495): fix order of columns for submitter exports.

demosplan/DemosPlanReportBundle/Logic/ExportReportService.php
Ticket:
https://yaits.demos-deutschland.de/T31157
Description:
Add deletion of statements to procedure report export by simply adding the category for the db-query.
This change counts for all projects as approved in https://demosdeutschland.slack.com/archives/CUZTNDTUH/p1675168703756689
=> feature (refs T31157): added deletion of statements to procedure report export

client/js/components/procedure/SegmentsBulkEdit/SegmentsBulkEdit.vue
**Ticket:** https://yaits.demos-deutschland.de/T28038
**Description:** This PR changes the order in the bulk edit (step 1). The place/status section should be placed above the 'add tags' section.
=> refac(T28038): bulk-edit: change placement of place/status section

demosplan/DemosPlanCoreBundle/Command/Data/RemoveUserDataCommand.php
Initially the only purpose was to get rid of the useless `|| !is_array($message)` in `RemoveUserDataCommand.php:923`. Along the way I needed to reduce code duplication and code complexity to get the change through sonarcloud
Code review or use `RemoveUserDataCommand`
=> refactor: reduce method complexity and duplication

templates/bundles/DemosPlanStatementBundle/DemosPlanStatement/new_public_participation_statement_vote.html.twig
**Ticket:** https://yaits.demos-deutschland.de/T31229
Adds wysiwyg filter to display html properly
=> fix(refs T31229): add wysiwyg filter

client/js/components/map/publicdetail/Map.vue
after fixing and refactoring the measuretools we have overseen an undefined variable which was forgotten to move to the instance state. Doing this forced me to move several other variables and methods too while this makes the fix a bit large it moves the code in the right direction
**Ticket:** https://yaits.demos-deutschland.de/T31275
=> fix(refs T31275): Fix-refactor measuretools

templates/bundles/DemosPlanStatementBundle/DemosPlanAssessment/cluster_detail.html.twig
**Ticket:** https://yaits.demos-deutschland.de/T25762
This has been forgotten when removing spacing from buttons.
=> Add spacing to button row

client/js/components/map/publicdetail/Map.vue
after fixing and refactoring the measuretools we have overseen another undefined variable. Now everything should work as expected
**Ticket:** https://yaits.demos-deutschland.de/T31291
https://yaits.demos-deutschland.de/T31301
=> fix(refs T31291, T31301): Catch undefined Reset measuretools

demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadUserData.php
probably removed by accident in https://github.com/demos-europe/demosplan-core/pull/827
=> fix: restore needed constant

demosplan/DemosPlanCoreBundle/Logic/DefaultTwigVariablesService.php, demosplan/DemosPlanCoreBundle/Resources/config/GlobalConfig.php, demosplan/DemosPlanCoreBundle/Resources/config/parameters_default.yml
**Ticket:** https://yaits.demos-deutschland.de/T30295
Allows to define links to external sites, that can be used by the FE to show them in the UI.
=> feature (refs T30295): allow to configure external links section

demosplan/DemosPlanCoreBundle/Resources/client/scss/_settings-color-assignment.dplan.scss, demosplan/DemosPlanCoreBundle/Resources/client/scss/_settings-color-palette.dplan.scss, demosplan/DemosPlanCoreBundle/Resources/client/scss/_trumps-3rd-party-resets.dplan.scss, demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_callout.scss, demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_map.scss, demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_proceduresearch.scss, demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_segmentlist.scss, demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_splitstatement.scss, demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_timepicker.scss, demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_tiptap.scss, demosplan/DemosPlanCoreBundle/Resources/client/scss/components/vendor/_multiselect.scss, demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_objects-cardboxes.dplan.scss, demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_switcher.scss, demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_wizard.scss, demosplan/DemosPlanCoreBundle/Resources/client/scss/token/_color.scss
https://yaits.demos-deutschland.de/T30974
- change name of variables for (color brand main).
=> chore (refs T30974): change name of variables for (color brand main).

client/js/components/user/DpMasterToebList/DpInviteMasterToeb.vue
**Ticket:** https://yaits.demos-deutschland.de/T31536
Description: The name of the button should be `Institution hinzufügen`.
- See the description in the ticket
=> Fix(refs:T31536): Change the naming from the button

client/js/bundles/procedure/administrationNew.js, client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue, client/js/store/procedure/NewProcedure.js
These commits accidentially were merged into main here https://github.com/demos-europe/demosplan-core/pull/877 but we need it for release. Hence these commits have been cherry picked for this PR
=> B t23632 enable automatic name extraction for release

demosplan/DemosPlanCoreBundle/Logic/Rpc/RpcErrorGenerator.php
Errors in RPC actions where silenced and did not leave a trace in logs. Therefore a logger is introduced.
Core review might be best
=> feat: Log errors that occur in rpc actions

demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
Ticket:
https://yaits.demos-deutschland.de/T31435
Description:
delete boilerplates of boilerplateGroups when a boilerplate group
is selected to be deleted.
=> feature (refs T31435): delete boilerplates of boilerplateGroup on GroupDelete

client/js/components/statement/publicStatementModal/StatementModal.vue, client/js/components/statement/publicStatementModal/formGroups/FormGroupMapReference.vue
**Ticket:** https://yaits.demos-deutschland.de/T31035
**Description:** This PR adds new classes to some elements in the `StatementModal` component which makes it possible to adjust required changes in the DiPlanBau Project.
_It is connected with the same PR in the DiPlanBau project._
=> Feat_T31342: adjust design: STN modal window - diplanbau

demosplan/DemosPlanCoreBundle/Controller/Faq/FaqController.php, demosplan/DemosPlanCoreBundle/Controller/MiscContent/DemosPlanMiscContentController.php, demosplan/DemosPlanCoreBundle/Logic/Faq/FaqHandler.php, templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/participation_area_skeleton.html.twig
**Ticket:** https://yaits.demos-deutschland.de/T31035
Description: This PR provides FAQ data to the information.html.twig file.
=> Feat_T31035: adjust design: about page - diplanbau

demosplan/DemosPlanDocumentBundle/Repository/ParagraphRepository.php, demosplan/DemosPlanDocumentBundle/Tools/ServiceImporter.php
**Ticket:** https://yaits.demos-deutschland.de/T31261
Description: This PR contains the bug fix from https://github.com/demos-europe/demosplan-core/pull/904 for https://yaits.demos-deutschland.de/T31394.
=> bug (refs T31261): fix import of docx paragraph-elements.

demosplan/DemosPlanCoreBundle/Twig/Extension/ProcedureExtension.php, demosplan/DemosPlanProcedureBundle/Repository/ProcedureProposalRepository.php, demosplan/DemosPlanStatementBundle/Repository/StatementFragmentRepository.php
This does not fix the referenced bug, but helps to find the cause of similar ones in the future.
**Ticket:** https://yaits.demos-deutschland.de/T31722
=> refactor (refs T31722): add missing exception causes

composer.lock
**Ticket:** https://yaits.demos-deutschland.de/T31336
Description:  update addon dependency
=> F (ref:T31336): new content-hash

demosplan/DemosPlanCoreBundle/Command/ContainerInitCommand.php
During container deployment this initialize command is called that performs any actions needed to keep the setup up2date. Doctrine migration and elasticsearch populate needs to be executed during startup to ensure current state.
code review or run the command
=> feat: perform migrations and elasticsearch populate

composer.lock
This PR just updates php vendors that are not updated by dependabot
review composer.lock if you may
=> chore: update php vendors that are not covered by dependabot

demosplan/DemosPlanCoreBundle/Resources/config/parameters_default.yml
Provide default values to `parameters_default.yml` to be able to build container.
Code review only, should not be able to break anything
=> feat: provide default values for database

demosplan/DemosPlanCoreBundle/Entity/File.php, demosplan/DemosPlanCoreBundle/Logic/FileService.php, demosplan/DemosPlanCoreBundle/Resources/config/parameters_default.yml, demosplan/DemosPlanProcedureBundle/Logic/ProcedureService.php
**Ticket:** https://yaits.demos-deutschland.de/T31722
=> fix (refs T31722): skip deleted files when copied from blueprint

composer.lock
**Ticket:** https://yaits.demos-deutschland.de/T30254
This PR updates the demosplan-addon in the composer.lock. 
=> feat (refs T30254): update demosplan-addon

demosplan/DemosPlanCoreBundle/Event/CreateSimplifiedStatementEvent.php
**Ticket:** https://yaits.demos-deutschland.de/T31928 
Description: adjust use statement
=> F (ref:F_T31928): adjust use statement

demosplan/DemosPlanCoreBundle/Logic/Import/Statement/ExcelImporter.php
**Ticket:** https://yaits.demos-deutschland.de/T31927
Description: handle values with int type
=> F (ref:F_T31927): handle values with int type

demosplan/DemosPlanCoreBundle/Logic/ApiRequest/JsonApiEsService.php
Ticket:
https://yaits.demos-deutschland.de/T31936
Description:
Adjust path to ElasticSearch total hits.
try to search the segments within EWM
=> feature (refs T31936): adjust path to ElasticSearchResult - TotalHits.

demosplan/DemosPlanCoreBundle/Entity/User/AiApiUser.php
Ticket:
https://yaits.demos-deutschland.de/T31926
Description:
changed order of constructor calls - parent first to be able to
overwrite properties.
=> feature (refs T31926): changed order of constructor calls

translations/messages+intl-icu.de.yml
**Ticket:** https://yaits.demos-deutschland.de/T31753
Description: just a little spelling mistake fix
=> Fix(refs:T31753): little spelling mistake correction

client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
[](https://yaits.demos-deutschland.de/T31984)
dpconfirm was written wrong (dpConfirm) and was adjusted here
=> Bug(refs t31984) fix dpconfirm

demosplan/DemosPlanCoreBundle/Resources/config/parameters_default.yml
=> refactor: set gateway_url to keycloak as default

demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanDepartmentController.php
**Ticket:** https://yaits.demos-deutschland.de/T32007
Method may return `Department` or array, need to check type before access
Create new department
=> fix (refs T32007): avoid type error

demosplan/DemosPlanCoreBundle/Resources/config/parameters_default.yml
Ticket:
https://yaits.demos-deutschland.de/T29882
Description:
adjust path to JsonSchema
https://github.com/demos-europe/demosplan-project-ewm/pull/38
=> feature (refs T29882): alter path to json schemas

client/js/components/report/DpReportGroup.vue, demosplan/DemosPlanCoreBundle/ResourceTypes/ReportEntryResourceType.php, demosplan/DemosPlanReportBundle/Logic/ReportMessageConverter.php
Ticket:
https://yaits.demos-deutschland.de/T32008
Description:
add orgaName to ReportEntries
=> feature (refs T32008): add orgaName to ReportEntries

yarn.lock
**Ticket:** https://yaits.demos-deutschland.de/T31971
This updates to the latest version which fixes [DpUpload](https://github.com/demos-europe/demosplan-ui/pull/138).
It should be possible to upload files which contain a `:` within their name.
https://github.com/demos-europe/demosplan-ui/pull/138
=> Update demosplan-ui to v0.0.18

client/js/components/procedure/AdministrationImport/AdministrationImport.vue
- line 37 was a partial duplication and this breaks our webpack build
=> fix administration import not loading addons

demosplan/DemosPlanCoreBundle/ValueObject/ValueObject.php
Description: adjust lock method return type
=> F adjust return type

client/js/components/procedure/imageAnnotator/DpImageAnnotator.vue
Ticket:
Description:
Adjust api call in DpImageAnnotator.vue
=> feature (refs T30254): Adjust api call in DpImageAnnotator.vue

client/js/components/map/map/DpOlMap.vue, client/js/components/map/publicdetail/Map.vue, client/js/components/procedure/listSubscriptions/ListSubscriptions.vue, client/js/components/procedure/publicindex/DpSearchProcedureMap.vue, package.json
**Ticket:** https://yaits.demos-deutschland.de/T32058
After a refactoring/bugfix some checkes to define if a extent is set failed because JS has a weired way to define "true"
(if You check it like `if([]) { /* this code will be executed */ }`, although `[] == false`).
=> fix(refs T32058): Make check for maxExtent do what's suppose to do

demosplan/DemosPlanCoreBundle/Resources/config/parameters_default.yml
sets gateway_url back to empty
=> set gateway_url back to empty

demosplan/DemosPlanCoreBundle/Logic/MailService.php
Moreover, do not delete mail attachments, when mail could not be sent
=> chore: do not report mails as sent in case of an error

composer.lock
Ticket:
Description:
update composer.lock
=> feature (refs T30254): update composer.lock

demosplan/DemosPlanCoreBundle/Logic/EntityContentChangeService.php
`getFieldMapping` did return a non-usable array format for specific cases. One call was adjusted so that an exception is thrown instead of continuing with the invalid return.
Also move `loadFieldMapping()` call up, so that it is loaded even if an empty string is passed as parameter instead of a class string.
**Ticket:** https://yaits.demos-deutschland.de/T30254
=> refactor (refs T30254): detect invalid state early

demosplan/DemosPlanCoreBundle/Entity/User/AnonymousUser.php
**Ticket:** https://yaits.demos-deutschland.de/T30525
For example report entries require a valid name to be given
Create a procedure via XBeteiligung message
=> chore (refs T30525): anonymous user name needs to be set

demosplan/DemosPlanCoreBundle/Resources/config/services.yml
Description: The TopLevelInterface is removed from demosplan addon
=> F remove top level interface from services yaml

composer.lock, demosplan/DemosPlanCoreBundle/Resources/config/services.yml
Ticket:
Description:
tag EntityFetcherInterface with class implementation and EntityManager as service.
update composer.lock due to changes made in demosplan addon.
=> F 30254 adjust service yml

demosplan/DemosPlanCoreBundle/Resources/config/services.yml
Ticket:
Description:
adjust service.yml tag FileUploadServiceInterface as a FileUploadService
=> feature (refs T30254): update services.yml

demosplan/DemosPlanCoreBundle/EventSubscriber/HandleEmailAddressSubscriber.php
Ticket:
Description:
instantiate paramter in constructor before usage.
=> feature (refs T30254): instantiate paramter in constructor before usage.

demosplan/DemosPlanCoreBundle/EventSubscriber/HandleEmailAddressSubscriber.php
Ticket:
Description:
instantiate array as empty before eventually filling it with values
=> feature (refs T30254): instantiate array as empty before eventually filling it with values

demosplan/DemosPlanCoreBundle/ResourceTypes/OrgaResourceType.php
**Ticket:** https://yaits.demos-deutschland.de/T31989
Anonymous "orga" is no real organisation.
=> fix (refs T31989): exclude pseudo-organisation from `Orga` resources

client/js/components/user/DpOrganisationFormFields.vue
https://yaits.demos-deutschland.de/T32219
The wrong permissions were checked for editing orgas imprint and data protection texts, hence was adjusted with this PR.
=> feat(refs: T30866): use correct permissions to edit orga imprint and data protection

yarn.lock
This fixes the "Failed to resolve async component" error also in release_ewm.
yarn install, yarn dev:ewm, check out any view with an editor (maybe statement detail view) and check if the link button works.
=> Bump demosplan UI to 0.0.19

composer.lock, demosplan/DemosPlanCoreBundle/Resources/config/services.yml
Ticket:
https://yaits.demos-deutschland.de/T32257
Description:
Remove a duplicated entry in Service.yml
Other Prs:
demosplan-addon: https://github.com/demos-europe/demosplan-addon/pull/46
demosplan-addon-maillane: https://github.com/demos-europe/demosplan-addon-maillane/pull/24
=> feature (refs T32257): Remove a duplicated entry in Service.yml

demosplan/DemosPlanCoreBundle/Controller/AssessmentTable/DemosPlanAssessmentTableController.php
**Ticket:** https://yaits.demos-deutschland.de/T30603
Description: remove wrong use statement
=> F_T30603 remove wrong use statement

demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/DplanAuthenticator.php
Update method signature to math used Interface `AuthenticatorInterface`
CodeReview should be probably best
=> chore: adjust method to match updated interface

templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/public_detail.html.twig, templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/public_index.html.twig
Description: the MapBundle was moved to core and this paths were not adjusted
=> F fix twigs paths

demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementController.php, demosplan/DemosPlanCoreBundle/Logic/Statement/StatementResourceTypeService.php, demosplan/DemosPlanCoreBundle/Resources/config/permissions.yml, demosplan/DemosPlanStatementBundle/Logic/StatementDeleter.php, demosplan/DemosPlanStatementBundle/Logic/StatementHandler.php, demosplan/DemosPlanStatementBundle/Logic/StatementService.php, tests/backend/core/Statement/Functional/StatementDeleterTest.php
This PR is a duplicate of https://github.com/demos-europe/demosplan-core/pull/1161 and needed to bring the changes to release_ewm.
=> B t22439 for release ewm

demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureResourceType.php
**Ticket:** https://yaits.demos-deutschland.de/T32390
=> fix (refs T32390): allow procedure access for planning offices

yarn.lock
upgrade yarn.lock to install latest version of demosplan-ui
=> fix(refs T32449): upgrade demosplan-ui to v0.0.21

demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
Call to trim with null is deprecated
=> chore: trim is not allowed to be called with null

demosplan/DemosPlanCoreBundle/EventSubscriber/ParametersProviderSubscriber.php
Description: use event interface instead event path
=> F use event interface instead event path

demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureResourceType.php
=> fix (refs T32390): use current syntax after merge from very old branch

demosplan/DemosPlanCoreBundle/Logic/FileUploadService.php
=> feature (refs T32390): add missing log statements

demosplan/DemosPlanCoreBundle/Logic/Statement/StatementResourceTypeService.php
Continuation of https://github.com/demos-europe/demosplan-core/pull/1295
=> chore: remove obsolete manual ES statement indexing

composer.json, composer.lock
Description: 
- not all adjustements made in demosplan are compatible with this branch that's why the dependency version has to be specified
=> F adjust dependency version

templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/contact_entry.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/imprint_entry.html.twig, templates/bundles/DemosPlanUserBundle/DemosPlanUser/alternative_login.html.twig
we renamed our company from "DEMOS E-Partizipation GmbH" to "DEMOS plan GmbH"
**Ticket:** https://yaits.demos-deutschland.de/T32513
=> chore(refs T32513): Adjust Company Name

client/js/components/procedure/DpSimplifiedNewStatementForm.vue
https://yaits.demos-deutschland.de/T32601
Fix for: https://github.com/demos-europe/demosplan-core/pull/1365
- data prop can not reference to another data prop before intialization
=> fix(refs T32601): fix initialization error

config/services_deployment.yml
Config folder has been moved to top level, relative path needs to be adjusted.
=> chore: fix relative path after refactoring

demosplan/DemosPlanCoreBundle/Logic/User/UserHandler.php
**Ticket:** https://yaits.demos-deutschland.de/T32879
Returnvalue was expected to be an array only.
=> F t32879 avoid type error

client/js/store/procedure/SplitStatementStore.js
**Ticket:** https://yaits.demos-deutschland.de/T32855
We need to import Vue here, because otherwise it is not available in the Addon and we get an error, that this function does not exist.
Verfahren -> STN aufteilen: Edit a segment and click on "Abbrechen" or try to delete a segment.
=> bug(refs T32855): Import Vue

demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/UserFromSecurityUserProvider.php
The Token may carry a User object already which may be fine as we only need `getUserIdentifier()` here
Code review may be best
=> chore: do not be overly specific in user provider

client/js/components/statement/assessmentTable/TocView/SearchAndSorting.vue
https://yaits.demos-deutschland.de/T32994
- Add E2E Hook/Selector.
=> fix (refs T32994): Add E2E Hook/Selector.

demosplan/DemosPlanCoreBundle/Event/Procedure/GetDatasheetVersionEvent.php
**Ticket:** https://yaits.demos-deutschland.de/T33075 
Description: Error 500 in verfahren public detail 
check /verfahren/{procedure}/public/detail
=> feature (refs T33075): add zero to datasheetversion variable

client/js/components/procedure/DpSimplifiedNewStatementForm.vue
https://yaits.demos-deutschland.de/T33015
Only use the submitter date as authored date if the submitter date is in valid format aka `YYYY-MM-DD` otherwise the default value of `''` will be used as authored date
=> fix(refs T33015): implement date validation check

client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaAttachments.vue
**Ticket:** https://yaits.demos-deutschland.de/T33031
Cherry pick from release (#1482), because the fix is also wanted in the release now.
=> bug(refs T33031): Hide upload files when editable is false (#1482)

yarn.lock
Ticket: https://yaits.demos-deutschland.de/T33012
Upgrade demosplan-ui to version 0.1.4
=> chore: Upgrade demosplan-ui

demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanAssessmentController.php
This is a cherrypick from 
https://github.com/demos-europe/demosplan-core/pull/1526
and
https://github.com/demos-europe/demosplan-core/pull/1513
=> fix(refs T31372): Add confirm message to confirm mstn

package.json, yarn.lock
Bump PortalVue to 3. this is vue3 Compatible
**Ticket:** https://yaits.demos-deutschland.de/T19759
=> chore(refs T32012): Bump PortalVue to 3

yarn.lock
**Ticket:** https://yaits.demos-deutschland.de/T33153
=> chore: Bump demosplan-ui to 0.1.4

composer.lock, demosplan/DemosPlanCoreBundle/Logic/User/UserHandler.php, demosplan/DemosPlanCoreBundle/Permissions/Permissions.php, demosplan/DemosPlanCoreBundle/Permissions/ProjectPermissions.php
Interfaces in demosplan-addon where adjusted, methods need to implement them correctly
run phpstan
=> chore: fix methods after interface BC breaks

composer.json, composer.lock
**Ticket:** https://yaits.demos-deutschland.de/T31018
Description: 
- some changes made in the 0.0.4 are required.
- adjust composer.lock
- Check out in branch release_ewm_3.0
- try cache clear
=> fix adjust demosplan addon version:

composer.lock
Due to a refactoring the interfaces needed to be adjusted. This PR updates the addon contracts to match the refactoring
run phpstan
=> chore: fix missing abstract method by updating addon contracts

composer.json, composer.lock
Update composer.lock to match php 8.2, fix version syntax
=> chore: update dependencies, update composer.lock with php 8.2

client/js/components/user/citizenRegisterForm/CitizenRegisterForm.vue, client/js/components/user/orgaRegisterForm/OrgaRegisterForm.vue
https://yaits.demos-deutschland.de/T33377
https://yaits.demos-deutschland.de/T33374
- add missing hooks/selectors for blp.
=> F t33374 add e2e hooks

demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserController.php, translations/messages+intl-icu.de.yml
https://yaits.demos-deutschland.de/T33426
Any problems during userdata save in welcome page lead to an infinitive redirect loop. We need to be more defensive in this case as this is reported to happen but hard to debug or trigger by purpose.
Code review might be best as it is hard to trigger this error. Perhaps you may return a non User object during save
=> chore (refs T33426): avoid eternal login loop

client/js/components/statement/publicStatementModal/StatementModal.vue
https://yaits.demos-deutschland.de/T32856
- add missing hook/selector.
=> chore (refs T32856): add missing hook/selector.

templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_footer.html.twig
https://yaits.demos-deutschland.de/T33309
- add missing Footer hook/selector.
=> chore (refs T33309): add missing Footer hook/selector.

demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_toggle.scss, templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_tags.html.twig
**Ticket:** https://yaits.demos-deutschland.de/T33507
The good old toggleAnything conflicts with tailwind specificity here. So, it has to raise specificity. Also, unneeded flow-root classes are removed.
The "Schlagworte" table should work + look as before.
=> fix(refs T33507): raise specificity

composer.json, composer.lock
Description: some adjustements have been made in demosplan addon that's why its version has to be adjusted in core 
to make compatible with main
=> fix adjust demosplan addon version

demosplan/DemosPlanCoreBundle/Entity/PlatformFaq.php
Description: adjust parameter type
=> fix adjust parameter type

demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
**Ticket:** https://yaits.demos-deutschland.de/T32776
This PR adjust the dispatch of the PostProcedureUpdatedEvent and improves code readability.
code review
=> feature (refs T33776): Adjust event dispatch and code readability

demosplan/DemosPlanCoreBundle/Entity/User/Orga.php, demosplan/DemosPlanCoreBundle/Repository/CoreRepository.php
**Ticket:** https://yaits.demos-deutschland.de/T33495
Avoid Error on update orgas, caused by wrong assertion on validation
Update a field in the orga list and save.
=> F t33495 fix update of orgas

demosplan/DemosPlanCoreBundle/Tools/ServiceImporter.php
Git silently merged changes a bit faulty
run anything
=> chore: fix fatal error after merge

demosplan/DemosPlanCoreBundle/Event/Procedure/GetDatasheetFilePathAbsoluteEvent.php, demosplan/DemosPlanCoreBundle/Event/Procedure/GetDatasheetVersionEvent.php
Description:  these events are related to the Datasheets logic ( which is removed from core ), they were added recently and have to be adjusted 
- extend DPlanEvent
- add missing event interface implementation
=> fix adjust events

demosplan/DemosPlanCoreBundle/Logic/Faq/FaqHandler.php, demosplan/DemosPlanCoreBundle/Logic/Faq/FaqService.php
**Ticket:** https://yaits.demos-deutschland.de/T33572
Description: some use statements were missing
=> Fix ref T33572 error while managing faq

demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php, demosplan/DemosPlanCoreBundle/Logic/Procedure/ServiceOutput.php, demosplan/DemosPlanCoreBundle/Logic/Procedure/ServiceStorage.php
**Ticket:** https://yaits.demos-deutschland.de/T33519 
Description: DemosPlanProcedureContrlooer::getProcedureWithPhaseNames() must return string but null.
test in browser
=> feature (refs T33519): add agency main email address to service output

Jenkinsfile, composer.json, composer.lock
yarn test did overload the workers as any test tried to use all cpus in parallel which crashed the servers
=> Heal jenkins worker load

client/js/components/document/ElementsAdminList.vue, client/js/components/news/DpNewsAdminList.vue, client/js/components/procedure/SegmentsList/SegmentsList.vue, client/js/components/statement/listStatements/ListStatements.vue
https://yaits.demos-deutschland.de/T30980
- add spacing & layout classes for DpBulkEditHeader.
https://github.com/demos-europe/demosplan-ui/pull/334
=> chore (refs T30980): add spacing & layout classes for DpBulkEditHeader.

config/packages/doctrine.yaml, phpunit.xml
#1430 introduced two minor bugs regarding tests that are fixed with this PR
phpunit tests should start
=> chore: fix errors introduced by flex upgrade

demosplan/DemosPlanCoreBundle/Logic/TransformMessageBagService.php
In some cases like console commands, the request stack is not available
run `bin/<project> debug:event-dispatcher`
=> chore: fix debug console command

demosplan/DemosPlanCoreBundle/Logic/Statement/NonAuthorizedAssignRemover.php
=> fix: add missing method call parameter

.gitignore
Core project caches, logs and assets should not be added to git. Thus they are included in .gitignore
code review
=> chore: add core project files to gitignore

client/js/components/statement/statement/DpAutofillSubmitterData.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig
https://yaits.demos-deutschland.de/T33763
=> chore (refs T33763): add missing Hooks/Selectors.

demosplan/DemosPlanCoreBundle/Logic/FileResponseGenerator/DocxResponseGenerator.php, demosplan/DemosPlanCoreBundle/Logic/FileResponseGenerator/FileResponseGeneratorAbstract.php, demosplan/DemosPlanCoreBundle/Logic/FileResponseGenerator/PdfResponseGenerator.php, demosplan/DemosPlanCoreBundle/Logic/FileResponseGenerator/XlsResponseGenerator.php
**Ticket:** https://yaits.demos-deutschland.de/T33543
Description: fix the Error :   NameGenerator::$nameGenerator must not be accessed before initialization
Test in Browser
=> B t33543 export file

client/js/components/button/BackToTopButton.vue, client/js/components/statement/assessmentTable/AssessmentTableFilter.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/includes/administration_list_pageheader.html.twig
https://yaits.demos-deutschland.de/T33661
=> chore (refs T33661): add missing Hooks/Selectors.

client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
https://yaits.demos-deutschland.de/T33662
=> chore (refs T33662): add missing Hooks/Selectors.

templates/bundles/DemosPlanCoreBundle/DemosPlanUser/password_recover.html.twig, templates/bundles/DemosPlanCoreBundle/UI/button.html.twig
https://yaits.demos-deutschland.de/T33659
- add dataCy attr to button UI Component.
=> chore (refs T33659): add missing Hooks/Selectors.

demosplan/DemosPlanCoreBundle/Exception/AccessDeniedException.php, demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
The new method is not used yet and triggering the exceptions may be difficult. Code review should be sufficient.
Must be merged together with https://github.com/demos-europe/demosplan-addon/pull/66.
=> feature: add `PermissionEvaluatorInterface::requireAllPermissions`

config/services.yml, demosplan/DemosPlanCoreBundle/Command/Data/ReplaceFilesCommand.php
Somehow the namespaces changed and need to be adjusted
code review or try to perform `bin/<project>` 
=> chore: fix DataFactory namespaces

demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureAPIController.php, templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/new_public_participation_statement_vote.html.twig
**Ticket:** 
- edit signing section sh content shall be removed in diplanrog
- https://github.com/demos-europe/demosplan-project-diplanrog/pull/31
=> Fix(refs:33913): remove sh link section in diplanrog

demosplan/DemosPlanCoreBundle/Event/Procedure/PostProcedureUpdatedEvent.php
Description: getProcedure Method missed in procedureUpdateEvent
we don't have any access to any page with this Error
=> feature: add missing getProcedure method

config/config_core.yml, config/parameters_default.yml, demosplan/DemosPlanCoreBundle/Logic/DefaultTwigVariablesService.php, demosplan/DemosPlanCoreBundle/Resources/config/GlobalConfig.php, templates/bundles/DemosPlanCoreBundle/DemosPlanCore/js/dplan.settings.js.twig
**Ticket:** https://yaits.demos-deutschland.de/T32195
Now that we use a version for the core and a distinct one for the project we need to define a variable for the core version
Code review only as this PR only provides the variable that might be used
=> chore refs (T32195): pass core version to frontend

client/js/bundles/document/elementsAdminList.js
**Ticket:** https://yaits.demos-deutschland.de/T34112
Import missing component, so it can be loaded in twig. 
Go to Verfahren -> Dokumente. There should be a box for uploading files.
=> bug(refs T34112): Import missing component

tests/frontend/unit/__snapshots__/SearchModal.spec.js.snap
Add missing attribute to snapshot. 
Run `yarn test`. You should get no errors.
=> chore: Fix jest tests

demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_public-statement.scss
**Ticket:** https://yaits.demos-deutschland.de/T34174
**Description:** This PR fixes the issue with lists and their numbering by adding styling for both `ul` and `ol` tags. The problem was that the initial value for `ol` did not work as expected, displaying bullets instead of numbers. As a solution, this PR sets the appropriate styling for each tag to resolve the numbering problem.
=> Fix(T34174): bulleted and numbered lists issue

demosplan/DemosPlanCoreBundle/Logic/CurrentContextProvider.php, demosplan/DemosPlanCoreBundle/Logic/User/CustomerService.php
split too long line
code review
=> feature: split too long line

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig, yarn.lock
**Ticket:** https://yaits.demos-deutschland.de/T34211
- the statements section has no margin when screen smaller
=> Fix(refs:T34211): publicdetail style incomplete

client/js/bundles/statement/listFinalGroup.js, templates/bundles/DemosPlanCoreBundle/DemosPlanCore/proceduremenu_statements.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_final_group.html.twig
**Ticket:** https://yaits.demos-deutschland.de/T34313
As Institution Coordinator goto
`/verfahren/<prcedure-id>/stellungnahmen/endfassungenGruppe`
- You need voted statements. 
If You use the upper Navigation (not the Tabs on the right hand side) then the tab nd content should change too when switching between "my statements" and "voted statements"
=> fix(refs T34313): Set active Tab

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_list_boilerplate.html.twig
https://yaits.demos-deutschland.de/T33945
https://github.com/demos-europe/demosplan-ui/pull/437
=> chore (refs T33945): add missing Hooks/Selectors.

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_boilerplate_group.html.twig
https://yaits.demos-deutschland.de/T33948
=> chore (refs T33948): add missing Hooks/Selectors.

templates/bundles/DemosPlanCoreBundle/sidemenu.html.twig
https://yaits.demos-deutschland.de/T34037
https://github.com/demos-europe/demosplan-ui/pull/444
- add E2E Hooks/Selectors.
=> chore (refs T34037): add E2E Hooks/Selectors.

client/js/components/statement/publicStatementLists/DpPublicStatementList.vue
**Ticket:** https://yaits.demos-deutschland.de/T34317
After fixing that the propper Time gets displayed, we lost the Hours/minuts.
here they are again....
=> fix(refs T34317): Add Hours to timestamp

demosplan/DemosPlanCoreBundle/Entity/User/AnonymousUser.php, demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/ApiUserProvider.php, demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/SecurityUserProvider.php
**Ticket:** https://yaits.demos-deutschland.de/T34194
Cherry-Pick from
https://github.com/demos-europe/demosplan-core/pull/1806
=> fix(refs T34194): Fix jwt calls

client/js/components/map/publicdetail/Map.vue
cherrypick from https://github.com/demos-europe/demosplan-core/pull/1874
**Ticket:** https://yaits.demos-deutschland.de/T33908
=> fix(refs T33908): use set extent to stay within the allowed area of the map

client/js/components/map/publicdetail/Map.vue
split the method createLayerSource  into 3 methods. this should not affect anything. Layers (WMS and WMTS) should still work.
This is a side outcome while bugfixing [T34144](https://yaits.demos-deutschland.de/T34144)
=> chore: Refactor `createLayerSource()`

demosplan/DemosPlanCoreBundle/Command/Data/GenerateOrganisationCommand.php
Minor correction of dplan-command description.
=> docs: add generate:organisation to dplan commands docs

composer.lock
Ticket:
https://yaits.demos-deutschland.de/T33807
Description:
Update composer.lock due to recent demosplan Addon changes. (v0.8)
=> feature (refs T32983): adjust composer.lock

config/services.yml
Ticket:
https://yaits.demos-deutschland.de/T33807
Description:
fix path within the services.yml
=> feature (refs T33807): fix path within the services.yml

yarn.lock
updates demosplan-ui to v0.1.13
=> bump demosplan-ui 0.1.13

demosplan/DemosPlanCoreBundle/Logic/User/OrgaHandler.php
**Tickets**: https://yaits.demos-deutschland.de/T32026
**Description**: Remove 'email2' from handler 
- https://github.com/demos-europe/demosplan-project-ewm/pull/86
=> feature (T32026) : remove unused attribute from handler

composer.json
Project namespace needs to be adjusted to match organization name
=> chore: Adjust namespace

client/js/components/procedure/SegmentsList/SegmentsList.vue, client/js/components/procedure/StatementSegmentsList/StatementSegment.vue, client/js/components/statement/listStatements/ListStatements.vue, demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_data-table.scss, demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_styled-html.scss
**Ticket:** https://yaits.demos-deutschland.de/T33650
Description:  Add a class called `table-text` to the `ListStatements` component to apply styling to text containing the `ul` and `ol` tags within the table.
=> fix(T34304): issue with numbering in the ListStatements component

composer.json
Composer name should match repository name to follow best practices
=> chore: rename composer package

demosplan/DemosPlanCoreBundle/Logic/Statement/TagService.php, demosplan/DemosPlanCoreBundle/Repository/TagRepository.php, tests/backend/core/Statement/Functional/TagServiceTest.php
**Ticket:** https://yaits.demos-deutschland.de/T34642
Tag(titles) should be unique per procedure.
=> fix (refs T34642): On create a new tag, check for already existing tag in procedure

client/js/bundles/user/unregisteredPublicagencyList.js, client/js/components/user/DpToggleForm.vue, client/js/components/user/ToggleForm.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanUser/unregistered_publicagency_list.html.twig
https://yaits.demos-deutschland.de/T33326
https://github.com/demos-europe/demosplan-ui/pull/532#pullrequestreview-1629126481
- Add DpToggleForm to Core.
=> chore (refs T33326): Add DpToggleForm to Core.

composer.json, composer.lock, templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/elements_list_entry_nojs.html.twig
Twig 2 has its eol in December 2023. A few changes have do be made https://github.com/twigphp/Twig/blob/3.x/CHANGELOG
=> chore: update to twig 3

demosplan/DemosPlanCoreBundle/Controller/GenericRpcController.php
Or to be precise, it adds it. We need a way to see when errors are happening.
Code review. Or try to provoke errors and check the logs.
=> feat: improves RPC route exception logging

yarn.lock
**Description:** Upgrade demosplan-ui to version **0.1.16**
=> upgrade demosplan-ui to v0.1.16

demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserController.php
https://yaits.demos-deutschland.de/T33553
- adjust useSaml for register user.
=> chore (refs T33553): adjust Trans-Key, useSaml for register user.

client/js/components/shared/NotifyContainer.vue, package.json, yarn.lock
This will overrule https://github.com/demos-europe/demosplan-core/pull/2029 and https://github.com/demos-europe/demosplan-core/pull/2115 to not break main in the meanwhile
=> chore: Bump demosplan UI 0.2.0

client/js/bundles/user/listDepartments.js, client/js/components/statement/publicStatementLists/DpPublicStatement.vue, client/js/components/user/DpOrganisationList/DpOrganisationListItem.vue, client/js/components/user/DpTableCardList/DpTableCard.vue, client/js/components/user/DpTableCardList/DpTableCardListHeader.vue, client/js/components/user/DpUserList/DpUserListItem.vue, client/js/components/user/DpUserListExtended.vue, client/js/components/user/DpUserListExtendedItem.vue
https://github.com/demos-europe/demosplan-ui/pull/548
https://github.com/demos-europe/demosplan-ui/pull/548#pullrequestreview-1661206171
https://demosdeutschland.slack.com/archives/C5BA8ABB2/p1696577655712089
- move DpTableCardList to Core.
=> chore: move DpTableCardList to Core.

client/js/components/statement/DpBoilerPlate.vue
**Ticket:** https://yaits.demos-deutschland.de/T34975
add lost list styles
=> fix(refs: T34975): show list items in Boilerplate modal

Jenkinsfile, config/config_core.yml, config/config_dev_container.yml, config/config_dev_container_services.yml, demosplan/DemosPlanCoreBundle/Application/DemosPlanKernel.php, demosplan/DemosPlanCoreBundle/Command/UpdateCommand.php, tests/backend/core/Core/Functional/EventFinderTest.php, tests/backend/core/Core/Unit/Logic/Elements/PlanningDocumentCategoryTreeReordererTest.php, tests/backend/core/Map/Unit/FeaturesToMapLayersConverterTest.php, tests/backend/core/Procedure/Functional/SubdomainHandlerTest.php, tests/backend/core/Statement/Functional/SimiliarStatementSubmitterTest.php, tests/backend/core/Statement/Functional/StatementDeleterTest.php, tests/backend/core/Statement/Functional/StatementMoverTest.php
Jenkins seems to have some kind of problem with its test environment and therefore cannot create the logs directory.
Additionally a lot of tests where broken again. These where handled.
=> chore: try to fix environment in tests

templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement_detail_statement_text.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_edit.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_new.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_email.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_send_email.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_unregistered_publicagency_email.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanUser/customer_settings_update_mail.html.twig
**Ticket:** https://yaits.demos-deutschland.de/T34971
Just type-o
=> fix(refs: T34971): Remove unwanted closing bracket

demosplan/DemosPlanCoreBundle/Logic/Faq/FaqService.php
Ticket:
https://yaits.demos-deutschland.de/T34983
Description:
fix type check for Faq or PlatformFaq.
=> feature (refs T34983): Fix manual Faq sort

templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_version.html.twig, translations/messages+intl-icu.de.yml
**Ticket:** https://yaits.demos-deutschland.de/T34359
Since we want to display the current version of a project in some Projects, This moves the logic to the core. To have one single source of truth.
After this is merged. The projects wich want to use this "feature" can easily include the partical.
=> feat(refs T34359): Display Version in diplanRog Console.

client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaAttachments.vue
**Ticket:** https://yaits.demos-deutschland.de/T34955
ProcedureId is now a required prop.
=> bug(refs T34955): Add required prop

demosplan/DemosPlanStatementBundle/Resources/client/js/components/originalStatementsTable/OriginalStatementsTableItem.vue
**Ticket:** https://yaits.demos-deutschland.de/T34920 -->
Description: adjust 'OriginakStatamentsTableItem' Vue : import and use mapMutations to make 'updateStatement' method available.
Start -> Manage -> Select procedure -> Balancing table 'Abwägungstabelle' -> Original Statements -> Show more +
=> f_T34920 show more causes an error message

client/js/components/user/CustomerSettings/CustomerSettingsSupport.vue
**Ticket:** https://yaits.demos-deutschland.de/T35173
as mandanten-admin (support) goto `/einstellungen/plattform` and try to edit a support-contact. The error, that You use an already used title should not appear and saving should be possible
=> fix(refs T35173): Skip own Title when checking for Uniqueness

demosplan/DemosPlanCoreBundle/Entity/User/Customer.php, demosplan/DemosPlanCoreBundle/ResourceTypes/CustomerResourceType.php
**Ticket:** https://yaits.demos-deutschland.de/T35204
Only checking for min string length / valid URL only in case of incoming user input to avoid errors on already existing empty strings.
todo: draft because not tested locally
change and save something in /einstellungen/plattform as role.cmu
- #2212
=> feat (refs T35204): Adjust input validation 

demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php
**Ticket:** https://yaits.demos-deutschland.de/T31243
Description: set new Key for column 'name' in XLSX statements Export. 
In Browser or Code Review
=> feature (ref 31243): set right key name for column name

demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php
**Ticket:** https://yaits.demos-deutschland.de/T31243
Description: set new Key for column 'name' in XLSX statements Export in function `createColumnsDefinitionForPotentialAreas`
In Browser or Code Review
=> feature (ref 31243): set new key for name in potential area

translations/messages+intl-icu.de.yml
**Ticket:** https://yaits.demos-deutschland.de/T35292
- one word had to be changed and 2 missing points at the end of a sentence
=> Fix(refs:35292): change one word and grammar

client/js/components/user/CustomerSettings/CustomerSettings.vue
**Ticket:** https://yaits.demos-deutschland.de/T35301
- remove unused buttons
=> Fix(refs:T35301): remove unused buttons

composer.lock, config/services.yml, demosplan/DemosPlanCoreBundle/Logic/Document/ParagraphService.php
**Ticket:** https://yaits.demos-deutschland.de/T35051
Implements the ParagraphServiceInterface to make the ParagraphService available in addons.
code review
=> feat (T35051): Implement ParagraphServiceInterface

client/js/components/user/CustomerSettings/CustomerSettingsBranding.vue
**Ticket:** https://yaits.demos-deutschland.de/T35313
- after click for delete the logo and save, it should have been deleted till you upload and save a new file
=> Fix(refs:T35313): the logo delete doesnt work correctly

client/js/components/support/DpSupport.vue, client/js/components/support/DpSupportCard.vue
**Ticket:** https://yaits.demos-deutschland.de/T35312
**Description:** This PR adjusts styling for the support card as well as fixes the issue where all cards were displayed instead of only the visible ones.
=> B t35312 adjust styling for support card

templates/bundles/DemosPlanCoreBundle/DemosPlanUser/login_idp_error.html.twig
**Ticket:** https://yaits.demos-deutschland.de/T35316
As Customer Support Admin add a mail address in the customer settings -> "Kontakt für fehlende Berechtigungen".
Then goto `/idp/login/error` and check if the prompted data is displayed.
=> fix(refs T35316): pass email address to support card

translations/messages+intl-icu.de.yml
**Ticket:** https://yaits.demos-deutschland.de/T35383
its tiny
=> fix(refs T35383): Type o

demosplan/DemosPlanCoreBundle/Command/ContainerInitCommand.php, tests/backend/base/MockMethodDefinition.php, tests/backend/core/Core/Functional/ContainerInitCommandTest.php, tests/backend/core/Core/Functional/HoneypotTest.php, tests/backend/core/Core/Functional/MailTest.php, tests/backend/core/Core/Functional/ProcedureExtensionTest.php, tests/backend/core/Core/Functional/ResourceLinkageFactoryTest.php, tests/backend/core/Core/Unit/Utilities/Twig/DateExtensionTest.php, tests/backend/core/Core/Unit/Utilities/Twig/IsNotExtensionTest.php, tests/backend/core/Core/Unit/Utilities/Twig/JsonDecodeExtensionTest.php, tests/backend/core/Core/Unit/Utilities/Twig/UCFirstExtensionTest.php
This PR fixes most of the remaining failing tests.
run tests, code review might be best, probably commitwise
=> Fix php tests

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_master.html.twig
**Ticket**: https://yaits.demos-deutschland.de/T35509
**Description**: Set Permission to access to authorized user.
Browser or code review
=> feature (ref 35509): set Permission in Core

templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/statement_detail_subheader.html.twig
https://yaits.demos-deutschland.de/T35510
- Easy fix to place the button on the same horizontal axis as the icons
- checkout
- select a procedure and  navigate to assessment table detail view
- check if the button is properly aligned on the same axis as the icons
=> fix(refs: T35510): add flex class to wrapper to align button properly

demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php
Command should not exit with success on addon install exception
=> chore: fix faulty catch reaction

client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
**Ticket:** https://yaits.demos-deutschland.de/T34593
Add more margin so there is more space between the badge and the close icon (I used tailwind class for this).
=> bug (refs T34593): Add more margin to beta badge

client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
**Ticket:** https://yaits.demos-deutschland.de/T34593
Since it is positioned absolute, we can change the position to the right and don't need any margin.
(https://github.com/demos-europe/demosplan-core/pull/2378)
=> bug (refs T34593): Remove margin and adjust positioning right

translations/messages+intl-icu.de.yml
=> fix/feat(refs T35650): Add Transkey for Filter used by an Addon

demosplan/DemosPlanCoreBundle/Entity/User/SupportContact.php
**Ticket:** https://yaits.demos-deutschland.de/T35794
Description: text field is not required.
=> f text field is not required

client/js/store/procedure/SplitStatementStore.js
**Ticket:** https://yaits.demos-deutschland.de/T35631
Those may lead the frontend to crash and should probably not be needed in a real world scenario
=> chore (refs T35631): Filter out segments with less than 10 characters

client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_new.html.twig
**Ticket:** https://yaits.demos-deutschland.de/T35737
Form uses SymfonyForms that already used csrf tokens
create a new procedure
=> chore refs T35737: fix duplicate csrf token

demosplan/DemosPlanCoreBundle/Logic/RpcStatementSynchronizer.php, demosplan/DemosPlanCoreBundle/Validator/CorrectDateOrderConstraintValidator.php, translations/validators.de.yml
**Ticket:** https://yaits.demos-deutschland.de/T35841
Description: 
- adjustement to make errors more comprehensive for the users.
- log errors which make issues fixen more easier
=> F T35841 statement release to vht not possible

demosplan/DemosPlanCoreBundle/Logic/ZipImportService.php
=> fix:  fix changed type back to string as needed

client/js/components/procedure/DpDashboardTaskCard.vue
**Description:** This PR includes necessary adjustments following the refactoring of the DpApi methods, which were carried out [here](https://github.com/demos-europe/demosplan-ui/commit/3a2b55a0d00c29d76fe26bcac2fddfd34c5f3ea1) and [here](https://github.com/demos-europe/demosplan-ui/pull/690)
PR in [demosplan-ui](https://github.com/demos-europe/demosplan-ui/pull/690)
=> Fix(T35884): some adjustments after refactoring DpApi methods

client/js/components/procedure/imageAnnotator/DpConvertAnnotatedPdf.vue, client/js/components/procedure/imageAnnotator/DpImageAnnotator.vue
***Ticket: https://yaits.demos-deutschland.de/T35879***
- the getRequest should have only a resourceType as parameter
=> Fix(refs: T35879): incorrect parameter in getRequest

client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue, client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue, client/js/components/statement/listStatements/ListStatements.vue, translations/messages+intl-icu.de.yml
**Ticket:** https://yaits.demos-deutschland.de/T35495
Description: 
- if statement is started to get segmented and the user would like change the statement, he has to finish the segmentation and to edit the segments otherwise the statement is readable only and there is a waning box to warn and inform the user
- so if the user would like change the statement he should do it before starting the segmentation
=> F t35495 stn shall not be overwritten when segmentdraftlist exist

client/js/components/procedure/AdministrationImport/AdministrationImportNone.vue, client/js/components/shared/TextContentRenderer.vue
https://yaits.demos-deutschland.de/T19759
https://yaits.demos-deutschland.de/T19787
https://github.com/demos-europe/demosplan-core/pull/1151
- migration Render Function to vue3.
=> chore (refs T19759 T19787): migration Render Function to vue3.

templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base.html.twig
**Ticket: ** https://yaits.demos-deutschland.de/T35874
cherry pick: https://github.com/demos-europe/demosplan-core/pull/2532
(cherry picked from commit b650ee0b81faf10d2d28a0fef95eeacb3c59a422)
=> fix(T35874): add white space wrapping for the procedure name (#2532)

package.json, yarn.lock
upgrade demosplan-ui to version 0.3.5
=> upgrade demosplan-ui to version 0.3.5

demosplan/DemosPlanCoreBundle/Services/Breadcrumb/Breadcrumb.php
Ticket:
Ticket: https://yaits.demos-deutschland.de/T35961
Description:
Just a small cleanup of things not in use.
original fix: https://github.com/demos-europe/demosplan-core/pull/2524
=> feature (refs T35961): cleanup leftovers that are not needed for chosen solution

demosplan/DemosPlanCoreBundle/Logic/ApiRequest/JsonApiEsService.php
=> fix (T35993): lock value object before usage

composer.lock, demosplan/DemosPlanCoreBundle/ResourceTypes/AbstractStatementResourceType.php
=> chore: update `composer.lock` to current EDT dependency

composer.lock
=> fix (refs T36008): update `composer.lock` to current EDT dependency

client/js/components/procedure/publicindex/DpSearchProcedureMap.vue
https://yaits.demos-deutschland.de/T34499
=> chore (refs T34499): add missing Hooks/Selectors.

client/js/components/statement/publicStatementModal/StatementModal.vue, client/js/components/statement/publicStatementModal/formGroups/FormGroupMapReference.vue
https://yaits.demos-deutschland.de/T34335
=> chore (refs T34335): add missing Hooks/Selectors.

client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
https://yaits.demos-deutschland.de/T36079
- the api call contains the non-conform JSON API spec property `group` which will result in an invalid api call hence has to be removed
- navigate to /abschnitte
- claim a segment and change data
- save
=> fix(refs T36079): fix segment can not be updated

client/js/components/faq/DpFaqItem.vue, client/js/components/procedure/StatementSegmentsList/SegmentsRecommendations.vue, client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue, client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue, client/js/components/statement/listStatements/ListStatements.vue, client/js/components/user/DpOrganisationList/DpOrganisationListItem.vue, client/js/components/user/DpUserList/DpUserListItem.vue
https://yaits.demos-deutschland.de/T36108
- All those api requests contain the non-conform JSON API spec property group which will result in an invalid api request hence has to be removed
=> bug(refs T36108): remove invalid request properties from dplan

client/js/components/procedure/admin/AdministrationProceduresList.vue
**Ticket:** https://yaits.demos-deutschland.de/T36153
- the dates were incorrect
- they showed only the same current date always
=> Fix(refs:36153): use the correct access for the dates

client/js/lib/procedure/CreateProcedure.js
**Ticket:** https://yaits.demos-deutschland.de/T36132
- the data had to be parsed
- code beautify
=> Fix(refs:36132): problem by creating new procedure

demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/03/Version20230324132250.php
The adjusted migration failed in an existing project. We need to ensure that field is nullable.
code review
=> chore: ensure that field is nullable as this is not the case in all projects

demosplan/DemosPlanCoreBundle/Addon/RpcAddonAssetsLoader.php
We should not just swallow exceptions but log them in order to allow debugging.
code review
=> chore: improve error logging in RpcAddonAssetsLoader

client/js/components/statement/assessmentTable/DpBulkEditStatement.vue
**Ticket:** https://yaits.demos-deutschland.de/T36229
Backend expects a JSON instead of a string.
Verfahren -> Abwägungstabelle -> Select a statement -> Bearbeiten -> Add a text and try to safe
=> bug(refs T36229): Send JSON instead of string

translations/messages+intl-icu.de.yml
**Ticket:** https://yaits.demos-deutschland.de/T36217
Description: Add missed Translation Key
=> feature (ref 36217): Add missed Translation Key

templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/pageheader.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanCore/proceduremenu_statements.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/includes/public_statement.html.twig
https://yaits.demos-deutschland.de/T34332
=> chore (refs T34332): Add missing Hooks/Selectors.

composer.lock
Description: update demosplan-addon: there is a new version v0.24
=> f adjust composer.lock

client/js/bundles/procedure/publicIndexSimpleList.js, client/js/components/procedure/publicindex/DpSearchProcedureMap.vue
Ticket: https://yaits.demos-deutschland.de/T36261
As we changed dpApi to use fetch under the hood, usage must be adapted.
The search should work again on the public index page.
=> Adapt xhr call to changed lib

demosplan/DemosPlanCoreBundle/Repository/NewsRepository.php
**Ticket:** [T36230](https://yaits.demos-deutschland.de/T36230)
Called Method "updateObjects" is provided by the CoreRepository (witch also extends the FluentRepository)
Login with Walter West and go to .aktuelles-area and toggle the status .
=> CoreRepository extended needed

demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanOrganisationAPIController.php, demosplan/DemosPlanCoreBundle/Logic/User/UserHandler.php
**Ticket:** https://yaits.demos-deutschland.de/T36289
Description: User can not delete some Organizations, because of different reasons like Organization hat users or procedure or ... But these errors are not displayed in the UI. Now we can show user because of which reason you can not delete organization
In UI or Code review
=> feature (ref 36289): Add Errors to Orga delete

composer.lock
https://yaits.demos-deutschland.de/T29878
Increase demoscore-addon version
=> feat (refs T29878): Update demosplan-addon version

client/js/components/statement/assessmentTable/ItemRow.vue
**Ticket:** https://yaits.demos-deutschland.de/T36341
Show title for icon only if there is an icon. 
Verfahren -> Abwägungstabelle -> The spaces should look like the screenshot in the ticket
=> bug(refs T36341): Show title for icon only if there is an icon

demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserAPIController.php, demosplan/DemosPlanCoreBundle/ResourceTypes/AdministratableUserResourceType.php
**Ticket:** https://yaits.demos-deutschland.de/T36294
Description: use condition to not show AiApiUser in the list
=> feature (ref 36294): find api user from list and unset that

demosplan/DemosPlanCoreBundle/Entity/User/SecurityUser.php, demosplan/DemosPlanCoreBundle/Logic/User/OrgaService.php, demosplan/DemosPlanCoreBundle/Logic/User/UserService.php, tests/backend/core/DemosPlanCoreBundle/Entity/User/SecurityUserTest.php
https://yaits.demos-deutschland.de/T36463
The user was sometimes invalidated when dealing with multiple roles. Hence even a successful login lead to no authenticated user
hard to test locally tbh. This is the test for. Otherwise code review
=> refs T36463: Fix login

client/js/components/user/CustomerSettings/CustomerSettings.vue, client/js/components/user/CustomerSettings/CustomerSettingsSignLanguageVideo.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_new.html.twig
**Ticket:** https://yaits.demos-deutschland.de/T36452
- Add currentCustomerId to child component
- Add value of sign language overview description to payload
- Fill customer data with current data on fetch 
- Add csrf token
Login as support -> Plattformeinstellungen -> try to save 
- Erklärung zur Barrierefreiheit
- Leichte Sprache
- Hinweise in Gebärdensprache
=> bug(refs T36452): Fill customer with currentdata props

client/js/components/support/DpSupport.vue
**Ticket:** https://yaits.demos-deutschland.de/T35464
**Description:** The .length property works on arrays, not on objects, so .length returns undefined in this case. To obtain the length of an object, it needs to be converted into an array first using Object.keys(), which allows accessing the length property.
=> Fix(T35464): dp-support layout issue 

translations/messages+intl-icu.de.yml
**Ticket:** https://yaits.demos-deutschland.de/T33654
Portalurl needs to be adjusted according to the current environment. We can reuse the twig variable used in the header.
URL in information text like stated in the ticket should be adjusted as variable is set. Otherwise code review
=> chore (refs T33654): use variable to portal in trans key

config/menus.yml
https://yaits.demos-deutschland.de/T36516
- Fix duplicate Hooks.
=> chore (refs T36516): Fix duplicate Hooks.

demosplan/DemosPlanCoreBundle/Transformers/AssessmentTable/StatementBulkEditTransformer.php, demosplan/DemosPlanCoreBundle/Transformers/Document/DocumentDashboardTransformer.php, demosplan/DemosPlanCoreBundle/Transformers/FaqCategoryTransformer.php, demosplan/DemosPlanCoreBundle/Transformers/Filters/AggregationFilterGroupTransformer.php, demosplan/DemosPlanCoreBundle/Transformers/Filters/AggregationFilterTypeTransformer.php, demosplan/DemosPlanCoreBundle/Transformers/HistoryDayTransformer.php
#2671 contained a BC break that needs to be fixed
call any page, no fatal error should occur
=> chore: fix bc break in fractal 0.20

client/js/store/map/Layers.js, tests/frontend/unit/__snapshots__/SearchModal.spec.js.snap
The FE tests were failing because the snapshot for `SearchModal.vue` had not been updated after changing the component.
Run `yarn test`, the tests should not fail.
https://github.com/demos-europe/demosplan-core/pull/2682
=> test: update snapshots

client/js/components/procedure/DpSimplifiedNewStatementForm.vue, client/js/components/procedure/Shared/SimilarStatementSubmitters/SimilarStatementSubmitters.vue
https://yaits.demos-deutschland.de/T34245
=> chore (refs T34245): Add missing Hooks/Selectors.

client/js/components/statement/listStatements/ListStatements.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_statements.html.twig
https://yaits.demos-deutschland.de/T34249
=> chore (refs T34249): Add missing Hooks/Selectors.

client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
**Ticket:** https://yaits.demos-deutschland.de/T25438
Remove unnecessary padding.
Verfahren -> Zusammenfassung -> Content of Status and Dokument should align
=> bug(refs T25438): Remove padding

client/js/components/procedure/admin/AdministrationProceduresList.vue
**Ticket:** https://yaits.demos-deutschland.de/T36396
Cherrypicked from https://github.com/demos-europe/demosplan-core/pull/2620
Dates should correctly reflect the Day the procedures were created.
=> fix(refs T36396): use the correct access for the dates

client/js/components/map/map/DpOlMap.vue, client/js/components/statement/assessmentTable/DpMapModal.vue
Backmerge eines hotfix aus https://github.com/demos-europe/demosplan-core/pull/2781
=> Merge release_robobsh into main

client/js/components/procedure/DpSimplifiedNewStatementForm.vue
https://yaits.demos-deutschland.de/T34245
- edit Hook/Selector.
=> chore (refs T34245): edit Hook/Selector.

client/js/components/document/DpMapSettingsPreview.vue, client/js/components/map/map/DpMapView.vue, client/js/components/map/map/DpOlMapLayer.vue
**Ticket:** https://yaits.demos-deutschland.de/T36493
Description: 
- show the default copyright in the map in basic settings for procedure, in startmap outcut and in plandrawing settings
- due to the projects there are different defaults
=> Feat(refs:T36493): show the default copyright note in the correct maps

client/js/components/statement/fragmentList/DpFragmentList.vue, client/js/components/statement/fragmentList/Fragment.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_statement_fragments.html.twig
**Ticket:** https://yaits.demos-deutschland.de/T36722
- some error fixes to show the entries
=> Fix(refs: T36722): missing fragment entries

demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php, demosplan/DemosPlanCoreBundle/Logic/ZipExportService.php
During bugfixing two small optimizations where found. The temporary filename included `'` and two methods of the `SegmentsExporter` where not needed to be public
code review
=> chore: minor exporter optimizations

client/js/components/statement/assessmentTable/DpEditField.vue, client/js/store/statement/Fragment.js
**Ticket:** https://yaits.demos-deutschland.de/T31399
Description:
- after claiming the fragment youshould be able to assign the fragment to an orga
- after saving the assignment to the orga you have to claim it again, if you would like change something else
=> F t31399 fragment cannot be assigned to orga

templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/includes/form_filter.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry_paragraph.tex.twig
**Ticket:** https://yaits.demos-deutschland.de/T26867
Description:  remove chapter from filter and export
=> f T26867 remove chapter from filter and export

client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue, client/js/components/statement/assessmentTable/EditableText.vue, client/js/components/statement/publicStatementModal/StatementModalRecheck.vue, client/js/store/statement/Statement.js
**Tickets:**
https://yaits.demos-deutschland.de/T36652 -> https://github.com/demos-europe/demosplan-core/pull/2847
https://yaits.demos-deutschland.de/T36753 -> https://github.com/demos-europe/demosplan-core/pull/2848
https://yaits.demos-deutschland.de/T36689 -> https://github.com/demos-europe/demosplan-core/pull/2846
=> fix: Cherry picks from oher Branches

package.json, yarn.lock
upgrade demosplan-ui to version 0.3.8 in release branch
=> upgrade demosplan-ui to version 0.3.8

templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/includes/form_filter.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry_paragraph.tex.twig
**Ticket:** https://yaits.demos-deutschland.de/T26867
Cherry Pick from https://github.com/demos-europe/demosplan-core/pull/2858
=> fix(refs  T26867): Cherry pick for t26867

client/js/components/statement/assessmentTable/SearchModal/SearchModal.vue, tests/frontend/unit/__snapshots__/SearchModal.spec.js.snap, tests/frontend/unit/store/storeHelpers/SplitStatementStore/HTMLIdxToProsemirrorIdx.spec.js
https://yaits.demos-deutschland.de/T34247
=> chore (refs T34247): Add missing Hooks/Selectors.

jest.config.js
due to https://github.com/demos-europe/demosplan-core/pull/2870 the config has to be adjusted, so that the tests doesnt fail
=> fix: remove setupFiles in config because it is not used any more

client/js/components/procedure/admin/AdministrationProceduresList.vue
https://yaits.demos-deutschland.de/T36838
https://github.com/demos-europe/demosplan-ui/pull/798
https://yaits.demos-deutschland.de/T36838#872739
- Add E-2-E Hooks/Selectors.
=> chore (refs T36838): Add E-2-E Hooks/Selectors.

client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue, client/js/components/procedure/basicSettings/AutoSwitchProcedurePhaseForm.vue, client/js/components/procedure/basicSettings/ExportSettings.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
https://yaits.demos-deutschland.de/T34084
=> F t34084 add missing hooks selectors

client/js/components/statement/assessmentTable/DpFilterModal.vue, client/js/components/statement/assessmentTable/FilterModalSelectItem.vue
https://demoseurope.youtrack.cloud/issue/DPP-2746/Missing-hooks-Filterung-nach-Einreichung
=> chore (refs T36840): add missing Hooks/Selectors.

client/js/components/statement/statement/DpAutofillSubmitterData.vue, client/js/components/statement/statement/SelectStatementCluster.vue, client/js/components/statement/voter/StatementVoter.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig, templates/bundles/DemosPlanCoreBundle/Extension/fileupload.html.twig
https://yaits.demos-deutschland.de/T36569
https://demoseurope.youtrack.cloud/issue/DPP-3254/Missing-hooks-fur-erstellen-von-neue-Stellungnahme
=> chore (refs T36569): Add missing Hooks/Selectors.

client/js/components/statement/listStatements/ListStatements.vue
https://yaits.demos-deutschland.de/T36853
https://demoseurope.youtrack.cloud/issue/DPP-2744/Missing-Hooks-Fur-Stellungnahme-Tabelle
=> chore (refs T36853): Add missing Hooks/Selectors.

client/js/components/procedure/admin/DpNewProcedure/CoupleTokenInput.vue, client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
https://demoseurope.youtrack.cloud/issue/DPP-11374
=> chore (refs DPP-11374): Add missing Hooks/Selectors.

client/js/components/statement/statement/DpAutofillSubmitterData.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-3254
- Use id instead of deprecated "name" attribute for abort link.
=> chore (refs DPLAN-3254): Add missing Hooks/Selectors.

client/js/components/map/map/DpMapView.vue
**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-11388/BLP-Schulung-Layout-Seite-Startkartenausschnitt-
festlegen-ist-kaputt
A Tiny Templatebug wants to be fixed.
=> feat(refs DPLAN-11388): Fix Template

client/js/components/map/map/DpMapView.vue, demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTablePdfExporter.php, demosplan/DemosPlanCoreBundle/Logic/Statement/DraftStatementService.php, demosplan/DemosPlanCoreBundle/Twig/Extension/LatexExtension.php, templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_entry.tex.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_entry_condensed.tex.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_original_entry.tex.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry_paragraph.tex.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry_public_citizen.tex.twig, tests/backend/core/Core/Unit/Utilities/Twig/LatexExtensionTest.php
**Ticket:** https://yaits.demos-deutschland.de/Txxyyzz -->](https://demoseurope.youtrack.cloud/issue/DPLAN-1924/Munchen-Prod-PDF-Export-eingereichter-STN-in-Bestatigungsmail-wird-falsch-dargestellt)
Description: this is picked from release
=> F (refs dplan 1924) change default ul latex pdf line width

client/js/components/statement/assessmentTable/AssessmentTableFilter.vue, client/js/components/statement/assessmentTable/DpExportModal.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_pageheader.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-3253
=> chore (refs DPLAN-3253): Add missing Hooks/Selectors.

demosplan/DemosPlanCoreBundle/Logic/StatementSynchronizer.php
**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-3274/5-2-Part-1-Durchgangsnummer-zu-Verfahrensschritten-hinzufugen
=> feat (DPLAN-3274): called method does not exist 

client/js/components/user/DpUserList/DpUserFormFields.vue
cherrypick from  https://github.com/demos-europe/demosplan-core/pull/2949
=> fix(refs CareKan-34): Use proper Event when using DpSelect for Departments 

composer.lock
php dependencies needs to be updated
=> chore: update php vendors

tests/frontend/unit/ParticipationPhases.spec.js
Its obvious tht single Quotes can't work within a single-quote string....
=> fix: Change type of Quotes to work within Quotes

.github/workflows/ado_sync.yml
this PR switches to new ado workflow that is using ssh for git operations
=> use ado_sync_workflow per ssh

.github/workflows/ado_sync.yml
pass the necessary secret to the reusable workflow, ensuring it is accessible for use within that context.
=> pass secret to reusable workflow

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_dashboard.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-11537
=> chore (refs DPLAN-11537): add missing Hooks/Selectors.

client/js/components/procedure/admin/DpNewProcedure/CoupleTokenInput.vue, client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
- As the tokenLength is never changed, it can also be hardcoded in the respective component
- comparison expression is simplified for better readability
- maxlength + minlength must be strings according to the validator of DpInput
Nothing should be different in the newProcedure view.
=> Chore: simplify components

.github/PULL_REQUEST_TEMPLATE.md
=> chore: Update GH-Template

client/js/components/statement/splitStatement/TagSelect.vue
**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-11559
=> fix(refs DPLAN-11559): Set fullwidth for Tags

config/permissions.yml, demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureMapSettingResourceType.php
*Description:*
- Add permissions to projects that have following url enabled: /verfahren/PROCEDURE_ID/verwalten/globaleGisEinstellungen
- Check that projects have rights
- [ x] Tests updated/created
=> B dplan 11557 add map permissions

client/js/store/map/ProcedureMapSettings.js
**Ticket:** DPLAN-3570
Push fields to array instead of to joined string.
=> bug(refs DPLAN-3570): Fix params for api request

demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureMapSettingResourceType.php
*Description:*
- Allow scales access (no permissions)
- Check that projects have rights
- [ x] Tests updated/created
=> B dplan 11557 remove scales check permission

client/js/components/procedure/admin/AdministrationProceduresList.vue, client/js/store/statement/Filter.js, tests/frontend/unit/__mocks__/UserFilterSetResource.mock.js, tests/frontend/unit/store/Filter.spec.js
DPLAN-11435
cherrypick from  https://github.com/demos-europe/demosplan-core/pull/3010
=> fix(refs dplan-11435): get hash for filter

client/js/components/statement/assessmentTable/DpFilterModal.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-2746/
https://github.com/demos-europe/demosplan-core/pull/2885/files
- add missing Hook/Selector.
=> chore (refs DPLAN-2746): add missing Hook/Selector.

tests/backend/core/Statement/Functional/StatementHandlerTest.php
=> chore: fix namespaces

client/js/components/map/admin/MapAdmin.vue, client/js/components/map/admin/MapAdminScales.vue, client/js/components/map/map/DpOlMap.vue, client/js/components/map/map/DpOlMapDragZoom.vue, client/js/components/map/map/DpOlMapScaleSelect.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-11427
- add missing Hook/Selector for Map.
=> chore (refs DPLAN-11427): add missing Hook/Selector for Map.

client/js/components/procedure/SegmentsList/SegmentsList.vue, client/js/components/shared/mixins/tableScrollbarMixin.js, client/js/components/statement/listStatements/ListStatements.vue, translations/messages+intl-icu.de.yml
cherry pick from https://github.com/demos-europe/demosplan-core/pull/3045
=> fix(refs dplan-11516): Make cusstom Scrollbar work in FF (cherry-pick)

templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/single_document_admin_edit.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/single_document_admin_new.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-11426
- Add missing Hooks/Selectors
=> chore (refs DPLAN-11426): Add missing Hooks/Selector.

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_boilerplate.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_tags.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-11497
- Add missing Hooks
=> chore (refs DPLAN-11497): Add missing Hooks/Selector.

client/js/components/map/map/DpOlMapDrawPoint.vue, client/js/components/procedure/basicSettings/ProcedureCoordinateGeolocation.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-11538
=> chore (refs DPLAN-11538): Add missing Hooks/Selectors.

templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/imprint_entry.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-11624
- delete Hamburg address & Fax from contact.
=> chore (refs DPLAN-11624): delete Hamburg address & Fax from contact.

client/js/components/statement/assessmentTable/DpEditSelectedItemsMenu.vue, client/js/components/statement/assessmentTable/DpSelectedItemsStatements.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-11604/Hooks-Abwagungstabelle
=> chore (refs DPLAN-11604): Add missing Hooks/Selectors.

.gitignore
https://www.dev.diplanung.de/DefaultCollection/BOP-HH/_workitems/edit/15514
adjust gitignore to avoid changes in core for local addon development
code review or change something in a local installed addon and see if the change isn't in the change list in core
List other PRs that are somehow connected to this and explain the connection.
- https://github.com/demos-europe/demosplan-core/pull/2653
=> feat (DPLAN-11407): add addonDev to gitingore

client/js/components/map/admin/LayerSettings.vue
DPLAN-1929
adding this Url in the layersettings should allow to select a Layer. 
https://cardo.cottbus.de/net3/public/ogc.ashx?NodeId=1636&SERVICE=WMS&Request=GetCapabilities
(it looks like the layer is wired configured. I coundnt see anythingg in the public detail and in qGis I only saw something in some zoome levels and only in one tiny region)
Every other layer, that worked before should still work
=> fix(refs dplan-1929) Add Layer Fallback

client/js/components/statement/publicStatementModal/StatementModal.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-11543
=> chore (refs DPLAN-11543): Add missing Hooks/Selectors.

client/js/components/procedure/DpSimplifiedNewStatementForm.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-3490/Hooks-Direkt-Import
- Add missing Hooks/Selectors for accordion.
=> chore (refs DPLAN-3490): Add missing Hooks/Selectors.

client/js/components/procedure/basicSettings/ParticipationPhases.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-11472
https://demoseurope.youtrack.cloud/issue/DPLAN-3499/Hooks-Grundeinstellungen
https://demosdeutschland.slack.com/archives/C5BA8ABB2/p1716292789639839
- Edit Hooks/Selectors.
=> chore (refs DPLAN-11472, DPLAN-3499): Edit Hooks/Selectors.

package.json, yarn.lock
=> chore: Bump demosplan-ui to v0.3.15

templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement_detail_statement_data.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-11605/Hooks-Stellungnahme-Detailansicht-Page
- Add missing Hook.
=> chore (refs DPLAN-11605): Add missing Hook.

client/js/components/procedure/basicSettings/DpEmailList.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-11504
Demosplan-UI PR: https://github.com/demos-europe/demosplan-ui/pull/868
EWM PR: https://github.com/demos-europe/demosplan-project-ewm/pull/115
Addon-maillane PR: https://github.com/demos-europe/demosplan-addon-maillane/pull/121
- Adjust data-cy Hooks/Selectors.
=> chore (refs DPLAN-11504): Adjust data-cy Hooks/Selectors.

config/permissions.yml
DPLAN-11673
This was forgotten when moving the code from twig to vue
=> fix(refs DPLAN-11673): Expose feature_xplan_defaultlayers Permission

config/permissions.yml
DPLAN-11673
Forgot even more Permissions to be exposed after a twig -> vue refactoring
=> fix(refs DPLAN-11673): Expose some map admin Permissions

composer.lock
Ticket: 
https://www.dev.diplanung.de/DefaultCollection/BOP-HH/_workitems/edit/15514
Description:
Update version of demosplan-addon to 0.24.3
=> fix (refs DPLAN-11422): bump demosplan-addon version

client/js/components/map/publicdetail/controls/CustomLayer.vue, client/js/components/map/publicdetail/controls/MapTools.vue, client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerList.vue, client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListLayer.vue, client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListWrapper.vue, client/js/components/map/publicdetail/controls/legendList/DpLayerLegend.vue, client/js/components/procedure/publicindex/drawer/ContentToggle.vue, client/js/components/procedure/publicindex/drawer/Search.vue, client/js/components/statement/publicStatementModal/StatementModal.vue, client/js/components/statement/publicStatementModal/StatementModalRecheck.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_public_participation_detail.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-11668/Hooks-Public-View-Hooks
- Add missing Hooks/Selectors in Public-View.
=> chore (refs DPLAN-11668): Add missing Hooks/Selectors in Public-View.

templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/pageheader.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_edit.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-11500/Fehlender-Hook-fur-Verfahren-bearbeiten
- Add missing Hook/Selector.
=> chore (refs DPLAN-11500): Add missing Hook/Selector.

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig
DPLAN-2005
Local styleguides don't recommend to use uppercase.
Verfahren Öffentlichkeitsansicht -> Headings shouldn't be completely in uppercase
=> bug(refs DPLAN-2005): Remove uppercase

demosplan/DemosPlanCoreBundle/Entity/File.php, demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureSettings.php, demosplan/DemosPlanCoreBundle/Entity/User/Orga.php, demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
This PR adds some return types to avoid symfony deprecation
run phpstan andor code review
=> F fix deprecations

client/js/components/procedure/admin/DpAddOrganisationList.vue
DPLAN-1912
Use correct property name.
Verfahren -> Institutionen verwalten -> Institutionen hinzufügen -> DEMOS Hamburger should show a postal code
=> bug(refs DPLAN-1912): Use correct property name

client/js/lib/procedure/charts/Legend.js
DPLAN-2168
You can check if an element exists by using the size() method from D3.js. It returns the number of elements in the current selection.
=> bug(refs DPLAN-2168): Use size method to see if element exists

demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
minor, because quite old PR and only Comments are left
recreation of https://github.com/demos-europe/demosplan/pull/2302
=> chore: minor: docblockadjustments

templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_header.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_oeb_header.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-11545/Hooks-Bobsh-Platform-Dropdown
=> chore (refs DPLAN-11545): Add missing Hooks/Selectors.

client/js/components/statement/publicStatementModal/StatementModal.vue
DPLAN-11746
The user should have some time to read the notification.
Login as Privatperson -> Verfahren -> Reden Sie mit -> Stellungnahme direkt einreichen -> There should be a short delay to read the notification
=> bug(refs DPLAN-11746): Add timeout before redirecting

client/js/components/procedure/publicindex/drawer/List.vue, client/js/components/procedure/publicindex/drawer/ListItem.vue, client/js/components/statement/publicStatementModal/formGroups/FormGroupMapReference.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail_form_confirmation_loggedin.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/includes/new_public_participation_statement_confirm_content.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-11668
=> chore (refs DPLAN-11668): Add missing Hooks/Selectors.

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_index.html.twig, translations/messages+intl-icu.de.yml
DPLAN-2759
For accessibility reasons there always should be a h1.
=> bug(refs DPLAN-2759): Add h1 heading for public index

client/js/components/user/DpUserList/DpUserList.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-11771/Hooks-Nutzende-verwalten
=> chore (refs DPLAN-11771): Add missing Hooks/Selectors.

templates/bundles/DemosPlanCoreBundle/DemosPlanUser/list_departments.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-11770/Hooks-Abteilung-verwalten
- Adjust Styling for `Neue Abteilung anlegen` accordion.
=> chore (refs DPLAN-11770): Add missing Hooks/Selectors.

.github/PULL_REQUEST_TEMPLATE.md
=> chore: Update and add template for PRs

client/js/components/procedure/admin/DpAddOrganisationList.vue, client/js/components/user/ToggleForm.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_pageheader.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_email.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_list_entry.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanUser/unregistered_publicagency_list.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-11743/Hooks-Institution-verwalten-und-via-Email-einladen-Unregistrierte-Institution
=> chore (refs DPLAN-11743): Add missing Hooks/Selectors.

client/js/components/user/DpOrganisationList/DpOrganisationFormFields.vue, client/js/components/user/DpOrganisationList/DpOrganisationList.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-11769/Hooks-Organisation-verwalten
=> chore (refs DPLAN-11769): Add missing Hooks/Selectors.

demosplan/DemosPlanCoreBundle/Command/Addon/AddonUninstallCommand.php
When uninstalling a local addon during development the symlink was not correctly deleted from the cache directory
you may install an addon via github/zip and one via addonDev local directory and uninstall them. Nothing should be left in the addons/cache folder
=> chore: remove symlink to local addon during uninstall

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_list_entry.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-11503/Fehlender-Hook-bei-Institution-verwalten
- Add missing Hooks.
=> chore (refs DPLAN-11503): Add missing Hooks/Selectors.

templates/bundles/DemosPlanCoreBundle/macros.html.twig
DPLAN-11814
Check if the Public Detail -> Documents list works again and the pager looks like expected.
=> fix(refs dplan-11814): Adjust pagerfanta-templates after upgrade

templates/bundles/DemosPlanCoreBundle/DemosPlanHelp/help_admin_contextual_help_list.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-11821
=> chore (refs DPLAN-11821): Add missing Hooks/Selectors.

client/js/components/procedure/DpSimplifiedNewStatementForm.vue, client/js/components/statement/statement/DpAutofillSubmitterData.vue, config/menus.yml, templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_statements.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-11846
- Edit Hooks/Selectors names.
- Standardize hooks names for all projects.
=> chore (refs DPLAN-11846): Edit Hooks/Selectors names.

client/js/components/user/DpOrganisationList/DpOrganisationFormFields.vue, translations/messages+intl-icu.de.yml
- when placing the checkbox below the "Neue Berechtigung..." button, it is less confusing where it belongs
- explicitly say which user groups may create procedures
- template is not needed here, v-if can directly be placed on the element
The checkbox/label should be placed below the button to add groups to an orga.
The label should show the updated content.
=> fix: optimize checkbox positioning + wording

client/js/components/procedure/AdministrationImport/ParticipationImport/ParticipationImport.vue, translations/messages+intl-icu.de.yml
https://demoseurope.youtrack.cloud/issue/DPLAN-1922/Hinweistext-bei-Beteiligungs-Import-zu-Uberspringen-von-STN-bei-erneutem-Import
- Add hint massage for participation import.
- Add Trans:Key.
=> chore (refs DPLAN-1922): Add hint massage for participation import.

.gitignore, .yarnrc.yml
We like to try that to ensure a more stable yarn
=> chore: Add yarnrc.yml to repos

client/js/components/map/admin/DpAdminLayerList.vue, client/js/components/map/admin/DpAdminLayerListItem.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_list.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-11389/Fehlende-Hooks-Planzeichnung-bearbeiten
=> chore (refs DPLAN-11389): Add missing Hooks/Selectors.

client/js/components/map/admin/LayerSettings.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_edit.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_new.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-11745/Hooks-Neu-Gislayer-Page-Edit-Gislayer-Page
=> chore (refs DPLAN-11745): Add missing Hooks/Selectors.

templates/bundles/DemosPlanCoreBundle/DemosPlanUser/list_departments.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-11770/Hooks-Abteilung-verwalten
- Add missing Hook/Selector.
=> chore (refs DPLAN-11770): Add missing Hook/Selector.

package.json
=> feature: remove extra package

client/js/components/map/admin/AdminLayerList.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/elements_admin_list.html.twig, tests/frontend/unit/__snapshots__/DpAdminLayerList.spec.js.snap
use newly added Permission in TWIG to hide the documents area where needed
and adjust Layout
=> feat(refs dplan-4020): Use permission

config/permissions.yml
https://demoseurope.youtrack.cloud/issue/DPLAN-11879/Permissions-Aktivieren-Bauen
Add new permission to display documents
=> I dplan 4020 new permission for map documents

client/js/components/map/admin/AdminLayerList.vue
**TIcket**
DPLAN-11953
(DPLAN-4020)
Changing to tailwind broke the Layout. And a Component wasn't entirely renamed....
=> feat(refs  DPLAN-11953, DPLAN-4020): Fix Header Col Position for AdminLayerList

composer.json, composer.lock
=> chore: bump demosplan-addon version

config/permissions.yml
https://demoseurope.youtrack.cloud/issue/DPLAN-4020/3-5-Als-Bearbeiterin-mochte-ich-eigene-Karten-zur-Planung-einbinden-konnen-um-Lagebeziehungen-oder-nicht-unmittelbar-erkennbare
Add new permissions to yml
=> F 4020 add permissions

client/js/components/statement/listStatements/ListStatements.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-12005
- add missing Hook.
=>  chore (refs DPLAN-12005): add missing Hook.

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_list_entry.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-11503
- Edit Hook naming.
=> chore (refs DPLAN-11503): Edit Hook naming.

demosplan/DemosPlanCoreBundle/Services/Queries/SqlQueriesService.php, tests/backend/core/Core/Functional/DynamicTransformerTest.php, tests/backend/core/Core/Unit/Logic/PermissionsTest.php
There are a few issues with our current phpunit tests that make the jenkins build fail
run all tests with `phpunit`. no fatal errors should occur
=> chore: fix tests that fail the build

client/js/components/procedure/DpSimplifiedNewStatementForm.vue, client/js/components/procedure/Shared/SimilarStatementSubmitters/SimilarStatementSubmitters.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-12027
- standardizing hooks names between projects.
=>  chore (refs DPLAN-12027): standardizing hooks names between projects.

client/js/components/procedure/admin/AdministrationPlaces.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-12028/Hooks-fur-Bearbeitungsschritte-Page
=>  chore (refs DPLAN-12028): Add missing Hooks/Selectors.

tests/frontend/unit/DpAdminLayerList.spec.js, tests/frontend/unit/DpBulkEditStatement.spec.js, tests/frontend/unit/FilterModalSelectItem.spec.js, tests/frontend/unit/__snapshots__/DpAdminLayerList.spec.js.snap, tests/frontend/unit/store/Layers.spec.js, tests/frontend/unit/store/Notify.spec.js, tests/frontend/unit/store/Statement.spec.js
Fix unit tests
- Vuex module names are case sensitive -> fix names
- Update snapshot for changed component
=> tests: fix unit tests

client/js/components/procedure/admin/AdministrationPlaces.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-12028/Hooks-fur-Bearbeitungsschritte-Page
https://demoseurope.youtrack.cloud/issue/DPLAN-12029/Hooks-fur-Token-und-Token-Container
- Add missing Hooks Prop.
=>  chore (refs DPLAN-12028, DPLAN-12029): Add missing Hooks.

client/js/components/faq/DpFaqCategoryItem.vue, client/js/components/faq/DpFaqItem.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanFaq/faq_admin_category_edit.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanFaq/faq_admin_edit.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-12078
- Add missing Hooks.
- Edit component name.
=>  chore (refs DPLAN-12078): add missing Hook.

client/js/components/procedure/SegmentsList/CustomSearch.vue, client/js/components/procedure/SegmentsList/FilterFlyout.vue, client/js/components/procedure/SegmentsList/SegmentsList.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-3485/Hooks-Abschnitte
=> chore (refs DPLAN-3485): Add missing Hooks/Selectors.

package.json, yarn.lock
Update demosplan-ui to v0.3.21
=> chore: Update demosplan-ui to v0.3.21

client/js/components/user/DpUserList/DpUserFormFields.vue
DPLAN-11488
I think the main issue was the wrong data while updating the select. But during the way to find that one I tried to make thinks more resilient. I hope its still reviewable :-/
=> fix(refs DPLAN-11488): Make departments updateable again

client/js/components/statement/StatementExportModal.vue, client/js/components/statement/assessmentTable/AssessmentTableFilter.vue, client/js/components/statement/assessmentTable/DpExportModal.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-12118
=> chor (refs DPLAN-12118): Add missing Hooks/Selectors.

client/js/components/user/DpUserList/DpUserList.vue
DPLAN-941
As Support goto the Users List.
search for a Name (Firstname AND Lastname) eg. "Lisa Bauer". The search should find all users with "Lisa" and all users with "bauer"
=> fix(refs DPLAN-941): Adjust Filter to find names with Blanks

client/js/components/statement/StatementExportModal.vue, tests/frontend/unit/StatementExportModal.spec.js
- Replace button with DpButton
- Replace section and headings with fieldset and legend (https://github.com/demos-europe/demosplan-core/pull/3448#discussion_r1682439411)
=> refactoring: some refactorings for StatementExportModal

client/js/components/procedure/publicindex/DpSearchProcedureMap.vue
DPLAN-12088
ADO [17346](https://www.dev.diplanung.de/DefaultCollection/DiPlan%20Incidents/_workitems/edit/17346)
We have to wait a little moment before we can fit to the bounds. Somehow the map needs its time.
With that fix, we should "zoom" to the procedure pins on load.
https://diplanbau-release.demos-europe.eu/app_dev.php/
=> feat(refs DPLAN-12088): Delay before trying to set the marker bounds

client/fe/webpack/moduleRules.js, config.webpack.js
This fixes the 302 on the Tailwind preflight.css file in Vue3 context.
=> Fix tailwind preflight resolution in Vue3

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_email.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_list.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_unregistered_publicagency_email.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_unregistered_publicagency_list.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-11743
- Unify Hooks/Selectors names.
=> chor (refs DPLAN-11743): Add missing Hooks/Selectors.

client/js/lib/map/GisLayerEdit.js
DPLAN-12026
We cant check if the element is not available due to some permissions..
as FP-A -> 
/verfahren/<procedure-id>verwalten/gislayer/neu
--> check if the console throws errors.
=> fix(refs dplan-12026): Prevent undefined

package.json, yarn.lock
Update demosplan-ui to v0.3.24
=> chore: Update demosplan-ui to v0.3.24

package.json, yarn.lock
Update demosplan-ui to v0.3.25
=> chore: Update demosplan-ui to v0.3.25

package.json, yarn.lock
0.3.26 should be 0.3.27. 
https://github.com/demos-europe/demosplan-ui/blob/main/CHANGELOG.md
see https://github.com/demos-europe/demosplan-ui/pull/968
=> chore: Bump demosplan UI@0.3.27

client/js/components/procedure/StatementSegmentsList/StatementSegment.vue, client/js/components/statement/splitStatement/SegmentationEditor.vue
DPLAN-12159
- We need to extend the prosemirror schema, because otherwise the class attribute gets stripped from the link. 
- Add click listener only if ref is defined
=> bug(refs DPLAN-12159): Add class to prosemirror schema

client/js/bundles/misccontent/dataProtection.js, translations/messages+intl-icu.de.yml
https://www.dev.diplanung.de/DefaultCollection/BOP-HH/_workitems/edit/14276
Data protection needs some updates. 
- Add some translations
- Add components needed in project file for table
https://github.com/demos-europe/demosplan-ui/pull/976
=> feat (refs AB#14276): Update data protection

client/js/components/procedure/SegmentsList/CustomSearch.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-12193
- Add missing Hooks.
=> chore (refs DPLAN-12193): Add missing Hooks.

package.json, yarn.lock
https://www.dev.diplanung.de/DefaultCollection/BOP-HH/_boards/board/t/BOP-HH-Team/Arbeitselemente/?workitem=14276
Bump `demosplan-ui` to make icons available in `demosplan-core` that are needed for the linked user story.
=> build(refs AB#14276): bump demosplan-ui to v0.3.28

client/js/components/statement/splitStatement/AssignedTags.vue, client/js/components/statement/splitStatement/SideBar.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-12286
https://demoseurope.youtrack.cloud/issue/DPLAN-12253
- Adjust SideBar Styling.
- Fix search-select component (add new Tag), when no Tags available.
- Adjust Style for tagTopics when there are few Tags || Topics.
- Go to EWM, login with `Motoko Kusanagi`
- Then `Verfahren ohne Schlagworte erstellen > STN anlegen > STN aufteilen > Klick auf "Schlagwort suchen" > es gibt keine Möglichkeit, ein Schlagwort und Thema anzulegen`
- For Scrolling Fix: `Verfahren mit einem Thema und vielen Schlagworten erstellen -> STN importieren -> Slicing-Tagging machen -> schlechte Usability`
- Fix for https://demoseurope.youtrack.cloud/issue/DPLAN-12286:
- Fix For: https://demoseurope.youtrack.cloud/issue/DPLAN-12253
=> chore (refs DPLAN-12286, DPLAN-12253): Adjust SideBar Styling.

client/js/components/statement/assessmentTable/DpExportModal.vue
https://www.dev.diplanung.de/DefaultCollection/BOP-HH/_boards/board/t/BOP-HH-Team/Arbeitselemente/?workitem=18560
It seemed like a good moment to clean up the template and use demosplan-ui components where possible.
- Navigate to the assessment table and original statement table and make sure that all export options work
=> refactor(refs AB#18560): use demosplan-ui components in export modal

client/js/components/procedure/admin/AdministrationPlaces.vue, client/js/components/statement/splitStatement/SideBar.vue, client/js/components/user/DpCreateItem.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-12198
https://demoseurope.youtrack.cloud/issue/DPLAN-12198/Konnen-wir-data-cybuttonRowsaveButton-und-data-cybuttonRowabortButton-zu-data-cysaveButton-und-data-cyabortButton-umbenennen#focus=Comments-4-51786.0-0
=> chore (refs DPLAN-12198): Add missing Hooks/Selectors.

package.json, yarn.lock
DPLAN-12305
We need the Bugfix from demosplan-ui...
https://github.com/demos-europe/demosplan-ui/tree/0.3.18-1
=> chore: Bump demosplan-ui to 0.3.18-1

translations/messages+intl-icu.de.yml
https://www.dev.diplanung.de/DefaultCollection/BOP-HH/_workitems/edit/18561
Change translation key to be more specific about what happens.
=> feat(refs AB#18561): Change trans key for export

client/js/components/statement/assessmentTable/DpTable.vue, client/js/components/statement/assessmentTable/ExportModal.vue, client/js/components/statement/originalStatementsTable/OriginalStatementsTable.vue, jest.config.js, templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_original_filter.html.twig, tests/frontend/unit/ExportModal.spec.js
https://www.dev.diplanung.de/DefaultCollection/EfA%20DiPlanung/_workitems/edit/18560
- the tests mostly cover if the template is rendered correctly depending on given conditions
- additional test cases (e.g. for interactions) may be added later
- run `yarn test ExportModal.spec.js` in the container
(to see the results of each test case, uncomment `verbose: true` in `jest.config.js`
=> test(refs #AB18560): add unit test for ExportModal.vue

templates/bundles/DemosPlanCoreBundle/DemosPlanUser/edit_orga.html.twig
[DPLAN-12340](https://demoseurope.youtrack.cloud/issue/DPLAN-12340/ADO-Issue-18958-Anpassung-Text-Daten-der-Organisation)
- Add data-cy
=> feat(refs DPLAN-12340 AB#18958): Add cypress selectors

demosplan/DemosPlanCoreBundle/Resources/config/GlobalConfig.php
[DPLAN-3224](https://demoseurope.youtrack.cloud/issue/DPLAN-3224/ADO-Issue-15558-Mandantenspezifischen-Link-auf-Cockpit-anpassen)
[ADO-15558](https://www.dev.diplanung.de/DefaultCollection/EfA%20DiPlanung/_workitems/edit/15558)
Include the customer in the cockpit url dynamically.
code review, local you can change the subdomain in the parameters.yml (subdomain: bb) and you should see the adjusted url in the interface.
=> feature (refs AB#15558): Include the customer in the cockpit url.

client/js/components/user/CustomerSettings/CustomerSettings.vue, client/js/components/user/CustomerSettings/CustomerSettingsSignLanguageVideo.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-12349/Hooks-BOB-SH-Plattformeinstellungen
- Add missing Hooks.
=> chore (refs DPLAN-12349): Add missing Hooks.

client/js/components/statement/publicStatementModal/StatementModalRecheck.vue
DPLAN-1998
Hide fields when they are empty. 
public detail -> Stellungnahme abgeben -> Persönliche Daten -> Straße und Hausnummer leer lassen/eingeben -> Überprüfen -> Straße and Hausnummer should show/not show
=> bug(refs DPLAN-1998): Hide fields when empty

package.json, yarn.lock
Update demosplan-ui to version 0.3.31
=> chore: Update demosplan-ui to v0.3.31

client/js/components/statement/DpStatementAnonymize.vue
DPLAN-12322
Add permission check for checkbox and some cypress selectors.
=> feat(refs DPLAN-12322): add permission

client/js/components/procedure/admin/DpAddOrganisationList.vue
DPLAN-12404
Add check for location Contacts so we don't run into an error.  
Verfahren -> Institutionen verwalten -> Institution hinzufügen -> institutions list should load
=> bug(refs DPLAN-12404): Check for location contacts in institutions

client/js/store/core/VuexApiRoutes.js
DPLAN-12419
Revert update to user 2.0 api due to unwanted side effects
=> chore (refs DPLAN-12419): rollback user api 2.0 route

client/js/components/map/publicdetail/Map.vue, demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php, demosplan/DemosPlanCoreBundle/Logic/Map/CoordinateJsonConverter.php, demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureMapSettingResourceType.php, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig, tests/backend/core/Core/Functional/SetTestPermissionsListenerTest.php
DPLAN-12406
Fix territory for public map. 
FE: 
- Add check for territory: Territory is a geojson object and features is an array
Verfahren -> Planungsdokument und Planzeichnung -> Geltungsbereich zeichnen -> Geltungsbereich einzeichnen -> Öffentlichkeitsansicht -> Drawings should be on the map
=> B dplan 12406 adjust controller territory field

Jenkinsfile
Improve Jenkins performance with distinct ci container and improved script preparation
=> chore: distinct ci container for better jenkins performance

templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement.html.twig
https://demoseurope.youtrack.cloud/issue/DPLAN-12424
- Add & Edit Hooks/Selectors.
=>  chore (refs DPLAN-12424): Add & Edit Hooks/Selectors.

.gitignore
This PR adds the newly needed var folder (but not its contents) to git
=> chore: add var folder to git

demosplan/DemosPlanCoreBundle/Logic/Orga/OrgaDeleter.php
Description: delete access control while deleting orga
=> f delete access control while deleting orga

client/js/components/map/publicdetail/Map.vue, composer.json, demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php, demosplan/DemosPlanCoreBundle/Logic/Map/CoordinateJsonConverter.php, demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureMapSettingResourceType.php, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig, tests/backend/core/Core/Functional/SetTestPermissionsListenerTest.php
DPLAN-12527
cherry-pick https://github.com/demos-europe/demosplan-core/pull/3656
And add a little bit more robustancy
=> fix(refs dplan-12527): Fix missing territory fallback

package.json, yarn.lock
=> chore: update demosplan-ui 0.3.33

client/js/components/procedure/Shared/SimilarStatementSubmitters/SimilarStatementSubmitters.vue, client/js/components/procedure/basicSettings/DpEmailList.vue, client/js/components/statement/splitStatement/SplitStatementView.vue, client/js/components/statement/voter/StatementVoter.vue, client/js/components/user/CustomerSettings/CustomerSettingsSupport.vue, package.json
DPLAN-12315
don't use the $on$off events within the code-Section anymore. Its removed in vue3. To maintain the functionality, I used the events straight from the child-component.
=> build(refs DPLAN-12315): Remove $on since its removed in vue3

package.json, yarn.lock
https://demoseurope.youtrack.cloud/issue/DPLAN-12516/Unnotiger-Leerraum-im-Stellungnahme-Fenster
The new version includes the restored slot for the close button
=> fix(refs DPLAN-12516): bump demosplan-ui to v0.3.34

package.json, yarn.lock
to get changes where its prohibited to paste formated text from word
Includes https://github.com/demos-europe/demosplan-ui/pull/1044
DPLAN-12602
=> fix(refs DPLAN-12602): Bump demosplan-ui@0.3.18-2

templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/DemosPlanAssessment/view_statement.html.twig
DPLAN-12616
- Only use link tag if there is a link.
- Only show paragraph if there are paragraphs
Login Datenerfassung -> Verfahren -> Stellungnahme -> Check documents and paragraphs
=> bug(refs DPLAN-12616): Add condition for document link

demosplan/DemosPlanCoreBundle/Command/Data/CopyFaqCommand.php
Description: copy the FAQ from one customer to another (picked)
=> chore (refs DPLAN-12006): copy the FAQ from one customer to another

client/js/components/map/publicdetail/controls/legendList/DpLayerLegend.vue, translations/messages+intl-icu.de.yml
DPLAN-12601
Clean up of https://github.com/demos-europe/demosplan-core/pull/3828. Add title if there is no legend available and a little refactoring.
=> bug(refs DPLAN-12601): Add title to layer legend

demosplan/DemosPlanCoreBundle/ResourceTypes/FileResourceType.php
[DPLAN-12698](https://demoseurope.youtrack.cloud/issue/DPLAN-12698/Abschnitte-bearbeiten-Weitere-Anhange-hochladen-funktioniert-nicht)
I added the statement list permission here to send filename and hash to frontend.
code review, test in interface in projects
=> feat (refs DPLAN-12689): add permission to check in file resourcetype

client/js/components/procedure/admin/AdministrationPlaces.vue
DPLAN-12623
Clean up of https://github.com/demos-europe/demosplan-core/pull/3838
=> bug(refs DPLAN-12623): Refactoring administration places

config/packages/framework.yaml
[According to the best practices](https://symfony.com/doc/current/performance.html#restrict-the-number-of-locales-enabled-in-the-application) only those locales should be generated, that are used
Translated keys should be seen as usual in the interface
=> chore: improve locale performance due to best practice

demosplan/DemosPlanCoreBundle/Command/Addon/AddonBuildFrontendCommand.php
Description: adjust deprecated command option
=> f adjust deprecated command option

client/js/components/statement/listStatements/ListStatements.vue
DPLAN-DPLAN-12715
Add link to original statements list. For now it is just a link to the general list. Link to specific original statement will be added later. 
Verfahren -> Stellungnahmen -> Click on dot menu for statement -> There should be a link "Originalstellungnahme"
=> bug(refs DPLAN-DPLAN-12715): Add link to orignal statements list

client/js/components/procedure/SegmentsList/FilterFlyout.vue, client/js/components/procedure/SegmentsList/SegmentsList.vue, client/js/store/procedure/SegmentFilter.js
Tickets: https://demoseurope.youtrack.cloud/issue/DPLAN-12460/Bei-Abschnittsliste-mit-wenigen-Eintragen-sind-nach-Klick-auf-drei-Punkte-die-Optionen-abgeschnitten and https://demoseurope.youtrack.cloud/issue/DPLAN-12254/Filter-Bearbeiter-Nicht-zugewiesen-funktioniert-nicht
Description: picked adjustments
=> F pick needed fixes

demosplan/DemosPlanCoreBundle/ResourceTypes/AbstractStatementResourceType.php
Description: adjust methods parameters
=> f DPLAN-12699 adjust methods parameters

client/js/components/statement/publicStatementModal/StatementModal.vue
DPLAN-12770
this.formData is bind to the store and is not allowed to be transformed without mutation. in vue2 this was just a warning. now, in vue3 it leads to a hard error.
Part of the vue3-Migration [DPLAN-12315](https://demoseurope.youtrack.cloud/issue/DPLAN-12315)
https://github.com/demos-europe/demosplan-core/pull/1151
=> fix(refs dplan-12770): Don't transform store-state (publicStatement)

config/packages/framework.yaml
Session cookie should be set in strict samesite mode as well as as secure only cookie when used in tls context
=> chore: use strict and secure session cookie

client/js/components/user/CustomerSettings/CustomerSettings.vue, client/js/components/user/CustomerSettings/CustomerSettingsBranding.vue, demosplan/DemosPlanCoreBundle/ResourceTypes/BrandingResourceType.php
DPLAN-12775
Sort of a rebuild from https://github.com/demos-europe/demosplan-core/pull/3935
its wasnt possible to cherrypick due to complex merge issues..
=> fix(refs DPLAN-12775): Fix saving style without logo

demosplan/DemosPlanCoreBundle/Utilities/Pagination/DemosPlanArrayAdapter.php
Interface and property visibility changed in major update
call assessmenttable
=> chore: fix pagerfanta pagination after major update

client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementPublicationAndVoting.vue
DPLAN-3217
Only send update request to BE if attributes have changed.
=> feat(refs DPLAN-3217 AB#15115): Fix update votes

package.json, yarn.lock
=> chore: bump demosplan-ui to 0.3.40

package.json, yarn.lock
https://demoseurope.youtrack.cloud/issue/DPLAN-12460/Bei-Abschnittsliste-mit-wenigen-Eintragen-sind-nach-Klick-auf-drei-Punkte-die-Optionen-abgeschnitten
The fixes for this bug is included in demosplan-ui v0.3.41 hence this PR bumps demosplan-ui
=> chore: bump demosplan-ui to 0.3.41

client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_released_group.html.twig
DPLAN-12315
DPLAN-12921
"empty" template-tags are a flaw in vue3
=> chore(refs dplan-12315): remove template tags

templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/send_statement.html.twig
otherwise we will see some utf-8 issues when the text is displayed
DPLAN-12844
DPLAN-12315
=> fix(refs DPLAN-12844): Pass Text as Propper String

.env, config/parameters_default.yml, demosplan/DemosPlanCoreBundle/EventSubscriber/ProcedureMetricsEmailEventSubscriber.php, demosplan/DemosPlanCoreBundle/Resources/config/GlobalConfig.php
Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-12667
Description:
PICK FOR EWM RELEASE
Send mail PostProcedureCreated to inform support about statistics regarding procedures of orga in customer.
setup eventSubscriber to be able to gather statistics about a created procedure. (Orga, Customer, Other Procedures by same Orga in same Customer)
insert/format the needed content and create the MailSend entity.
Introduce new permission to activate this new metrics email feature.
=> F dplan 12667 pick procedureMetrics Mail for release ewm

client/js/components/statement/originalStatementsTable/OriginalStatementsTableItem.vue, client/js/store/statement/AssessmentTable.js, demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-13016/HHBOP-Eingeschrankte-Anzahl-an-Originalstellungnahmen-in-BOP-Prod-Verfahren
Description: use element id to get paragraphs titles
=> f DPLAN 13016 use element id to get paragraphs titles

config/menus.yml
https://demoseurope.youtrack.cloud/issue/DPLAN-12535/DiPlanROG-Unique-Hook-fur-Abwagungstabelle-Link
- adjust Hook/Selector for statements list link.
=> chore (refs DPLAN-12535): adjust Hook/Selector for statements list link.

client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue, client/js/components/statement/assessmentTable/FragmentsButton.vue
This is a leftover after we moved from camel to pascal case.
=> fix(refs DPLAN-13038): Use Pascalcase for store name

package.json, yarn.lock
Update demosplan-ui to v0.3.42
=> chore: Update demosplan-ui to v0.3.42

.reviewdog.yml
DEVOPS-867
Eslint has gotten much faster and we're confident that this now works with our reviewdog setup.
=> feat: Re-enable eslint on reviewdog

demosplan/DemosPlanCoreBundle/Controller/GenericApiController.php, tests/backend/core/Core/Functional/Command/AddonAutoinstallCommandTest.php, tests/backend/core/DemosPlanCoreBundle/Entity/User/SecurityUserTest.php
https://www.dev.diplanung.de/DefaultCollection/EfA%20DiPlanung/_workitems/edit/20738
Some tests where failing
run tests
=> chore: fix a bunch of backend tests

client/fe/config/projectConfig.js, client/fe/index.js, client/js/InitVue.js, client/js/bootstrap.js, client/js/bundles/admin/statistics.js, client/js/components/map/map/DpOlMapDrawPoint.vue, client/js/components/map/publicdetail/Map.vue, client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue, client/js/components/statement/assessmentTable/utils/changeUrlforPager.js, client/js/components/statement/splitStatement/SideBar.vue, client/js/lib/addon/loadAddonComponents.js, client/js/lib/procedure/charts/DonutChart.js, client/js/lib/statement/DeleteFragmentButton.js, client/js/store/core/initStore.js, config/linters/eslintrc.complete.js, stylelint.config.js, tests/frontend/unit/StatusBadge.spec.js, tests/frontend/unit/store/Statement.spec.js
15 linting-problems where autofixable. Some other, simple ones, i fixed by my self.
Remaining:
✖ 349 problems (61 errors, 288 warnings)
=> chore: Run lint fix

client/js/components/user/DpUserList/DpUserFormFields.vue, templates/bundles/DemosPlanCoreBundle/DemosPlanUser/gateway_newUser.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanUser/list_departments.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanUser/list_orgas.html.twig
- success_message, fail_message are not filled anywhere
- organisationList is not called in this file
=> chore: Remove unused Code

demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php
cherry pick from: https://github.com/demos-europe/demosplan-core/commit/72d501367eec9bae84bdbff96c177c71ca9ed864
=> chore: trim github repository url

demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadFileData.php
Tests for non-root users failed due to permission reasons.
run the testsuite as any user with development container Version >5.8
=> chore: fix test permission for non-root users

demosplan/DemosPlanCoreBundle/Addon/AddonInfo.php
With the PermissionInitializer::isEnabled() hook the addon can decide on a request basis, whether it is enabled or not.
the core should work as before with and without addons installed
=> chore: add addon hook isEnabled

package.json, yarn.lock
[DPLAN-12968](https://demoseurope.youtrack.cloud/issue/DPLAN-12968/ADO-Issue-21840-Admin-Institutionsliste-Institutionen-konnen-durchsucht-werden)
v0.3.34 contains the new condensed search field with the search button attached to the search field and the text 'Suche' replaced by the magnifying glass icon
For this to fully work, https://github.com/demos-europe/demosplan-core/pull/4193 has to be merged, too.
=> build(refs DPLAN-12968, #AB21840): bump demosplan-ui to v0.3.43

client/js/components/user/DpOrganisationList/DpOrganisationList.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-13082/Orga-wird-nur-nach-Seitenrefresh-geloscht
**Description:** Get updated organizations after the deleteOrganisation action.
=> Fix(dplan-13082): delete orga issue 

client/js/components/document/DpMapSettingsPreview.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-12415
- adjust Hooks/Selectors for gisLayer links.
=> chore (refs DPLAN-12415): adjust Hooks/Selectors for gisLayer links.

config/allowedMimeTypes.yml
Description: allow csv/text files
=> f allow csv-text files

demosplan/DemosPlanCoreBundle/Entity/User/Role.php
https://demoseurope.youtrack.cloud/issue/DPLAN-13034
- Remove code that is unneeded and introduced in this PR https://github.com/demos-europe/demosplan-core/pull/4163
=> fix DPLAN-13034 remove unneeded code

client/js/components/statement/splitStatement/SideBar.vue, client/js/components/statement/splitStatement/SplitStatementView.vue, client/js/lib/prosemirror/utilities.js
Applied Tracking Evens to track statement slicing and tagging. 
Check if matomo is enabled for instance you want to check 
1. Go though slicing tagging steps several times 
2. Check matomo / behaviour / events / ST Slicing Tagging
=> feat: tracking slicing tagging

package.json, yarn.lock
https://demoseurope.youtrack.cloud/issue/DPLAN-12969/ADO-Issue-21841-Admin-Institutionsliste-Institutionen-konnen-nach-Schlagworten-gefiltert-werden
demosplan-ui v0.3.44 contains styling changes for DpFlyout: the flyout trigger can now have a darker background if the prop `variant` is set to `'dark'`
=> build(refs DPLAN-12969, #AB21841): bump demosplan-ui to v0.3.44

demosplan/DemosPlanCoreBundle/ResourceTypes/AdministratableUserResourceType.php
https://demoseurope.youtrack.cloud/issue/DPLAN-13034
This ticket is already done, and I took the advantage to upgrade the resource type because now the project mentioned in the ticket will have the latest edt version
- Login as support user
- Create a new user
- Update user
I've started a documentation based on the learnings that I've seen in resource types. This PR helped me to consolidate some of them:
https://demoseurope.youtrack.cloud/articles/DEV-A-189/Resource-Type-Create-relationship
https://demoseurope.youtrack.cloud/articles/DEV-A-193/Resource-Type-Update-relationship
https://demoseurope.youtrack.cloud/articles/DEV-A-194/Resource-Type-Update-attribute
=> B dplan 13034 upgrade resource type

demosplan/DemosPlanCoreBundle/ValueObject/CommonUserData.php, demosplan/DemosPlanCoreBundle/ValueObject/OzgKeycloakUserData.php
https://demoseurope.youtrack.cloud/issue/DPLAN-12292/ADO-Issue-19137-Adressdaten-aus-Keycloak-ubernehmen
Add logs to additional fields detected from Keycloak
**I will merge to main after release is merge in main**
=> feat (DPLAN_12292) Log additional fields coming from Keycloak

package.json, yarn.lock
The new version contains styling changes to DpTreeList (padding-bottom is only applied to branches, not leaves)
=> build: bump demosplan-ui to v.0.3.45

client/js/components/statement/listStatements/ListStatements.vue
DPLAN-2801
https://demoseurope.youtrack.cloud/issue/DPLAN-2801/Unterstreichen-von-Link-bei-Hover-fehlt
Description: Add underline effect to button on hover and active state
yarn test
Verfahren/ Stellungnahmen/ Klick auf "..."
=> B dplan 2801 underline buttons in flyout

templates/bundles/DemosPlanCoreBundle/DemosPlanNews/public_newsdetail.html.twig
Ticket: https://demoseurope.youtrack.cloud/tickets/DS-30/BOP-HH-PROD-Stage-BOP-HH-Bug-im-Bereich-Aktuelles
Description:
adjust route to get file : 
- use 'core_file_procedure' instead of 'core_file' route to get file.
- add procedureId as route parameter.
=> f DS-30 adjust route to get file :

CHANGELOG.md, demosplan/DemosPlanCoreBundle/Logic/DefaultTwigVariablesService.php, demosplan/DemosPlanCoreBundle/Resources/config/GlobalConfig.php
DPLAN-14844
fix for case of empty array / no external_links defined
https://github.com/demos-europe/demosplan-project-diplanbau/pull/278
https://github.com/demos-europe/demosplan-project-diplanfest/pull/122
https://github.com/demos-europe/demosplan-project-diplanrog/pull/167
=> B dplan 14844 fix

demosplan/DemosPlanCoreBundle/Validator/PostcodeConstraintValidator.php
Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-14951
Description: allow post code with 4 digits
=> f DPLAN-14951 allow post code with 4 digits

demosplan/DemosPlanCoreBundle/Controller/Report/DemosPlanReportController.php
DPLAN-11903
Changed current time to Berlin timezone using Carbon.
Verfahren/ Protokoll/ Download
=> bug(refs DPLAN-11903): wrong-timestamp

config/parameters_default.yml, translations/messages+intl-icu.de.yml
Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-14977
Description: adjust pictogram min resolution
=> f DPLAN-14977 : adjust pictogram min resolution

CHANGELOG.md, client/fe/config/config.js
DPLAN-14790
There are not only `plyr-` classes but also ones with `plyr_`, that need to be included for safelist.
Build in prod mode (yarn prod:project) and go to Gebärdensprache. Video controls should be placed correctly inside the video.
=> bug(refs DPLAN-14790): Extend safelist for purge css

client/js/components/user/DpUserList/DpUserList.vue
DPLAN-12188
Description: Refactored search to DbSearchField for new design and reset function.
Login as support/ use search
=> Refac(dplan 12188) no reset button

demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php, demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/OriginalStatementResourceConfigBuilder.php, demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/StatementResourceConfigBuilder.php, demosplan/DemosPlanCoreBundle/ResourceTypes/OriginalStatementResourceType.php, demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-12928/E-Mail-Import-geht-nicht
Description:
The Condition to filter out Segments from OriginalStatements or Statements did not work as intended.
Pick of https://github.com/demos-europe/demosplan-core/pull/4294
=> f_DPLAN-12928 Pick of condition fix from f_DPLAN-12928_fix_non-segment_condition.

client/js/components/statement/assessmentTable/DpFilterModal.vue
DPLAN-12943 stn filter icon
Centered filter icon
Abwägungstabelle -> Filtern
=> b(refs:DPLAN-12943) STN filter icon

client/js/bundles/procedure/administrationListBoilerplate.js, client/js/components/procedure/admin/InstitutionTagManagement/TagList.vue, client/js/components/shared/TextContentRenderer.vue, client/js/components/statement/splitStatement/DpCreateTag.vue, client/js/components/tags/TagListEditForm.vue, client/js/components/tags/TagsCreateForm.vue, client/js/components/tags/TagsImportForm.vue, client/js/components/tags/TagsList.vue, client/js/components/user/DpUserList/DpUserList.vue, client/js/store/core/initStore.js, client/js/store/map/Layers.js, client/js/store/procedure/FilterFlyout.js, tests/frontend/unit/store/Notify.spec.js
=> chore: Fix linter issues

templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_original_view.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_view.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_import.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_new.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_new_master.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/list_subscriptions.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_statement_fragments.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanUser/alternative_login.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanUser/citizen_register_form.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanUser/orga_data_entry.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanUser/orga_register_form.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanUser/portal_user.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanUser/user_set_password.html.twig
the encoded csrf token comes as string. with that we should not compute the value wen passing it to vue.
=> chore: adjust csrf tokens. Pass them as strings

demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-15167
Description:
remove duplicated lines
=> DPLAN-15167 remove duplicated lines

demosplan/DemosPlanCoreBundle/Logic/MailService.php
Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-15048/ADO-Issue-24228-Produktion-Integration-Diplan-Beteiligung-Bauleitplanung-Bestatigungsmails-STN-Einreichung-enthalten-keinen-PDF
Description:
pass content type and name for the email attachments explicitly to the message->attach method to be flysystem compatible.
Delete Attachments only after the mail has been marked as sent successfully.
enhance logging for future investigations.
In order to be compatible with the FlySystem storage we had to implement the ```Email::attach``` method instead of the previously used ```Email::attachFromPatch``` method. They handle their defaults for 'name' and 'contentType' slightly different, as there is no way to guess a name or mime-type from the filepath when just a stream is provided.
=> ADO-24228 attempt to fix email attachments - at least enhance logging

client/js/components/assessmenttable/DpNewStatement.vue, client/js/components/user/DpOrganisationList/DpOrganisationFormFields.vue
DPLAN-15155
Extended the if statement to ensure length does not cause an error.
Create new Stn and choose existing user from drowdown
=> Bug(refs DPLAN-15155): New stn select user

client/js/store/map/ProcedureMapSettings.js, config/permissions.yml
https://demoseurope.youtrack.cloud/issue/DPLAN-15223/Fehlermeldung-bei-Klick-auf-Erwiderung-verfassen-uber-Abschnittsansicht
Check if permission is enable before requesting ProcedureMapSettingResourceType
=> fix DPLAN-15223: Check if permission is enable before making request

client/js/bundles/report/list.js, client/js/components/report/DpReportGroup.vue, client/js/components/report/DpReportListing.vue, demosplan/DemosPlanCoreBundle/Tools/ServiceImporter.php
DPLAN-14783
Already reviewed with https://github.com/demos-europe/demosplan-core/pull/4385
So this is a merge for release_diplanbau only
=> F dplan 14783 fe part for extend reports for diplanbau

client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
after fixing an issue with the place and assignee, sending the recommendation got lost. Here is it again
DPLAN-14909 (DPLAN-14846)
=> fix(refs DPLAN-14909, DPLAN-14846): Send recommendation text again

client/js/bundles/user/listOrgas.js, client/js/components/user/DpOrganisationList/DpOrganisationList.vue
- needs demosplan-ui update
DPLAN-15146
Only send fields to fetch the orga which are permitted
To fix the Bug https://github.com/demos-europe/demosplan-core/pull/4446 is required
=> fix(refs DPLAN-15146): Pass propper Values to orgafilter and orgaRequest

package.json, yarn.lock
The demosplan-ui link should only be added locally and not be committed.
=> bug: Remove demosplan-ui link from package.json

client/js/components/procedure/StatementSegmentsList/StatementSegment.vue, client/js/components/report/DpReportListing.vue
DPLAN-14909
For every segment the places and the assignable user gets requested. That can be a lot of requests. And always the store gets filled with the same data.
So we should prevent that.
=> fix(refs dplan-14909): Prevent multiple fetches of the same Ressoruce (Place/AssignableUser)

templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig
DPLAN-15156
Added margin to align input fields
Create new statement
=> F(refs DPLAN-15156) alignment input fields

client/js/components/statement/assessmentTable/AssessmentTableFilter.vue, client/js/components/statement/assessmentTable/DpEditSelectedItemsMenu.vue, client/js/components/statement/assessmentTable/DpMapModal.vue, client/js/components/statement/assessmentTable/DpSelectedItemsFragments.vue, client/js/components/statement/assessmentTable/DpSelectedItemsStatements.vue, client/js/components/statement/assessmentTable/DpTable.vue, client/js/components/statement/assessmentTable/ExportModal.vue, client/js/components/statement/assessmentTable/TocView/SearchAndSorting.vue, client/js/components/statement/originalStatementsTable/OriginalStatementsTable.vue, client/js/store/statement/Statement.js, templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_original_filter.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_original_view.html.twig, tests/frontend/unit/ExportModal.spec.js
[DPLAN-15256](https://demoseurope.youtrack.cloud/issue/DPLAN-15256)
Fixes all errors in ExportModal.spec.js.
Run ExportModal.spec.js, there should be no errors.
=> test(refs DPLAN-15256): fix export modal test

client/js/components/procedure/DpSearchProcedures.vue
DPLAN-15164
Refactored to DpRadio to fix spacing issue.
walter west -> verfahrensliste -> einreichende suchen
=> b(refs:DPLAN-15164):  radio btn spacing

demosplan/DemosPlanCoreBundle/Logic/Orga/OrgaDeleter.php, demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureDeleter.php
Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-15355/Slugs-loschen-wenn-relevante-Organisation-oder-Verfahren-geloscht-wird
Description: delete slugs when relevant orga or procedure is deleted
=> f DPLAN-15355 delete slugs when relevant orga or procedure is deleted

templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig
DPLAN-12821
Changed abort route to to direct the user back to the site whey they came from.
Try to create new stn and abort as Datenerfasser
=> b(refs: DPLAN-12821) change abort route 

client/js/components/statement/listStatements/ListStatements.vue
DPLAN-15374
Add Translator.trans function to confirm texts
Delete a STN
=> b(refs: DPLAN-15374) Add Translator.trans function to confirm texts

client/js/components/statement/originalStatementsTable/OriginalStatementsTable.vue, client/js/components/statement/publicStatementLists/DpPublicStatementList.vue, client/js/store/statement/Filter.js, tests/frontend/unit/DpBulkEditStatement.spec.js, tests/frontend/unit/StatementExportModal.spec.js
DPLAN-15337
- Use DpDraggable instead of vue draggable. 
- Fix some linter issues
Privatperson -> Öffentliches Verfahren -> Save statement as draft -> Meine Entwürfe -> Page should not be empty and the drafts should be shown
=> bug (refs DPLAN-15337): Use dpDraggable

client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
DPLAN-15384
Add permission check for menu entry final email.
Verfahren -> Stellungnahmen -> Detailansicht -> Bearbeiten -> There should be no menu entry for final email if the permission is not activated
=> bug(refs DPLAN-15384): Add condition for menu entry final email

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/includes/public_statement.html.twig
DPLAN-15407
Add margin for more space between the elements
=> b(refs: DPLAN-15174) add margin for more space between the elements

client/js/lib/procedure/DPWizard.js
DPLAN-15192
Use element.style.display to make manual btns visible
login as Walter West -> Grundeinstellungen -> Assistenten starten
=> B dplan 15192 fix wizard btns

client/js/components/user/DpUserList/DpUserFormFields.vue
=> fix(refs dplan-15400): Update Roles after changing the orga

client/js/components/faq/DpFaqItem.vue, client/js/lib/procedure/DPWizard.js
https://github.com/demos-europe/demosplan-core/commit/1150bdc0e4ea461461d33e1b2690b384ca86b3ae
cherry-pick commit hash: 1150bdc0e4ea461461d33e1b2690b384ca86b3ae
https://github.com/demos-europe/demosplan-core/pull/4537#event-17151659385
cherry-pick commit hash: a55b97d839962fa71ba6ed332420213af9e91dd1
=> cherry-pick from main

package.json, yarn.lock
[DPLAN-15396](https://demoseurope.youtrack.cloud/issue/DPLAN-15396/Abschnitte-Suche-funktioniert-nicht)
The new version contains
- a fix for updating currentValue in DpResettableInput
=> chore(refs DPLAN-15396, #AB9149): bump demosplan-ui to v0.4.12

package.json, yarn.lock
upgrade demosplan-ui to v0.4.12
=> upgrade demosplan-ui

client/js/components/statement/publicStatementModal/StatementModal.vue
DPLAN-1998
Add aria-hidden to step two to not focus empty inputs.
How to review/test
Create a Stn a citizen and use screen reader
=> b dplan 1998 Add aria-hidden

CHANGELOG.md, composer.json, composer.lock, config/services.yml, demosplan/DemosPlanCoreBundle/Event/Statement/ManualOriginalStatementCreatedEvent.php, demosplan/DemosPlanCoreBundle/Logic/User/OrgaService.php
**Ticket:** https://www.dev.diplanung.de/DefaultCollection/EfA%20DiPlanung/_workitems/edit/10592
cherry pick
=> feat (ADO-10592): pick add orga service interface and bump demosplan addon

config/permissions.yml
DPLAN-15074
Minor adjustment of description in permissions to improve readability.
This has no logically impact.
This PR is not necessary for the related (actual) PR.
https://github.com/demos-europe/demosplan-project-diplanrog/pull/176
=> feat (refs DPLAN-15074): Enable (statement and segment) excel-import

.github/dependabot.yml, client/fe/webpack/moduleRules.js, client/js/components/procedure/DpSimplifiedNewStatementForm.vue, config.webpack.js, package.json, yarn.lock
to avoid conflicts in the yarn.lock file, I just upddated a couple of dependencies by hand.
- Some dependencies are tidy coupled to @masterportal/masterportalapi. they should only be updates as bundle. To ensure that, I listed them in the dependabot.yml
- with that: olcs has some issues with resolving its path with our env, so I had to teak webpack a bit (again)..
=> chore: Bump a bunch of Yarn dependencies and clean dependabot.yml

client/js/components/procedure/publicindex/DpSearchProcedureMap.vue
=> fix(refs dplan-15262): Update List even after searching AND filtering

.github/dependabot.yml
=> chore: fix dependabot syntax, @ needs to be quoted

demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php
Ticket: https://demoseurope.youtrack.cloud/tickets/DS-82/Zip-Ex-Import-RO-EWM
Description
this xls export can be imported later and html tags have to be preserved or converted (markdown) in some cases otherwise the provided structure and formatting will be lost
=> f DS-82 preserve underlined and strike through text 

demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementFromRowBuilder.php
Ticket: https://demoseurope.youtrack.cloud/tickets/DS-82/Zip-Ex-Import-RO-EWM
Description : parse down statement text to preserve the provided formatting
=> Ds 82 parse down text to preserve provided formatting

client/js/components/user/DpOrganisationList/DpOrganisationFormFields.vue
[DPLAN-15412](https://demoseurope.youtrack.cloud/issue/DPLAN-15412)
This PR changes the size of the select field back to its original size, after the previous fix addressed the missing padding but increased the overall size too much.
#4642 : This PR addressed the main issue of the ticket.
=> fix(refs DPLAN-15412): reduce size of select

demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php
Ticket: https://demoseurope.youtrack.cloud/tickets/DS-82/Zip-Ex-Import-RO-EWM
Description: adjust closing tag
=> f-DPLAN-82 adjust closing tag

composer.json, composer.lock, demosplan/DemosPlanCoreBundle/Controller/Segment/SegmentController.php, demosplan/DemosPlanCoreBundle/Event/Statement/RecommendationRequestEvent.php, tests/backend/core/Core/Unit/Logic/Segment/RpcBulkEditor/SegmentBulkEditorServiceTest.php
Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-15432/Implementierung-von-demospipes-2-in-demosplan
Description: create new Routes for similar replies base on demospipes 2
=> RecommendationRequestEvent and use in SegmentController

client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue
Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-15432/Implementierung-von-demospipes-2-in-demosplan
Description: use correct property
=> feature (ref: DPLAN-15432): use correct property

tests/backend/core/Core/Unit/Logic/Segment/RpcBulkEditor/SegmentBulkEditorServiceTest.php
No specific ticket - test infrastructure improvement
Fix unique constraint failure in test to ensure tests run reliably.
=> chore: fix unique constraint failure in test

client/js/components/map/publicdetail/DiplanKarteWrapper.vue, config/packages/nelmio_security.yaml, package.json, templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig, yarn.lock
[DPLAN-15731](https://demoseurope.youtrack.cloud/issue/DPLAN-15731/DiplanKarten-updaten-und-nonce-and-DiPlanKarten-ubergeben)
Update diplankarten and change it to web component. Pass nonce to diplankarten. Revert temporary csp changes.
1. Start diplanfest and open a procedure.
2. Check if the map is shown in the tab "Interaktive Karte"
3. Check if there are any error messages corresponding to diplankarte in the console
=> feat(refs: DPLAN-15731): Update diplan karten and add nonce

demosplan/DemosPlanCoreBundle/Logic/Segment/Export/ImageLinkConverter.php
=> fix: DPLAN-15863 adjust error level

client/js/store/map/Layers.js
the filter was well crafted and then destroyed. Sorry for that. I thought I simplify it. But everything have been necessary.
DPLAN-15912
=> fix(refs DPLAN-15912): Role Back imprudent changes.

client/js/components/statement/listOriginalStatements/ListOriginalStatements.vue
=> fix DPLAN-15235: Adjust permission name

composer.lock
=> chore: update php dependencies

client/js/store/statement/Statement.js
DPLAN-16070
The storemethod got an Id  but expected an object. 
by changing it to Id, the selected State in the original stn list works again.
=> fix(refs dplan-16070): Use proper Id to set selectedState

client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
[DPLAN-15083](https://demoseurope.youtrack.cloud/issue/DPLAN-15083)
Replaced outdated VPopover with DpTooltip from demosplan-ui. I also moved the logic for constructing the text out of the template and into computeds.
1. Open a project that still has the AssessmentTable, ideally robobsh.
2. Check if the tooltips contain the correct text and are fit to the content.
=> fix(refs: DPLAN-15083): replace VPopover with DpTooltip

client/js/components/statement/publicStatementModal/formGroups/FormGroupEvaluationMailViaEmail.vue
**Description:** Fix an issue in main that is preventing the build process.
=> fix an error that is preventing the build process

package.json, yarn.lock
DPLAN-15854
Updates diplan-karten to the version 1.0.1
1. Login as a private user, open a procedure and check if the map is shown in the tab "Interaktive Karte"
=> feat(refs: DPLAN-15854): update diplan-karten to 1.0.1

demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_pageheader.scss, templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/pageheader.html.twig, templates/bundles/DemosPlanCoreBundle/DemosPlanCore/proceduremenu_statements.html.twig
DPLAN-16090
optimize breaks in breadcrumps in public detail
=> fix(refs dplan-16090):  mobile layout breadcrump

translations/messages+intl-icu.de.yml
Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-16067/Ado-Issue-32485-Ruckmeldung-zu-Stellungnahme-steuerbar-Ubernahmesprint-in-DiPlanRog
Description: adjust translation key text
=> feat (ref: DPLAN-16067) : adjust translation key text

client/js/components/map/publicdetail/Map.vue
by now the request was send to the be and from there fetched from the source. due to security policies we have to fetch straight from the FE.
DPLAN-16074
=> fix(refs: DPLAN-16074): Move getFeatureInfo request to the Frontend

client/js/components/map/admin/AdminLayerList.vue, client/js/components/map/publicdetail/Map.vue, client/js/store/map/Layers.js
DPLAN-16134
When a request is used in different places, its important to check, that the requested fields are necessary and even more important available in that circumstance.
=> fix(refs DPLAN-16134): Only send valid fields when requesting Layers

client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementEntry.vue, client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementSubmitter.vue
[DPLAN-16172](https://demoseurope.youtrack.cloud/issue/DPLAN-16172/Nicht-moglich-um-in-Inputfelder-von-Eingereicht-von-etwas-zu-schreiben)
- for v-model to work in vue 3, we need to use modelValue
- DpInput has been updated to not support value anymore
=> fix(refs DPLAN-16172): use modelValue for DpInput

client/js/components/procedure/admin/AdministrationProceduresList.vue
Somehow the originally intended search field width in the procedure list got lost, it is hereby restored. :sparkles: 
Also, there was a purple notification because of the 'procedure' include in the AdministrationProcedure fetch request, so I removed it.
=> fix: increase search field width

templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-16339/Grundeinstellungen-Ein-verwirrendes-geschweifte-Klammer
Description: remove extra closing brace
=> f DPLAN-16339 remove extra closing brace

composer.json
bump demosplan-addon from v0.59 to v0.60
=> bump demosplan-addon from v0.59 to v0.60

translations/messages+intl-icu.de.yml
https://www.dev.diplanung.de/DefaultCollection/EfA%20DiPlanung/_workitems/edit/XXXXX](https://demoseurope.youtrack.cloud/issue/DPLAN-16549/Keine-Ergebnisse-auf-der-Startseite-bei-bestimmten-Verfahrensschritten)
Adjusted procedure phase filtering. 
go to procedure overview list --> filter by newly added procedure phases.
=>  b_(refs DPLAN-16547): adjusted phase filtering

client/js/components/map/admin/MapAdmin.vue
[DPLAN-15660](https://demoseurope.youtrack.cloud/issue/DPLAN-15660/Ado-Issue-28780-Admin-Panel-erweitern-um-Einstellungen-der-Karte-vorzunehmen)
Since I merged my FE into the BE branch, and that branch only targeted the project, this additional PR is needed to have the changes in the core.
see this PR: #5247
=> feat(refs:DPLAN-15660): turn off scales when diplankarte

client/fe/webpack/runWebpack.js, client/js/components/map/publicdetail/Map.vue, client/js/components/procedure/StatementSegmentsList/SegmentsRecommendations.vue, client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue, client/js/components/statement/assessmentTable/CopyStatementModal.vue, client/js/components/statement/assessmentTable/DpMoveStatementModal.vue, client/js/components/statement/assessmentTable/ExportModal.vue, client/js/components/statement/publicStatementModal/StatementModalRecheck.vue, client/js/components/user/DpUserList/DpUserList.vue
Before:
```
✖ 486 problems (76 errors, 410 warnings)
29 errors and 30 warnings potentially fixable with the `--fix` option.
```
After:
```
✖ 427 problems (47 errors, 380 warnings)
```
=> chore: autofix linting issues
